import SecureAppGate from "@/components/shared/SecureAppGate";
import { Badge } from "@/components/ui/badge";
import { Copy, Download, FileText, Scale, X } from "lucide-react";
import { useState as useReactState } from "react";
import { toast } from "sonner";

type DocType =
  | "NDA"
  | "Sale Agreement"
  | "Rental Agreement"
  | "MOU"
  | "Power of Attorney";

interface DocForm {
  party1: string;
  party2: string;
  date: string;
  extra: string;
}

const DOC_TYPES: { type: DocType; fields: string }[] = [
  { type: "NDA", fields: "Confidential scope" },
  { type: "Sale Agreement", fields: "Property address" },
  { type: "Rental Agreement", fields: "Monthly rent (₹)" },
  { type: "MOU", fields: "Purpose / subject" },
  { type: "Power of Attorney", fields: "Scope of authority" },
];

function generateDoc(type: DocType, form: DocForm): string {
  const date = form.date || new Date().toLocaleDateString("en-IN");
  return `${type.toUpperCase()}\n${"=".repeat(60)}\n\nThis ${type} is entered into on ${date}\n\nPARTY 1: ${form.party1 || "[Party 1 Name]"}\nPARTY 2: ${form.party2 || "[Party 2 Name]"}\n\nDETAILS: ${form.extra || "[See schedule]"}\n\nWHEREAS the parties wish to establish a formal agreement\nregarding the above-mentioned matter:\n\n1. TERMS AND CONDITIONS\n   The parties agree to abide by all applicable laws\n   and regulations of India.\n\n2. CONFIDENTIALITY\n   All information shared under this agreement shall\n   remain strictly confidential.\n\n3. GOVERNING LAW\n   This agreement is governed by the laws of India\n   and jurisdiction of Ahmedabad, Gujarat.\n\n4. SIGNATURES\n   Party 1: ___________________  Date: __________\n   ${form.party1 || "[Party 1]"}\n\n   Party 2: ___________________  Date: __________\n   ${form.party2 || "[Party 2]"}\n\n${"=".repeat(60)}\nGenerated by MSTC GLOBAL Legal Command — ${new Date().toLocaleString("en-IN")}\n`;
}

const LEGAL_AI_TEAMS = [
  {
    tier: 1,
    name: "Chief Legal Officer",
    ais: [
      {
        name: "Justice AI",
        role: "Chief Legal Officer",
        status: "ACTIVE",
        tasks: 14,
      },
    ],
  },
  {
    tier: 2,
    name: "Senior Lawyer AIs",
    ais: [
      {
        name: "Lex AI",
        role: "Contracts & Agreements",
        status: "ACTIVE",
        tasks: 8,
      },
      {
        name: "Veda AI",
        role: "Compliance & Regulatory",
        status: "ACTIVE",
        tasks: 5,
      },
      {
        name: "Sutra AI",
        role: "Litigation & Disputes",
        status: "ACTIVE",
        tasks: 2,
      },
      { name: "Niti AI", role: "Property Law", status: "ACTIVE", tasks: 11 },
      { name: "Dharma AI", role: "Corporate Law", status: "ACTIVE", tasks: 3 },
      {
        name: "Raksha AI",
        role: "Privacy & Data Law",
        status: "ACTIVE",
        tasks: 6,
      },
    ],
  },
  {
    tier: 3,
    name: "Specialist Lawyer AIs",
    ais: [
      {
        name: "Deed Drafter AI",
        role: "Property Deed Drafting",
        status: "ACTIVE",
        tasks: 7,
      },
      {
        name: "Agreement Builder AI",
        role: "Rental & MOUs",
        status: "ACTIVE",
        tasks: 4,
      },
      {
        name: "NDA Guardian AI",
        role: "Non-Disclosure Agreements",
        status: "ACTIVE",
        tasks: 3,
      },
      {
        name: "Policy Writer AI",
        role: "Privacy Policies",
        status: "ACTIVE",
        tasks: 3,
      },
      {
        name: "RERA Counsel AI",
        role: "RERA Registrations",
        status: "ACTIVE",
        tasks: 9,
      },
      {
        name: "GST Legal AI",
        role: "GST Compliance",
        status: "ACTIVE",
        tasks: 4,
      },
      {
        name: "Notice Drafter AI",
        role: "Legal Notices",
        status: "ACTIVE",
        tasks: 2,
      },
      {
        name: "Response AI",
        role: "Legal Notice Replies",
        status: "ACTIVE",
        tasks: 1,
      },
      {
        name: "Court Filing AI",
        role: "Court Document Preparation",
        status: "ACTIVE",
        tasks: 2,
      },
      {
        name: "Due Diligence AI",
        role: "Property Due Diligence",
        status: "ACTIVE",
        tasks: 5,
      },
      {
        name: "Title Examiner AI",
        role: "Property Title Search",
        status: "ACTIVE",
        tasks: 6,
      },
      {
        name: "Stamp Duty AI",
        role: "Stamp Duty Calculation",
        status: "ACTIVE",
        tasks: 8,
      },
      {
        name: "Registration AI",
        role: "Property Registration Guidance",
        status: "ACTIVE",
        tasks: 4,
      },
      {
        name: "Indemnity AI",
        role: "Indemnity Bonds & Guarantees",
        status: "ACTIVE",
        tasks: 2,
      },
      {
        name: "Power of Attorney AI",
        role: "PoA Documents",
        status: "ACTIVE",
        tasks: 3,
      },
    ],
  },
  {
    tier: 4,
    name: "Worker Legal AIs",
    ais: [
      {
        name: "Document OCR AI",
        role: "Digitizes Scanned Legal Documents",
        status: "ACTIVE",
        tasks: 12,
      },
      {
        name: "Clause Extractor AI",
        role: "Pulls Key Clauses from Agreements",
        status: "ACTIVE",
        tasks: 9,
      },
      {
        name: "Risk Flag AI",
        role: "Highlights Risky Clauses in Red",
        status: "ACTIVE",
        tasks: 7,
      },
      {
        name: "Deadline Tracker AI",
        role: "Tracks Legal Deadlines & Renewals",
        status: "ACTIVE",
        tasks: 14,
      },
      {
        name: "Form Auto-Fill AI",
        role: "Pre-fills Legal Forms from Data",
        status: "ACTIVE",
        tasks: 11,
      },
      {
        name: "Legal Summary AI",
        role: "Summarizes Long Legal Documents",
        status: "ACTIVE",
        tasks: 8,
      },
      {
        name: "Jargon Explainer AI",
        role: "Translates Legal Language",
        status: "ACTIVE",
        tasks: 6,
      },
      {
        name: "Precedent Search AI",
        role: "Finds Relevant Cases & Precedents",
        status: "ACTIVE",
        tasks: 3,
      },
      {
        name: "Compliance Calendar AI",
        role: "Live Regulatory Filing Calendar",
        status: "ACTIVE",
        tasks: 5,
      },
      {
        name: "Audit AI",
        role: "Monthly Legal Health Audit",
        status: "ACTIVE",
        tasks: 4,
      },
      {
        name: "Version Control AI",
        role: "Tracks Every Document Version",
        status: "ACTIVE",
        tasks: 10,
      },
      {
        name: "Signature Tracker AI",
        role: "Tracks Signed/Pending Documents",
        status: "ACTIVE",
        tasks: 13,
      },
      {
        name: "Renewal Alert AI",
        role: "Alerts Before Expiry (30/60/90 days)",
        status: "ACTIVE",
        tasks: 7,
      },
      {
        name: "Archive AI",
        role: "Auto-Archives Executed Documents",
        status: "ACTIVE",
        tasks: 6,
      },
    ],
  },
];

const VARIED_STATUSES = [
  "ACTIVE",
  "ACTIVE",
  "STANDBY",
  "ACTIVE",
  "PROCESSING",
  "ACTIVE",
  "STANDBY",
  "ACTIVE",
  "ACTIVE",
  "STANDBY",
  "ACTIVE",
  "PROCESSING",
  "ACTIVE",
  "ACTIVE",
  "STANDBY",
  "ACTIVE",
  "ACTIVE",
  "ACTIVE",
  "PROCESSING",
  "STANDBY",
  "ACTIVE",
  "ACTIVE",
  "ACTIVE",
  "STANDBY",
  "PROCESSING",
  "ACTIVE",
  "ACTIVE",
  "ACTIVE",
  "STANDBY",
  "ACTIVE",
];

const POLICIES = [
  {
    name: "Privacy Policy",
    updated: "2025-05-26",
    status: "Published",
    version: "v3.2",
  },
  {
    name: "Terms & Conditions",
    updated: "2025-04-10",
    status: "Published",
    version: "v2.8",
  },
  {
    name: "Cookie Policy",
    updated: "2025-03-22",
    status: "Published",
    version: "v1.5",
  },
  {
    name: "Disclaimer",
    updated: "2025-05-01",
    status: "Published",
    version: "v2.1",
  },
  {
    name: "Refund Policy",
    updated: "2025-02-15",
    status: "Draft",
    version: "v1.0",
  },
];

const RECENT_DOCS = [
  {
    id: 1,
    name: "Prahlad Nagar Sale Deed",
    category: "Property",
    status: "Executed",
    risk: "Low",
    date: "2025-05-24",
  },
  {
    id: 2,
    name: "NDA — Bopal Developer",
    category: "Corporate",
    status: "Signed",
    risk: "Low",
    date: "2025-05-22",
  },
  {
    id: 3,
    name: "Residential Lease — Nilesh Shah",
    category: "Rental",
    status: "Active",
    risk: "Low",
    date: "2025-05-20",
  },
  {
    id: 4,
    name: "GST Compliance Report Q1",
    category: "Regulatory",
    status: "Filed",
    risk: "Low",
    date: "2025-05-18",
  },
];

export default function LegalCommandPage() {
  const [activeTab, setActiveTab] = useReactState<
    "dashboard" | "docs" | "policies" | "forms"
  >("dashboard");
  const [docModal, setDocModal] = useReactState<DocType | null>(null);
  const [docForm, setDocForm] = useReactState<DocForm>({
    party1: "",
    party2: "",
    date: "",
    extra: "",
  });
  const [generatedDoc, setGeneratedDoc] = useReactState<string | null>(null);

  function handleGenerate(e: React.FormEvent) {
    e.preventDefault();
    if (!docModal) return;
    setGeneratedDoc(generateDoc(docModal, docForm));
  }

  function handleCopyDoc() {
    if (!generatedDoc) return;
    navigator.clipboard
      .writeText(generatedDoc)
      .then(() => toast.success("Copied to clipboard!"));
  }

  function handleDownloadDoc() {
    if (!generatedDoc || !docModal) return;
    const blob = new Blob([generatedDoc], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `legal_document_${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Document downloaded");
  }

  return (
    <SecureAppGate appName="Legalities Command">
      <div
        className="min-h-screen bg-background pb-20"
        data-ocid="legal_command.page"
      >
        <div className="sticky top-0 z-10 border-b border-gold-800/30 bg-card/90 backdrop-blur-md px-4 py-3">
          <div className="flex items-center gap-2">
            <Scale className="w-4 h-4 text-gold-400" />
            <h1 className="font-serif font-bold text-base sm:text-lg text-foreground">
              Legalities Command
            </h1>
          </div>
          <div className="flex gap-2 mt-3 overflow-x-auto">
            {(["dashboard", "docs", "policies", "forms"] as const).map(
              (tab) => (
                <button
                  key={tab}
                  type="button"
                  onClick={() => setActiveTab(tab)}
                  className={`px-3 py-1 rounded-full text-xs border capitalize whitespace-nowrap transition-colors ${activeTab === tab ? "bg-gold-700/30 text-gold-300 border-gold-600/50" : "border-gold-800/30 text-gold-600"}`}
                  data-ocid={`legal_command.tab.${tab}`}
                >
                  {tab}
                </button>
              ),
            )}
          </div>
        </div>

        <div className="px-4 py-4">
          {activeTab === "dashboard" && (
            <>
              <div className="grid grid-cols-3 gap-3 mb-5">
                {[
                  {
                    label: "Legal Health Score",
                    value: "96/100",
                    color: "text-green-400",
                  },
                  {
                    label: "Active Documents",
                    value: "847",
                    color: "text-gold-400",
                  },
                  {
                    label: "Legal AIs Active",
                    value: "36",
                    color: "text-blue-400",
                  },
                ].map((s) => (
                  <div
                    key={s.label}
                    className="rounded-xl border border-gold-800/30 bg-card p-3 text-center"
                  >
                    <p className={`font-serif text-lg font-bold ${s.color}`}>
                      {s.value}
                    </p>
                    <p className="text-xs text-muted-foreground mt-0.5 leading-tight">
                      {s.label}
                    </p>
                  </div>
                ))}
              </div>
              {LEGAL_AI_TEAMS.map((tier) => (
                <div key={tier.tier} className="mb-4">
                  <h3 className="text-xs font-semibold text-gold-600 uppercase tracking-wide mb-2">
                    Tier {tier.tier} — {tier.name}
                  </h3>
                  <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                    {tier.ais.map((ai, aiIdx) => {
                      const statusIdx =
                        LEGAL_AI_TEAMS.slice(0, tier.tier - 1).reduce(
                          (s, t) => s + t.ais.length,
                          0,
                        ) + aiIdx;
                      const variedStatus =
                        VARIED_STATUSES[statusIdx % VARIED_STATUSES.length];
                      return (
                        <div
                          key={ai.name}
                          className="rounded-xl border border-gold-800/30 bg-card p-3"
                        >
                          <div className="flex items-center justify-between mb-1">
                            <span className="text-xs font-medium text-foreground truncate">
                              {ai.name}
                            </span>
                            <span
                              className={`text-[10px] ${variedStatus === "ACTIVE" ? "text-green-400" : variedStatus === "STANDBY" ? "text-yellow-400" : "text-blue-400"}`}
                            >
                              {variedStatus}
                            </span>
                          </div>
                          <p className="text-[10px] text-muted-foreground">
                            {ai.role}
                          </p>
                          <p className="text-[10px] text-gold-600 mt-0.5">
                            {ai.tasks} tasks today
                          </p>
                        </div>
                      );
                    })}
                  </div>
                </div>
              ))}
            </>
          )}

          {activeTab === "docs" && (
            <>
              <h3 className="font-serif font-semibold text-foreground mb-3">
                Recent Documents
              </h3>
              <div className="space-y-2">
                {RECENT_DOCS.map((doc, i) => (
                  <div
                    key={doc.id}
                    className="flex items-center gap-3 p-3 rounded-xl border border-gold-800/30 bg-card"
                    data-ocid={`legal_command.doc.item.${i + 1}`}
                  >
                    <FileText className="w-4 h-4 text-gold-500 shrink-0" />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-foreground truncate">
                        {doc.name}
                      </p>
                      <p className="text-xs text-muted-foreground">
                        {doc.category} • {doc.date}
                      </p>
                    </div>
                    <div className="flex gap-1.5 shrink-0">
                      <Badge
                        variant="outline"
                        className="text-[10px] border border-green-800/30 text-green-300 bg-green-900/10"
                      >
                        {doc.status}
                      </Badge>
                      <Badge
                        variant="outline"
                        className={`text-[10px] border ${doc.risk === "High" ? "bg-red-900/20 text-red-300 border-red-800/30" : "bg-blue-900/20 text-blue-300 border-blue-800/30"}`}
                      >
                        Risk: {doc.risk}
                      </Badge>
                    </div>
                  </div>
                ))}
              </div>
            </>
          )}

          {activeTab === "policies" && (
            <>
              <h3 className="font-serif font-semibold text-foreground mb-3">
                Policy Manager
              </h3>
              <div className="space-y-2">
                {POLICIES.map((policy, i) => (
                  <div
                    key={policy.name}
                    className="flex items-center justify-between p-3 rounded-xl border border-gold-800/30 bg-card"
                    data-ocid={`legal_command.policy.item.${i + 1}`}
                  >
                    <div>
                      <p className="text-sm font-medium text-foreground">
                        {policy.name}
                      </p>
                      <p className="text-xs text-muted-foreground">
                        Updated {policy.updated} • {policy.version}
                      </p>
                    </div>
                    <div className="flex items-center gap-2">
                      <Badge
                        variant="outline"
                        className={`text-xs border ${policy.status === "Published" ? "bg-green-900/20 text-green-300 border-green-800/30" : "bg-yellow-900/20 text-yellow-300 border-yellow-800/30"}`}
                      >
                        {policy.status}
                      </Badge>
                      <button
                        type="button"
                        className="text-xs text-gold-500 hover:text-gold-400 transition-colors"
                        data-ocid={`legal_command.policy.edit_button.${i + 1}`}
                      >
                        Edit
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </>
          )}

          {activeTab === "forms" && (
            <>
              <h3 className="font-serif font-semibold text-foreground mb-3">
                Legal Form Builder
              </h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {DOC_TYPES.map((d, i) => (
                  <div
                    key={d.type}
                    className="flex items-center justify-between p-3 rounded-xl border border-gold-800/30 bg-card"
                    data-ocid={`legal_command.form.item.${i + 1}`}
                  >
                    <div>
                      <p className="text-sm text-foreground font-medium">
                        {d.type}
                      </p>
                      <p className="text-xs text-muted-foreground">
                        {d.fields}
                      </p>
                    </div>
                    <button
                      type="button"
                      onClick={() => {
                        setDocModal(d.type);
                        setDocForm({
                          party1: "",
                          party2: "",
                          date: "",
                          extra: "",
                        });
                        setGeneratedDoc(null);
                      }}
                      className="text-xs text-gold-500 hover:text-gold-400 transition-colors"
                      data-ocid={`legal_command.form.open_button.${i + 1}`}
                    >
                      Generate
                    </button>
                  </div>
                ))}
              </div>

              {/* Document Generation Modal */}
              {docModal && (
                <div
                  className="fixed inset-0 z-50 flex items-center justify-center p-4"
                  onClick={() => {
                    setDocModal(null);
                    setGeneratedDoc(null);
                  }}
                  onKeyDown={(e) => e.key === "Escape" && setDocModal(null)}
                  role="dialog"
                  aria-modal="true"
                >
                  <div className="absolute inset-0 bg-black/70" />
                  <div
                    className="relative bg-card border border-gold-700/40 rounded-2xl p-5 w-full max-w-md max-h-[90vh] overflow-y-auto"
                    onClick={(e) => e.stopPropagation()}
                    onKeyDown={() => {}}
                    data-ocid="legal_command.doc_dialog"
                  >
                    <div className="flex items-center justify-between mb-4">
                      <h2 className="font-serif font-bold text-gold-400">
                        {docModal}
                      </h2>
                      <button
                        type="button"
                        onClick={() => {
                          setDocModal(null);
                          setGeneratedDoc(null);
                        }}
                        className="text-gold-600 hover:text-gold-400"
                        data-ocid="legal_command.doc_dialog.close_button"
                      >
                        <X className="w-4 h-4" />
                      </button>
                    </div>
                    {!generatedDoc ? (
                      <form onSubmit={handleGenerate} className="space-y-3">
                        <div>
                          <label className="text-xs text-gold-600">
                            Party 1 Name *
                          </label>
                          <input
                            value={docForm.party1}
                            onChange={(e) =>
                              setDocForm((f) => ({
                                ...f,
                                party1: e.target.value,
                              }))
                            }
                            placeholder="MSTC GLOBAL"
                            required
                            className="w-full mt-1 px-3 py-2 rounded-lg border border-gold-800/40 bg-background text-sm text-foreground focus:outline-none"
                            data-ocid="legal_command.party1_input"
                          />
                        </div>
                        <div>
                          <label className="text-xs text-gold-600">
                            Party 2 Name *
                          </label>
                          <input
                            value={docForm.party2}
                            onChange={(e) =>
                              setDocForm((f) => ({
                                ...f,
                                party2: e.target.value,
                              }))
                            }
                            placeholder="Client / Counterparty"
                            required
                            className="w-full mt-1 px-3 py-2 rounded-lg border border-gold-800/40 bg-background text-sm text-foreground focus:outline-none"
                            data-ocid="legal_command.party2_input"
                          />
                        </div>
                        <div>
                          <label className="text-xs text-gold-600">Date</label>
                          <input
                            type="date"
                            value={docForm.date}
                            onChange={(e) =>
                              setDocForm((f) => ({
                                ...f,
                                date: e.target.value,
                              }))
                            }
                            className="w-full mt-1 px-3 py-2 rounded-lg border border-gold-800/40 bg-background text-sm text-foreground focus:outline-none"
                            data-ocid="legal_command.date_input"
                          />
                        </div>
                        <div>
                          <label className="text-xs text-gold-600">
                            {DOC_TYPES.find((d) => d.type === docModal)?.fields}
                          </label>
                          <input
                            value={docForm.extra}
                            onChange={(e) =>
                              setDocForm((f) => ({
                                ...f,
                                extra: e.target.value,
                              }))
                            }
                            placeholder="Enter details..."
                            className="w-full mt-1 px-3 py-2 rounded-lg border border-gold-800/40 bg-background text-sm text-foreground focus:outline-none"
                            data-ocid="legal_command.extra_input"
                          />
                        </div>
                        <button
                          type="submit"
                          className="w-full py-2.5 rounded-lg bg-gold-700/30 hover:bg-gold-700/40 text-gold-300 text-sm font-medium transition-colors"
                          data-ocid="legal_command.generate_button"
                        >
                          Generate Document
                        </button>
                      </form>
                    ) : (
                      <div>
                        <textarea
                          readOnly
                          value={generatedDoc}
                          rows={14}
                          className="w-full px-3 py-2 rounded-lg border border-gold-800/30 bg-background text-xs text-foreground font-mono resize-none focus:outline-none"
                          data-ocid="legal_command.doc_preview"
                        />
                        <div className="flex gap-2 mt-3">
                          <button
                            type="button"
                            onClick={handleCopyDoc}
                            className="flex-1 flex items-center justify-center gap-1.5 py-2 rounded-lg bg-gold-700/20 hover:bg-gold-700/30 text-gold-400 text-sm border border-gold-700/40 transition-colors"
                            data-ocid="legal_command.copy_button"
                          >
                            <Copy className="w-3.5 h-3.5" /> Copy
                          </button>
                          <button
                            type="button"
                            onClick={handleDownloadDoc}
                            className="flex-1 flex items-center justify-center gap-1.5 py-2 rounded-lg bg-card hover:bg-card/80 text-foreground text-sm border border-gold-800/30 transition-colors"
                            data-ocid="legal_command.download_button"
                          >
                            <Download className="w-3.5 h-3.5" /> Download (.txt)
                          </button>
                        </div>
                        <button
                          type="button"
                          onClick={() => setGeneratedDoc(null)}
                          className="w-full mt-2 py-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors"
                        >
                          ← Edit fields
                        </button>
                      </div>
                    )}
                  </div>
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </SecureAppGate>
  );
}
