export interface AgentDefinition {
  id: string;
  name: string;
  clusterId: number;
  clusterName: string;
  description: string;
  autonomyLevel: number;
  status: "active" | "idle" | "processing" | "error";
  performanceScore: number;
  tasksToday: number;
  tasksThisWeek: number;
  tasksAllTime: number;
  currentTask: string;
  lastActions: string[];
  capabilities: string[];
  dataSource: "real" | "simulated";
  controlEnabled: boolean;
}
export interface ClusterDefinition {
  clusterId: number;
  clusterName: string;
  clusterDescription: string;
  category: string;
  color: string;
  agents: AgentDefinition[];
}

const a = (
  id: string,
  name: string,
  cid: number,
  cn: string,
  desc: string,
  al: number,
  st: "active" | "idle" | "processing" | "error",
  ps: number,
  td: number,
  tw: number,
  ta: number,
  ct: string,
  la: string[],
  cap: string[],
  ds: "real" | "simulated",
): AgentDefinition => ({
  id,
  name,
  clusterId: cid,
  clusterName: cn,
  description: desc,
  autonomyLevel: al,
  status: st,
  performanceScore: ps,
  tasksToday: td,
  tasksThisWeek: tw,
  tasksAllTime: ta,
  currentTask: ct,
  lastActions: la,
  capabilities: cap,
  dataSource: ds,
  controlEnabled: true,
});

export const clusterData26to35: ClusterDefinition[] = [
  {
    clusterId: 26,
    clusterName: "Deep Property Intelligence",
    clusterDescription:
      "Hyper-local property intelligence for every listing and locality",
    category: "Property",
    color: "#10b981",
    agents: [
      a(
        "c26_1",
        "Micro-Market Pulse AI",
        26,
        "Deep Property Intelligence",
        "Street-level intelligence per micro-market",
        8,
        "active",
        94,
        87,
        521,
        20840,
        "Scanning Bopal price movements",
        [
          "Scanned Satellite prices",
          "Updated Bodakdev index",
          "Flagged Navrangpura surge",
          "Compared Gota vs Chandkheda",
          "Reported micro-market shifts",
        ],
        [
          "Hyper-local price tracking",
          "Street-level analysis",
          "Demand signal detection",
        ],
        "simulated",
      ),
      a(
        "c26_2",
        "Society Health Score AI",
        26,
        "Deep Property Intelligence",
        "Rates society maintenance and management quality",
        7,
        "active",
        91,
        62,
        372,
        14880,
        "Scoring Shivalik society health",
        [
          "Scored 5 new societies",
          "Updated defaulter rates",
          "Flagged poor maintenance",
          "Reviewed society AGMs",
          "Generated health reports",
        ],
        [
          "Society quality rating",
          "Defaulter % tracking",
          "Management reputation",
        ],
        "simulated",
      ),
      a(
        "c26_3",
        "Vastu Compliance AI",
        26,
        "Deep Property Intelligence",
        "Analyses floor plans for Vastu compliance score",
        7,
        "idle",
        88,
        34,
        204,
        8160,
        "Awaiting floor plan upload",
        [
          "Scored 3 floor plans",
          "Flagged north-east defects",
          "Suggested corrections",
          "Updated compliance DB",
          "Ran batch Vastu check",
        ],
        [
          "Vastu score calculation",
          "Defect detection",
          "Correction suggestions",
        ],
        "simulated",
      ),
      a(
        "c26_4",
        "Shadow & Sunlight AI",
        26,
        "Deep Property Intelligence",
        "Maps sunlight entry direction for any flat",
        6,
        "active",
        86,
        51,
        306,
        12240,
        "Calculating east-facing sun hours",
        [
          "Mapped 12 flat orientations",
          "Calculated winter shadows",
          "Updated sun entry data",
          "Flagged dark listings",
          "Compared facing types",
        ],
        ["Sunlight direction mapping", "Shadow analysis", "Seasonal variation"],
        "simulated",
      ),
      a(
        "c26_5",
        "Noise Pollution Map AI",
        26,
        "Deep Property Intelligence",
        "Overlays ambient noise levels on property map",
        7,
        "active",
        89,
        73,
        438,
        17520,
        "Mapping SG Highway noise",
        [
          "Updated highway noise band",
          "Scored railway proximity",
          "Flagged market noise",
          "Mapped 8 localities",
          "Generated noise heatmap",
        ],
        ["Noise level overlay", "Source identification", "Decibel scoring"],
        "simulated",
      ),
      a(
        "c26_6",
        "Air Quality Index Display AI",
        26,
        "Deep Property Intelligence",
        "Shows live AQI for each listing locality",
        8,
        "active",
        93,
        112,
        672,
        26880,
        "Fetching Prahlad Nagar AQI",
        [
          "Pulled live AQI data",
          "Updated 15 localities",
          "Flagged high-AQI zones",
          "Compared seasonal AQI",
          "Sent AQI alerts",
        ],
        ["Live AQI fetch", "Locality comparison", "Seasonal trend"],
        "real",
      ),
      a(
        "c26_7",
        "Flood Risk Zone AI",
        26,
        "Deep Property Intelligence",
        "Shows flood and waterlogging risk per property",
        7,
        "active",
        90,
        58,
        348,
        13920,
        "Mapping Vatva flood zones",
        [
          "Updated NDMA flood data",
          "Flagged low-lying plots",
          "Mapped drainage zones",
          "Scored 20 localities",
          "Generated risk report",
        ],
        ["Flood risk scoring", "NDMA data integration", "Drainage analysis"],
        "real",
      ),
      a(
        "c26_8",
        "Earthquake Zone Display AI",
        26,
        "Deep Property Intelligence",
        "Shows Gujarat seismic zone rating per listing",
        6,
        "idle",
        87,
        22,
        132,
        5280,
        "Idle - last checked seismic DB",
        [
          "Updated zone III areas",
          "Flagged vulnerable plots",
          "Ran seismic query",
          "Synced NDMA data",
          "Generated zone map",
        ],
        ["Seismic zone display", "Risk rating", "Building vulnerability"],
        "real",
      ),
      a(
        "c26_9",
        "Crime Safety Index AI",
        26,
        "Deep Property Intelligence",
        "Locality safety score from public data sources",
        7,
        "active",
        85,
        44,
        264,
        10560,
        "Scoring Nikol safety index",
        [
          "Updated crime indices",
          "Flagged high-risk zones",
          "Scored 10 localities",
          "Pulled police data",
          "Generated safety map",
        ],
        ["Safety score calc", "Crime data fetch", "Trend monitoring"],
        "simulated",
      ),
      a(
        "c26_10",
        "School Proximity Ranker AI",
        26,
        "Deep Property Intelligence",
        "Ranks nearest schools by quality and distance",
        8,
        "active",
        92,
        96,
        576,
        23040,
        "Ranking Bopal area schools",
        [
          "Ranked 8 school clusters",
          "Updated fee data",
          "Scored board quality",
          "Mapped proximity zones",
          "Generated school cards",
        ],
        ["School quality ranking", "Distance calculation", "Fee comparison"],
        "simulated",
      ),
      a(
        "c26_11",
        "Hospital Access AI",
        26,
        "Deep Property Intelligence",
        "Shows nearest hospitals with distance and type",
        7,
        "active",
        91,
        78,
        468,
        18720,
        "Mapping Satellite hospitals",
        [
          "Updated hospital DB",
          "Mapped 5 specialty clinics",
          "Scored emergency access",
          "Generated access cards",
          "Ranked by distance",
        ],
        ["Hospital proximity", "Specialty mapping", "Emergency access"],
        "simulated",
      ),
      a(
        "c26_12",
        "Green Space AI",
        26,
        "Deep Property Intelligence",
        "Shows green cover percentage within 1km radius",
        6,
        "active",
        88,
        49,
        294,
        11760,
        "Calculating Thaltej green cover",
        [
          "Scanned 8 localities",
          "Updated park data",
          "Scored green cover %",
          "Flagged low-green areas",
          "Generated green map",
        ],
        ["Green cover scoring", "Park proximity", "Satellite analysis"],
        "simulated",
      ),
      a(
        "c26_13",
        "Power Cut History AI",
        26,
        "Deep Property Intelligence",
        "Tracks average monthly power cut hours per locality",
        7,
        "idle",
        84,
        18,
        108,
        4320,
        "Idle - syncing DISCOM data",
        [
          "Pulled DISCOM records",
          "Updated cut history",
          "Scored 12 localities",
          "Flagged high-cut zones",
          "Generated power report",
        ],
        ["Power cut tracking", "DISCOM data sync", "Trend analysis"],
        "real",
      ),
      a(
        "c26_14",
        "Water Supply Score AI",
        26,
        "Deep Property Intelligence",
        "Rates municipal water reliability per locality",
        7,
        "active",
        87,
        55,
        330,
        13200,
        "Scoring Gota water supply",
        [
          "Scored 10 localities",
          "Updated supply data",
          "Flagged shortage zones",
          "Compared seasonal supply",
          "Generated water cards",
        ],
        ["Supply reliability", "Shortage detection", "Seasonal tracking"],
        "real",
      ),
      a(
        "c26_15",
        "Parking Intelligence AI",
        26,
        "Deep Property Intelligence",
        "Analyses dedicated and visitor parking per society",
        6,
        "active",
        86,
        41,
        246,
        9840,
        "Auditing Prahladnagar parking",
        [
          "Audited 6 societies",
          "Flagged parking deficit",
          "Scored visitor parking",
          "Updated parking DB",
          "Generated parking report",
        ],
        ["Parking ratio calc", "Visitor space tracking", "Deficit flagging"],
        "simulated",
      ),
      a(
        "c26_16",
        "Lift & Amenity Audit AI",
        26,
        "Deep Property Intelligence",
        "Flags non-functional amenities based on resident data",
        7,
        "active",
        83,
        36,
        216,
        8640,
        "Auditing Thaltej amenities",
        [
          "Flagged 3 broken lifts",
          "Updated amenity status",
          "Scored 8 societies",
          "Pulled resident reports",
          "Generated audit log",
        ],
        ["Amenity status tracking", "Resident data parsing", "Defect flagging"],
        "simulated",
      ),
      a(
        "c26_17",
        "Builder Litigation Tracker AI",
        26,
        "Deep Property Intelligence",
        "Counts active court cases against any builder",
        8,
        "active",
        95,
        103,
        618,
        24720,
        "Scanning Adani Realty cases",
        [
          "Pulled court records",
          "Updated case counts",
          "Flagged high-litigation",
          "Tracked 15 builders",
          "Generated risk alerts",
        ],
        ["Court case tracking", "Builder risk scoring", "Legal DB sync"],
        "real",
      ),
      a(
        "c26_18",
        "Resale Velocity AI",
        26,
        "Deep Property Intelligence",
        "Tracks how fast properties in a society resell",
        7,
        "processing",
        89,
        67,
        402,
        16080,
        "Calculating Vastrapur resale days",
        [
          "Computed avg resale days",
          "Ranked top societies",
          "Flagged slow resale",
          "Updated velocity index",
          "Generated velocity chart",
        ],
        ["Resale speed calc", "Society ranking", "Trend detection"],
        "simulated",
      ),
      a(
        "c26_19",
        "Occupancy Rate AI",
        26,
        "Deep Property Intelligence",
        "Shows occupied vs vacant flat ratio per society",
        7,
        "active",
        90,
        81,
        486,
        19440,
        "Scanning Bodakdev occupancy",
        [
          "Updated occupancy data",
          "Flagged high vacancy",
          "Scored 12 societies",
          "Compared quarterly trends",
          "Generated occupancy map",
        ],
        ["Occupancy ratio calc", "Vacancy flagging", "Trend comparison"],
        "simulated",
      ),
      a(
        "c26_20",
        "Hidden Cost Estimator AI",
        26,
        "Deep Property Intelligence",
        "Calculates all costs beyond the listed price",
        9,
        "active",
        97,
        138,
        828,
        33120,
        "Computing total cost for 3BHK",
        [
          "Computed stamp duty",
          "Added GST charges",
          "Calculated maintenance deposit",
          "Estimated moving costs",
          "Generated total cost card",
        ],
        ["Total cost calc", "Duty computation", "Hidden fee detection"],
        "real",
      ),
    ],
  },
  {
    clusterId: 27,
    clusterName: "Deep Finance & Investment",
    clusterDescription:
      "Advanced financial analysis and investment intelligence tools",
    category: "Finance",
    color: "#f59e0b",
    agents: [
      a(
        "c27_1",
        "Portfolio Stress Test AI",
        27,
        "Deep Finance & Investment",
        "Simulates recession and rate hike scenarios on portfolio",
        8,
        "active",
        93,
        72,
        432,
        17280,
        "Running rate hike simulation",
        [
          "Ran recession scenario",
          "Tested vacancy stress",
          "Simulated rate +2%",
          "Scored portfolio risk",
          "Generated stress report",
        ],
        ["Portfolio simulation", "Risk scenario testing", "Resilience scoring"],
        "simulated",
      ),
      a(
        "c27_2",
        "Real Return Calculator AI",
        27,
        "Deep Finance & Investment",
        "Subtracts inflation and tax to show real returns",
        9,
        "active",
        96,
        115,
        690,
        27600,
        "Computing post-inflation returns",
        [
          "Calculated real returns",
          "Subtracted TDS impact",
          "Adjusted for inflation",
          "Compared 5yr returns",
          "Generated return card",
        ],
        ["Real return calc", "Inflation adjustment", "Tax impact analysis"],
        "real",
      ),
      a(
        "c27_3",
        "Opportunity Cost AI",
        27,
        "Deep Finance & Investment",
        "Compares property vs mutual funds and gold",
        8,
        "active",
        94,
        89,
        534,
        21360,
        "Comparing property vs MF",
        [
          "Ran property vs FD",
          "Compared gold returns",
          "Modelled SIP equivalent",
          "Generated comparison chart",
          "Updated benchmark data",
        ],
        [
          "Multi-asset comparison",
          "Return benchmarking",
          "Opportunity analysis",
        ],
        "simulated",
      ),
      a(
        "c27_4",
        "Black Money Risk AI",
        27,
        "Deep Finance & Investment",
        "Flags high cash component demand in transactions",
        9,
        "active",
        97,
        54,
        324,
        12960,
        "Scanning listing cash demands",
        [
          "Flagged 2 risky listings",
          "Reported cash patterns",
          "Alerted legal team",
          "Scored 15 listings",
          "Generated risk alerts",
        ],
        [
          "Cash demand detection",
          "Transaction risk scoring",
          "Compliance flagging",
        ],
        "real",
      ),
      a(
        "c27_5",
        "Tax Optimization AI",
        27,
        "Deep Finance & Investment",
        "Finds legal ways to minimize property transaction tax",
        9,
        "active",
        96,
        108,
        648,
        25920,
        "Optimizing stamp duty structure",
        [
          "Found 54EC opportunity",
          "Suggested joint ownership",
          "Reduced stamp duty",
          "Calculated tax savings",
          "Generated tax plan",
        ],
        [
          "Tax saving identification",
          "Legal structure advice",
          "Duty minimization",
        ],
        "real",
      ),
      a(
        "c27_6",
        "Home Loan Balance Transfer AI",
        27,
        "Deep Finance & Investment",
        "Analyzes if bank balance transfer saves money",
        8,
        "active",
        92,
        77,
        462,
        18480,
        "Comparing HDFC vs SBI rates",
        [
          "Compared 5 bank rates",
          "Calculated transfer savings",
          "Flagged best option",
          "Generated BT report",
          "Updated rate DB",
        ],
        ["Transfer saving calc", "Rate comparison", "Break-even analysis"],
        "real",
      ),
      a(
        "c27_7",
        "Pre-EMI vs Full EMI AI",
        27,
        "Deep Finance & Investment",
        "Calculates under-construction EMI difference",
        8,
        "active",
        91,
        63,
        378,
        15120,
        "Computing pre-EMI for Godrej",
        [
          "Calculated pre-EMI cost",
          "Compared full EMI",
          "Generated recommendation",
          "Scored 6 projects",
          "Updated EMI models",
        ],
        ["EMI comparison", "Under-construction calc", "Cost difference"],
        "real",
      ),
      a(
        "c27_8",
        "Joint Ownership Tax AI",
        27,
        "Deep Finance & Investment",
        "Shows tax benefits of husband-wife joint ownership",
        8,
        "active",
        95,
        88,
        528,
        21120,
        "Calculating joint ownership tax",
        [
          "Computed HRA benefits",
          "Calculated 80C savings",
          "Showed stamp concession",
          "Generated tax card",
          "Ran 10 scenarios",
        ],
        [
          "Joint ownership tax calc",
          "HRA optimization",
          "Stamp duty concession",
        ],
        "real",
      ),
      a(
        "c27_9",
        "NRI Tax Complexity AI",
        27,
        "Deep Finance & Investment",
        "Explains NRI-specific TDS DTAA and repatriation rules",
        8,
        "idle",
        90,
        31,
        186,
        7440,
        "Idle - NRI query queue empty",
        [
          "Explained TDS rules",
          "Clarified DTAA treaty",
          "Guided repatriation",
          "Generated NRI guide",
          "Updated policy data",
        ],
        ["NRI TDS calculation", "DTAA application", "Repatriation guidance"],
        "real",
      ),
      a(
        "c27_10",
        "GIFT City Investment AI",
        27,
        "Deep Finance & Investment",
        "Covers IFSC zone benefits and foreign currency options",
        7,
        "active",
        89,
        45,
        270,
        10800,
        "Analysing GIFT City yield",
        [
          "Updated IFSC benefits",
          "Compared GIFT vs local",
          "Generated yield report",
          "Flagged currency options",
          "Ran investment model",
        ],
        ["IFSC benefit analysis", "Currency option calc", "GIFT City modeling"],
        "simulated",
      ),
      a(
        "c27_11",
        "Succession Planning AI",
        27,
        "Deep Finance & Investment",
        "Compares will vs gift deed vs family trust options",
        8,
        "active",
        93,
        59,
        354,
        14160,
        "Generating succession options",
        [
          "Compared 3 structures",
          "Calculated tax impact",
          "Generated succession plan",
          "Flagged legal steps",
          "Updated template library",
        ],
        [
          "Succession structure compare",
          "Tax implication calc",
          "Legal step guidance",
        ],
        "real",
      ),
      a(
        "c27_12",
        "PMAY Eligibility AI",
        27,
        "Deep Finance & Investment",
        "Checks PMAY subsidy eligibility and subsidy amount",
        9,
        "active",
        97,
        124,
        744,
        29760,
        "Checking PMAY eligibility",
        [
          "Verified 8 applications",
          "Calculated subsidies",
          "Flagged ineligible",
          "Generated eligibility card",
          "Updated PMAY rules",
        ],
        ["PMAY eligibility check", "Subsidy calculation", "Rule validation"],
        "real",
      ),
      a(
        "c27_13",
        "Credit Score Impact AI",
        27,
        "Deep Finance & Investment",
        "Models how home loan affects CIBIL score over time",
        7,
        "active",
        88,
        52,
        312,
        12480,
        "Modelling CIBIL impact for client",
        [
          "Ran CIBIL model",
          "Projected 2yr score",
          "Flagged risk factors",
          "Generated impact chart",
          "Updated credit model",
        ],
        ["CIBIL impact modelling", "Score projection", "Risk factor analysis"],
        "simulated",
      ),
      a(
        "c27_14",
        "SARFAESI Alert AI",
        27,
        "Deep Finance & Investment",
        "Flags properties under SARFAESI bank action",
        9,
        "active",
        96,
        41,
        246,
        9840,
        "Scanning SARFAESI notices",
        [
          "Found 2 SARFAESI props",
          "Flagged auction risk",
          "Alerted buyers",
          "Updated notice DB",
          "Generated risk alerts",
        ],
        ["SARFAESI detection", "Bank action flagging", "Buyer risk alert"],
        "real",
      ),
      a(
        "c27_15",
        "Auction Property Intelligence AI",
        27,
        "Deep Finance & Investment",
        "Guides buyers through bank auction property process",
        8,
        "idle",
        91,
        28,
        168,
        6720,
        "Idle - auction queue empty",
        [
          "Explained auction process",
          "Listed upcoming auctions",
          "Guided documentation",
          "Flagged reserve prices",
          "Generated auction guide",
        ],
        [
          "Auction process guidance",
          "Reserve price tracking",
          "Documentation checklist",
        ],
        "real",
      ),
      a(
        "c27_16",
        "Developer Finance AI",
        27,
        "Deep Finance & Investment",
        "Analyses construction finance options for builders",
        7,
        "active",
        87,
        47,
        282,
        11280,
        "Analysing builder loan options",
        [
          "Compared 4 lenders",
          "Calculated construction cost",
          "Modelled draw schedule",
          "Generated finance plan",
          "Updated lender DB",
        ],
        [
          "Construction finance calc",
          "Lender comparison",
          "Draw schedule model",
        ],
        "simulated",
      ),
      a(
        "c27_17",
        "Lease vs Buy Commercial AI",
        27,
        "Deep Finance & Investment",
        "Compares lease vs buy for commercial properties",
        8,
        "active",
        92,
        66,
        396,
        15840,
        "Running lease vs buy model",
        [
          "Ran 5yr lease model",
          "Calculated buy IRR",
          "Compared NPV outcomes",
          "Generated decision chart",
          "Updated commercial DB",
        ],
        ["Lease buy comparison", "IRR calculation", "NPV analysis"],
        "real",
      ),
      a(
        "c27_18",
        "Reinvestment Planner AI",
        27,
        "Deep Finance & Investment",
        "Shows capital gains reinvestment options under 54EC",
        9,
        "active",
        95,
        83,
        498,
        19920,
        "Planning 54F reinvestment",
        [
          "Identified 54EC bonds",
          "Calculated LTCG savings",
          "Suggested 54F property",
          "Generated reinvest plan",
          "Updated tax rules",
        ],
        ["Capital gains planning", "54EC bond guidance", "LTCG minimization"],
        "real",
      ),
      a(
        "c27_19",
        "SIP + Property Combo AI",
        27,
        "Deep Finance & Investment",
        "Builds hybrid SIP plus property wealth plan",
        7,
        "active",
        89,
        58,
        348,
        13920,
        "Building hybrid wealth plan",
        [
          "Modelled SIP+property mix",
          "Optimised allocation",
          "Ran 10yr projection",
          "Generated wealth plan",
          "Updated fund data",
        ],
        [
          "SIP property blending",
          "Allocation optimization",
          "Wealth projection",
        ],
        "simulated",
      ),
      a(
        "c27_20",
        "EMI Affordability Timeline AI",
        27,
        "Deep Finance & Investment",
        "Shows month when EMI drops under 30% of income",
        8,
        "active",
        93,
        99,
        594,
        23760,
        "Projecting EMI relief timeline",
        [
          "Computed income growth",
          "Calculated EMI timeline",
          "Flagged relief month",
          "Generated timeline chart",
          "Updated salary model",
        ],
        [
          "EMI timeline projection",
          "Income growth modeling",
          "Relief month calculation",
        ],
        "simulated",
      ),
    ],
  },
  {
    clusterId: 28,
    clusterName: "Legal & Compliance Deep",
    clusterDescription:
      "Deep legal analysis and compliance tools for property transactions",
    category: "Legal",
    color: "#8b5cf6",
    agents: [
      a(
        "c28_1",
        "Title Chain Verifier AI",
        28,
        "Legal & Compliance Deep",
        "Traces property ownership chain back 30 years",
        9,
        "active",
        96,
        74,
        444,
        17760,
        "Verifying Vastrapur plot title",
        [
          "Traced 3 title chains",
          "Flagged ownership gap",
          "Verified mutation records",
          "Generated title report",
          "Updated legal DB",
        ],
        ["Title chain tracing", "Gap detection", "Mutation verification"],
        "real",
      ),
      a(
        "c28_2",
        "Encumbrance Certificate Reader AI",
        28,
        "Legal & Compliance Deep",
        "Extracts and explains all encumbrances from EC",
        9,
        "active",
        97,
        88,
        528,
        21120,
        "Reading EC for Satellite flat",
        [
          "Read 5 EC documents",
          "Extracted lien details",
          "Flagged active charges",
          "Generated EC summary",
          "Updated encumbrance DB",
        ],
        ["EC extraction", "Encumbrance explanation", "Lien detection"],
        "real",
      ),
      a(
        "c28_3",
        "Sale Deed Analyzer AI",
        28,
        "Legal & Compliance Deep",
        "Extracts material terms and flags risks in deeds",
        9,
        "active",
        95,
        63,
        378,
        15120,
        "Analysing Bodakdev sale deed",
        [
          "Analysed 4 deeds",
          "Flagged risky clauses",
          "Extracted key terms",
          "Generated risk report",
          "Updated clause DB",
        ],
        [
          "Deed term extraction",
          "Risk clause flagging",
          "Plain language summary",
        ],
        "real",
      ),
      a(
        "c28_4",
        "Power of Attorney Risk AI",
        28,
        "Legal & Compliance Deep",
        "Detects and flags risky GPA-based transactions",
        9,
        "active",
        96,
        47,
        282,
        11280,
        "Scanning GPA transactions",
        [
          "Flagged 2 GPA risks",
          "Alerted buyers",
          "Reviewed 8 transactions",
          "Generated risk alerts",
          "Updated GPA rules",
        ],
        ["GPA risk detection", "Transaction flagging", "Buyer alerting"],
        "real",
      ),
      a(
        "c28_5",
        "Benami Property Alert AI",
        28,
        "Legal & Compliance Deep",
        "Flags properties with potential Benami transaction risk",
        9,
        "active",
        97,
        39,
        234,
        9360,
        "Scanning for Benami patterns",
        [
          "Flagged 1 Benami risk",
          "Reviewed ownership chain",
          "Alerted compliance",
          "Generated Benami alert",
          "Updated detection model",
        ],
        [
          "Benami pattern detection",
          "Ownership analysis",
          "Compliance alerting",
        ],
        "real",
      ),
      a(
        "c28_6",
        "Court Order Checker AI",
        28,
        "Legal & Compliance Deep",
        "Checks for court stays or attachments on property",
        9,
        "active",
        96,
        55,
        330,
        13200,
        "Checking court orders for plot",
        [
          "Checked 6 properties",
          "Found 1 attachment",
          "Pulled court records",
          "Generated order report",
          "Updated court DB",
        ],
        ["Court order checking", "Attachment detection", "Stay order tracking"],
        "real",
      ),
      a(
        "c28_7",
        "RERA Complaint History AI",
        28,
        "Legal & Compliance Deep",
        "Shows full RERA complaint history for any project",
        9,
        "active",
        95,
        82,
        492,
        19680,
        "Fetching RERA complaints",
        [
          "Pulled RERA data",
          "Found 3 complaints",
          "Ranked complaint severity",
          "Generated history card",
          "Updated RERA DB",
        ],
        [
          "RERA history fetch",
          "Complaint severity ranking",
          "Project risk scoring",
        ],
        "real",
      ),
      a(
        "c28_8",
        "Society NOC Tracker AI",
        28,
        "Legal & Compliance Deep",
        "Tracks NOC requirements for resale transactions",
        8,
        "idle",
        88,
        24,
        144,
        5760,
        "Idle - no active resale NOCs",
        [
          "Tracked 3 NOC requests",
          "Sent deadline reminder",
          "Flagged pending NOC",
          "Generated NOC checklist",
          "Updated society DB",
        ],
        ["NOC requirement tracking", "Deadline reminders", "Resale compliance"],
        "real",
      ),
      a(
        "c28_9",
        "Mutation Status Tracker AI",
        28,
        "Legal & Compliance Deep",
        "Tracks property mutation status in AMC records",
        8,
        "active",
        92,
        61,
        366,
        14640,
        "Checking mutation for buyer",
        [
          "Tracked 5 mutations",
          "Flagged pending status",
          "Pulled AMC records",
          "Generated mutation report",
          "Updated status DB",
        ],
        ["Mutation status check", "AMC record sync", "Pending flag"],
        "real",
      ),
      a(
        "c28_10",
        "Property Tax Dues Checker AI",
        28,
        "Legal & Compliance Deep",
        "Checks outstanding AMC property tax for any listing",
        9,
        "active",
        97,
        93,
        558,
        22320,
        "Checking tax dues for seller",
        [
          "Checked 7 properties",
          "Found Rs 24k dues",
          "Alerted seller agent",
          "Generated dues report",
          "Updated tax DB",
        ],
        ["Tax dues checking", "Outstanding detection", "AMC data sync"],
        "real",
      ),
      a(
        "c28_11",
        "Development Plan Compliance AI",
        28,
        "Legal & Compliance Deep",
        "Checks if construction matches approved dev plan",
        8,
        "active",
        91,
        42,
        252,
        10080,
        "Checking DP compliance",
        [
          "Verified 3 constructions",
          "Flagged FSI violation",
          "Pulled DP approvals",
          "Generated compliance report",
          "Updated plan DB",
        ],
        ["DP compliance check", "FSI verification", "Approval matching"],
        "real",
      ),
      a(
        "c28_12",
        "FSI & TDR Calculator AI",
        28,
        "Legal & Compliance Deep",
        "Calculates Floor Space Index and TDR for any plot",
        9,
        "active",
        96,
        76,
        456,
        18240,
        "Computing FSI for plot",
        [
          "Calculated plot FSI",
          "Added TDR potential",
          "Generated FSI report",
          "Scored development potential",
          "Updated DP zones",
        ],
        ["FSI calculation", "TDR computation", "Development potential"],
        "real",
      ),
      a(
        "c28_13",
        "Conversion Permission AI",
        28,
        "Legal & Compliance Deep",
        "Guides agricultural to non-agricultural land conversion",
        8,
        "idle",
        89,
        19,
        114,
        4560,
        "Idle - no conversion requests",
        [
          "Guided NA conversion",
          "Listed required docs",
          "Checked zone status",
          "Generated conversion guide",
          "Updated policy DB",
        ],
        ["NA conversion guidance", "Document checklist", "Zone verification"],
        "real",
      ),
      a(
        "c28_14",
        "Dispute Resolution Guide AI",
        28,
        "Legal & Compliance Deep",
        "Guides through RERA civil court or consumer forum",
        8,
        "active",
        93,
        53,
        318,
        12720,
        "Guiding RERA dispute case",
        [
          "Guided 2 RERA cases",
          "Suggested civil court",
          "Drafted complaint steps",
          "Generated resolution plan",
          "Updated case DB",
        ],
        ["RERA guidance", "Forum selection", "Step-by-step plan"],
        "real",
      ),
      a(
        "c28_15",
        "Agreement to Sale vs Sale Deed AI",
        28,
        "Legal & Compliance Deep",
        "Explains difference risks and next steps per stage",
        8,
        "active",
        92,
        67,
        402,
        16080,
        "Explaining ATS vs sale deed",
        [
          "Explained ATS timeline",
          "Flagged ATS risks",
          "Guided deed registration",
          "Generated comparison card",
          "Updated legal guide",
        ],
        ["ATS vs deed comparison", "Risk explanation", "Stage guidance"],
        "real",
      ),
    ],
  },
  {
    clusterId: 29,
    clusterName: "Events Hospitality & Cultural",
    clusterDescription:
      "Complete AI suite for events hospitality and cultural management",
    category: "Events",
    color: "#ec4899",
    agents: [
      a(
        "c29_1",
        "Event Capacity Optimizer AI",
        29,
        "Events Hospitality & Cultural",
        "Recommends perfect venue config for guest count and budget",
        8,
        "active",
        91,
        57,
        342,
        13680,
        "Optimising 200-guest venue layout",
        [
          "Optimised banquet layout",
          "Suggested theatre config",
          "Calculated standing capacity",
          "Generated seating plan",
          "Updated venue DB",
        ],
        ["Venue config optimization", "Capacity planning", "Budget alignment"],
        "simulated",
      ),
      a(
        "c29_2",
        "Catering Intelligence AI",
        29,
        "Events Hospitality & Cultural",
        "Suggests catering packages quantities and pricing",
        7,
        "active",
        88,
        43,
        258,
        10320,
        "Suggesting wedding catering menu",
        [
          "Suggested Gujarati menu",
          "Calculated per-head cost",
          "Compared 3 caterers",
          "Generated catering plan",
          "Updated menu DB",
        ],
        [
          "Catering package suggestion",
          "Quantity calculation",
          "Caterer comparison",
        ],
        "simulated",
      ),
      a(
        "c29_3",
        "Entertainment Matcher AI",
        29,
        "Events Hospitality & Cultural",
        "Matches artists and performers to event type and budget",
        8,
        "active",
        92,
        68,
        408,
        16320,
        "Matching artist for Navratri",
        [
          "Matched 3 garba artists",
          "Checked availability",
          "Compared quotes",
          "Generated artist card",
          "Updated booking DB",
        ],
        ["Artist matching", "Budget alignment", "Availability check"],
        "simulated",
      ),
      a(
        "c29_4",
        "Event Budget Planner AI",
        29,
        "Events Hospitality & Cultural",
        "Creates complete event budget breakdown instantly",
        8,
        "active",
        93,
        84,
        504,
        20160,
        "Building corporate event budget",
        [
          "Built wedding budget",
          "Calculated venue %",
          "Added contingency",
          "Generated budget sheet",
          "Updated cost DB",
        ],
        ["Budget breakdown", "Cost allocation", "Contingency planning"],
        "real",
      ),
      a(
        "c29_5",
        "RSVP Intelligence AI",
        29,
        "Events Hospitality & Cultural",
        "Predicts actual attendance from confirmed RSVPs",
        7,
        "idle",
        85,
        21,
        126,
        5040,
        "Idle - no active events",
        [
          "Predicted attendance",
          "Applied no-show model",
          "Generated headcount",
          "Flagged low RSVP",
          "Updated RSVP model",
        ],
        ["Attendance prediction", "No-show modeling", "Headcount generation"],
        "simulated",
      ),
      a(
        "c29_6",
        "Event Day Timeline AI",
        29,
        "Events Hospitality & Cultural",
        "Generates minute-by-minute event day timeline",
        8,
        "active",
        90,
        49,
        294,
        11760,
        "Building Diwali event timeline",
        [
          "Built 8hr timeline",
          "Added buffer slots",
          "Flagged clash risks",
          "Generated printable plan",
          "Updated template DB",
        ],
        ["Timeline generation", "Buffer planning", "Clash detection"],
        "simulated",
      ),
      a(
        "c29_7",
        "Vendor Comparison AI",
        29,
        "Events Hospitality & Cultural",
        "Compares vendors side by side for any category",
        8,
        "active",
        92,
        76,
        456,
        18240,
        "Comparing 4 decor vendors",
        [
          "Compared 5 caterers",
          "Ranked decor vendors",
          "Scored AV suppliers",
          "Generated comparison table",
          "Updated vendor DB",
        ],
        ["Vendor ranking", "Side-by-side comparison", "Score generation"],
        "real",
      ),
      a(
        "c29_8",
        "Post-Event Analytics AI",
        29,
        "Events Hospitality & Cultural",
        "Analyses attendance feedback and cost after events",
        7,
        "idle",
        87,
        16,
        96,
        3840,
        "Idle - processing last event data",
        [
          "Calculated cost-per-head",
          "Scored feedback 4.2/5",
          "Generated post report",
          "Flagged improvements",
          "Updated analytics DB",
        ],
        ["Post-event analysis", "Feedback scoring", "Cost-per-head calc"],
        "real",
      ),
      a(
        "c29_9",
        "Cultural Calendar AI",
        29,
        "Events Hospitality & Cultural",
        "Maintains live calendar of Ahmedabad cultural events",
        7,
        "active",
        89,
        62,
        372,
        14880,
        "Updating Navratri calendar",
        [
          "Added 5 MSTC events",
          "Pulled festival dates",
          "Updated cultural DB",
          "Generated calendar view",
          "Flagged date conflicts",
        ],
        [
          "Cultural event tracking",
          "Festival calendar",
          "Date conflict detection",
        ],
        "real",
      ),
      a(
        "c29_10",
        "Artist Availability AI",
        29,
        "Events Hospitality & Cultural",
        "Checks artist calendar and shows available booking slots",
        8,
        "active",
        91,
        53,
        318,
        12720,
        "Checking Falguni Pathak slots",
        [
          "Checked 8 artist calendars",
          "Found 3 open dates",
          "Flagged conflicts",
          "Generated availability card",
          "Updated artist DB",
        ],
        ["Artist calendar check", "Slot availability", "Conflict flagging"],
        "real",
      ),
      a(
        "c29_11",
        "Event Permit Guide AI",
        29,
        "Events Hospitality & Cultural",
        "Guides through all Ahmedabad event permit requirements",
        8,
        "active",
        93,
        38,
        228,
        9120,
        "Generating police NOC guide",
        [
          "Listed police NOC steps",
          "Added fire permit guide",
          "Included food license",
          "Generated permit checklist",
          "Updated legal DB",
        ],
        [
          "Permit requirement guide",
          "NOC documentation",
          "Compliance checklist",
        ],
        "real",
      ),
      a(
        "c29_12",
        "Hospitality Package Builder AI",
        29,
        "Events Hospitality & Cultural",
        "Builds custom hospitality packages for corporates",
        7,
        "active",
        88,
        45,
        270,
        10800,
        "Building pharma corp package",
        [
          "Built 3 corp packages",
          "Priced accommodation",
          "Added transport options",
          "Generated package PDF",
          "Updated package DB",
        ],
        ["Package customization", "Corporate pricing", "PDF generation"],
        "simulated",
      ),
      a(
        "c29_13",
        "Wedding Planner AI",
        29,
        "Events Hospitality & Cultural",
        "Handles full wedding venue catering and cultural planning",
        9,
        "active",
        95,
        97,
        582,
        23280,
        "Planning Patel wedding 2025",
        [
          "Booked 3 venues",
          "Arranged 200-pax catering",
          "Coordinated garba",
          "Generated wedding plan",
          "Updated booking DB",
        ],
        ["Full wedding planning", "Vendor coordination", "Timeline management"],
        "simulated",
      ),
      a(
        "c29_14",
        "Corporate Event AI",
        29,
        "Events Hospitality & Cultural",
        "Manages product launches conferences and corporate events",
        8,
        "active",
        92,
        71,
        426,
        17040,
        "Planning tech product launch",
        [
          "Planned AGM event",
          "Booked conference hall",
          "Arranged AV setup",
          "Generated event brief",
          "Updated corp DB",
        ],
        [
          "Corporate event planning",
          "Conference management",
          "AV coordination",
        ],
        "simulated",
      ),
      a(
        "c29_15",
        "Social Media Event AI",
        29,
        "Events Hospitality & Cultural",
        "Generates pre during and post event social content calendar",
        7,
        "active",
        89,
        58,
        348,
        13920,
        "Creating Navratri content plan",
        [
          "Created Instagram plan",
          "Generated reel ideas",
          "Drafted post captions",
          "Scheduled content calendar",
          "Updated social DB",
        ],
        ["Social content generation", "Content calendar", "Caption drafting"],
        "simulated",
      ),
    ],
  },
  {
    clusterId: 30,
    clusterName: "NGO CSR & Social Impact",
    clusterDescription:
      "AI tools for NGO operations CSR management and social impact measurement",
    category: "NGO",
    color: "#06b6d4",
    agents: [
      a(
        "c30_1",
        "CSR Spend Optimizer AI",
        30,
        "NGO CSR & Social Impact",
        "Helps corporates allocate CSR budget for maximum impact",
        8,
        "active",
        92,
        44,
        264,
        10560,
        "Optimising CSR for pharma client",
        [
          "Optimised 3 CSR budgets",
          "Ranked NGO initiatives",
          "Calculated impact ROI",
          "Generated allocation plan",
          "Updated impact DB",
        ],
        [
          "CSR allocation optimization",
          "Impact ROI calculation",
          "Initiative ranking",
        ],
        "simulated",
      ),
      a(
        "c30_2",
        "Impact Report Generator AI",
        30,
        "NGO CSR & Social Impact",
        "Auto-generates quarterly CSR impact reports with visuals",
        8,
        "active",
        91,
        37,
        222,
        8880,
        "Generating Q1 impact report",
        [
          "Generated Q4 report",
          "Added 12 visuals",
          "Calculated lives impacted",
          "Generated PDF report",
          "Updated report DB",
        ],
        [
          "Impact report generation",
          "Visualization creation",
          "Lives-impacted calc",
        ],
        "real",
      ),
      a(
        "c30_3",
        "Donation Tax Benefit AI",
        30,
        "NGO CSR & Social Impact",
        "Shows exact 80G tax benefit for any donation amount",
        9,
        "active",
        97,
        88,
        528,
        21120,
        "Calculating 80G for donation",
        [
          "Calculated 5 80G benefits",
          "Generated tax certificates",
          "Updated 80G rules",
          "Ran batch calculations",
          "Generated benefit cards",
        ],
        [
          "80G tax calculation",
          "Donation optimization",
          "Certificate generation",
        ],
        "real",
      ),
      a(
        "c30_4",
        "Volunteer Matcher AI",
        30,
        "NGO CSR & Social Impact",
        "Matches volunteers to initiatives by skills and location",
        7,
        "active",
        88,
        31,
        186,
        7440,
        "Matching volunteers for drive",
        [
          "Matched 15 volunteers",
          "Scored skill fit",
          "Checked availability",
          "Generated match report",
          "Updated volunteer DB",
        ],
        ["Volunteer matching", "Skill fit scoring", "Availability check"],
        "simulated",
      ),
      a(
        "c30_5",
        "Grant Opportunity AI",
        30,
        "NGO CSR & Social Impact",
        "Scans available grants applicable to MSTC NGO work",
        8,
        "active",
        90,
        26,
        156,
        6240,
        "Scanning new govt grants",
        [
          "Found 2 new grants",
          "Calculated eligibility",
          "Generated grant guide",
          "Flagged deadlines",
          "Updated grant DB",
        ],
        ["Grant discovery", "Eligibility checking", "Deadline tracking"],
        "real",
      ),
      a(
        "c30_6",
        "Social Impact Scorecard AI",
        30,
        "NGO CSR & Social Impact",
        "Shows live MSTC NGO impact scorecard visibly",
        8,
        "active",
        93,
        51,
        306,
        12240,
        "Updating impact scorecard",
        [
          "Updated lives count",
          "Added project milestones",
          "Calculated impact score",
          "Generated scorecard",
          "Updated metrics DB",
        ],
        ["Impact scoring", "Lives-touched tracking", "Milestone measurement"],
        "real",
      ),
      a(
        "c30_7",
        "Community Need Mapper AI",
        30,
        "NGO CSR & Social Impact",
        "Maps underserved communities with NGO opportunity overlay",
        7,
        "idle",
        86,
        18,
        108,
        4320,
        "Idle - awaiting census data",
        [
          "Mapped 5 communities",
          "Scored need levels",
          "Flagged priority zones",
          "Generated need map",
          "Updated community DB",
        ],
        ["Need mapping", "Priority zone detection", "Opportunity overlay"],
        "simulated",
      ),
      a(
        "c30_8",
        "Fundraising AI",
        30,
        "NGO CSR & Social Impact",
        "Generates fundraising campaigns and tracks progress",
        8,
        "active",
        91,
        62,
        372,
        14880,
        "Running Diwali fundraiser",
        [
          "Generated campaign brief",
          "Set Rs 5L target",
          "Tracked 62% progress",
          "Generated donor report",
          "Updated fundraise DB",
        ],
        ["Campaign generation", "Target tracking", "Donor reporting"],
        "simulated",
      ),
      a(
        "c30_9",
        "NGO Compliance AI",
        30,
        "NGO CSR & Social Impact",
        "Tracks FCRA 80G annual filing deadlines for MSTC NGO",
        9,
        "active",
        96,
        43,
        258,
        10320,
        "Checking FCRA renewal date",
        [
          "Checked FCRA status",
          "Flagged 80G renewal",
          "Tracked annual filing",
          "Generated compliance calendar",
          "Updated deadline DB",
        ],
        ["FCRA compliance tracking", "80G renewal", "Filing deadline alert"],
        "real",
      ),
      a(
        "c30_10",
        "Storytelling AI",
        30,
        "NGO CSR & Social Impact",
        "Generates compelling impact stories from raw data",
        7,
        "active",
        89,
        55,
        330,
        13200,
        "Writing impact story for donor",
        [
          "Wrote 3 impact stories",
          "Generated donor narrative",
          "Created beneficiary profile",
          "Drafted annual story",
          "Updated story library",
        ],
        ["Impact story writing", "Donor narrative", "Beneficiary profile"],
        "simulated",
      ),
    ],
  },
  {
    clusterId: 31,
    clusterName: "Sports Music & Media",
    clusterDescription:
      "Complete AI suite for sports music media and tourism management",
    category: "Media",
    color: "#f97316",
    agents: [
      a(
        "c31_1",
        "Athlete Profile AI",
        31,
        "Sports Music & Media",
        "Builds rich profile cards with stats and sponsorship status",
        8,
        "active",
        92,
        61,
        366,
        14640,
        "Building cricketer profile card",
        [
          "Built 5 athlete profiles",
          "Updated achievement stats",
          "Scored sponsorship value",
          "Generated profile cards",
          "Updated athlete DB",
        ],
        ["Profile card generation", "Stats tracking", "Sponsorship scoring"],
        "real",
      ),
      a(
        "c31_2",
        "Sponsorship Matcher AI",
        31,
        "Sports Music & Media",
        "Matches brands to athletes by demographics and budget",
        8,
        "active",
        91,
        48,
        288,
        11520,
        "Matching brand for footballer",
        [
          "Matched 3 brand-athlete pairs",
          "Scored demographic fit",
          "Compared budgets",
          "Generated match report",
          "Updated sponsorship DB",
        ],
        [
          "Brand-athlete matching",
          "Demographic fit scoring",
          "Budget comparison",
        ],
        "simulated",
      ),
      a(
        "c31_3",
        "Sports Event Planner AI",
        31,
        "Sports Music & Media",
        "Plans complete tournaments with fixtures and logistics",
        8,
        "active",
        90,
        73,
        438,
        17520,
        "Planning district cricket event",
        [
          "Planned 5-team fixture",
          "Booked ground",
          "Arranged umpires",
          "Generated event schedule",
          "Updated event DB",
        ],
        ["Tournament planning", "Fixture generation", "Logistics coordination"],
        "simulated",
      ),
      a(
        "c31_4",
        "Performance Analytics AI",
        31,
        "Sports Music & Media",
        "Tracks athlete performance metrics with visible charts",
        8,
        "active",
        93,
        84,
        504,
        20160,
        "Tracking sprinter performance",
        [
          "Tracked 8 athletes",
          "Charted improvement curve",
          "Flagged performance drop",
          "Generated analytics report",
          "Updated metrics DB",
        ],
        ["Performance tracking", "Chart generation", "Trend detection"],
        "real",
      ),
      a(
        "c31_5",
        "Music Genre Intelligence AI",
        31,
        "Sports Music & Media",
        "Categorises artists by genre style language and suitability",
        7,
        "active",
        88,
        52,
        312,
        12480,
        "Categorising new Gujarati artist",
        [
          "Categorised 10 artists",
          "Scored event suitability",
          "Mapped genre clusters",
          "Generated genre tags",
          "Updated music DB",
        ],
        ["Genre categorization", "Suitability scoring", "Style mapping"],
        "simulated",
      ),
      a(
        "c31_6",
        "Artist Booking AI",
        31,
        "Sports Music & Media",
        "Manages full artist booking workflow end to end",
        9,
        "active",
        96,
        99,
        594,
        23760,
        "Processing booking for Diwali",
        [
          "Processed 3 bookings",
          "Sent quote to client",
          "Generated agreement draft",
          "Tracked payment status",
          "Updated booking DB",
        ],
        ["Full booking workflow", "Agreement generation", "Payment tracking"],
        "real",
      ),
      a(
        "c31_7",
        "Royalty Tracker AI",
        31,
        "Sports Music & Media",
        "Tracks music royalties and payments for MSTC artists",
        8,
        "active",
        94,
        45,
        270,
        10800,
        "Tracking royalties for artist",
        [
          "Tracked 12 royalty entries",
          "Calculated quarterly due",
          "Generated royalty statement",
          "Flagged overdue payments",
          "Updated royalty DB",
        ],
        ["Royalty calculation", "Payment tracking", "Statement generation"],
        "real",
      ),
      a(
        "c31_8",
        "Media Coverage Tracker AI",
        31,
        "Sports Music & Media",
        "Aggregates all media coverage of MSTC events and clients",
        7,
        "active",
        89,
        67,
        402,
        16080,
        "Tracking coverage for launch",
        [
          "Pulled 8 news mentions",
          "Scored coverage quality",
          "Summarised media reach",
          "Generated coverage report",
          "Updated media DB",
        ],
        ["Media monitoring", "Coverage scoring", "Reach calculation"],
        "real",
      ),
      a(
        "c31_9",
        "Streaming Analytics AI",
        31,
        "Sports Music & Media",
        "Tracks live stream viewer count and engagement metrics",
        7,
        "idle",
        85,
        15,
        90,
        3600,
        "Idle - no active streams",
        [
          "Tracked last event stream",
          "Calculated peak viewers",
          "Scored engagement rate",
          "Generated stream report",
          "Updated analytics DB",
        ],
        ["Stream viewer tracking", "Engagement scoring", "Peak detection"],
        "real",
      ),
      a(
        "c31_10",
        "Press Release Generator AI",
        31,
        "Sports Music & Media",
        "Auto-generates press releases for all MSTC events",
        8,
        "active",
        93,
        58,
        348,
        13920,
        "Drafting award ceremony PR",
        [
          "Drafted 3 press releases",
          "Added media quotes",
          "Generated distribution list",
          "Sent to media contacts",
          "Updated PR library",
        ],
        ["Press release generation", "Media distribution", "Quote integration"],
        "simulated",
      ),
      a(
        "c31_11",
        "Tourism Itinerary AI",
        31,
        "Sports Music & Media",
        "Builds complete Gujarat travel itineraries",
        8,
        "active",
        91,
        76,
        456,
        18240,
        "Building 5-day Gujarat itinerary",
        [
          "Built heritage route",
          "Added MSTC properties",
          "Calculated travel cost",
          "Generated itinerary PDF",
          "Updated tourism DB",
        ],
        ["Itinerary generation", "Property integration", "Cost calculation"],
        "simulated",
      ),
      a(
        "c31_12",
        "Destination Intelligence AI",
        31,
        "Sports Music & Media",
        "Provides rich destination profiles with best season data",
        7,
        "active",
        88,
        44,
        264,
        10560,
        "Profiling Rann of Kutch",
        [
          "Profiled 6 destinations",
          "Added seasonal data",
          "Scored attraction quality",
          "Generated destination card",
          "Updated destination DB",
        ],
        ["Destination profiling", "Seasonal analysis", "Attraction scoring"],
        "simulated",
      ),
      a(
        "c31_13",
        "Travel Cost Estimator AI",
        31,
        "Sports Music & Media",
        "Estimates complete trip costs including all categories",
        8,
        "active",
        92,
        83,
        498,
        19920,
        "Estimating Gujarat trip cost",
        [
          "Estimated 4 trip budgets",
          "Added transport costs",
          "Included accommodation",
          "Generated cost breakdown",
          "Updated cost DB",
        ],
        ["Full trip cost calc", "Transport pricing", "Accommodation costing"],
        "real",
      ),
      a(
        "c31_14",
        "Influencer Collaboration AI",
        31,
        "Sports Music & Media",
        "Identifies and manages travel lifestyle influencer relationships",
        7,
        "active",
        87,
        39,
        234,
        9360,
        "Identifying Gujarat influencers",
        [
          "Found 5 influencers",
          "Scored follower fit",
          "Drafted collaboration brief",
          "Tracked engagement",
          "Updated influencer DB",
        ],
        ["Influencer discovery", "Fit scoring", "Collaboration tracking"],
        "simulated",
      ),
      a(
        "c31_15",
        "Content Monetization AI",
        31,
        "Sports Music & Media",
        "Identifies revenue from content licensing and syndication",
        7,
        "active",
        89,
        47,
        282,
        11280,
        "Finding monetization for videos",
        [
          "Found 2 license opportunities",
          "Calculated syndication value",
          "Identified platform deals",
          "Generated monetization plan",
          "Updated revenue DB",
        ],
        [
          "Monetization discovery",
          "License valuation",
          "Platform deal finding",
        ],
        "simulated",
      ),
    ],
  },
  {
    clusterId: 32,
    clusterName: "Advanced Analytics & Reporting",
    clusterDescription:
      "Deep analytics reporting and business intelligence for all MSTC operations",
    category: "Analytics",
    color: "#6366f1",
    agents: [
      a(
        "c32_1",
        "Real-Time Revenue Dashboard AI",
        32,
        "Advanced Analytics & Reporting",
        "Tracks live revenue across all MSTC service lines",
        9,
        "active",
        97,
        142,
        852,
        34080,
        "Updating revenue dashboard",
        [
          "Updated 8 service lines",
          "Calculated daily revenue",
          "Flagged low-revenue line",
          "Generated revenue chart",
          "Synced payment data",
        ],
        [
          "Live revenue tracking",
          "Service line breakdown",
          "Payment data sync",
        ],
        "real",
      ),
      a(
        "c32_2",
        "Lead-to-Deal Conversion AI",
        32,
        "Advanced Analytics & Reporting",
        "Tracks every lead through funnel with stage rates",
        9,
        "active",
        96,
        118,
        708,
        28320,
        "Calculating conversion rates",
        [
          "Tracked 45 leads",
          "Calculated stage rates",
          "Flagged drop-off point",
          "Generated funnel chart",
          "Updated CRM data",
        ],
        ["Funnel stage tracking", "Conversion rate calc", "Drop-off detection"],
        "real",
      ),
      a(
        "c32_3",
        "Channel Attribution AI",
        32,
        "Advanced Analytics & Reporting",
        "Shows which channel generates the best quality leads",
        8,
        "active",
        94,
        87,
        522,
        20880,
        "Attributing last-week leads",
        [
          "Attributed 38 leads",
          "Ranked WhatsApp first",
          "Scored referral quality",
          "Generated attribution chart",
          "Updated channel DB",
        ],
        ["Channel attribution", "Lead quality scoring", "Source ranking"],
        "real",
      ),
      a(
        "c32_4",
        "Client Lifetime Value AI",
        32,
        "Advanced Analytics & Reporting",
        "Calculates predicted total revenue per client relationship",
        8,
        "active",
        93,
        72,
        432,
        17280,
        "Computing CLV for top clients",
        [
          "Computed CLV for 20 clients",
          "Ranked by predicted value",
          "Flagged at-risk clients",
          "Generated CLV report",
          "Updated revenue model",
        ],
        ["CLV calculation", "Client ranking", "Revenue prediction"],
        "simulated",
      ),
      a(
        "c32_5",
        "Churn Prediction AI",
        32,
        "Advanced Analytics & Reporting",
        "Identifies clients likely to switch to competitor",
        9,
        "active",
        95,
        59,
        354,
        14160,
        "Running churn model",
        [
          "Flagged 4 churn risks",
          "Triggered retention actions",
          "Scored churn probability",
          "Generated churn report",
          "Updated prediction model",
        ],
        [
          "Churn probability scoring",
          "Retention triggering",
          "Risk identification",
        ],
        "simulated",
      ),
      a(
        "c32_6",
        "Revenue Forecasting AI",
        32,
        "Advanced Analytics & Reporting",
        "Predicts next period revenue from current pipeline",
        8,
        "active",
        93,
        101,
        606,
        24240,
        "Forecasting Q2 revenue",
        [
          "Forecasted 30-day revenue",
          "Ran pipeline model",
          "Generated forecast chart",
          "Flagged pipeline gaps",
          "Updated forecast model",
        ],
        ["Revenue forecasting", "Pipeline modelling", "Gap identification"],
        "simulated",
      ),
      a(
        "c32_7",
        "Cost Per Lead AI",
        32,
        "Advanced Analytics & Reporting",
        "Tracks acquisition cost per lead across all channels",
        8,
        "active",
        92,
        66,
        396,
        15840,
        "Calculating WhatsApp CPL",
        [
          "Calculated CPL by channel",
          "Ranked cheapest source",
          "Flagged high-CPL channels",
          "Generated CPL report",
          "Updated cost DB",
        ],
        ["CPL calculation", "Channel cost comparison", "Budget efficiency"],
        "real",
      ),
      a(
        "c32_8",
        "Market Share AI",
        32,
        "Advanced Analytics & Reporting",
        "Estimates MSTC share of Ahmedabad real estate transactions",
        7,
        "active",
        88,
        43,
        258,
        10320,
        "Estimating Q1 market share",
        [
          "Estimated 2.3% share",
          "Compared to last quarter",
          "Flagged share loss",
          "Generated market chart",
          "Updated share model",
        ],
        ["Market share estimation", "Trend tracking", "Competitor comparison"],
        "simulated",
      ),
      a(
        "c32_9",
        "Benchmark AI",
        32,
        "Advanced Analytics & Reporting",
        "Compares MSTC performance against industry benchmarks",
        8,
        "active",
        91,
        57,
        342,
        13680,
        "Running benchmark comparison",
        [
          "Ran 5 benchmarks",
          "Flagged below-avg metrics",
          "Compared to industry",
          "Generated benchmark report",
          "Updated benchmark DB",
        ],
        [
          "Benchmark comparison",
          "Industry data sync",
          "Performance gap detection",
        ],
        "real",
      ),
      a(
        "c32_10",
        "Cohort Analysis AI",
        32,
        "Advanced Analytics & Reporting",
        "Groups clients by joining date and tracks cohort performance",
        7,
        "active",
        89,
        48,
        288,
        11520,
        "Analysing Jan 2024 cohort",
        [
          "Analysed 4 cohorts",
          "Calculated retention rates",
          "Compared cohort revenue",
          "Generated cohort chart",
          "Updated cohort model",
        ],
        ["Cohort grouping", "Retention calculation", "Revenue comparison"],
        "simulated",
      ),
      a(
        "c32_11",
        "Heatmap Analytics AI",
        32,
        "Advanced Analytics & Reporting",
        "Shows which pages and tools drive the most enquiries",
        8,
        "active",
        92,
        79,
        474,
        18960,
        "Generating site heatmap",
        [
          "Generated 3 heatmaps",
          "Flagged high-exit pages",
          "Scored tool engagement",
          "Generated heatmap report",
          "Updated analytics DB",
        ],
        ["Heatmap generation", "Engagement scoring", "Exit page detection"],
        "real",
      ),
      a(
        "c32_12",
        "A/B Result Publisher AI",
        32,
        "Advanced Analytics & Reporting",
        "Publishes A/B test results with visible improvement data",
        7,
        "idle",
        86,
        22,
        132,
        5280,
        "Idle - awaiting test conclusion",
        [
          "Published 2 A/B results",
          "Calculated % improvement",
          "Declared winning variant",
          "Generated result card",
          "Updated test DB",
        ],
        [
          "A/B result publishing",
          "Winner determination",
          "Improvement quantification",
        ],
        "real",
      ),
      a(
        "c32_13",
        "ROI Attribution AI",
        32,
        "Advanced Analytics & Reporting",
        "Shows measured ROI for every MSTC investment and feature",
        8,
        "active",
        93,
        64,
        384,
        15360,
        "Calculating new feature ROI",
        [
          "Calculated feature ROI",
          "Measured campaign return",
          "Ranked investments",
          "Generated ROI report",
          "Updated attribution DB",
        ],
        ["ROI measurement", "Investment ranking", "Feature impact calc"],
        "real",
      ),
      a(
        "c32_14",
        "Predictive Pipeline AI",
        32,
        "Advanced Analytics & Reporting",
        "Forecasts deals likely to close in next 30 60 90 days",
        9,
        "active",
        96,
        108,
        648,
        25920,
        "Running pipeline forecast",
        [
          "Forecast 12 deals (30d)",
          "Ranked by probability",
          "Flagged stale pipeline",
          "Generated forecast chart",
          "Updated pipeline model",
        ],
        ["Pipeline forecasting", "Deal probability", "Stale detection"],
        "simulated",
      ),
      a(
        "c32_15",
        "Executive Summary AI",
        32,
        "Advanced Analytics & Reporting",
        "Writes Monday morning AI executive summary automatically",
        9,
        "active",
        97,
        1,
        7,
        280,
        "Writing weekly executive brief",
        [
          "Wrote last Monday brief",
          "Included 8 KPI highlights",
          "Flagged 2 critical issues",
          "Generated PDF summary",
          "Sent to MD inbox",
        ],
        ["Weekly summary writing", "KPI highlighting", "Issue flagging"],
        "simulated",
      ),
    ],
  },
  {
    clusterId: 33,
    clusterName: "Infrastructure & Platform",
    clusterDescription:
      "Platform health monitoring performance and infrastructure management",
    category: "Infrastructure",
    color: "#64748b",
    agents: [
      a(
        "c33_1",
        "Platform Health Monitor AI",
        33,
        "Infrastructure & Platform",
        "Tracks real-time platform health score and uptime",
        9,
        "active",
        99,
        288,
        1728,
        69120,
        "Monitoring platform health",
        [
          "Checked uptime 99.97%",
          "Flagged slow API call",
          "Measured response time",
          "Generated health score",
          "Updated status dashboard",
        ],
        ["Uptime monitoring", "Response time tracking", "Health scoring"],
        "real",
      ),
      a(
        "c33_2",
        "Feature Usage AI",
        33,
        "Infrastructure & Platform",
        "Shows which features are used most and least",
        8,
        "active",
        95,
        143,
        858,
        34320,
        "Tracking feature usage today",
        [
          "Ranked EMI calc #1",
          "Flagged unused tool",
          "Scored 24 features",
          "Generated usage chart",
          "Updated usage DB",
        ],
        ["Feature usage tracking", "Usage ranking", "Unused detection"],
        "real",
      ),
      a(
        "c33_3",
        "Error Pattern AI",
        33,
        "Infrastructure & Platform",
        "Clusters similar errors and prioritises fixes",
        9,
        "active",
        97,
        76,
        456,
        18240,
        "Clustering todays errors",
        [
          "Clustered 12 errors",
          "Flagged critical pattern",
          "Prioritised top 3 fixes",
          "Generated error report",
          "Updated pattern DB",
        ],
        ["Error clustering", "Priority ranking", "Pattern detection"],
        "real",
      ),
      a(
        "c33_4",
        "Load Testing AI",
        33,
        "Infrastructure & Platform",
        "Simulates high traffic to test platform resilience",
        7,
        "idle",
        91,
        8,
        48,
        1920,
        "Idle - next test scheduled",
        [
          "Ran 5k user simulation",
          "Identified bottleneck",
          "Measured peak capacity",
          "Generated load report",
          "Updated test DB",
        ],
        ["Load simulation", "Bottleneck detection", "Capacity measurement"],
        "real",
      ),
      a(
        "c33_5",
        "Database Health AI",
        33,
        "Infrastructure & Platform",
        "Monitors data integrity storage and query performance",
        9,
        "active",
        98,
        192,
        1152,
        46080,
        "Monitoring DB query health",
        [
          "Checked DB integrity",
          "Flagged slow query",
          "Monitored storage 78%",
          "Generated health report",
          "Optimised 3 queries",
        ],
        ["DB integrity checking", "Query performance", "Storage monitoring"],
        "real",
      ),
      a(
        "c33_6",
        "API Health AI",
        33,
        "Infrastructure & Platform",
        "Monitors all external API connections for failures",
        9,
        "active",
        98,
        241,
        1446,
        57840,
        "Monitoring Google Maps API",
        [
          "Checked 8 APIs",
          "Flagged maps latency",
          "Measured news feed uptime",
          "Generated API report",
          "Triggered fallback",
        ],
        ["API uptime monitoring", "Latency detection", "Fallback triggering"],
        "real",
      ),
      a(
        "c33_7",
        "Deployment Monitor AI",
        33,
        "Infrastructure & Platform",
        "Tracks every deployment and flags regressions",
        9,
        "active",
        97,
        12,
        72,
        2880,
        "Monitoring latest deployment",
        [
          "Tracked deployment v2.4",
          "Flagged 0 regressions",
          "Measured deploy time",
          "Generated deploy report",
          "Updated version DB",
        ],
        ["Deployment tracking", "Regression detection", "Version management"],
        "real",
      ),
      a(
        "c33_8",
        "Backup Verification AI",
        33,
        "Infrastructure & Platform",
        "Confirms all backups completed and shows last verified time",
        9,
        "active",
        99,
        48,
        288,
        11520,
        "Verifying backup integrity",
        [
          "Verified 3 backups",
          "Confirmed last backup 02:00",
          "Checked data integrity",
          "Generated backup report",
          "Updated verification log",
        ],
        ["Backup verification", "Integrity confirmation", "Schedule tracking"],
        "real",
      ),
      a(
        "c33_9",
        "Cost Optimization AI",
        33,
        "Infrastructure & Platform",
        "Monitors infrastructure costs and suggests savings",
        8,
        "active",
        93,
        34,
        204,
        8160,
        "Scanning for cost savings",
        [
          "Found Rs 3k monthly saving",
          "Flagged unused resources",
          "Recommended downsizing",
          "Generated savings report",
          "Updated cost model",
        ],
        ["Cost monitoring", "Savings identification", "Resource optimization"],
        "real",
      ),
      a(
        "c33_10",
        "Capacity Planner AI",
        33,
        "Infrastructure & Platform",
        "Predicts when infrastructure will hit capacity limits",
        8,
        "active",
        94,
        27,
        162,
        6480,
        "Projecting growth capacity",
        [
          "Projected 6mo capacity",
          "Flagged storage limit",
          "Modelled user growth",
          "Generated capacity plan",
          "Updated growth model",
        ],
        ["Capacity projection", "Limit detection", "Growth modelling"],
        "simulated",
      ),
    ],
  },
  {
    clusterId: 34,
    clusterName: "Hyper-Personalization",
    clusterDescription:
      "AI that deeply personalizes every aspect of the user experience",
    category: "Personalization",
    color: "#a855f7",
    agents: [
      a(
        "c34_1",
        "Behavioral Clone AI",
        34,
        "Hyper-Personalization",
        "Builds complete behavioral model of each user after 3 visits",
        9,
        "active",
        96,
        178,
        1068,
        42720,
        "Modelling 23 returning users",
        [
          "Modelled 8 new profiles",
          "Updated 15 existing",
          "Detected preference shifts",
          "Generated behaviour cards",
          "Updated clone DB",
        ],
        ["Behavioral modelling", "Preference detection", "Profile updating"],
        "simulated",
      ),
      a(
        "c34_2",
        "Preference Memory AI",
        34,
        "Hyper-Personalization",
        "Remembers all stated preferences across all sessions",
        9,
        "active",
        97,
        203,
        1218,
        48720,
        "Syncing preference memory",
        [
          "Stored 47 preferences",
          "Updated 3BHK preference",
          "Remembered price range",
          "Generated preference card",
          "Updated memory DB",
        ],
        ["Preference storage", "Session memory", "Profile enrichment"],
        "real",
      ),
      a(
        "c34_3",
        "Life Stage AI",
        34,
        "Hyper-Personalization",
        "Detects life stage and adapts content accordingly",
        8,
        "active",
        93,
        87,
        522,
        20880,
        "Detecting user life stages",
        [
          "Detected 12 life stages",
          "Adapted 5 homepages",
          "Flagged empty nester",
          "Updated content for retiree",
          "Generated stage card",
        ],
        ["Life stage detection", "Content adaptation", "Segment updating"],
        "simulated",
      ),
      a(
        "c34_4",
        "Wealth Signal AI",
        34,
        "Hyper-Personalization",
        "Infers wealth band from behaviour and adjusts listings",
        8,
        "active",
        92,
        112,
        672,
        26880,
        "Inferring wealth for 18 users",
        [
          "Inferred 18 wealth bands",
          "Adjusted price ranges",
          "Filtered luxury listings",
          "Generated wealth profile",
          "Updated signal model",
        ],
        ["Wealth band inference", "Price range adjustment", "Luxury filtering"],
        "simulated",
      ),
      a(
        "c34_5",
        "Intent Intensity AI",
        34,
        "Hyper-Personalization",
        "Measures buyer seriousness from casual to ready-to-buy",
        9,
        "active",
        95,
        134,
        804,
        32160,
        "Scoring buyer intent levels",
        [
          "Scored 34 active users",
          "Flagged 5 ready-to-buy",
          "Adjusted chat tone",
          "Generated intent report",
          "Updated intensity model",
        ],
        ["Intent scoring", "Readiness flagging", "Tone adjustment"],
        "simulated",
      ),
      a(
        "c34_6",
        "Seasonal Behavior AI",
        34,
        "Hyper-Personalization",
        "Times communications to match user seasonal patterns",
        7,
        "active",
        89,
        58,
        348,
        13920,
        "Analysing Diwali buy patterns",
        [
          "Detected post-Diwali pattern",
          "Scheduled seasonal alerts",
          "Updated 8 user timings",
          "Generated seasonal plan",
          "Updated behaviour model",
        ],
        [
          "Seasonal pattern detection",
          "Communication timing",
          "Alert scheduling",
        ],
        "simulated",
      ),
      a(
        "c34_7",
        "Device Preference AI",
        34,
        "Hyper-Personalization",
        "Optimises experience for each user device preference",
        7,
        "active",
        88,
        91,
        546,
        21840,
        "Optimising mobile experience",
        [
          "Detected mobile-first users",
          "Optimised desktop layout",
          "Adjusted image sizes",
          "Generated device report",
          "Updated preference DB",
        ],
        [
          "Device preference tracking",
          "Layout optimization",
          "Image adaptation",
        ],
        "real",
      ),
      a(
        "c34_8",
        "Time-of-Day Optimizer AI",
        34,
        "Hyper-Personalization",
        "Sends messages when each user is most receptive",
        8,
        "active",
        93,
        147,
        882,
        35280,
        "Scheduling optimal send times",
        [
          "Found 7pm peak for user A",
          "Scheduled 22 messages",
          "Avoided off-peak sends",
          "Generated timing report",
          "Updated time model",
        ],
        [
          "Optimal timing detection",
          "Message scheduling",
          "Off-peak avoidance",
        ],
        "simulated",
      ),
      a(
        "c34_9",
        "Return Visit Intelligence AI",
        34,
        "Hyper-Personalization",
        "Shows what is new since each user last visited",
        8,
        "active",
        94,
        162,
        972,
        38880,
        "Preparing return visit brief",
        [
          "Prepared 28 return briefs",
          "Highlighted new listings",
          "Flagged price changes",
          "Generated change summary",
          "Updated visit DB",
        ],
        [
          "Return visit detection",
          "Change highlighting",
          "New listing flagging",
        ],
        "real",
      ),
      a(
        "c34_10",
        "Saved Search Evolution AI",
        34,
        "Hyper-Personalization",
        "Evolves saved searches as market conditions change",
        8,
        "active",
        92,
        73,
        438,
        17520,
        "Evolving 14 saved searches",
        [
          "Evolved 14 searches",
          "Added new Bopal listings",
          "Removed sold properties",
          "Generated search update",
          "Updated search DB",
        ],
        ["Search evolution", "Market adaptation", "Stale removal"],
        "simulated",
      ),
      a(
        "c34_11",
        "Budget Evolution AI",
        34,
        "Hyper-Personalization",
        "Tracks how stated budget changes across user visits",
        8,
        "active",
        91,
        88,
        528,
        21120,
        "Tracking budget shifts",
        [
          "Detected budget increase",
          "Updated 6 user budgets",
          "Adjusted recommendations",
          "Generated budget card",
          "Updated evolution DB",
        ],
        [
          "Budget change tracking",
          "Recommendation adjustment",
          "Profile updating",
        ],
        "real",
      ),
      a(
        "c34_12",
        "Comparison History AI",
        34,
        "Hyper-Personalization",
        "Remembers all comparisons and never shows duplicates",
        7,
        "active",
        89,
        64,
        384,
        15360,
        "Tracking comparison history",
        [
          "Stored 32 comparisons",
          "Filtered seen pairs",
          "Generated new comparison",
          "Updated history DB",
          "Flagged repeat attempt",
        ],
        ["Comparison storage", "Duplicate prevention", "New pair generation"],
        "real",
      ),
      a(
        "c34_13",
        "Decision Point AI",
        34,
        "Hyper-Personalization",
        "Detects when user is at decision point and provides info",
        9,
        "active",
        96,
        103,
        618,
        24720,
        "Detecting decision moments",
        [
          "Detected 8 decision points",
          "Provided closing info",
          "Sent urgency nudge",
          "Generated decision card",
          "Updated trigger model",
        ],
        ["Decision detection", "Closing info provision", "Urgency nudging"],
        "simulated",
      ),
      a(
        "c34_14",
        "Micro-Moment AI",
        34,
        "Hyper-Personalization",
        "Serves appropriate content for quick or deep sessions",
        7,
        "active",
        88,
        119,
        714,
        28560,
        "Detecting micro-moments",
        [
          "Detected 19 micro-moments",
          "Served quick mobile card",
          "Provided deep desktop view",
          "Generated moment report",
          "Updated moment model",
        ],
        [
          "Micro-moment detection",
          "Session type serving",
          "Content length adjustment",
        ],
        "simulated",
      ),
      a(
        "c34_15",
        "Dark Pattern Detector AI",
        34,
        "Hyper-Personalization",
        "Ensures all persuasion is ethical with no dark patterns",
        9,
        "active",
        99,
        47,
        282,
        11280,
        "Auditing site for dark patterns",
        [
          "Audited 3 new features",
          "Cleared 2 designs",
          "Flagged 0 dark patterns",
          "Generated ethics report",
          "Updated ethics DB",
        ],
        ["Dark pattern detection", "Ethics auditing", "Persuasion review"],
        "real",
      ),
    ],
  },
  {
    clusterId: 35,
    clusterName: "Communication & Outreach",
    clusterDescription:
      "AI-powered multi-channel communication and client outreach management",
    category: "Communication",
    color: "#22c55e",
    agents: [
      a(
        "c35_1",
        "WhatsApp Campaign AI",
        35,
        "Communication & Outreach",
        "Manages all WhatsApp broadcast campaigns end to end",
        9,
        "active",
        96,
        132,
        792,
        31680,
        "Running Diwali WhatsApp blast",
        [
          "Sent 450 broadcast msgs",
          "Tracked 38% open rate",
          "Segmented buyer list",
          "Generated campaign report",
          "Updated WhatsApp DB",
        ],
        ["Campaign management", "Segmentation", "Open rate tracking"],
        "real",
      ),
      a(
        "c35_2",
        "SMS Campaign AI",
        35,
        "Communication & Outreach",
        "Sends targeted SMS with property alerts to non-WhatsApp users",
        8,
        "active",
        92,
        87,
        522,
        20880,
        "Running price drop SMS",
        [
          "Sent 230 SMS alerts",
          "Tracked delivery rate",
          "Segmented non-WA users",
          "Generated SMS report",
          "Updated SMS DB",
        ],
        ["SMS targeting", "Delivery tracking", "Non-WA segmentation"],
        "real",
      ),
      a(
        "c35_3",
        "Email Newsletter AI",
        35,
        "Communication & Outreach",
        "Sends AI-curated weekly newsletter personalised per segment",
        8,
        "active",
        93,
        1,
        7,
        280,
        "Preparing weekly newsletter",
        [
          "Sent last newsletter",
          "Achieved 24% open rate",
          "Personalised 4 segments",
          "Generated content mix",
          "Updated subscriber DB",
        ],
        ["Newsletter curation", "Segmentation", "Open rate optimization"],
        "simulated",
      ),
      a(
        "c35_4",
        "Push Notification AI",
        35,
        "Communication & Outreach",
        "Sends PWA push notifications for price drops and matches",
        8,
        "active",
        91,
        78,
        468,
        18720,
        "Sending price drop pushes",
        [
          "Sent 156 push notifications",
          "Tracked 12% click rate",
          "Segmented by match",
          "Generated push report",
          "Updated push DB",
        ],
        [
          "Push notification sending",
          "Click rate tracking",
          "Match segmentation",
        ],
        "real",
      ),
      a(
        "c35_5",
        "Re-engagement AI",
        35,
        "Communication & Outreach",
        "Re-engages users who have not visited in 30 plus days",
        8,
        "active",
        89,
        43,
        258,
        10320,
        "Re-engaging dormant users",
        [
          "Identified 43 dormant users",
          "Sent 43 re-engage messages",
          "Got 8 responses",
          "Generated re-engage report",
          "Updated dormant DB",
        ],
        [
          "Dormant user detection",
          "Re-engagement messaging",
          "Response tracking",
        ],
        "simulated",
      ),
      a(
        "c35_6",
        "Birthday/Anniversary AI",
        35,
        "Communication & Outreach",
        "Sends personalised messages on client special dates",
        7,
        "active",
        91,
        12,
        72,
        2880,
        "Sending today birthday messages",
        [
          "Sent 3 birthday messages",
          "Sent 1 anniversary msg",
          "Personalised each message",
          "Tracked open rates",
          "Updated date DB",
        ],
        [
          "Birthday detection",
          "Anniversary tracking",
          "Personalised messaging",
        ],
        "real",
      ),
      a(
        "c35_7",
        "New Listing Alert AI",
        35,
        "Communication & Outreach",
        "Instantly notifies matching buyers when new listing added",
        9,
        "active",
        97,
        67,
        402,
        16080,
        "Sending new listing alerts",
        [
          "Notified 67 matching buyers",
          "Matched 3 new listings",
          "Tracked 22% response",
          "Generated alert report",
          "Updated match DB",
        ],
        ["Instant alert sending", "Buyer matching", "Response tracking"],
        "real",
      ),
      a(
        "c35_8",
        "Price Drop Notification AI",
        35,
        "Communication & Outreach",
        "Notifies shortlisted buyers instantly when price drops",
        9,
        "active",
        96,
        54,
        324,
        12960,
        "Processing price drop alerts",
        [
          "Sent 54 price drop alerts",
          "Notified shortlist viewers",
          "Tracked urgent responses",
          "Generated drop report",
          "Updated alert DB",
        ],
        ["Price drop detection", "Instant notification", "Shortlist alerting"],
        "real",
      ),
      a(
        "c35_9",
        "Market Event Notifier AI",
        35,
        "Communication & Outreach",
        "Notifies relevant clients on major market events",
        8,
        "active",
        93,
        28,
        168,
        6720,
        "Drafting RBI policy alert",
        [
          "Sent RBI rate alert",
          "Notified 120 loan clients",
          "Drafted market update",
          "Generated event brief",
          "Updated event DB",
        ],
        [
          "Market event detection",
          "Client segmentation",
          "Instant notification",
        ],
        "real",
      ),
      a(
        "c35_10",
        "Deal Stage Notifier AI",
        35,
        "Communication & Outreach",
        "Notifies clients at every stage of their transaction",
        9,
        "active",
        97,
        89,
        534,
        21360,
        "Sending stage update messages",
        [
          "Sent 89 stage updates",
          "Updated 12 transactions",
          "Tracked client responses",
          "Generated stage report",
          "Updated deal DB",
        ],
        ["Stage notification", "Transaction tracking", "Client communication"],
        "real",
      ),
      a(
        "c35_11",
        "Document Reminder AI",
        35,
        "Communication & Outreach",
        "Reminds clients about pending documents and deadlines",
        8,
        "active",
        94,
        61,
        366,
        14640,
        "Sending document reminders",
        [
          "Sent 61 doc reminders",
          "Flagged overdue docs",
          "Tracked completion rate",
          "Generated reminder log",
          "Updated deadline DB",
        ],
        ["Document reminding", "Deadline tracking", "Completion monitoring"],
        "real",
      ),
      a(
        "c35_12",
        "Follow-Up Sequence AI",
        35,
        "Communication & Outreach",
        "Manages automated 7-touch follow-up for every new lead",
        9,
        "active",
        96,
        113,
        678,
        27120,
        "Running lead follow-up sequences",
        [
          "Sent 113 follow-up msgs",
          "Completed 8 sequences",
          "Flagged no-response leads",
          "Generated sequence report",
          "Updated CRM sequences",
        ],
        ["7-touch sequencing", "Lead nurturing", "Response tracking"],
        "simulated",
      ),
      a(
        "c35_13",
        "Win-Back AI",
        35,
        "Communication & Outreach",
        "Analyses cold leads and generates re-engagement strategy",
        8,
        "active",
        91,
        37,
        222,
        8880,
        "Analysing cold lead reasons",
        [
          "Analysed 37 cold leads",
          "Identified top 3 reasons",
          "Generated win-back plan",
          "Sent 12 win-back msgs",
          "Updated cold lead DB",
        ],
        ["Cold lead analysis", "Win-back strategy", "Re-engagement messaging"],
        "simulated",
      ),
      a(
        "c35_14",
        "Referral Request AI",
        35,
        "Communication & Outreach",
        "Requests referrals from happy clients at right moment",
        8,
        "active",
        93,
        24,
        144,
        5760,
        "Sending post-deal referral asks",
        [
          "Sent 24 referral requests",
          "Got 6 positive responses",
          "Tracked referral pipeline",
          "Generated referral report",
          "Updated referral DB",
        ],
        ["Referral timing", "Request messaging", "Pipeline tracking"],
        "simulated",
      ),
      a(
        "c35_15",
        "Feedback Collection AI",
        35,
        "Communication & Outreach",
        "Collects feedback after every interaction and processes results",
        8,
        "active",
        92,
        98,
        588,
        23520,
        "Collecting interaction feedback",
        [
          "Collected 98 feedbacks",
          "Calculated 4.3/5 avg score",
          "Flagged negative feedback",
          "Generated feedback report",
          "Updated feedback DB",
        ],
        ["Feedback collection", "Score calculation", "Negative flagging"],
        "real",
      ),
    ],
  },
];

export const CLUSTER_26_35_TOTAL = clusterData26to35.reduce(
  (sum, c) => sum + c.agents.length,
  0,
);
export const allAgents26to35: AgentDefinition[] = clusterData26to35.flatMap(
  (c) => c.agents,
);
