// MSTC GLOBAL — Backend AI Cluster Definitions (Clusters B1–B14, 225 agents)

export type BackendClusterCode =
  | "B1"
  | "B2"
  | "B3"
  | "B4"
  | "B5"
  | "B6"
  | "B7"
  | "B8"
  | "B9"
  | "B10"
  | "B11"
  | "B12"
  | "B13"
  | "B14";

export type BackendIntelligenceCategory =
  | "autonomous"
  | "ml"
  | "neural"
  | "analytics"
  | "security"
  | "graph"
  | "timeseries"
  | "communication"
  | "innovation"
  | "admin"
  | "multimodal"
  | "vertical"
  | "operations"
  | "reinforcement";

export interface BackendAgent {
  id: string;
  name: string;
  cluster: string;
  clusterCode: BackendClusterCode;
  type: "backend";
  specialty: string;
  intelligenceCategory: BackendIntelligenceCategory;
  status: "active" | "idle" | "processing" | "error";
  tasksToday: number;
  accuracy: number;
  description: string;
}

export interface BackendClusterConfig {
  code: BackendClusterCode;
  name: string;
  description: string;
  agentCount: number;
  primaryCategory: BackendIntelligenceCategory;
  color: string;
}

const ba = (
  id: string,
  name: string,
  code: BackendClusterCode,
  cluster: string,
  specialty: string,
  cat: BackendIntelligenceCategory,
  status: "active" | "idle" | "processing" | "error",
  tasks: number,
  accuracy: number,
  desc: string,
): BackendAgent => ({
  id,
  name,
  cluster,
  clusterCode: code,
  type: "backend",
  specialty,
  intelligenceCategory: cat,
  status,
  tasksToday: tasks,
  accuracy,
  description: desc,
});

// ── CLUSTER B1: Autonomous Operation AIs (25 agents) ──────────────────────────
const B1_CLUSTER = "Autonomous Operation AIs";
const B1_AGENTS: BackendAgent[] = [
  ba(
    "b1-auto-matcher",
    "Auto-Matcher AI",
    "B1",
    B1_CLUSTER,
    "Daily buyer-to-property matching across all active leads",
    "autonomous",
    "active",
    1247,
    94,
    "Runs daily matching of all active buyers against every available property, generates prioritized match lists",
  ),
  ba(
    "b1-auto-publisher",
    "Auto-Publisher AI",
    "B1",
    B1_CLUSTER,
    "New listing auto-formatting, scoring, and publishing",
    "autonomous",
    "active",
    34,
    97,
    "Auto-formats, scores, and publishes new listings without manual intervention within 5 minutes of import",
  ),
  ba(
    "b1-auto-followup",
    "Auto-Follow-Up AI",
    "B1",
    B1_CLUSTER,
    "Optimal-time lead follow-ups with full action logging",
    "autonomous",
    "active",
    456,
    93,
    "Follows up with all leads at individually optimal times, logs every action in the CRM automatically",
  ),
  ba(
    "b1-auto-alert",
    "Auto-Alert AI",
    "B1",
    B1_CLUSTER,
    "Price drop, new match, market update automatic alerts",
    "autonomous",
    "active",
    789,
    96,
    "Sends price drop, new property match, and market update alerts to relevant clients automatically",
  ),
  ba(
    "b1-auto-report",
    "Auto-Report AI",
    "B1",
    B1_CLUSTER,
    "Weekly/monthly market report auto-generation and publishing",
    "autonomous",
    "active",
    7,
    94,
    "Generates and publishes weekly and monthly market reports automatically without any manual input",
  ),
  ba(
    "b1-auto-audit",
    "Auto-Audit AI",
    "B1",
    B1_CLUSTER,
    "Nightly data quality audit: missing fields, outdated prices",
    "autonomous",
    "active",
    1,
    98,
    "Nightly audit of all data for quality issues: missing fields, outdated prices, and duplicate entries",
  ),
  ba(
    "b1-auto-seo",
    "Auto-SEO AI",
    "B1",
    B1_CLUSTER,
    "Continuous meta title, description, content optimization",
    "autonomous",
    "active",
    234,
    89,
    "Continuously optimizes meta titles, descriptions, alt text, and content structure for search visibility",
  ),
  ba(
    "b1-auto-translate",
    "Auto-Translate AI",
    "B1",
    B1_CLUSTER,
    "Immediate Gujarati and Hindi translation of all new content",
    "autonomous",
    "active",
    567,
    97,
    "All new content is immediately translated into Gujarati and Hindi as soon as it is published",
  ),
  ba(
    "b1-auto-cleanup",
    "Auto-Cleanup AI",
    "B1",
    B1_CLUSTER,
    "Duplicate listings, stale data, broken links removal",
    "autonomous",
    "active",
    89,
    96,
    "Removes duplicate listings, clears stale data, and fixes broken links daily with full cleanup log",
  ),
  ba(
    "b1-auto-escalation",
    "Auto-Escalation AI",
    "B1",
    B1_CLUSTER,
    "2-hour unanswered enquiry priority escalation",
    "autonomous",
    "active",
    23,
    98,
    "Any enquiry unanswered for 2 hours is automatically escalated with priority flag to the relevant team",
  ),
  ba(
    "b1-auto-pricing",
    "Auto-Pricing AI",
    "B1",
    B1_CLUSTER,
    "Market monitoring and listing price adjustment suggestions",
    "autonomous",
    "processing",
    45,
    87,
    "Monitors market prices continuously, suggests listing price adjustments — awaits human approval",
  ),
  ba(
    "b1-auto-valuation",
    "Auto-Valuation AI",
    "B1",
    B1_CLUSTER,
    "Weekly revaluation of all listings from market movement",
    "autonomous",
    "active",
    7,
    91,
    "Revalues all listings every week based on recent market transactions and comparable sales data",
  ),
  ba(
    "b1-auto-lead-score",
    "Auto-Lead Score AI",
    "B1",
    B1_CLUSTER,
    "Daily lead rescoring from new behavioral signals",
    "autonomous",
    "active",
    1234,
    93,
    "Rescores every active lead daily based on new browsing behavior, enquiry patterns, and engagement",
  ),
  ba(
    "b1-auto-content",
    "Auto-Content AI",
    "B1",
    B1_CLUSTER,
    "Stale blog post, area guide, FAQ automatic refresh",
    "autonomous",
    "active",
    34,
    90,
    "Detects and refreshes stale blog posts, area guides, and FAQ entries automatically",
  ),
  ba(
    "b1-auto-backup",
    "Auto-Backup AI",
    "B1",
    B1_CLUSTER,
    "Backup completion verification and timestamped logging",
    "autonomous",
    "active",
    4,
    99,
    "Verifies all scheduled backups completed successfully, logs each verification with exact timestamp",
  ),
  ba(
    "b1-auto-compliance",
    "Auto-Compliance AI",
    "B1",
    B1_CLUSTER,
    "RERA deadlines, legal filings, regulatory change monitoring",
    "autonomous",
    "active",
    12,
    97,
    "Monitors all RERA deadlines, legal filing requirements, and regulatory changes — alerts before deadline",
  ),
  ba(
    "b1-auto-benchmark",
    "Auto-Benchmark AI",
    "B1",
    B1_CLUSTER,
    "Weekly MSTC performance vs industry benchmark comparison",
    "autonomous",
    "active",
    7,
    92,
    "Compares all MSTC KPIs against industry benchmarks weekly and flags underperforming metrics",
  ),
  ba(
    "b1-auto-nurture",
    "Auto-Nurture AI",
    "B1",
    B1_CLUSTER,
    "7-touch automated lead nurture sequence management",
    "autonomous",
    "active",
    234,
    91,
    "Manages complete 7-touch automated nurture sequence for every new lead from initial contact",
  ),
  ba(
    "b1-auto-referral",
    "Auto-Referral AI",
    "B1",
    B1_CLUSTER,
    "Post-deal optimal-timing referral request to happy clients",
    "autonomous",
    "active",
    12,
    88,
    "Requests referrals from happy clients at the optimal time post-deal, tracked and followed up",
  ),
  ba(
    "b1-auto-feedback",
    "Auto-Feedback AI",
    "B1",
    B1_CLUSTER,
    "Post-interaction feedback request and result processing",
    "autonomous",
    "active",
    89,
    94,
    "Automatically requests feedback after every client interaction and processes results for improvement",
  ),
  ba(
    "b1-auto-renewal",
    "Auto-Renewal AI",
    "B1",
    B1_CLUSTER,
    "Agreement expiry, renewal, and deadline reminders",
    "autonomous",
    "active",
    23,
    97,
    "Monitors expiring agreements, subscription renewals, and important deadlines — alerts in advance",
  ),
  ba(
    "b1-auto-import",
    "Auto-Import AI",
    "B1",
    B1_CLUSTER,
    "Excel/CSV upload monitor with auto-process and import",
    "autonomous",
    "active",
    8,
    96,
    "Monitors for new Excel or CSV uploads and automatically processes and imports them into the platform",
  ),
  ba(
    "b1-auto-sitemap",
    "Auto-Sitemap AI",
    "B1",
    B1_CLUSTER,
    "Sitemap regeneration on every new page/listing addition",
    "autonomous",
    "active",
    34,
    99,
    "Regenerates the XML sitemap automatically whenever new pages or listings are added to the platform",
  ),
  ba(
    "b1-auto-performance",
    "Auto-Performance AI",
    "B1",
    B1_CLUSTER,
    "Weekly page speed, Core Web Vitals, mobile score report",
    "autonomous",
    "active",
    7,
    96,
    "Weekly automated report on page speed, Core Web Vitals, and mobile performance scores",
  ),
  ba(
    "b1-auto-security",
    "Auto-Security AI",
    "B1",
    B1_CLUSTER,
    "Daily vulnerability scan: spam, fake leads, data integrity",
    "autonomous",
    "active",
    1,
    99,
    "Daily automated security scan covering vulnerabilities, spam patterns, fake leads, and data integrity",
  ),
];

// ── CLUSTER B2: Machine Learning AIs (20 agents) ───────────────────────────────
const B2_CLUSTER = "Machine Learning AIs";
const B2_AGENTS: BackendAgent[] = [
  ba(
    "b2-lead-scoring-ml",
    "Lead Scoring ML",
    "B2",
    B2_CLUSTER,
    "Conversion probability prediction from 100+ behavioral signals",
    "ml",
    "active",
    2341,
    93,
    "Predicts lead conversion probability from 100+ behavioral signals continuously throughout each session",
  ),
  ba(
    "b2-price-prediction-ml",
    "Price Prediction ML",
    "B2",
    B2_CLUSTER,
    "3–12 month property price prediction by locality and type",
    "ml",
    "active",
    30,
    88,
    "Predicts property prices 3 to 12 months ahead for each Ahmedabad locality and property type",
  ),
  ba(
    "b2-churn-prediction-ml",
    "Churn Prediction ML",
    "B2",
    B2_CLUSTER,
    "Going-cold lead prediction before it happens",
    "ml",
    "active",
    456,
    87,
    "Predicts which leads are about to go cold before they do — triggers re-engagement proactively",
  ),
  ba(
    "b2-demand-forecasting-ml",
    "Demand Forecasting ML",
    "B2",
    B2_CLUSTER,
    "30-day enquiry volume prediction by locality and type",
    "ml",
    "active",
    30,
    86,
    "Forecasts enquiry volume 30 days ahead for each locality and property type combination",
  ),
  ba(
    "b2-conversion-optimizer-ml",
    "Conversion Optimizer ML",
    "B2",
    B2_CLUSTER,
    "Continuous A/B testing of page elements for max conversion",
    "ml",
    "active",
    24,
    89,
    "Continuously A/B tests page elements, CTAs, and layouts to maximize enquiry conversion rates",
  ),
  ba(
    "b2-content-recommendation-ml",
    "Content Recommendation ML",
    "B2",
    B2_CLUSTER,
    "Per-user valuable content prediction",
    "ml",
    "active",
    1234,
    90,
    "Predicts which content each specific user will find most valuable based on behavioral patterns",
  ),
  ba(
    "b2-fraud-detection-ml",
    "Fraud Detection ML",
    "B2",
    B2_CLUSTER,
    "Fake leads, spam enquiries, suspicious activity detection",
    "ml",
    "active",
    89,
    96,
    "Detects and quarantines fake leads, spam enquiries, and all forms of suspicious activity",
  ),
  ba(
    "b2-sentiment-ml",
    "Sentiment Analysis ML",
    "B2",
    B2_CLUSTER,
    "Real-time sentiment scoring on all messages and reviews",
    "ml",
    "active",
    3456,
    94,
    "Scores sentiment on every incoming message, review, and feedback in real time",
  ),
  ba(
    "b2-image-quality-ml",
    "Image Quality ML",
    "B2",
    B2_CLUSTER,
    "Listing photo quality scoring on multiple dimensions",
    "ml",
    "active",
    234,
    91,
    "Scores every listing photo on brightness, composition, resolution, clutter, and visual appeal",
  ),
  ba(
    "b2-doc-classification-ml",
    "Document Classification ML",
    "B2",
    B2_CLUSTER,
    "Any uploaded document auto-classified by type",
    "ml",
    "active",
    345,
    94,
    "Automatically classifies any uploaded document by type: sale deed, EC, RERA, loan sanction, etc.",
  ),
  ba(
    "b2-valuation-ml",
    "Valuation ML",
    "B2",
    B2_CLUSTER,
    "AVM from comparable transactions + location + property features",
    "ml",
    "active",
    1234,
    90,
    "Automated valuation model combining comparable transactions, location data, and property features",
  ),
  ba(
    "b2-rental-yield-ml",
    "Rental Yield ML",
    "B2",
    B2_CLUSTER,
    "Rental yield prediction by locality, type, and floor",
    "ml",
    "active",
    789,
    89,
    "Predicts rental yield for any property based on locality, property type, floor, and current market",
  ),
  ba(
    "b2-builder-score-ml",
    "Builder Score ML",
    "B2",
    B2_CLUSTER,
    "Dynamic builder trust score from delivery and complaint history",
    "ml",
    "active",
    456,
    91,
    "Dynamic builder trust score calculated from delivery history, complaint records, and quality ratings",
  ),
  ba(
    "b2-client-ltv-ml",
    "Client LTV ML",
    "B2",
    B2_CLUSTER,
    "Total lifetime value prediction for each client relationship",
    "ml",
    "active",
    234,
    87,
    "Predicts total lifetime value of each client across all MSTC service lines over their relationship",
  ),
  ba(
    "b2-enquiry-intent-ml",
    "Enquiry Intent ML",
    "B2",
    B2_CLUSTER,
    "Enquiry intent classification: hot/warm/cold/spam",
    "ml",
    "active",
    1678,
    93,
    "Classifies every incoming enquiry as hot, warm, cold, or spam with confidence score",
  ),
  ba(
    "b2-price-negotiation-ml",
    "Price Negotiation ML",
    "B2",
    B2_CLUSTER,
    "Optimal negotiation range prediction for any listing",
    "ml",
    "active",
    789,
    88,
    "Predicts the optimal negotiation range for any listing based on market, days-on-market, and demand",
  ),
  ba(
    "b2-market-cycle-ml",
    "Market Cycle ML",
    "B2",
    B2_CLUSTER,
    "Current market phase classification from 50+ indicators",
    "ml",
    "processing",
    30,
    86,
    "Classifies the current Ahmedabad market phase using 50+ economic, construction, and demand indicators",
  ),
  ba(
    "b2-risk-scoring-ml",
    "Risk Scoring ML",
    "B2",
    B2_CLUSTER,
    "Property risk score: legal, physical, financial, market",
    "ml",
    "active",
    892,
    89,
    "Calculates comprehensive property risk score across legal, physical, financial, and market risk dimensions",
  ),
  ba(
    "b2-recommendation-ml",
    "Recommendation ML",
    "B2",
    B2_CLUSTER,
    "Collaborative filtering: clients like you bought these properties",
    "ml",
    "active",
    1234,
    90,
    "Collaborative filtering: 'Clients with your profile bought these properties' recommendations",
  ),
  ba(
    "b2-nlp-query-ml",
    "NLP Query ML",
    "B2",
    B2_CLUSTER,
    "Natural language property query understanding in 3 languages",
    "ml",
    "active",
    3456,
    94,
    "Understands natural language property search queries in English, Gujarati, and Hindi",
  ),
];

// ── CLUSTER B3: Neural Network AIs (15 agents) ───────────────────────────────────
const B3_CLUSTER = "Neural Network AIs";
const B3_AGENTS: BackendAgent[] = [
  ba(
    "b3-ann",
    "ANN Lead Scorer",
    "B3",
    B3_CLUSTER,
    "Artificial neural network lead quality scoring",
    "neural",
    "active",
    2341,
    93,
    "Artificial Neural Network scoring lead quality from all available input signals with multi-layer processing",
  ),
  ba(
    "b3-cnn",
    "CNN Photo Analyzer",
    "B3",
    B3_CLUSTER,
    "Convolutional neural network property photo intelligence",
    "neural",
    "active",
    456,
    91,
    "Convolutional Neural Network that scores, classifies, and recommends enhancements for every property photo",
  ),
  ba(
    "b3-rnn",
    "RNN Market Predictor",
    "B3",
    B3_CLUSTER,
    "Recurrent neural network time-series price prediction",
    "neural",
    "active",
    30,
    87,
    "Recurrent Neural Network trained on 5 years of Ahmedabad price data for accurate time-series prediction",
  ),
  ba(
    "b3-gan",
    "GAN Property Visualizer",
    "B3",
    B3_CLUSTER,
    "Generative adversarial network furnished property visualization",
    "neural",
    "processing",
    23,
    83,
    "GAN that creates furnished and renovated property visualizations from empty room photos",
  ),
  ba(
    "b3-gnn",
    "GNN Relationship Mapper",
    "B3",
    B3_CLUSTER,
    "Graph neural network client/property/builder relationship mapping",
    "neural",
    "active",
    234,
    88,
    "Graph Neural Network that maps and analyzes client, property, and builder relationship networks",
  ),
  ba(
    "b3-transformer",
    "Transformer Document AI",
    "B3",
    B3_CLUSTER,
    "Transformer model for legal document structured data extraction",
    "neural",
    "active",
    345,
    92,
    "Transformer model that reads any legal document and extracts fully structured data accurately",
  ),
  ba(
    "b3-bert",
    "BERT Query AI",
    "B3",
    B3_CLUSTER,
    "Bidirectional encoder contextual property search query understanding",
    "neural",
    "active",
    3456,
    94,
    "BERT bidirectional encoder understanding full context of property search queries in 3 languages",
  ),
  ba(
    "b3-deep-sentiment",
    "Deep Sentiment AI",
    "B3",
    B3_CLUSTER,
    "Deep learning sentiment on reviews, messages, and feedback",
    "neural",
    "active",
    2341,
    94,
    "Deep learning model for nuanced sentiment analysis on all reviews, messages, and client feedback",
  ),
  ba(
    "b3-ocr",
    "OCR Document AI",
    "B3",
    B3_CLUSTER,
    "Optical character recognition for scanned document data extraction",
    "neural",
    "active",
    567,
    93,
    "Optical character recognition that reads any scanned document and extracts fully structured data",
  ),
  ba(
    "b3-face-verification",
    "Face Verification AI",
    "B3",
    B3_CLUSTER,
    "Identity photo vs Aadhaar/PAN match verification (consent-based)",
    "neural",
    "idle",
    12,
    96,
    "Verifies uploaded identity photos match Aadhaar or PAN cards for high-value transaction security",
  ),
  ba(
    "b3-timeseries",
    "Time-Series Forecast AI",
    "B3",
    B3_CLUSTER,
    "Deep learning on price, enquiry, and transaction time series",
    "neural",
    "active",
    30,
    87,
    "Deep learning model trained on property price, enquiry volume, and transaction time series data",
  ),
  ba(
    "b3-tabular",
    "Tabular Data AI",
    "B3",
    B3_CLUSTER,
    "Neural network on structured property data for deal closure prediction",
    "neural",
    "active",
    1234,
    89,
    "Neural network on structured property data — best predictor of deal closure probability",
  ),
  ba(
    "b3-multi-label",
    "Multi-Label Classifier AI",
    "B3",
    B3_CLUSTER,
    "Property classification across 20+ dimensions simultaneously",
    "neural",
    "active",
    892,
    91,
    "Classifies any property across 20+ dimensions simultaneously: type, condition, investment grade, etc.",
  ),
  ba(
    "b3-encoder-decoder",
    "Encoder-Decoder AI",
    "B3",
    B3_CLUSTER,
    "Property data format to human-readable summary translation",
    "neural",
    "active",
    1678,
    92,
    "Translates between raw property data formats and natural human-readable summaries for any audience",
  ),
  ba(
    "b3-rl",
    "Reinforcement Learning AI",
    "B3",
    B3_CLUSTER,
    "Optimal decision sequences for lead nurturing and pricing",
    "neural",
    "active",
    456,
    86,
    "Learns optimal decision sequences for lead nurturing, pricing strategy, and client engagement",
  ),
];

// ── CLUSTER B4: Data & Analytics AIs (20 agents) ───────────────────────────────
const B4_CLUSTER = "Data & Analytics AIs";
const B4_AGENTS: BackendAgent[] = [
  ba(
    "b4-revenue",
    "Real-Time Revenue AI",
    "B4",
    B4_CLUSTER,
    "Live revenue tracking across all 8 service lines",
    "analytics",
    "active",
    1440,
    99,
    "Real-time revenue tracking across all 8 MSTC service lines with drill-down by service and date",
  ),
  ba(
    "b4-lead-funnel",
    "Lead Funnel AI",
    "B4",
    B4_CLUSTER,
    "Lead tracking from acquisition through deal closure",
    "analytics",
    "active",
    1234,
    96,
    "Tracks every lead through all stages: acquisition, qualification, site visit, negotiation, and deal",
  ),
  ba(
    "b4-channel-attribution",
    "Channel Attribution AI",
    "B4",
    B4_CLUSTER,
    "Best lead source identification: WhatsApp, Google, referral",
    "analytics",
    "active",
    234,
    93,
    "Identifies which channels generate the best quality leads: WhatsApp, Google, referral, social media",
  ),
  ba(
    "b4-clv",
    "CLV Calculator AI",
    "B4",
    B4_CLUSTER,
    "Client lifetime value across all 8 MSTC service lines",
    "analytics",
    "active",
    234,
    90,
    "Calculates client lifetime value across all services, not just property transactions",
  ),
  ba(
    "b4-cohort",
    "Cohort Analysis AI",
    "B4",
    B4_CLUSTER,
    "Client cohort grouping and performance tracking over time",
    "analytics",
    "processing",
    30,
    91,
    "Groups clients by join date, tracks performance metrics for each cohort over time",
  ),
  ba(
    "b4-heatmap",
    "Heatmap AI",
    "B4",
    B4_CLUSTER,
    "Page, section, tool enquiry and conversion heatmaps",
    "analytics",
    "active",
    1440,
    92,
    "Generates heatmaps showing which pages, sections, and tools drive the most enquiries and conversions",
  ),
  ba(
    "b4-ab-testing",
    "A/B Testing AI",
    "B4",
    B4_CLUSTER,
    "Controlled experiments on any page element with winner reporting",
    "analytics",
    "active",
    8,
    94,
    "Runs controlled A/B experiments on any page element, reports statistical winners automatically",
  ),
  ba(
    "b4-roi",
    "ROI Attribution AI",
    "B4",
    B4_CLUSTER,
    "Measured ROI for every feature and campaign",
    "analytics",
    "active",
    30,
    91,
    "Measures and attributes ROI for every feature built and every marketing campaign run",
  ),
  ba(
    "b4-pipeline",
    "Predictive Pipeline AI",
    "B4",
    B4_CLUSTER,
    "Deals likely to close in 30/60/90 day windows",
    "analytics",
    "active",
    234,
    87,
    "Forecasts which deals in the pipeline are likely to close within 30, 60, and 90 day windows",
  ),
  ba(
    "b4-market-share",
    "Market Share AI",
    "B4",
    B4_CLUSTER,
    "MSTC share estimation of Ahmedabad real estate transactions",
    "analytics",
    "processing",
    30,
    82,
    "Estimates and tracks MSTC's market share of total Ahmedabad real estate transactions",
  ),
  ba(
    "b4-benchmark",
    "Benchmark AI",
    "B4",
    B4_CLUSTER,
    "MSTC KPI comparison against industry standards",
    "analytics",
    "active",
    30,
    90,
    "Compares all MSTC KPIs against published industry standards and peer benchmarks",
  ),
  ba(
    "b4-cost-per-lead",
    "Cost Per Lead AI",
    "B4",
    B4_CLUSTER,
    "Lead acquisition cost tracking across all channels",
    "analytics",
    "active",
    30,
    94,
    "Tracks lead acquisition cost for every channel and campaign with trending analysis",
  ),
  ba(
    "b4-churn-analysis",
    "Churn Analysis AI",
    "B4",
    B4_CLUSTER,
    "Why leads go cold: price, timing, competition, service gap",
    "analytics",
    "active",
    234,
    88,
    "Analyzes why leads go cold: price mismatch, bad timing, competitor, or service gap",
  ),
  ba(
    "b4-revenue-forecast",
    "Revenue Forecast AI",
    "B4",
    B4_CLUSTER,
    "Next month/quarter/year revenue forecast from pipeline",
    "analytics",
    "active",
    30,
    85,
    "Forecasts next month, quarter, and year revenue based on current pipeline and historical patterns",
  ),
  ba(
    "b4-executive-summary",
    "Executive Summary AI",
    "B4",
    B4_CLUSTER,
    "Monday morning one-page AI business metrics brief",
    "analytics",
    "active",
    7,
    94,
    "Every Monday generates a one-page executive brief covering all key business metrics and insights",
  ),
  ba(
    "b4-competitive-intelligence",
    "Competitive Intelligence AI",
    "B4",
    B4_CLUSTER,
    "Competing agency listing, pricing, campaign monitoring",
    "analytics",
    "active",
    24,
    83,
    "Monitors competing real estate agencies' listings, pricing strategies, and marketing campaigns",
  ),
  ba(
    "b4-brand-health",
    "Brand Health AI",
    "B4",
    B4_CLUSTER,
    "MSTC brand sentiment and visibility tracking across platforms",
    "analytics",
    "active",
    24,
    87,
    "Tracks MSTC brand sentiment and visibility across Google, JustDial, social media, and news",
  ),
  ba(
    "b4-session-recording",
    "Session Recording AI",
    "B4",
    B4_CLUSTER,
    "Anonymized user session recording and UX friction identification",
    "analytics",
    "active",
    1440,
    91,
    "Records anonymized user sessions and identifies UX friction points for platform improvement",
  ),
  ba(
    "b4-funnel-dropoff",
    "Funnel Drop-Off AI",
    "B4",
    B4_CLUSTER,
    "Exact form, search, journey abandonment point identification",
    "analytics",
    "active",
    1440,
    93,
    "Identifies the exact point where users abandon forms, searches, and conversion journeys",
  ),
  ba(
    "b4-predictive-hiring",
    "Predictive Hiring AI",
    "B4",
    B4_CLUSTER,
    "Skill gap identification and ideal hire profile recommendations",
    "analytics",
    "idle",
    7,
    80,
    "Identifies organizational skill gaps and recommends ideal hire profiles to accelerate growth",
  ),
];

// ── CLUSTER B5: Security & Integrity AIs (15 agents) ───────────────────────────
const B5_CLUSTER = "Security & Integrity AIs";
const B5_AGENTS: BackendAgent[] = [
  ba(
    "b5-threat-detection",
    "Threat Detection AI",
    "B5",
    B5_CLUSTER,
    "Incoming traffic attack pattern, bot, scraper monitoring",
    "security",
    "active",
    1440,
    98,
    "Monitors all incoming traffic for attack patterns, bot behavior, and competitor scraping continuously",
  ),
  ba(
    "b5-fake-lead",
    "Fake Lead AI",
    "B5",
    B5_CLUSTER,
    "Fake/spam lead quarantine before reaching the team",
    "security",
    "active",
    345,
    97,
    "Detects and quarantines all fake or spam leads before they reach the sales team",
  ),
  ba(
    "b5-data-integrity",
    "Data Integrity AI",
    "B5",
    B5_CLUSTER,
    "Continuous data consistency and accuracy validation",
    "security",
    "active",
    1440,
    99,
    "Continuously validates all platform data for consistency, accuracy, and referential integrity",
  ),
  ba(
    "b5-privacy-compliance",
    "Privacy Compliance AI",
    "B5",
    B5_CLUSTER,
    "IT Act and GDPR-principle data handling compliance",
    "security",
    "active",
    1440,
    98,
    "Ensures all data handling complies with India's IT Act and GDPR principles at all times",
  ),
  ba(
    "b5-vulnerability-scanner",
    "Vulnerability Scanner AI",
    "B5",
    B5_CLUSTER,
    "Weekly automated security scan of all platform endpoints",
    "security",
    "active",
    7,
    97,
    "Runs weekly automated security scan of all platform endpoints and reports vulnerabilities",
  ),
  ba(
    "b5-incident-response",
    "Incident Response AI",
    "B5",
    B5_CLUSTER,
    "Security event instant containment and alert",
    "security",
    "active",
    0,
    99,
    "On detection of any security event: instant containment action and immediate team alert",
  ),
  ba(
    "b5-anti-scraping",
    "Anti-Scraping AI",
    "B5",
    B5_CLUSTER,
    "Competitor listing scraping detection and blocking",
    "security",
    "active",
    23,
    96,
    "Detects and blocks competitor scraping of MSTC listings and client data",
  ),
  ba(
    "b5-login-security",
    "Login Security AI",
    "B5",
    B5_CLUSTER,
    "Admin login pattern monitoring and anomaly enforcement",
    "security",
    "active",
    1440,
    99,
    "Monitors admin login patterns, flags anomalies, and enforces multi-factor authentication when needed",
  ),
  ba(
    "b5-export-control",
    "Data Export Control AI",
    "B5",
    B5_CLUSTER,
    "All bulk data exports controlled and logged",
    "security",
    "active",
    12,
    99,
    "Controls all bulk data exports from the admin dashboard and maintains immutable export logs",
  ),
  ba(
    "b5-content-moderation",
    "Content Moderation AI",
    "B5",
    B5_CLUSTER,
    "All user-submitted content reviewed before publishing",
    "security",
    "active",
    234,
    95,
    "Reviews all user-submitted content for appropriateness and accuracy before it goes live",
  ),
  ba(
    "b5-identity-verification",
    "Identity Verification AI",
    "B5",
    B5_CLUSTER,
    "High-value transaction participant identity verification",
    "security",
    "idle",
    8,
    97,
    "Optional identity verification for high-value transaction participants with consent management",
  ),
  ba(
    "b5-doc-authenticity",
    "Document Authenticity AI",
    "B5",
    B5_CLUSTER,
    "Uploaded document genuineness vs manipulation check",
    "security",
    "active",
    156,
    93,
    "Checks if uploaded documents appear genuine vs digitally manipulated using visual forensics",
  ),
  ba(
    "b5-session-security",
    "Session Security AI",
    "B5",
    B5_CLUSTER,
    "Session hijacking, token theft, suspicious behavior detection",
    "security",
    "active",
    1440,
    99,
    "Detects session hijacking attempts, token theft, and suspicious session behavior in real time",
  ),
  ba(
    "b5-api-security",
    "API Security AI",
    "B5",
    B5_CLUSTER,
    "API call abuse, rate limit violations, injection monitoring",
    "security",
    "active",
    1440,
    98,
    "Monitors all API calls for abuse, rate limit violations, and injection attack patterns",
  ),
  ba(
    "b5-audit-trail",
    "Audit Trail AI",
    "B5",
    B5_CLUSTER,
    "Immutable log of all admin actions, data changes, AI decisions",
    "security",
    "active",
    1440,
    100,
    "Maintains an immutable, tamper-proof log of every admin action, data change, and AI decision",
  ),
];

// ── CLUSTER B6: Graph & Relationship AIs (10 agents) ─────────────────────────────
const B6_CLUSTER = "Graph & Relationship AIs";
const B6_AGENTS: BackendAgent[] = [
  ba(
    "b6-client-network",
    "Client Network AI",
    "B6",
    B6_CLUSTER,
    "Client referral chain and relationship visual mapping",
    "graph",
    "active",
    234,
    90,
    "Builds and visualizes client referral chains and full relationship maps across the MSTC network",
  ),
  ba(
    "b6-property-network",
    "Property Network AI",
    "B6",
    B6_CLUSTER,
    "Property links by builder, locality, price band, competition",
    "graph",
    "active",
    456,
    91,
    "Links properties across builder, locality, price band, and competing listing relationships",
  ),
  ba(
    "b6-service-crossuse",
    "Service Cross-Use AI",
    "B6",
    B6_CLUSTER,
    "Multi-service MSTC clients relationship mapping",
    "graph",
    "active",
    234,
    89,
    "Maps which clients use multiple MSTC service verticals and identifies cross-sell opportunities",
  ),
  ba(
    "b6-builder-ecosystem",
    "Builder Ecosystem AI",
    "B6",
    B6_CLUSTER,
    "Builder JV, sub-contractor, investor relationship mapping",
    "graph",
    "active",
    120,
    87,
    "Maps builder ecosystem relationships: joint ventures, sub-contractors, and investor connections",
  ),
  ba(
    "b6-deal-network",
    "Deal Network AI",
    "B6",
    B6_CLUSTER,
    "All closed deals mapped by agent, channel, locality, type",
    "graph",
    "active",
    456,
    92,
    "Maps every closed deal across agent, channel, locality, and client type for pattern analysis",
  ),
  ba(
    "b6-influencer-map",
    "Influencer Map AI",
    "B6",
    B6_CLUSTER,
    "Architects, lawyers, accountants referral relationship map",
    "graph",
    "active",
    120,
    88,
    "Maps referral relationships with architects, lawyers, accountants, and other professional influencers",
  ),
  ba(
    "b6-knowledge-graph",
    "Knowledge Graph AI",
    "B6",
    B6_CLUSTER,
    "Property → locality → builder → RERA → price knowledge links",
    "graph",
    "active",
    1440,
    93,
    "Maintains a comprehensive knowledge graph linking all real estate concepts, entities, and relationships",
  ),
  ba(
    "b6-risk-propagation",
    "Risk Propagation AI",
    "B6",
    B6_CLUSTER,
    "Builder issue impact on all connected properties in network",
    "graph",
    "active",
    89,
    91,
    "If one builder has issues, instantly maps and flags all affected properties across the network",
  ),
  ba(
    "b6-opportunity-cluster",
    "Opportunity Cluster AI",
    "B6",
    B6_CLUSTER,
    "Lead + property + timing + agent opportunity cluster mapping",
    "graph",
    "active",
    345,
    88,
    "Maps optimal opportunity clusters: right lead, right property, right timing, right agent",
  ),
  ba(
    "b6-community-graph",
    "Community Graph AI",
    "B6",
    B6_CLUSTER,
    "Clients, partners, staff, media, regulators community map",
    "graph",
    "active",
    120,
    86,
    "Maps MSTC's full community network: clients, partners, staff, media contacts, and regulators",
  ),
];

// ── CLUSTER B7: Time-Series & Historical AIs (10 agents) ─────────────────────────
const B7_CLUSTER = "Time-Series & Historical AIs";
const B7_AGENTS: BackendAgent[] = [
  ba(
    "b7-price-history",
    "Price History AI",
    "B7",
    B7_CLUSTER,
    "5-year price history per locality and project",
    "timeseries",
    "active",
    30,
    96,
    "Full 5-year price history for every Ahmedabad locality and project with trend visualization",
  ),
  ba(
    "b7-enquiry-volume",
    "Enquiry Volume AI",
    "B7",
    B7_CLUSTER,
    "2-year weekly enquiry volume with trend and seasonality",
    "timeseries",
    "active",
    7,
    95,
    "2-year weekly enquiry volume data with trend extraction and seasonal pattern identification",
  ),
  ba(
    "b7-deal-velocity",
    "Deal Velocity AI",
    "B7",
    B7_CLUSTER,
    "Property selling speed trends per locality over time",
    "timeseries",
    "active",
    30,
    93,
    "Tracks how quickly properties are selling in each Ahmedabad locality over time",
  ),
  ba(
    "b7-interest-rate-history",
    "Interest Rate History AI",
    "B7",
    B7_CLUSTER,
    "Home loan rate history 2015–today with RBI events marked",
    "timeseries",
    "active",
    1,
    98,
    "Complete home loan interest rate history from 2015 to today with all RBI policy events marked",
  ),
  ba(
    "b7-jantri-history",
    "Jantri Rate History AI",
    "B7",
    B7_CLUSTER,
    "All Gujarat jantri revisions with market impact analysis",
    "timeseries",
    "active",
    1,
    97,
    "All historical Gujarat jantri rate revisions with measured market impact analysis for each change",
  ),
  ba(
    "b7-infra-timeline",
    "Infrastructure Timeline AI",
    "B7",
    B7_CLUSTER,
    "Complete Ahmedabad infrastructure history and future pipeline",
    "timeseries",
    "active",
    1,
    94,
    "Complete timeline of Ahmedabad infrastructure: past projects and full announced future pipeline",
  ),
  ba(
    "b7-policy-history",
    "Policy Impact History AI",
    "B7",
    B7_CLUSTER,
    "RERA, GST, demonetization, COVID market impact timeline",
    "timeseries",
    "active",
    1,
    95,
    "RERA, GST, demonetization, COVID — all policy events with measured Ahmedabad market impact",
  ),
  ba(
    "b7-client-journey",
    "Client Journey History AI",
    "B7",
    B7_CLUSTER,
    "Every client full timeline from first contact to post-sale",
    "timeseries",
    "active",
    1234,
    97,
    "Full timeline for every client: first contact, all interactions, deal, and post-sale relationship",
  ),
  ba(
    "b7-platform-growth",
    "Platform Growth AI",
    "B7",
    B7_CLUSTER,
    "MSTC own growth: properties, clients, deals, features timeline",
    "timeseries",
    "active",
    1,
    95,
    "MSTC's own growth timeline: properties, clients, deals, and features across all time",
  ),
  ba(
    "b7-market-cycle-history",
    "Market Cycle History AI",
    "B7",
    B7_CLUSTER,
    "Ahmedabad market cycles mapped: boom, correction, recovery",
    "timeseries",
    "active",
    1,
    94,
    "Maps all Ahmedabad market cycles historically: boom, correction, recovery, and growth phases",
  ),
];

// ── CLUSTER B8: Communication & Outreach AIs (20 agents) ───────────────────────
const B8_CLUSTER = "Communication & Outreach AIs";
const B8_AGENTS: BackendAgent[] = [
  ba(
    "b8-whatsapp-campaign",
    "WhatsApp Campaign AI",
    "B8",
    B8_CLUSTER,
    "Broadcast segment, draft, send, and track management",
    "communication",
    "active",
    12,
    93,
    "Manages all WhatsApp broadcast campaigns: segmentation, drafting, scheduling, sending, and tracking",
  ),
  ba(
    "b8-sms-campaign",
    "SMS Campaign AI",
    "B8",
    B8_CLUSTER,
    "Targeted SMS for non-WhatsApp users",
    "communication",
    "active",
    8,
    91,
    "Manages targeted SMS campaigns for leads and clients who prefer SMS over WhatsApp",
  ),
  ba(
    "b8-push-notification",
    "Push Notification AI",
    "B8",
    B8_CLUSTER,
    "PWA push: price drops, new matches, market alerts",
    "communication",
    "active",
    234,
    95,
    "Sends PWA push notifications: price drops, new property matches, and market alerts to subscribers",
  ),
  ba(
    "b8-re-engagement",
    "Re-Engagement AI",
    "B8",
    B8_CLUSTER,
    "30-day inactive user compelling re-engagement message",
    "communication",
    "active",
    23,
    87,
    "Generates and sends compelling re-engagement messages to users inactive for 30 or more days",
  ),
  ba(
    "b8-birthday",
    "Birthday AI",
    "B8",
    B8_CLUSTER,
    "Client birthday and property anniversary personalized messages",
    "communication",
    "active",
    4,
    98,
    "Sends personalized messages on client birthdays and property purchase anniversaries",
  ),
  ba(
    "b8-new-listing-alert",
    "New Listing Alert AI",
    "B8",
    B8_CLUSTER,
    "Instant matching buyer notification when listing is added",
    "communication",
    "active",
    34,
    96,
    "Instantly notifies all matching buyers when a new listing matching their criteria is published",
  ),
  ba(
    "b8-price-drop-alert",
    "Price Drop Alert AI (B8)",
    "B8",
    B8_CLUSTER,
    "Instant notification to shortlisters and viewers on price drops",
    "communication",
    "active",
    12,
    97,
    "Immediately notifies anyone who shortlisted or viewed a property when its price drops",
  ),
  ba(
    "b8-market-event",
    "Market Event AI",
    "B8",
    B8_CLUSTER,
    "RBI announcement and major event relevant client notification",
    "communication",
    "active",
    2,
    94,
    "Notifies relevant clients when major market events occur: RBI decisions, jantri changes, policy updates",
  ),
  ba(
    "b8-deal-stage",
    "Deal Stage AI",
    "B8",
    B8_CLUSTER,
    "Client transaction stage progress notifications",
    "communication",
    "active",
    45,
    97,
    "Automatically notifies clients at every stage of their ongoing property transaction",
  ),
  ba(
    "b8-doc-reminder",
    "Document Reminder AI",
    "B8",
    B8_CLUSTER,
    "Pending documents, deadlines, payment due date reminders",
    "communication",
    "active",
    89,
    98,
    "Sends timely reminders for pending documents, approaching deadlines, and payment due dates",
  ),
  ba(
    "b8-followup-sequence",
    "Follow-Up Sequence AI",
    "B8",
    B8_CLUSTER,
    "7-touch automated follow-up for every new lead",
    "communication",
    "active",
    234,
    91,
    "Manages the full 7-touch automated follow-up sequence for every new lead from first contact",
  ),
  ba(
    "b8-winback",
    "Win-Back AI",
    "B8",
    B8_CLUSTER,
    "Cold lead re-engagement strategy and execution",
    "communication",
    "active",
    23,
    82,
    "Analyzes why leads went cold, generates tailored re-engagement strategy, and executes it",
  ),
  ba(
    "b8-referral-request",
    "Referral Request AI",
    "B8",
    B8_CLUSTER,
    "Post-deal referral request at optimal timing",
    "communication",
    "active",
    8,
    88,
    "Requests referrals from happy clients at the optimal timing post-deal close",
  ),
  ba(
    "b8-feedback-collection",
    "Feedback Collection AI",
    "B8",
    B8_CLUSTER,
    "Post-interaction feedback request and processing",
    "communication",
    "active",
    89,
    94,
    "Requests feedback after every interaction, processes results for service improvement",
  ),
  ba(
    "b8-broadcast-manager",
    "Broadcast Manager AI",
    "B8",
    B8_CLUSTER,
    "All outbound communication channel management",
    "communication",
    "active",
    234,
    93,
    "Manages all outbound communication across WhatsApp, SMS, email, and push notification channels",
  ),
  ba(
    "b8-unsubscribe-manager",
    "Unsubscribe Manager AI",
    "B8",
    B8_CLUSTER,
    "Opt-out management and compliance enforcement",
    "communication",
    "active",
    12,
    99,
    "Manages all opt-outs across every communication channel and ensures full compliance",
  ),
  ba(
    "b8-template-library",
    "Template Library AI",
    "B8",
    B8_CLUSTER,
    "Message template maintenance and optimization",
    "communication",
    "active",
    7,
    91,
    "Maintains and continuously optimizes the library of message templates for every scenario",
  ),
  ba(
    "b8-ab-message",
    "A/B Message AI",
    "B8",
    B8_CLUSTER,
    "Message variant testing with automatic winner deployment",
    "communication",
    "active",
    4,
    90,
    "Tests different message variants for each use case and automatically deploys the winning version",
  ),
  ba(
    "b8-communication-analytics",
    "Communication Analytics AI",
    "B8",
    B8_CLUSTER,
    "Open rates, click rates, response rates across all channels",
    "communication",
    "active",
    24,
    95,
    "Tracks open rates, click rates, and response rates across every communication channel",
  ),
  ba(
    "b8-newsletter",
    "Newsletter AI",
    "B8",
    B8_CLUSTER,
    "Weekly AI-curated personalized newsletter per segment",
    "communication",
    "active",
    7,
    90,
    "Generates and sends weekly AI-curated newsletter, personalized for each subscriber segment",
  ),
];

// ── CLUSTER B9: Innovation & Growth AIs (15 agents) ─────────────────────────────
const B9_CLUSTER = "Innovation & Growth AIs";
const B9_AGENTS: BackendAgent[] = [
  ba(
    "b9-feature-suggestion",
    "Feature Suggestion AI",
    "B9",
    B9_CLUSTER,
    "Weekly ranked feature ideas from user behavior analysis",
    "innovation",
    "active",
    7,
    88,
    "Every week, generates a ranked list of new feature ideas based on user behavior patterns",
  ),
  ba(
    "b9-tech-upgrade",
    "Technology Upgrade AI",
    "B9",
    B9_CLUSTER,
    "Tech landscape monitoring and platform upgrade recommendations",
    "innovation",
    "active",
    7,
    85,
    "Monitors global tech landscape and recommends platform upgrades for competitive advantage",
  ),
  ba(
    "b9-business-expansion",
    "Business Expansion AI",
    "B9",
    B9_CLUSTER,
    "New city and service expansion opportunity identification",
    "innovation",
    "active",
    7,
    83,
    "Identifies and analyzes opportunities for geographic and service line expansion",
  ),
  ba(
    "b9-partnership",
    "Partnership AI",
    "B9",
    B9_CLUSTER,
    "Strategic partner identification and scoring",
    "innovation",
    "active",
    7,
    84,
    "Identifies and scores potential strategic partners: banks, builders, agents, and service providers",
  ),
  ba(
    "b9-pricing-strategy",
    "Pricing Strategy AI",
    "B9",
    B9_CLUSTER,
    "Optimal service and commission pricing recommendations",
    "innovation",
    "active",
    7,
    86,
    "Recommends optimal pricing for MSTC services and commission structures from market analysis",
  ),
  ba(
    "b9-market-entry",
    "Market Entry AI",
    "B9",
    B9_CLUSTER,
    "New real estate segment entry analysis",
    "innovation",
    "idle",
    1,
    82,
    "Analyzes opportunities and risks for entering new real estate segments: luxury, commercial, industrial",
  ),
  ba(
    "b9-innovation-pipeline",
    "Innovation Pipeline AI",
    "B9",
    B9_CLUSTER,
    "All ideas tracked from suggestion through deployment",
    "innovation",
    "active",
    30,
    90,
    "Tracks every innovation idea from initial suggestion through development, testing, and deployment",
  ),
  ba(
    "b9-competitor-response",
    "Competitor Response AI",
    "B9",
    B9_CLUSTER,
    "Competitor feature launch evaluation for MSTC response",
    "innovation",
    "active",
    7,
    84,
    "When competitors launch features, evaluates if and how MSTC should respond",
  ),
  ba(
    "b9-feedback-loop",
    "Client Feedback Loop AI",
    "B9",
    B9_CLUSTER,
    "Client feedback conversion to product improvement tickets",
    "innovation",
    "active",
    89,
    92,
    "Converts all client feedback into actionable product improvement tickets with priority scoring",
  ),
  ba(
    "b9-industry-trend",
    "Industry Trend AI",
    "B9",
    B9_CLUSTER,
    "Global PropTech, FinTech, LegalTech trend monitoring",
    "innovation",
    "active",
    24,
    86,
    "Monitors global PropTech, FinTech, and LegalTech trends and recommends adoption",
  ),
  ba(
    "b9-regulatory-radar",
    "Regulatory Radar AI",
    "B9",
    B9_CLUSTER,
    "Upcoming Gujarat/India real estate regulatory change monitoring",
    "innovation",
    "active",
    24,
    93,
    "Monitors upcoming regulatory changes in Gujarat and India real estate, alerts before impact",
  ),
  ba(
    "b9-talent-intelligence",
    "Talent Intelligence AI",
    "B9",
    B9_CLUSTER,
    "Skill gap identification and hiring priority suggestions",
    "innovation",
    "idle",
    7,
    80,
    "Identifies organizational skill gaps and suggests hiring priorities for growth acceleration",
  ),
  ba(
    "b9-strategic-risk",
    "Strategic Risk AI",
    "B9",
    B9_CLUSTER,
    "Regulatory, competitive, market, operational risk identification",
    "innovation",
    "active",
    7,
    87,
    "Identifies strategic risks across regulatory, competitive, market, and operational dimensions",
  ),
  ba(
    "b9-growth-lever",
    "Growth Lever AI",
    "B9",
    B9_CLUSTER,
    "Highest-impact growth actions ranked by ROI",
    "innovation",
    "active",
    7,
    85,
    "Identifies and ranks the highest-impact actions to accelerate MSTC growth by ROI",
  ),
  ba(
    "b9-future-state",
    "Future State AI",
    "B9",
    B9_CLUSTER,
    "MSTC 3-year modeling under different growth scenarios",
    "innovation",
    "processing",
    7,
    81,
    "Models MSTC's strategic position in 3 years under optimistic, base, and conservative growth scenarios",
  ),
];

// ── CLUSTER B10: Admin Intelligence AIs (15 agents) ────────────────────────────
const B10_CLUSTER = "Admin Intelligence AIs";
const B10_AGENTS: BackendAgent[] = [
  ba(
    "b10-dashboard-personal",
    "Dashboard Personalization AI",
    "B10",
    B10_CLUSTER,
    "Role-based admin dashboard configuration per user",
    "admin",
    "active",
    12,
    95,
    "Configures admin dashboard layout and widgets based on each admin user's role and usage patterns",
  ),
  ba(
    "b10-widget-intelligence",
    "Widget Intelligence AI",
    "B10",
    B10_CLUSTER,
    "Dashboard widget rearrangement from usage patterns",
    "admin",
    "active",
    1440,
    93,
    "Rearranges dashboard widgets based on each admin's actual usage patterns and priorities",
  ),
  ba(
    "b10-alert-priority",
    "Alert Priority AI",
    "B10",
    B10_CLUSTER,
    "Alert management ensuring only high-priority ones interrupt",
    "admin",
    "active",
    1440,
    96,
    "Manages all system alerts, ensures only genuinely high-priority alerts interrupt admin workflow",
  ),
  ba(
    "b10-quick-action",
    "Quick Action AI",
    "B10",
    B10_CLUSTER,
    "Most common admin actions surfaced as one-click commands",
    "admin",
    "active",
    1440,
    94,
    "Learns most common admin actions and surfaces them as one-click quick commands",
  ),
  ba(
    "b10-custom-report",
    "Custom Report AI",
    "B10",
    B10_CLUSTER,
    "Natural language to instant custom report generation",
    "admin",
    "active",
    89,
    92,
    "Natural language query: 'Show NRI leads in last 90 days' → generates instant custom report",
  ),
  ba(
    "b10-drill-down",
    "Drill-Down AI",
    "B10",
    B10_CLUSTER,
    "Any dashboard number click expands to full detail",
    "admin",
    "active",
    1440,
    97,
    "Every number on every dashboard is clickable — auto-expands to full detail and source data",
  ),
  ba(
    "b10-annotation",
    "Annotation AI",
    "B10",
    B10_CLUSTER,
    "Admin metric notes preserved as context across sessions",
    "admin",
    "active",
    45,
    95,
    "Admins can annotate any metric; AI preserves context and references annotations in future sessions",
  ),
  ba(
    "b10-correlation",
    "Correlation AI",
    "B10",
    B10_CLUSTER,
    "Hidden metric correlations surfaced with explanations",
    "admin",
    "active",
    24,
    87,
    "Surfaces hidden correlations: 'Leads up but deals flat — here's why' with supporting data",
  ),
  ba(
    "b10-command-bar",
    "Command Bar AI",
    "B10",
    B10_CLUSTER,
    "Plain-language admin command execution",
    "admin",
    "active",
    234,
    93,
    "Type any command in plain language and AI executes it: filters, reports, actions, configurations",
  ),
  ba(
    "b10-goal-tracking",
    "Goal Tracking AI",
    "B10",
    B10_CLUSTER,
    "Monthly/quarterly goal tracking with trajectory alerts",
    "admin",
    "active",
    1440,
    96,
    "Tracks monthly and quarterly goals, alerts on positive and negative trajectory changes",
  ),
  ba(
    "b10-anomaly-alert",
    "Anomaly Alert AI",
    "B10",
    B10_CLUSTER,
    "Metric spike/drop detection with likely cause explanation",
    "admin",
    "active",
    234,
    91,
    "Detects unusual spikes or drops in any metric and explains the most likely cause",
  ),
  ba(
    "b10-workflow",
    "Workflow AI",
    "B10",
    B10_CLUSTER,
    "Admin workflow learning and optimization suggestions",
    "admin",
    "active",
    1440,
    89,
    "Learns each admin's workflow patterns and suggests optimizations and automations",
  ),
  ba(
    "b10-role-management",
    "Role Management AI",
    "B10",
    B10_CLUSTER,
    "Staff access, permissions, audit trail management",
    "admin",
    "active",
    12,
    99,
    "Manages staff access levels, permission changes, and maintains full access audit trail",
  ),
  ba(
    "b10-meeting-brief",
    "Meeting Brief AI",
    "B10",
    B10_CLUSTER,
    "Pre-meeting complete client brief from CRM data",
    "admin",
    "active",
    12,
    93,
    "Before any client meeting, generates a complete brief from all CRM data and interaction history",
  ),
  ba(
    "b10-daily-digest",
    "Daily Digest AI",
    "B10",
    B10_CLUSTER,
    "Morning digest: yesterday summary, today's priorities",
    "admin",
    "active",
    1,
    95,
    "Every morning: what happened yesterday, what needs attention today, and key alerts for the day",
  ),
];

// ── CLUSTER B11: Multimodal AIs (15 agents) ─────────────────────────────────────
const B11_CLUSTER = "Multimodal AIs";
const B11_AGENTS: BackendAgent[] = [
  ba(
    "b11-property-synth",
    "Property Intelligence Synthesizer",
    "B11",
    B11_CLUSTER,
    "Text + photos + floor plan + location → complete intelligence card",
    "multimodal",
    "active",
    234,
    92,
    "Synthesizes text, photos, floor plans, and location data into a complete property intelligence card",
  ),
  ba(
    "b11-client-profile",
    "Client Profile Builder",
    "B11",
    B11_CLUSTER,
    "Chat + browsing + forms + voice → unified client profile",
    "multimodal",
    "active",
    456,
    91,
    "Builds unified client profile from chat history, browsing behavior, form submissions, and voice inputs",
  ),
  ba(
    "b11-market-briefing",
    "Market Briefing AI",
    "B11",
    B11_CLUSTER,
    "News + price data + charts → spoken and written market brief",
    "multimodal",
    "active",
    24,
    90,
    "Synthesizes news, price data, and charts into a complete spoken and written market brief",
  ),
  ba(
    "b11-due-diligence-synth",
    "Due Diligence Synthesizer",
    "B11",
    B11_CLUSTER,
    "Documents + photos + RERA data → unified due diligence score",
    "multimodal",
    "active",
    89,
    91,
    "Combines documents, photos, and RERA data into a unified due diligence score and report",
  ),
  ba(
    "b11-negotiation-intel",
    "Negotiation Intelligence AI",
    "B11",
    B11_CLUSTER,
    "Property data + market + urgency → full negotiation strategy",
    "multimodal",
    "active",
    156,
    88,
    "Combines property data, market conditions, and client urgency signals into a complete negotiation strategy",
  ),
  ba(
    "b11-loan-optimization",
    "Loan Optimization AI",
    "B11",
    B11_CLUSTER,
    "Salary slips + statements + property + rates → optimal loan",
    "multimodal",
    "active",
    234,
    92,
    "Processes salary slips, bank statements, property details, and current rates for optimal loan structure",
  ),
  ba(
    "b11-investment-analysis",
    "Investment Analysis AI",
    "B11",
    B11_CLUSTER,
    "Property + forecast + tax profile + portfolio → full recommendation",
    "multimodal",
    "active",
    178,
    89,
    "Full investment recommendation from property data, forecasts, tax profile, and existing portfolio",
  ),
  ba(
    "b11-complaint-resolution",
    "Complaint Resolution AI",
    "B11",
    B11_CLUSTER,
    "Complaint + documents + precedents → complete resolution strategy",
    "multimodal",
    "active",
    34,
    91,
    "Generates complete resolution strategy from complaint details, supporting documents, and precedents",
  ),
  ba(
    "b11-visit-report",
    "Site Visit Report AI",
    "B11",
    B11_CLUSTER,
    "Photos + notes + property data → complete site visit report",
    "multimodal",
    "active",
    89,
    93,
    "Processes site visit photos and notes with property data to generate a complete structured report",
  ),
  ba(
    "b11-full-journey",
    "Full Journey AI",
    "B11",
    B11_CLUSTER,
    "All interactions synthesized → next best action recommendation",
    "multimodal",
    "active",
    1234,
    90,
    "Synthesizes all interactions across all channels to generate the single best next action recommendation",
  ),
  ba(
    "b11-voice-to-action",
    "Voice-to-Action AI",
    "B11",
    B11_CLUSTER,
    "Voice command → any platform action execution",
    "multimodal",
    "active",
    345,
    91,
    "Processes voice commands and executes any platform action: search, filter, enquire, report",
  ),
  ba(
    "b11-image-to-data",
    "Image-to-Data AI",
    "B11",
    B11_CLUSTER,
    "Any property image → structured data extraction",
    "multimodal",
    "active",
    456,
    89,
    "Extracts structured data from any property image: room count, condition, features, approximate area",
  ),
  ba(
    "b11-video-tour",
    "Video Tour AI",
    "B11",
    B11_CLUSTER,
    "Video walkthrough processing → key features and description",
    "multimodal",
    "active",
    23,
    86,
    "Processes video walkthroughs, extracts key property features, and generates a structured description",
  ),
  ba(
    "b11-speech-to-form",
    "Speech-to-Form AI",
    "B11",
    B11_CLUSTER,
    "User speaks requirements → form filled automatically",
    "multimodal",
    "active",
    234,
    90,
    "User speaks their property requirements and the relevant form is filled automatically from speech",
  ),
  ba(
    "b11-data-to-story",
    "Data-to-Story AI",
    "B11",
    B11_CLUSTER,
    "Raw analytics data → human-readable narrative report",
    "multimodal",
    "active",
    89,
    92,
    "Converts raw analytics data into compelling, human-readable narrative reports for any audience",
  ),
];

// ── CLUSTER B12: Specialized Vertical AIs (25 agents) ────────────────────────────
const B12_CLUSTER = "Specialized Vertical AIs";
const B12_AGENTS: BackendAgent[] = [
  ba(
    "b12-capacity-optimizer",
    "Capacity Optimizer AI",
    "B12",
    B12_CLUSTER,
    "Event venue capacity optimization",
    "vertical",
    "active",
    34,
    91,
    "Optimizes venue capacity allocation for events based on guest profile, seating, and safety requirements",
  ),
  ba(
    "b12-budget-planner",
    "Budget Planner AI",
    "B12",
    B12_CLUSTER,
    "Event budget breakdown and optimization",
    "vertical",
    "active",
    45,
    90,
    "Builds comprehensive event budget breakdown with optimization suggestions per line item",
  ),
  ba(
    "b12-vendor-comparator",
    "Vendor Comparator AI",
    "B12",
    B12_CLUSTER,
    "Event vendor comparison table across quality and cost",
    "vertical",
    "active",
    23,
    89,
    "Compares event vendors across quality, cost, reliability, and past performance",
  ),
  ba(
    "b12-timeline-generator",
    "Timeline Generator AI",
    "B12",
    B12_CLUSTER,
    "Event day timeline auto-generation",
    "vertical",
    "active",
    34,
    93,
    "Auto-generates a detailed event day timeline from event type, duration, and guest count",
  ),
  ba(
    "b12-rsvp-predictor",
    "RSVP Predictor AI",
    "B12",
    B12_CLUSTER,
    "Event attendance prediction from RSVP patterns",
    "vertical",
    "active",
    12,
    87,
    "Predicts actual attendance from RSVP response rates and historical patterns",
  ),
  ba(
    "b12-csr-optimizer",
    "CSR Budget Optimizer AI",
    "B12",
    B12_CLUSTER,
    "CSR spend optimization for maximum social impact",
    "vertical",
    "active",
    7,
    88,
    "Optimizes CSR budget allocation across initiatives for maximum measurable social impact",
  ),
  ba(
    "b12-impact-report",
    "Impact Report AI",
    "B12",
    B12_CLUSTER,
    "CSR and NGO activity impact report generation",
    "vertical",
    "active",
    4,
    91,
    "Generates comprehensive impact reports for all CSR and NGO activities with outcome metrics",
  ),
  ba(
    "b12-donation-tax",
    "Donation Tax Calculator AI",
    "B12",
    B12_CLUSTER,
    "80G donation tax benefit calculation",
    "vertical",
    "active",
    89,
    99,
    "Calculates exact Section 80G tax benefit for any donation amount and taxpayer profile",
  ),
  ba(
    "b12-volunteer-matcher",
    "Volunteer Matcher AI",
    "B12",
    B12_CLUSTER,
    "Volunteer-to-initiative optimal matching",
    "vertical",
    "active",
    12,
    88,
    "Matches volunteers to the most suitable initiatives based on skills, availability, and interest",
  ),
  ba(
    "b12-grant-finder",
    "Grant Finder AI",
    "B12",
    B12_CLUSTER,
    "Available grant opportunity identification for NGO",
    "vertical",
    "active",
    7,
    86,
    "Identifies available grants and funding opportunities suitable for MSTC's NGO initiatives",
  ),
  ba(
    "b12-athlete-profiler",
    "Athlete Profiler AI",
    "B12",
    B12_CLUSTER,
    "Athlete performance profile and sponsorship value analysis",
    "vertical",
    "active",
    12,
    87,
    "Creates comprehensive athlete profiles with performance data and sponsorship value assessment",
  ),
  ba(
    "b12-sponsorship-matcher",
    "Sponsorship Matcher AI",
    "B12",
    B12_CLUSTER,
    "Athlete-to-sponsor optimal matching",
    "vertical",
    "active",
    8,
    85,
    "Matches athletes to the most suitable sponsorship opportunities based on profile and goals",
  ),
  ba(
    "b12-tournament-planner",
    "Tournament Planner AI",
    "B12",
    B12_CLUSTER,
    "Sports tournament planning and logistics",
    "vertical",
    "active",
    4,
    88,
    "Plans and manages all logistics for sports tournaments: scheduling, venues, brackets, and officials",
  ),
  ba(
    "b12-performance-tracker",
    "Performance Tracker AI",
    "B12",
    B12_CLUSTER,
    "Athlete and team performance analytics",
    "vertical",
    "active",
    34,
    90,
    "Tracks and analyzes athlete and team performance metrics across all sports managed by MSTC",
  ),
  ba(
    "b12-media-monitor",
    "Media Monitor AI",
    "B12",
    B12_CLUSTER,
    "Sports and cultural events media coverage tracking",
    "vertical",
    "active",
    24,
    87,
    "Monitors media coverage for all MSTC sports and cultural events across all platforms",
  ),
  ba(
    "b12-genre-intelligence",
    "Genre Intelligence AI",
    "B12",
    B12_CLUSTER,
    "Music genre trends and audience preference analysis",
    "vertical",
    "active",
    24,
    86,
    "Analyzes music genre trends and audience preferences for MSTC's cultural event programming",
  ),
  ba(
    "b12-booking-workflow",
    "Booking Workflow AI",
    "B12",
    B12_CLUSTER,
    "Artist booking process automation",
    "vertical",
    "active",
    34,
    92,
    "Automates the complete artist booking workflow from inquiry through contract to event day",
  ),
  ba(
    "b12-royalty-tracker",
    "Royalty Tracker AI",
    "B12",
    B12_CLUSTER,
    "Music royalty calculation and distribution tracking",
    "vertical",
    "active",
    7,
    91,
    "Tracks and calculates music royalties for all artists managed through MSTC's cultural division",
  ),
  ba(
    "b12-artist-availability",
    "Artist Availability AI",
    "B12",
    B12_CLUSTER,
    "Real-time artist availability and scheduling",
    "vertical",
    "active",
    45,
    94,
    "Tracks real-time availability of all artists and manages scheduling across all events",
  ),
  ba(
    "b12-content-monetization",
    "Content Monetization AI",
    "B12",
    B12_CLUSTER,
    "Creative content monetization strategy optimization",
    "vertical",
    "active",
    12,
    86,
    "Identifies and optimizes monetization opportunities for all creative content produced by MSTC artists",
  ),
  ba(
    "b12-itinerary-builder",
    "Itinerary Builder AI",
    "B12",
    B12_CLUSTER,
    "Gujarat tourism personalized itinerary generation",
    "vertical",
    "active",
    89,
    91,
    "Generates fully personalized Gujarat tourism itineraries based on interests, duration, and budget",
  ),
  ba(
    "b12-destination-intelligence",
    "Destination Intelligence AI",
    "B12",
    B12_CLUSTER,
    "Gujarat destination deep intelligence and travel insights",
    "vertical",
    "active",
    45,
    89,
    "Deep intelligence on every Gujarat destination: culture, seasons, attractions, and travel tips",
  ),
  ba(
    "b12-cost-estimator",
    "Cost Estimator AI",
    "B12",
    B12_CLUSTER,
    "Tourism trip total cost estimation",
    "vertical",
    "active",
    89,
    93,
    "Estimates the complete cost of any Gujarat tourism trip: transport, accommodation, food, activities",
  ),
  ba(
    "b12-influencer-manager",
    "Influencer Manager AI",
    "B12",
    B12_CLUSTER,
    "Tourism and cultural event influencer campaign management",
    "vertical",
    "active",
    12,
    85,
    "Manages influencer campaigns for MSTC tourism and cultural events from identification to reporting",
  ),
  ba(
    "b12-experience-curator",
    "Experience Curator AI",
    "B12",
    B12_CLUSTER,
    "Unique Gujarat experience discovery and packaging",
    "vertical",
    "active",
    34,
    88,
    "Discovers and packages unique Gujarat cultural experiences for high-value tourism clients",
  ),
];

// ── CLUSTER B13: Platform Operations AIs (15 agents) ───────────────────────────
const B13_CLUSTER = "Platform Operations AIs";
const B13_AGENTS: BackendAgent[] = [
  ba(
    "b13-platform-health",
    "Platform Health AI",
    "B13",
    B13_CLUSTER,
    "Real-time uptime, response time, error rate health score",
    "operations",
    "active",
    1440,
    99,
    "Real-time platform health score tracking uptime, response time, and error rate continuously",
  ),
  ba(
    "b13-feature-usage",
    "Feature Usage AI",
    "B13",
    B13_CLUSTER,
    "Most/least used feature tracking to guide roadmap",
    "operations",
    "active",
    1440,
    97,
    "Tracks feature usage frequency, identifies most and least used features to guide development roadmap",
  ),
  ba(
    "b13-error-pattern",
    "Error Pattern AI",
    "B13",
    B13_CLUSTER,
    "Error clustering by type, frequency, and impact",
    "operations",
    "active",
    1440,
    96,
    "Clusters all platform errors by type, frequency, and user impact to prioritize fixes",
  ),
  ba(
    "b13-load-test",
    "Load Test AI",
    "B13",
    B13_CLUSTER,
    "High traffic simulation before major events",
    "operations",
    "idle",
    2,
    95,
    "Simulates high traffic loads before major promotional events or campaigns to prevent downtime",
  ),
  ba(
    "b13-database-health",
    "Database Health AI",
    "B13",
    B13_CLUSTER,
    "Data integrity, storage, and query performance monitoring",
    "operations",
    "active",
    1440,
    98,
    "Continuously monitors database integrity, storage utilization, and query performance",
  ),
  ba(
    "b13-api-health",
    "API Health AI",
    "B13",
    B13_CLUSTER,
    "All external API connection failure monitoring",
    "operations",
    "active",
    1440,
    99,
    "Monitors all external API connections for failures, latency spikes, and unexpected responses",
  ),
  ba(
    "b13-deployment-monitor",
    "Deployment Monitor AI",
    "B13",
    B13_CLUSTER,
    "Deployment tracking and regression flagging",
    "operations",
    "active",
    4,
    97,
    "Tracks every deployment, monitors for performance regressions, and alerts immediately",
  ),
  ba(
    "b13-backup-verification",
    "Backup Verification AI",
    "B13",
    B13_CLUSTER,
    "Backup completion confirmation and last verified time display",
    "operations",
    "active",
    4,
    100,
    "Confirms all backups completed successfully, displays last verified timestamp prominently",
  ),
  ba(
    "b13-cost-optimization",
    "Cost Optimization AI",
    "B13",
    B13_CLUSTER,
    "Infrastructure cost monitoring and reduction suggestions",
    "operations",
    "processing",
    7,
    88,
    "Monitors all infrastructure costs and continuously suggests optimization opportunities",
  ),
  ba(
    "b13-capacity-planner",
    "Capacity Planner AI",
    "B13",
    B13_CLUSTER,
    "Infrastructure scaling need prediction",
    "operations",
    "active",
    7,
    90,
    "Predicts when infrastructure will need scaling based on growth trends and usage patterns",
  ),
  ba(
    "b13-performance",
    "Performance AI (B13)",
    "B13",
    B13_CLUSTER,
    "Core Web Vitals, page speed, mobile score continuous monitoring",
    "operations",
    "active",
    1440,
    97,
    "Continuous monitoring of Core Web Vitals, page speed scores, and mobile performance metrics",
  ),
  ba(
    "b13-cdn-optimizer",
    "CDN Optimizer AI",
    "B13",
    B13_CLUSTER,
    "Asset delivery optimization across devices and connections",
    "operations",
    "active",
    1440,
    96,
    "Optimizes content delivery network configuration for fastest asset delivery across all devices",
  ),
  ba(
    "b13-cache-intelligence",
    "Cache Intelligence AI",
    "B13",
    B13_CLUSTER,
    "Caching strategy management ensuring data freshness",
    "operations",
    "active",
    1440,
    95,
    "Intelligently manages caching strategy balancing performance with data freshness requirements",
  ),
  ba(
    "b13-code-quality",
    "Code Quality AI",
    "B13",
    B13_CLUSTER,
    "Codebase health monitoring and technical debt flagging",
    "operations",
    "active",
    24,
    91,
    "Monitors codebase health, identifies technical debt hotspots, and flags risky code patterns",
  ),
  ba(
    "b13-dependency",
    "Dependency AI",
    "B13",
    B13_CLUSTER,
    "Third-party dependency updates and vulnerability monitoring",
    "operations",
    "active",
    24,
    97,
    "Monitors all third-party dependencies for available updates and security vulnerabilities",
  ),
];

// ── CLUSTER B14: Reinforcement Learning AIs (10 agents) ──────────────────────────
const B14_CLUSTER = "Reinforcement Learning AIs";
const B14_AGENTS: BackendAgent[] = [
  ba(
    "b14-click-learning",
    "Click Learning AI",
    "B14",
    B14_CLUSTER,
    "Click behavior learning and content rearrangement",
    "reinforcement",
    "active",
    1440,
    92,
    "Learns from every click and rearranges content toward highest engagement patterns",
  ),
  ba(
    "b14-search-learning",
    "Search Learning AI",
    "B14",
    B14_CLUSTER,
    "Search quality continuous improvement from every query",
    "reinforcement",
    "active",
    3456,
    93,
    "Every search makes search smarter. Accuracy improved from 1,247 training searches this month",
  ),
  ba(
    "b14-chat-learning",
    "Chat Learning AI",
    "B14",
    B14_CLUSTER,
    "Chat AI quality improvement from every conversation",
    "reinforcement",
    "active",
    892,
    94,
    "Every conversation improves chat AI quality. Current monthly score: 94/100",
  ),
  ba(
    "b14-pricing-learning",
    "Pricing Learning AI",
    "B14",
    B14_CLUSTER,
    "Valuation accuracy retraining from every deal and loss",
    "reinforcement",
    "active",
    234,
    90,
    "Every closed deal and lost lead retrains the valuation model, improving accuracy continuously",
  ),
  ba(
    "b14-lead-learning",
    "Lead Learning AI",
    "B14",
    B14_CLUSTER,
    "Lead scoring retraining from every conversion and loss",
    "reinforcement",
    "active",
    456,
    92,
    "Every converted or lost lead retrains the lead scoring model with visible accuracy improvement",
  ),
  ba(
    "b14-recommendation-learning",
    "Recommendation Learning AI",
    "B14",
    B14_CLUSTER,
    "Recommender retraining from accept/reject signals",
    "reinforcement",
    "active",
    789,
    91,
    "Every recommendation acceptance or rejection retrains the recommender. Acceptance rate: 67%",
  ),
  ba(
    "b14-content-learning",
    "Content Learning AI",
    "B14",
    B14_CLUSTER,
    "Content performance retraining from read/ignored signals",
    "reinforcement",
    "active",
    1234,
    89,
    "Every article read or ignored retrains the content AI. Performance score improved 23% this month",
  ),
  ba(
    "b14-filter-learning",
    "Filter Learning AI",
    "B14",
    B14_CLUSTER,
    "User filter preference learning and auto-surfacing",
    "reinforcement",
    "active",
    2341,
    90,
    "Learns user filter preferences, automatically surfaces most likely-used filters first",
  ),
  ba(
    "b14-sequence-learning",
    "Sequence Learning AI",
    "B14",
    B14_CLUSTER,
    "Enquiry-leading page sequence identification and optimization",
    "reinforcement",
    "active",
    1440,
    87,
    "Identifies which page sequences lead to enquiries and optimizes user journeys toward them",
  ),
  ba(
    "b14-timing-learning",
    "Timing Learning AI",
    "B14",
    B14_CLUSTER,
    "Per-user optimal outreach timing learning",
    "reinforcement",
    "active",
    789,
    88,
    "Learns best outreach time for each user. Optimal: Tuesday 7pm. Accuracy improving weekly",
  ),
];

// ── Exports ──────────────────────────────────────────────────────────────
export const BACKEND_CLUSTERS: BackendClusterConfig[] = [
  {
    code: "B1",
    name: "Autonomous Operation AIs",
    description: "25 self-executing AI agents that run the platform 24/7",
    agentCount: 25,
    primaryCategory: "autonomous",
    color: "#c9a84c",
  },
  {
    code: "B2",
    name: "Machine Learning AIs",
    description: "20 ML models continuously learning from all platform data",
    agentCount: 20,
    primaryCategory: "ml",
    color: "#3b82f6",
  },
  {
    code: "B3",
    name: "Neural Network AIs",
    description: "15 deep neural network AIs for advanced pattern recognition",
    agentCount: 15,
    primaryCategory: "neural",
    color: "#a855f7",
  },
  {
    code: "B4",
    name: "Data & Analytics AIs",
    description: "20 analytics AIs turning raw data into business intelligence",
    agentCount: 20,
    primaryCategory: "analytics",
    color: "#10b981",
  },
  {
    code: "B5",
    name: "Security & Integrity AIs",
    description: "15 security AIs protecting the platform and all data",
    agentCount: 15,
    primaryCategory: "security",
    color: "#ef4444",
  },
  {
    code: "B6",
    name: "Graph & Relationship AIs",
    description: "10 graph AIs mapping all business relationships",
    agentCount: 10,
    primaryCategory: "graph",
    color: "#f97316",
  },
  {
    code: "B7",
    name: "Time-Series & Historical AIs",
    description:
      "10 historical intelligence AIs analyzing all time-series data",
    agentCount: 10,
    primaryCategory: "timeseries",
    color: "#06b6d4",
  },
  {
    code: "B8",
    name: "Communication & Outreach AIs",
    description: "20 outreach AIs managing all client communications",
    agentCount: 20,
    primaryCategory: "communication",
    color: "#ec4899",
  },
  {
    code: "B9",
    name: "Innovation & Growth AIs",
    description: "15 strategic AIs driving business growth and innovation",
    agentCount: 15,
    primaryCategory: "innovation",
    color: "#22c55e",
  },
  {
    code: "B10",
    name: "Admin Intelligence AIs",
    description: "15 AIs making the admin dashboard smarter every day",
    agentCount: 15,
    primaryCategory: "admin",
    color: "#eab308",
  },
  {
    code: "B11",
    name: "Multimodal AIs",
    description: "15 AIs processing text, images, voice, and data together",
    agentCount: 15,
    primaryCategory: "multimodal",
    color: "#8b5cf6",
  },
  {
    code: "B12",
    name: "Specialized Vertical AIs",
    description: "25 deep-specialist AIs for each MSTC service vertical",
    agentCount: 25,
    primaryCategory: "vertical",
    color: "#14b8a6",
  },
  {
    code: "B13",
    name: "Platform Operations AIs",
    description: "15 AIs ensuring platform reliability and performance",
    agentCount: 15,
    primaryCategory: "operations",
    color: "#6366f1",
  },
  {
    code: "B14",
    name: "Reinforcement Learning AIs",
    description: "10 RL AIs that get smarter with every user interaction",
    agentCount: 10,
    primaryCategory: "reinforcement",
    color: "#f43f5e",
  },
];

export const ALL_BACKEND_AGENTS: BackendAgent[] = [
  ...B1_AGENTS,
  ...B2_AGENTS,
  ...B3_AGENTS,
  ...B4_AGENTS,
  ...B5_AGENTS,
  ...B6_AGENTS,
  ...B7_AGENTS,
  ...B8_AGENTS,
  ...B9_AGENTS,
  ...B10_AGENTS,
  ...B11_AGENTS,
  ...B12_AGENTS,
  ...B13_AGENTS,
  ...B14_AGENTS,
];

export const BACKEND_CLUSTER_NAMES: Record<BackendClusterCode, string> = {
  B1: "Autonomous Operation AIs",
  B2: "Machine Learning AIs",
  B3: "Neural Network AIs",
  B4: "Data & Analytics AIs",
  B5: "Security & Integrity AIs",
  B6: "Graph & Relationship AIs",
  B7: "Time-Series & Historical AIs",
  B8: "Communication & Outreach AIs",
  B9: "Innovation & Growth AIs",
  B10: "Admin Intelligence AIs",
  B11: "Multimodal AIs",
  B12: "Specialized Vertical AIs",
  B13: "Platform Operations AIs",
  B14: "Reinforcement Learning AIs",
};

export const BACKEND_CLUSTER_STATS: Record<
  string,
  { total: number; active: number; health: number }
> = Object.fromEntries(
  (Object.keys(BACKEND_CLUSTER_NAMES) as BackendClusterCode[]).map((code) => {
    const agents = ALL_BACKEND_AGENTS.filter((a) => a.clusterCode === code);
    const active = agents.filter(
      (a) => a.status === "active" || a.status === "processing",
    ).length;
    const health = Math.round((active / agents.length) * 100);
    return [code, { total: agents.length, active, health }];
  }),
);
