// MSTC GLOBAL — Frontend AI Cluster Definitions (Clusters F1–F10, 235 agents)

export type FrontendClusterCode =
  | "F1"
  | "F2"
  | "F3"
  | "F4"
  | "F5"
  | "F6"
  | "F7"
  | "F8"
  | "F9"
  | "F10";

export type FrontendIntelligenceCategory =
  | "receptive"
  | "conversational"
  | "analytical"
  | "generative"
  | "predictive"
  | "emotional";

export interface FrontendAgent {
  id: string;
  name: string;
  cluster: string;
  clusterCode: FrontendClusterCode;
  type: "frontend";
  specialty: string;
  intelligenceCategory: FrontendIntelligenceCategory;
  status: "active" | "idle" | "processing" | "error";
  tasksToday: number;
  accuracy: number;
  description: string;
}

export interface FrontendClusterConfig {
  code: FrontendClusterCode;
  name: string;
  description: string;
  agentCount: number;
  primaryCategory: FrontendIntelligenceCategory;
  color: string;
}

// Helper to create an agent concisely
const fa = (
  id: string,
  name: string,
  code: FrontendClusterCode,
  cluster: string,
  specialty: string,
  cat: FrontendIntelligenceCategory,
  status: "active" | "idle" | "processing" | "error",
  tasks: number,
  accuracy: number,
  desc: string,
): FrontendAgent => ({
  id,
  name,
  cluster,
  clusterCode: code,
  type: "frontend",
  specialty,
  intelligenceCategory: cat,
  status,
  tasksToday: tasks,
  accuracy,
  description: desc,
});

// ── CLUSTER F1: AI Reception & Welcome Layer (20 agents) ──────────────────────
const F1_CLUSTER = "AI Reception & Welcome Layer";
const F1_AGENTS: FrontendAgent[] = [
  fa(
    "f1-grand-receptionist",
    "Grand Receptionist AI",
    "F1",
    F1_CLUSTER,
    "Visitor greeting & language personalization",
    "receptive",
    "active",
    1847,
    98,
    "Greets every visitor by name (returning) or warm welcome (new), switches to detected language automatically",
  ),
  fa(
    "f1-language-detector",
    "Language Detector AI",
    "F1",
    F1_CLUSTER,
    "Browser/system language detection & site-wide switch",
    "receptive",
    "active",
    1203,
    99,
    "Detects browser/system language, switches entire site to English/Gujarati/Hindi instantly",
  ),
  fa(
    "f1-visitor-profiler",
    "Visitor Profiler AI",
    "F1",
    F1_CLUSTER,
    "Real-time visitor classification within 10 seconds",
    "analytical",
    "active",
    984,
    91,
    "Profiles visitor as investor/family buyer/tenant/NRI/corporate within 10 seconds of arrival",
  ),
  fa(
    "f1-first-impression",
    "First Impression Optimizer AI",
    "F1",
    F1_CLUSTER,
    "Hero section dynamic content based on visitor profile",
    "receptive",
    "active",
    1102,
    93,
    "Adjusts hero section content based on visitor profile before they scroll",
  ),
  fa(
    "f1-return-visitor",
    "Return Visitor Memory AI",
    "F1",
    F1_CLUSTER,
    "Session memory: search history, viewed and shortlisted items",
    "receptive",
    "active",
    674,
    96,
    "Remembers everything from last visit: searches, views, shortlists — resumes seamlessly",
  ),
  fa(
    "f1-onboarding",
    "New Visitor Onboarding AI",
    "F1",
    F1_CLUSTER,
    "First-time visitor guided tour overlay",
    "receptive",
    "idle",
    289,
    94,
    "Subtle guided tour overlay highlighting key platform features for first-time visitors",
  ),
  fa(
    "f1-vip-recognition",
    "VIP Recognition AI",
    "F1",
    F1_CLUSTER,
    "High-value returning client detection and experience upgrade",
    "receptive",
    "active",
    47,
    97,
    "Detects high-value returning clients, upgrades their experience silently and immediately",
  ),
  fa(
    "f1-time-greeter",
    "Time-of-Day Greeter AI",
    "F1",
    F1_CLUSTER,
    "Context-aware time-based greeting messages",
    "receptive",
    "active",
    1560,
    99,
    "Good morning/afternoon/evening greetings — context-aware based on India Standard Time",
  ),
  fa(
    "f1-device-adapter",
    "Device Adapter AI",
    "F1",
    F1_CLUSTER,
    "Mobile/tablet/desktop layout variant optimization",
    "receptive",
    "active",
    1234,
    99,
    "Instantly detects device type, serves optimized layout variant for every visitor",
  ),
  fa(
    "f1-connection-speed",
    "Connection Speed AI",
    "F1",
    F1_CLUSTER,
    "Slow connection detection and lite-mode serving",
    "receptive",
    "active",
    423,
    97,
    "Detects slow connections, serves lite version automatically with no quality loss",
  ),
  fa(
    "f1-accessibility",
    "Accessibility AI",
    "F1",
    F1_CLUSTER,
    "Screen reader, motor impairment & visual preference adaptation",
    "receptive",
    "active",
    312,
    98,
    "Detects accessibility needs, adapts UI for screen readers, motor impairments, visual preferences",
  ),
  fa(
    "f1-geo-location",
    "Geo-Location AI",
    "F1",
    F1_CLUSTER,
    "City/country detection for locally relevant content",
    "analytical",
    "active",
    1103,
    95,
    "Detects visitor city/country, shows locally relevant properties, events, and services first",
  ),
  fa(
    "f1-referral-source",
    "Referral Source AI",
    "F1",
    F1_CLUSTER,
    "Traffic source attribution and experience tailoring",
    "analytical",
    "active",
    834,
    93,
    "Identifies if visitor came via Google/WhatsApp/Instagram, tailors landing experience accordingly",
  ),
  fa(
    "f1-session-continuity",
    "Session Continuity AI",
    "F1",
    F1_CLUSTER,
    "Interrupted session resumption from exact last position",
    "receptive",
    "active",
    201,
    96,
    "Resumes interrupted sessions exactly where the visitor left off — no repeat browsing needed",
  ),
  fa(
    "f1-mood-calibrator",
    "Mood Calibrator AI",
    "F1",
    F1_CLUSTER,
    "Browsing vs serious intent calibration via behavioral signals",
    "analytical",
    "processing",
    892,
    87,
    "Calibrates whether user is casually browsing vs seriously searching based on time and scroll patterns",
  ),
  fa(
    "f1-intent-classifier",
    "Intent Classifier AI",
    "F1",
    F1_CLUSTER,
    "Real-time visitor intent: buy/rent/invest/explore/enquire",
    "analytical",
    "active",
    1067,
    89,
    "Classifies visitor intent in real time: buy / rent / invest / explore / enquire with high accuracy",
  ),
  fa(
    "f1-urgency-detector",
    "Urgency Detector AI",
    "F1",
    F1_CLUSTER,
    "Urgency signal detection from rapid scrolling and multi-searches",
    "analytical",
    "active",
    334,
    88,
    "Detects urgency signals (rapid scroll, multiple searches) and elevates service level immediately",
  ),
  fa(
    "f1-persona-matcher",
    "Persona Matcher AI",
    "F1",
    F1_CLUSTER,
    "Automatic matching of visitor to most relevant AI staff persona",
    "receptive",
    "active",
    712,
    91,
    "Automatically routes visitor to the most relevant AI staff persona based on profiling data",
  ),
  fa(
    "f1-welcome-banner",
    "Welcome Banner AI",
    "F1",
    F1_CLUSTER,
    "Personalized top banner: AI-ready help message with agent name",
    "receptive",
    "active",
    1560,
    97,
    "Generates personalized banner: 'Aryan is ready to help you find a 3BHK in Satellite'",
  ),
  fa(
    "f1-exit-prediction",
    "Exit Prediction AI",
    "F1",
    F1_CLUSTER,
    "30-second pre-exit prediction with retention trigger",
    "predictive",
    "active",
    456,
    84,
    "Predicts 30 seconds before a visitor leaves, triggers a contextually relevant retention action",
  ),
];

// ── CLUSTER F2: AI Chat Universe (30 agents) ──────────────────────────────────
const F2_CLUSTER = "AI Chat Universe";
const F2_AGENTS: FrontendAgent[] = [
  fa(
    "f2-orchestrator",
    "Master Chat Orchestrator AI",
    "F2",
    F2_CLUSTER,
    "Routes every chat message to the right specialist AI",
    "conversational",
    "active",
    2341,
    99,
    "Central router: directs every incoming message to the correct specialist AI persona instantly",
  ),
  fa(
    "f2-property-aryan",
    "Property Concierge AI (Aryan)",
    "F2",
    F2_CLUSTER,
    "Property search, shortlisting, comparison via chat",
    "conversational",
    "active",
    387,
    94,
    "Handles all property search, shortlisting, and comparison queries through natural chat conversation",
  ),
  fa(
    "f2-finance-priya",
    "Finance Advisor AI (Priya)",
    "F2",
    F2_CLUSTER,
    "Home loan, EMI, investment, tax questions via chat",
    "conversational",
    "active",
    241,
    93,
    "Answers all home loan, EMI calculation, investment strategy, and tax questions via chat",
  ),
  fa(
    "f2-legal-vikram",
    "Legal Expert AI (Vikram)",
    "F2",
    F2_CLUSTER,
    "RERA, agreement, title, compliance questions via chat",
    "conversational",
    "active",
    178,
    96,
    "Handles RERA compliance, agreement analysis, title queries, and legal compliance via chat",
  ),
  fa(
    "f2-client-meera",
    "Client Relations AI (Meera)",
    "F2",
    F2_CLUSTER,
    "Follow-ups, complaints, relationship management via chat",
    "conversational",
    "active",
    312,
    92,
    "Manages all client follow-ups, complaint resolution, and relationship nurturing through chat",
  ),
  fa(
    "f2-market-rohan",
    "Market Intelligence AI (Rohan)",
    "F2",
    F2_CLUSTER,
    "Market trends, price forecasts, locality questions via chat",
    "conversational",
    "active",
    156,
    91,
    "Answers market trends, price forecasts, and locality analysis questions via conversational chat",
  ),
  fa(
    "f2-events-kavya",
    "Events Concierge AI (Kavya)",
    "F2",
    F2_CLUSTER,
    "Event planning, hospitality, venue queries via chat",
    "conversational",
    "active",
    89,
    90,
    "Handles event planning, venue selection, hospitality packages, and booking queries via chat",
  ),
  fa(
    "f2-tech-dev",
    "Technology Support AI (Dev)",
    "F2",
    F2_CLUSTER,
    "Platform issues, PWA install, feature help via chat",
    "conversational",
    "active",
    134,
    95,
    "Resolves platform issues, guides PWA installation, and explains all features via chat",
  ),
  fa(
    "f2-ngo-sana",
    "NGO Liaison AI (Sana)",
    "F2",
    F2_CLUSTER,
    "CSR, donations, volunteering, social impact queries via chat",
    "conversational",
    "active",
    67,
    93,
    "Handles CSR initiatives, donation processes, volunteer signup, and social impact queries via chat",
  ),
  fa(
    "f2-nri-aditya",
    "NRI Specialist AI (Aditya)",
    "F2",
    F2_CLUSTER,
    "FEMA, repatriation, NRI buying process via chat",
    "conversational",
    "active",
    112,
    95,
    "Specializes in NRI-specific queries: FEMA compliance, repatriation process, NRI buying guide",
  ),
  fa(
    "f2-tourism-lara",
    "Tourism & Culture AI (Lara)",
    "F2",
    F2_CLUSTER,
    "Gujarat tourism, cultural events, itinerary via chat",
    "conversational",
    "active",
    78,
    91,
    "Handles Gujarat tourism planning, cultural event bookings, and personalized itinerary creation",
  ),
  fa(
    "f2-sports-desk",
    "Sports Desk AI",
    "F2",
    F2_CLUSTER,
    "Athlete profiles, sponsorship, sports events via chat",
    "conversational",
    "idle",
    34,
    89,
    "Handles athlete profile queries, sponsorship matching, and sports event planning through chat",
  ),
  fa(
    "f2-voice-chat",
    "Voice Chat AI",
    "F2",
    F2_CLUSTER,
    "Full voice input/output: speak query, hear answer",
    "conversational",
    "active",
    223,
    92,
    "Provides full voice input and output — users speak queries and hear AI responses naturally",
  ),
  fa(
    "f2-multilingual",
    "Multilingual Switch AI",
    "F2",
    F2_CLUSTER,
    "Mid-conversation language switching to Gujarati/Hindi",
    "conversational",
    "active",
    445,
    98,
    "Enables seamless mid-conversation language switching between English, Gujarati, and Hindi",
  ),
  fa(
    "f2-chat-memory",
    "Chat Memory AI",
    "F2",
    F2_CLUSTER,
    "Cross-session conversation memory — never repeats questions",
    "conversational",
    "active",
    1234,
    97,
    "Retains every conversation across all sessions, never asks the same question twice",
  ),
  fa(
    "f2-proactive",
    "Proactive Outreach AI",
    "F2",
    F2_CLUSTER,
    "3-minute page silence trigger with helpful non-intrusive message",
    "conversational",
    "active",
    567,
    88,
    "After 3 minutes of inactivity on a page, initiates a helpful, perfectly timed outreach message",
  ),
  fa(
    "f2-lead-qualify",
    "Lead Qualification AI",
    "F2",
    F2_CLUSTER,
    "Invisible lead qualification: budget, timeline, location, type",
    "analytical",
    "active",
    891,
    93,
    "Qualifies leads during chat conversation: budget, timeline, location preference, property type — invisibly",
  ),
  fa(
    "f2-chat-to-form",
    "Chat-to-Form AI",
    "F2",
    F2_CLUSTER,
    "Converts chat conversation into a filled form automatically",
    "generative",
    "active",
    234,
    91,
    "Converts any chat conversation into a pre-filled form automatically, saving user time and effort",
  ),
  fa(
    "f2-chat-to-whatsapp",
    "Chat-to-WhatsApp AI",
    "F2",
    F2_CLUSTER,
    "Escalates chat to WhatsApp with full conversation context",
    "conversational",
    "active",
    156,
    96,
    "Escalates any chat to WhatsApp seamlessly with full conversation context pre-loaded",
  ),
  fa(
    "f2-chat-to-call",
    "Chat-to-Call AI",
    "F2",
    F2_CLUSTER,
    "Instant callback request creation with full context",
    "conversational",
    "active",
    89,
    97,
    "When user requests a call, instantly creates a callback request with full conversation context",
  ),
  fa(
    "f2-sentiment",
    "Sentiment Monitor AI",
    "F2",
    F2_CLUSTER,
    "Message-level sentiment: frustration/confusion/satisfaction detection",
    "analytical",
    "active",
    2341,
    94,
    "Reads every message for emotional tone — frustration, confusion, satisfaction — adjusts AI tone",
  ),
  fa(
    "f2-typing-predictor",
    "Typing Predictor AI",
    "F2",
    F2_CLUSTER,
    "Intent prediction while user is typing",
    "predictive",
    "active",
    1678,
    86,
    "Predicts what the user is typing, pre-loads the answer before they finish for instant response",
  ),
  fa(
    "f2-faq-interceptor",
    "FAQ Interceptor AI",
    "F2",
    F2_CLUSTER,
    "Instant FAQ answers without routing delays",
    "conversational",
    "active",
    1023,
    98,
    "Detects frequently asked questions and answers them instantly without routing to specialist AIs",
  ),
  fa(
    "f2-complaint-handler",
    "Complaint Handler AI",
    "F2",
    F2_CLUSTER,
    "Complaint language detection and priority resolution mode",
    "conversational",
    "active",
    67,
    95,
    "Detects complaint language immediately and elevates to priority resolution mode automatically",
  ),
  fa(
    "f2-negotiation-coach",
    "Negotiation Coach AI",
    "F2",
    F2_CLUSTER,
    "Private chat negotiation strategy coaching",
    "conversational",
    "active",
    112,
    90,
    "Coaches buyers in private chat mode on optimal negotiation strategy for any specific property",
  ),
  fa(
    "f2-doc-request",
    "Document Request AI",
    "F2",
    F2_CLUSTER,
    "Chat-based document preparation and delivery",
    "generative",
    "active",
    189,
    94,
    "Prepares and delivers requested documents directly within the chat conversation interface",
  ),
  fa(
    "f2-appointment",
    "Appointment Scheduler AI",
    "F2",
    F2_CLUSTER,
    "Site visits, calls, meetings scheduled directly in chat",
    "conversational",
    "active",
    234,
    96,
    "Schedules site visits, phone calls, and meetings directly within the chat without leaving the page",
  ),
  fa(
    "f2-chat-analytics",
    "Chat Analytics AI",
    "F2",
    F2_CLUSTER,
    "Cross-chat pattern analysis and weekly response improvement",
    "analytical",
    "processing",
    45,
    92,
    "Tracks all chat interactions, identifies patterns, and continuously improves response quality weekly",
  ),
  fa(
    "f2-multi-chat",
    "Multi-Chat AI",
    "F2",
    F2_CLUSTER,
    "Parallel conversations with multiple AI personas simultaneously",
    "conversational",
    "active",
    78,
    93,
    "Enables users to have parallel simultaneous chats with multiple AI personas at once",
  ),
  fa(
    "f2-handoff",
    "Chat Handoff AI",
    "F2",
    F2_CLUSTER,
    "Seamless mid-conversation persona transfer without context loss",
    "conversational",
    "active",
    234,
    97,
    "Transfers conversations between AI personas mid-chat without any loss of context or continuity",
  ),
];

// ── CLUSTER F3: AI Property Experience Layer (40 agents) ──────────────────────
const F3_CLUSTER = "AI Property Experience Layer";
const F3_AGENTS: FrontendAgent[] = [
  fa(
    "f3-live-valuation",
    "Live Valuation AI",
    "F3",
    F3_CLUSTER,
    "Real-time estimated value badge on every listing",
    "analytical",
    "active",
    2341,
    93,
    "Real-time estimated property value badge on every listing, updated daily from market comparables",
  ),
  fa(
    "f3-price-trend",
    "Price Trend AI",
    "F3",
    F3_CLUSTER,
    "6-month price trend sparkline chart on listing cards",
    "analytical",
    "active",
    1456,
    94,
    "Shows 6-month price trend sparkline chart on every listing card with directional color coding",
  ),
  fa(
    "f3-demand-pulse",
    "Demand Pulse AI",
    "F3",
    F3_CLUSTER,
    "High/Moderate/Low demand indicator from enquiry velocity",
    "analytical",
    "active",
    1102,
    91,
    "Calculates demand level (High/Moderate/Low) based on real-time enquiry velocity per listing",
  ),
  fa(
    "f3-days-on-market",
    "Days on Market AI",
    "F3",
    F3_CLUSTER,
    "Color-coded live counter: green → amber → red staleness",
    "analytical",
    "active",
    2100,
    99,
    "Live days-on-market counter, color-coded from green (fresh) to amber to red (stale)",
  ),
  fa(
    "f3-enquiry-counter",
    "Enquiry Counter AI",
    "F3",
    F3_CLUSTER,
    "Live animating weekly enquiry counter per listing",
    "analytical",
    "active",
    1890,
    98,
    "Displays live animating enquiry count: '47 people enquired this week' per listing",
  ),
  fa(
    "f3-view-counter",
    "View Counter AI",
    "F3",
    F3_CLUSTER,
    "Monthly view counter per listing",
    "analytical",
    "active",
    2341,
    99,
    "Tracks and displays monthly view count on every listing as social proof signal",
  ),
  fa(
    "f3-shortlist-counter",
    "Shortlist Counter AI",
    "F3",
    F3_CLUSTER,
    "Social proof shortlist count per listing",
    "analytical",
    "active",
    1234,
    98,
    "Shows live count of users who shortlisted each property as a strong social proof signal",
  ),
  fa(
    "f3-price-drop-alert",
    "Price Drop Alert AI",
    "F3",
    F3_CLUSTER,
    "Flashing badge for price drops with % and amount saved",
    "predictive",
    "active",
    67,
    97,
    "Displays flashing badge when price drops, showing percentage and rupee amount saved instantly",
  ),
  fa(
    "f3-investment-grade",
    "Investment Grade AI",
    "F3",
    F3_CLUSTER,
    "A/B/C/D investment grade badge based on yield/appreciation/risk",
    "analytical",
    "active",
    892,
    89,
    "Assigns A/B/C/D investment grade to every listing based on rental yield, appreciation, and risk profile",
  ),
  fa(
    "f3-locality-score",
    "Locality Score AI",
    "F3",
    F3_CLUSTER,
    "Composite locality score: connectivity, amenities, growth, safety",
    "analytical",
    "active",
    456,
    91,
    "Composite score card for every locality: connectivity, amenities, growth potential, and safety",
  ),
  fa(
    "f3-similar-properties",
    "Similar Properties AI",
    "F3",
    F3_CLUSTER,
    "Always-fresh similar property recommendations",
    "analytical",
    "active",
    1234,
    92,
    "Shows always-fresh similar property suggestions: '4 similar properties available right now'",
  ),
  fa(
    "f3-compare",
    "Compare AI",
    "F3",
    F3_CLUSTER,
    "Side-by-side comparison of up to 3 properties with AI verdict",
    "analytical",
    "active",
    334,
    94,
    "Side-by-side comparison of up to 3 properties with AI-generated investment verdict and recommendation",
  ),
  fa(
    "f3-virtual-staging",
    "Virtual Staging AI",
    "F3",
    F3_CLUSTER,
    "Furnished visualization of empty flat from listing photos",
    "generative",
    "idle",
    23,
    87,
    "Creates furnished room visualizations from empty flat photos using AI generation technology",
  ),
  fa(
    "f3-floor-plan",
    "Floor Plan AI",
    "F3",
    F3_CLUSTER,
    "Floor plan annotation: room sizes, Vastu score, flow rating",
    "analytical",
    "active",
    234,
    88,
    "Reads and annotates floor plans with room dimensions, Vastu compliance score, and flow rating",
  ),
  fa(
    "f3-walk-score",
    "Walk Score AI",
    "F3",
    F3_CLUSTER,
    "Walkability score to market, school, metro, hospital",
    "analytical",
    "active",
    1102,
    93,
    "Calculates walkability score showing proximity to market, school, metro station, and hospitals",
  ),
  fa(
    "f3-possession-risk",
    "Possession Risk AI",
    "F3",
    F3_CLUSTER,
    "Under-construction possession risk meter from builder track record",
    "predictive",
    "active",
    312,
    90,
    "Risk meter for under-construction properties based on builder's track record and RERA history",
  ),
  fa(
    "f3-builder-trust",
    "Builder Trust AI",
    "F3",
    F3_CLUSTER,
    "Builder trust score: delivery, quality, legal, customer service",
    "analytical",
    "active",
    456,
    91,
    "Dynamic trust score for every builder: delivery history, quality, legal record, customer satisfaction",
  ),
  fa(
    "f3-negotiation-range",
    "Negotiation Range AI",
    "F3",
    F3_CLUSTER,
    "Estimated negotiation range displayed on listing",
    "predictive",
    "active",
    789,
    86,
    "Shows estimated negotiation range: 'This property can likely be negotiated ₹2–4L below asking'",
  ),
  fa(
    "f3-roi-calculator",
    "ROI Calculator AI",
    "F3",
    F3_CLUSTER,
    "Quick buy-to-rent ROI visible on every listing",
    "analytical",
    "active",
    1023,
    92,
    "Instant ROI calculation for buy-to-rent scenario, visible directly on every listing card",
  ),
  fa(
    "f3-rental-yield",
    "Rental Yield AI",
    "F3",
    F3_CLUSTER,
    "Estimated monthly rental yield badge on listings",
    "analytical",
    "active",
    1234,
    93,
    "Estimated monthly rental yield badge displayed prominently on every property listing",
  ),
  fa(
    "f3-micro-market",
    "Micro-Market AI",
    "F3",
    F3_CLUSTER,
    "Street-level appreciation vs broad locality comparison",
    "analytical",
    "active",
    678,
    88,
    "Shows micro-market stats: 'This street appreciated 34% vs 22% for the broader locality'",
  ),
  fa(
    "f3-society-health",
    "Society Health AI",
    "F3",
    F3_CLUSTER,
    "Maintenance quality, management, defaulter % per society",
    "analytical",
    "active",
    345,
    87,
    "Displays maintenance quality, management rating, and defaulter percentage for every housing society",
  ),
  fa(
    "f3-vastu",
    "Vastu AI",
    "F3",
    F3_CLUSTER,
    "Full Vastu compliance score with specific issue flags",
    "analytical",
    "active",
    456,
    85,
    "Full Vastu compliance score with specific issue flags for main door, kitchen, and master bedroom",
  ),
  fa(
    "f3-sunlight",
    "Sunlight AI",
    "F3",
    F3_CLUSTER,
    "Flat-specific morning and evening sunlight analysis",
    "analytical",
    "active",
    789,
    90,
    "Analyzes flat orientation: 'Morning sun in bedroom, evening sun in living room' per unit",
  ),
  fa(
    "f3-noise-map",
    "Noise Map AI",
    "F3",
    F3_CLUSTER,
    "Ambient noise overlay: highway, railway, market proximity",
    "analytical",
    "active",
    567,
    88,
    "Ambient noise overlay showing proximity to highway, railway, or market with decibel estimation",
  ),
  fa(
    "f3-aqi",
    "AQI Display AI",
    "F3",
    F3_CLUSTER,
    "Live air quality index per listing locality",
    "analytical",
    "active",
    1102,
    94,
    "Displays live air quality index from real monitoring stations for each listing's locality",
  ),
  fa(
    "f3-flood-risk",
    "Flood Risk AI",
    "F3",
    F3_CLUSTER,
    "NDMA-based flood and waterlogging risk per property",
    "analytical",
    "active",
    234,
    91,
    "NDMA-based flood and waterlogging risk assessment for every property location",
  ),
  fa(
    "f3-school-ranker",
    "School Ranker AI",
    "F3",
    F3_CLUSTER,
    "Top 5 schools within 3km ranked by quality and distance",
    "analytical",
    "active",
    892,
    92,
    "Lists top 5 schools within 3km ranked by academic quality and exact walking/driving distance",
  ),
  fa(
    "f3-hospital-access",
    "Hospital Access AI",
    "F3",
    F3_CLUSTER,
    "Nearest hospitals by type: government, private, specialty",
    "analytical",
    "active",
    678,
    93,
    "Shows nearest hospitals categorized by type: government, private, and specialty medical centers",
  ),
  fa(
    "f3-hidden-cost",
    "Hidden Cost AI",
    "F3",
    F3_CLUSTER,
    "Total cost popup: stamp duty + GST + registration + moving",
    "analytical",
    "active",
    1234,
    96,
    "Complete cost breakdown popup: listing price + stamp duty + registration + GST + deposit + moving",
  ),
  fa(
    "f3-resale-velocity",
    "Resale Velocity AI",
    "F3",
    F3_CLUSTER,
    "Average resale timeline for this society/locality",
    "predictive",
    "active",
    456,
    87,
    "Shows average resale speed: 'Properties in this society typically resell within 45 days'",
  ),
  fa(
    "f3-occupancy",
    "Occupancy AI",
    "F3",
    F3_CLUSTER,
    "% of flats occupied vs vacant in each society",
    "analytical",
    "active",
    567,
    89,
    "Displays percentage of occupied vs vacant flats in every society — key liveability indicator",
  ),
  fa(
    "f3-power-reliability",
    "Power Reliability AI",
    "F3",
    F3_CLUSTER,
    "Average monthly power cut hours per locality",
    "analytical",
    "active",
    345,
    88,
    "Shows average power cut hours per month for each locality from historical records",
  ),
  fa(
    "f3-water-supply",
    "Water Supply AI",
    "F3",
    F3_CLUSTER,
    "Municipal water supply reliability score",
    "analytical",
    "active",
    289,
    87,
    "Municipal water supply reliability score for each locality from AMC data and resident feedback",
  ),
  fa(
    "f3-green-space",
    "Green Space AI",
    "F3",
    F3_CLUSTER,
    "% green cover within 1km radius",
    "analytical",
    "active",
    234,
    90,
    "Calculates percentage of green cover (parks, gardens, trees) within 1km radius of each property",
  ),
  fa(
    "f3-builder-litigation",
    "Builder Litigation AI",
    "F3",
    F3_CLUSTER,
    "Active court cases against builder — visible count",
    "analytical",
    "active",
    178,
    92,
    "Shows count of active court cases against each builder sourced from public RERA and court records",
  ),
  fa(
    "f3-price-negotiation",
    "Price Negotiation AI",
    "F3",
    F3_CLUSTER,
    "Real-time negotiation range from market signals",
    "predictive",
    "active",
    892,
    87,
    "Real-time negotiation range based on days-on-market, demand signals, and comparable transactions",
  ),
  fa(
    "f3-property-report",
    "Property Report AI",
    "F3",
    F3_CLUSTER,
    "One-click full PDF report for any listing",
    "generative",
    "active",
    312,
    95,
    "Generates a comprehensive PDF property report with all intelligence data in one click",
  ),
  fa(
    "f3-ar-view",
    "AR View AI",
    "F3",
    F3_CLUSTER,
    "AR overlay: point phone at location, see MSTC properties",
    "generative",
    "idle",
    34,
    83,
    "Augmented reality overlay: point phone camera at any location to see MSTC properties nearby",
  ),
  fa(
    "f3-3d-tour",
    "3D Tour AI",
    "F3",
    F3_CLUSTER,
    "3D walkthrough assembled from listing photos",
    "generative",
    "active",
    89,
    86,
    "Assembles a 3D virtual walkthrough from available listing photos using AI reconstruction",
  ),
];

// ── CLUSTER F4: AI Market Intelligence Display (20 agents) ────────────────────
const F4_CLUSTER = "AI Market Intelligence Display";
const F4_AGENTS: FrontendAgent[] = [
  fa(
    "f4-market-pulse",
    "Ahmedabad Market Pulse AI",
    "F4",
    F4_CLUSTER,
    "Live overall market health, direction, momentum dashboard",
    "analytical",
    "active",
    1102,
    93,
    "Live dashboard showing overall Ahmedabad market health, price direction, and transaction momentum",
  ),
  fa(
    "f4-price-index",
    "Price Index AI",
    "F4",
    F4_CLUSTER,
    "Ahmedabad residential price index updated weekly",
    "analytical",
    "active",
    678,
    94,
    "Ahmedabad residential property price index updated weekly from real registration data",
  ),
  fa(
    "f4-locality-race",
    "Locality Appreciation Race AI",
    "F4",
    F4_CLUSTER,
    "Fastest appreciating Ahmedabad localities right now",
    "analytical",
    "active",
    456,
    91,
    "Shows which Ahmedabad localities are appreciating fastest in real time with comparative charts",
  ),
  fa(
    "f4-demand-supply",
    "Demand vs Supply AI",
    "F4",
    F4_CLUSTER,
    "Live buyers vs available properties per locality chart",
    "analytical",
    "active",
    789,
    92,
    "Live chart showing buyer count vs property availability across every Ahmedabad locality",
  ),
  fa(
    "f4-transaction-volume",
    "Transaction Volume AI",
    "F4",
    F4_CLUSTER,
    "Monthly Ahmedabad property registration count",
    "analytical",
    "active",
    345,
    96,
    "Tracks and displays monthly registered property transaction count for Ahmedabad",
  ),
  fa(
    "f4-interest-rate",
    "Interest Rate Tracker AI",
    "F4",
    F4_CLUSTER,
    "Live home loan rates from all major banks",
    "analytical",
    "active",
    1234,
    97,
    "Shows current home loan interest rates from SBI, HDFC, ICICI, Axis, Kotak — updated daily",
  ),
  fa(
    "f4-rbi-policy",
    "RBI Policy AI",
    "F4",
    F4_CLUSTER,
    "RBI policy dates, decisions, and home loan impact analysis",
    "analytical",
    "active",
    234,
    95,
    "Tracks RBI policy decisions, upcoming dates, and analyzes direct impact on home loan rates",
  ),
  fa(
    "f4-jantri-rate",
    "Jantri Rate AI",
    "F4",
    F4_CLUSTER,
    "Gujarat jantri rates by locality with last revision date",
    "analytical",
    "active",
    567,
    96,
    "Current Gujarat jantri rates organized by locality, with last revision date and historical changes",
  ),
  fa(
    "f4-project-ticker",
    "New Project Ticker AI",
    "F4",
    F4_CLUSTER,
    "Scrolling ticker of new Ahmedabad project launches",
    "analytical",
    "active",
    89,
    91,
    "Live scrolling ticker showing all new real estate project launches in Ahmedabad",
  ),
  fa(
    "f4-market-prediction",
    "Market Prediction AI",
    "F4",
    F4_CLUSTER,
    "6-month market outlook with direction and confidence score",
    "predictive",
    "active",
    345,
    87,
    "6-month Ahmedabad market outlook with price direction, confidence score, and key driving factors",
  ),
  fa(
    "f4-infra-impact",
    "Infrastructure Impact AI",
    "F4",
    F4_CLUSTER,
    "Infrastructure projects and their price impact per locality",
    "analytical",
    "active",
    234,
    89,
    "Maps which metro, highway, and airport projects are driving property prices in which localities",
  ),
  fa(
    "f4-seasonal",
    "Seasonal Opportunity AI",
    "F4",
    F4_CLUSTER,
    "Festival/budget/monsoon season historical price behavior",
    "predictive",
    "active",
    156,
    88,
    "Shows historical price patterns for festival season, union budget period, and monsoon season",
  ),
  fa(
    "f4-global-impact",
    "Global Impact AI",
    "F4",
    F4_CLUSTER,
    "Global market signals and their Ahmedabad impact",
    "analytical",
    "active",
    178,
    85,
    "Tracks US Fed rates, global recession signals, and analyzes their impact on Ahmedabad property market",
  ),
  fa(
    "f4-best-time",
    "Best Time to Buy AI",
    "F4",
    F4_CLUSTER,
    "Personalized buy timing recommendation per visitor profile",
    "predictive",
    "active",
    567,
    86,
    "Personalized recommendation: 'For your profile, now is a good time to buy in Bopal'",
  ),
  fa(
    "f4-weekly-report",
    "Weekly Market Report AI",
    "F4",
    F4_CLUSTER,
    "Monday morning AI-written fresh market report on homepage",
    "generative",
    "active",
    7,
    92,
    "Every Monday, generates a fresh AI-written market report published prominently on the homepage",
  ),
  fa(
    "f4-correction-risk",
    "Price Correction Risk AI",
    "F4",
    F4_CLUSTER,
    "Overheated localities at correction risk identification",
    "predictive",
    "active",
    234,
    88,
    "Identifies overheated Ahmedabad localities at risk of price correction with risk indicators",
  ),
  fa(
    "f4-rental-market",
    "Rental Market AI",
    "F4",
    F4_CLUSTER,
    "Rental demand, vacancy, yield trends by locality",
    "analytical",
    "active",
    456,
    90,
    "Tracks rental demand, vacancy rates, and yield trends across every Ahmedabad locality",
  ),
  fa(
    "f4-commercial-market",
    "Commercial Market AI",
    "F4",
    F4_CLUSTER,
    "Office, retail, commercial trends in Ahmedabad",
    "analytical",
    "active",
    234,
    89,
    "Comprehensive commercial real estate analysis: office, retail, and warehouse trends in Ahmedabad",
  ),
  fa(
    "f4-nri-market",
    "NRI Market AI",
    "F4",
    F4_CLUSTER,
    "NRI buying trends: localities, property types, price bands",
    "analytical",
    "active",
    312,
    91,
    "Tracks NRI buying trends: most popular localities, property types, and price bands",
  ),
  fa(
    "f4-comparison",
    "Market Comparison AI",
    "F4",
    F4_CLUSTER,
    "Ahmedabad vs Surat vs Mumbai vs Bangalore investment comparison",
    "analytical",
    "active",
    189,
    90,
    "Compares Ahmedabad with Surat, Mumbai, and Bangalore across key investment metrics",
  ),
];

// ── CLUSTER F5: AI Finance & Calculator Tools (25 agents) ─────────────────────
const F5_CLUSTER = "AI Finance & Calculator Tools";
const F5_AGENTS: FrontendAgent[] = [
  fa(
    "f5-emi-calculator",
    "Smart EMI Calculator AI",
    "F5",
    F5_CLUSTER,
    "EMI with amortization table, prepayment impact, tax savings",
    "analytical",
    "active",
    3421,
    99,
    "Full EMI calculator with amortization table, prepayment impact analysis, and Section 24 tax savings",
  ),
  fa(
    "f5-stamp-duty",
    "Stamp Duty Calculator AI",
    "F5",
    F5_CLUSTER,
    "Exact stamp duty + registration for any Gujarat property",
    "analytical",
    "active",
    2341,
    99,
    "Calculates exact stamp duty and registration charges for any property in any Gujarat locality",
  ),
  fa(
    "f5-capital-gains",
    "Capital Gains AI",
    "F5",
    F5_CLUSTER,
    "STCG and LTCG calculation for any property sale scenario",
    "analytical",
    "active",
    1234,
    98,
    "Calculates short-term and long-term capital gains for any property sale scenario with indexation",
  ),
  fa(
    "f5-rental-yield-tool",
    "Rental Yield AI Tool",
    "F5",
    F5_CLUSTER,
    "Gross, net, and after-tax rental yield full calculation",
    "analytical",
    "active",
    1567,
    97,
    "Complete rental yield calculation: gross yield, net yield after expenses, and post-tax return",
  ),
  fa(
    "f5-rent-vs-buy",
    "Rent vs Buy AI",
    "F5",
    F5_CLUSTER,
    "10-year comprehensive financial comparison with NPV analysis",
    "analytical",
    "active",
    892,
    95,
    "Comprehensive 10-year financial comparison of renting vs buying with Net Present Value analysis",
  ),
  fa(
    "f5-loan-comparator",
    "Home Loan Comparator AI",
    "F5",
    F5_CLUSTER,
    "SBI, HDFC, ICICI, Axis, Kotak rate comparison for your profile",
    "analytical",
    "active",
    1102,
    96,
    "Compares SBI, HDFC, ICICI, Axis, Kotak home loans — finds best rate for each visitor's profile",
  ),
  fa(
    "f5-loan-eligibility",
    "Loan Eligibility AI",
    "F5",
    F5_CLUSTER,
    "Instant eligibility from salary + age + existing loans",
    "analytical",
    "active",
    2341,
    97,
    "Instant home loan eligibility: enter salary, age, and existing obligations to get max loan amount",
  ),
  fa(
    "f5-portfolio-stress",
    "Portfolio Stress Test AI",
    "F5",
    F5_CLUSTER,
    "Recession, rate hike, vacancy scenario simulation",
    "predictive",
    "active",
    234,
    89,
    "Simulates recession, rate hike, and high-vacancy scenarios for any property investment portfolio",
  ),
  fa(
    "f5-opportunity-cost",
    "Opportunity Cost AI",
    "F5",
    F5_CLUSTER,
    "Property vs mutual fund vs gold vs FD comparison",
    "analytical",
    "active",
    567,
    91,
    "Compares property investment against mutual funds, gold, and FD at same investment amount and tenure",
  ),
  fa(
    "f5-pmay",
    "PMAY Eligibility AI",
    "F5",
    F5_CLUSTER,
    "Instant PMAY subsidy calculation: EWS/LIG/MIG-I/MIG-II",
    "analytical",
    "active",
    1023,
    98,
    "Instant PMAY eligibility check and subsidy calculation across EWS, LIG, MIG-I, and MIG-II categories",
  ),
  fa(
    "f5-credit-score",
    "Credit Score Impact AI",
    "F5",
    F5_CLUSTER,
    "Home loan impact on CIBIL score over 5 years — timeline",
    "predictive",
    "active",
    456,
    90,
    "Shows how taking a home loan affects CIBIL score over a 5-year timeline with optimization tips",
  ),
  fa(
    "f5-balance-transfer",
    "Balance Transfer AI",
    "F5",
    F5_CLUSTER,
    "Loan switching ROI: savings amount and payback period",
    "analytical",
    "active",
    334,
    93,
    "Calculates if switching lenders is worth it: total savings and months to recover transfer costs",
  ),
  fa(
    "f5-tax-savings",
    "Tax Savings AI",
    "F5",
    F5_CLUSTER,
    "80C, 24(b), 80EEA total annual tax savings from home loan",
    "analytical",
    "active",
    1234,
    97,
    "Calculates total annual tax savings from home loan under Sections 80C, 24(b), and 80EEA",
  ),
  fa(
    "f5-joint-ownership",
    "Joint Ownership AI",
    "F5",
    F5_CLUSTER,
    "Exact tax benefits of adding spouse as co-owner",
    "analytical",
    "active",
    678,
    95,
    "Calculates exact additional tax benefits from adding spouse as co-owner with dual deduction analysis",
  ),
  fa(
    "f5-nri-repatriation",
    "NRI Repatriation AI",
    "F5",
    F5_CLUSTER,
    "NRI property sale repatriation amount step-by-step",
    "analytical",
    "active",
    234,
    96,
    "Step-by-step guide on how much an NRI can repatriate after selling Indian property under FEMA",
  ),
  fa(
    "f5-real-return",
    "Real Return AI",
    "F5",
    F5_CLUSTER,
    "Nominal return minus inflation, tax, maintenance = real return",
    "analytical",
    "active",
    567,
    92,
    "Calculates true real return: nominal return minus inflation, income tax, and maintenance costs",
  ),
  fa(
    "f5-hidden-cost-tool",
    "Hidden Cost AI Tool",
    "F5",
    F5_CLUSTER,
    "Complete cost beyond list price — every rupee accounted",
    "analytical",
    "active",
    1567,
    98,
    "Comprehensive tool accounting for every cost beyond the list price of any property transaction",
  ),
  fa(
    "f5-reinvestment",
    "Reinvestment AI",
    "F5",
    F5_CLUSTER,
    "54/54F/54EC reinvestment options comparison for max tax saving",
    "analytical",
    "active",
    345,
    94,
    "Compares Section 54, 54F, and 54EC reinvestment options to maximize capital gains tax savings",
  ),
  fa(
    "f5-pre-emi",
    "Pre-EMI vs Full EMI AI",
    "F5",
    F5_CLUSTER,
    "Under-construction monthly difference and total interest saved",
    "analytical",
    "active",
    789,
    96,
    "Calculates exact monthly difference and total interest saving between pre-EMI and full EMI options",
  ),
  fa(
    "f5-sip-property",
    "SIP + Property AI",
    "F5",
    F5_CLUSTER,
    "Optimal SIP-to-property split for any wealth target",
    "analytical",
    "active",
    456,
    90,
    "Finds optimal split between SIP and property investment for any wealth target in any timeframe",
  ),
  fa(
    "f5-commercial-yield",
    "Commercial Yield AI",
    "F5",
    F5_CLUSTER,
    "Commercial property yield: office, retail, warehouse analysis",
    "analytical",
    "active",
    234,
    89,
    "Full commercial property yield analysis across office, retail, and warehouse property segments",
  ),
  fa(
    "f5-reits-vs-direct",
    "REITs vs Direct AI",
    "F5",
    F5_CLUSTER,
    "REITs vs direct property ownership comparison per profile",
    "analytical",
    "active",
    312,
    88,
    "Compares REIT investment against direct property ownership for each visitor's specific financial profile",
  ),
  fa(
    "f5-auction",
    "Auction Property AI",
    "F5",
    F5_CLUSTER,
    "Bank auction property process, risks, discount, bidding guide",
    "generative",
    "active",
    178,
    91,
    "Complete guide to bank auction properties: process, typical discounts, risks, and bidding strategy",
  ),
  fa(
    "f5-gst-calculator",
    "GST Calculator AI",
    "F5",
    F5_CLUSTER,
    "Exact GST calculation for any under-construction property",
    "analytical",
    "active",
    1345,
    99,
    "Calculates exact GST applicable on any under-construction property transaction scenario",
  ),
  fa(
    "f5-wealth-planner",
    "Total Wealth Planner AI",
    "F5",
    F5_CLUSTER,
    "Integrated property + SIP + insurance + gold wealth plan",
    "generative",
    "active",
    234,
    88,
    "Integrates property, SIP, insurance, and gold into a comprehensive personalized wealth plan",
  ),
];

// ── CLUSTER F6: AI Content & Discovery Layer (20 agents) ──────────────────────
const F6_CLUSTER = "AI Content & Discovery Layer";
const F6_AGENTS: FrontendAgent[] = [
  fa(
    "f6-news-curator",
    "Live News Curator AI",
    "F6",
    F6_CLUSTER,
    "Real-time real estate news curation and relevance scoring",
    "analytical",
    "active",
    48,
    93,
    "Pulls and curates real estate news from multiple sources, scores for relevance, displays top 10",
  ),
  fa(
    "f6-breaking-alert",
    "Breaking Alert AI",
    "F6",
    F6_CLUSTER,
    "Flashing alerts for major market events and RBI decisions",
    "analytical",
    "active",
    12,
    97,
    "Triggers flashing alerts for major market events: rate cuts, policy changes, jantri revisions",
  ),
  fa(
    "f6-blog-writer",
    "Blog Writer AI",
    "F6",
    F6_CLUSTER,
    "Weekly AI-written blog posts: area guides, market commentary",
    "generative",
    "active",
    7,
    91,
    "Writes weekly blog posts on area guides, market commentary, and first-time buyer tips automatically",
  ),
  fa(
    "f6-area-guide",
    "Area Guide AI",
    "F6",
    F6_CLUSTER,
    "Rich AI-generated area guides for every Ahmedabad locality",
    "generative",
    "active",
    24,
    90,
    "Generates rich area guides for every Ahmedabad locality: lifestyle, connectivity, prices, amenities",
  ),
  fa(
    "f6-faq",
    "FAQ AI",
    "F6",
    F6_CLUSTER,
    "Dynamic FAQs that update based on what users actually ask",
    "conversational",
    "active",
    1234,
    96,
    "Every page has a dynamic FAQ section that updates automatically based on real user query patterns",
  ),
  fa(
    "f6-glossary",
    "Glossary AI",
    "F6",
    F6_CLUSTER,
    "Any technical term on the site: hover for plain-language definition",
    "conversational",
    "active",
    567,
    98,
    "Any technical term on the site: hover to see an instant plain-language definition and context",
  ),
  fa(
    "f6-market-commentary",
    "Market Commentary AI",
    "F6",
    F6_CLUSTER,
    "Daily one-paragraph AI market commentary on homepage",
    "generative",
    "active",
    1,
    92,
    "Generates and publishes a fresh daily one-paragraph market commentary on the homepage",
  ),
  fa(
    "f6-case-study",
    "Case Study AI",
    "F6",
    F6_CLUSTER,
    "Monthly anonymized AI case study: client success stories",
    "generative",
    "active",
    1,
    89,
    "Monthly AI-generated anonymized case study: How a family found their dream home in Ahmedabad",
  ),
  fa(
    "f6-freshness",
    "Content Freshness AI",
    "F6",
    F6_CLUSTER,
    "Stale content detection and auto-refresh across site",
    "analytical",
    "active",
    234,
    95,
    "Continuously detects stale content anywhere on the site, flags for refresh or auto-updates it",
  ),
  fa(
    "f6-trending",
    "Trending Topics AI",
    "F6",
    F6_CLUSTER,
    "What Ahmedabad property buyers are searching most this week",
    "analytical",
    "active",
    168,
    94,
    "Shows what Ahmedabad buyers are searching most this week: areas, property types, price bands",
  ),
  fa(
    "f6-search-intelligence",
    "Search Intelligence AI",
    "F6",
    F6_CLUSTER,
    "Intent-based search query understanding (not just keywords)",
    "analytical",
    "active",
    2341,
    95,
    "Understands every search query by intent, not just keywords — finds what users actually mean",
  ),
  fa(
    "f6-voice-search",
    "Voice Search AI",
    "F6",
    F6_CLUSTER,
    "Natural language voice search for properties and services",
    "conversational",
    "active",
    456,
    91,
    "Full voice search: 'Show me 3BHK flats under 80 lakhs near Bopal with a good school nearby'",
  ),
  fa(
    "f6-multilingual-content",
    "Multilingual Content AI",
    "F6",
    F6_CLUSTER,
    "All content in English/Gujarati/Hindi with live toggle",
    "generative",
    "active",
    5678,
    97,
    "Every piece of content available in English, Gujarati, and Hindi with a live language toggle",
  ),
  fa(
    "f6-social-proof",
    "Social Proof AI",
    "F6",
    F6_CLUSTER,
    "Google reviews, JustDial, WhatsApp testimonials aggregation",
    "analytical",
    "active",
    234,
    88,
    "Aggregates and displays social proof from Google, JustDial, and WhatsApp testimonials",
  ),
  fa(
    "f6-personalized-feed",
    "Personalized Feed AI",
    "F6",
    F6_CLUSTER,
    "Homepage personalizes to each visitor's interests after 2 visits",
    "analytical",
    "active",
    789,
    90,
    "After 2 visits, personalizes the homepage content feed to each visitor's demonstrated interests",
  ),
  fa(
    "f6-related-content",
    "Related Content AI",
    "F6",
    F6_CLUSTER,
    "AI-curated related content at the bottom of every page",
    "analytical",
    "active",
    1234,
    92,
    "At the bottom of every page: AI-curated 'You might also find this useful' content suggestions",
  ),
  fa(
    "f6-search-autocomplete",
    "Search Autocomplete AI",
    "F6",
    F6_CLUSTER,
    "Full search intent prediction from first 3 characters",
    "predictive",
    "active",
    3456,
    93,
    "Predicts full search intent from just 3 characters typed — instant smart suggestions appear",
  ),
  fa(
    "f6-zero-results",
    "Zero Results AI",
    "F6",
    F6_CLUSTER,
    "3 alternative suggestions when search returns nothing",
    "conversational",
    "active",
    234,
    95,
    "When search returns nothing, immediately offers 3 relevant alternative suggestions",
  ),
  fa(
    "f6-translation",
    "Content Translation AI",
    "F6",
    F6_CLUSTER,
    "One-click content block translation to preferred language",
    "generative",
    "active",
    1567,
    98,
    "Any content block can be translated to any supported language with a single click",
  ),
  fa(
    "f6-reading-time",
    "Reading Time AI",
    "F6",
    F6_CLUSTER,
    "Estimated reading time displayed on all articles and guides",
    "analytical",
    "active",
    456,
    99,
    "Shows estimated reading time on all articles, guides, and long-form content pages",
  ),
];

// ── CLUSTER F7: AI Generative Tools (25 agents) ───────────────────────────────
const F7_CLUSTER = "AI Generative Tools";
const F7_AGENTS: FrontendAgent[] = [
  fa(
    "f7-property-desc",
    "Property Description AI",
    "F7",
    F7_CLUSTER,
    "Profile-tailored rich property descriptions on click",
    "generative",
    "active",
    456,
    92,
    "Click any listing: AI writes a rich, personalized description tailored to the visitor's profile",
  ),
  fa(
    "f7-proposal",
    "Personalized Proposal AI",
    "F7",
    F7_CLUSTER,
    "One-click full PDF property proposal with investment case",
    "generative",
    "active",
    234,
    91,
    "One-click generation of a full PDF property proposal with personalized investment case",
  ),
  fa(
    "f7-brochure",
    "Custom Brochure AI",
    "F7",
    F7_CLUSTER,
    "Select 3–5 properties → branded MSTC PDF brochure",
    "generative",
    "active",
    89,
    90,
    "Select 3 to 5 properties and AI instantly builds a branded MSTC PDF brochure ready to share",
  ),
  fa(
    "f7-whatsapp-draft",
    "WhatsApp Draft AI",
    "F7",
    F7_CLUSTER,
    "Perfectly worded WhatsApp property sharing message",
    "generative",
    "active",
    567,
    94,
    "Generates a perfectly worded WhatsApp message to share any property with all key details",
  ),
  fa(
    "f7-email-draft",
    "Email Draft AI",
    "F7",
    F7_CLUSTER,
    "Professional property enquiry email ready to send",
    "generative",
    "active",
    345,
    93,
    "Generates a professional property enquiry email for any listing, ready to send in one click",
  ),
  fa(
    "f7-negotiation-script",
    "Negotiation Script AI",
    "F7",
    F7_CLUSTER,
    "Complete negotiation script: what to say, offer, counter",
    "generative",
    "active",
    178,
    89,
    "Complete step-by-step negotiation script: opening offer, expected counter, final resolution language",
  ),
  fa(
    "f7-offer-letter",
    "Offer Letter AI",
    "F7",
    F7_CLUSTER,
    "Formal property offer letter with all terms ready to submit",
    "generative",
    "active",
    112,
    93,
    "Generates a formal property offer letter with all material terms, ready to submit to seller",
  ),
  fa(
    "f7-complaint-letter",
    "Complaint Letter AI",
    "F7",
    F7_CLUSTER,
    "Legally worded RERA/builder complaint letter in minutes",
    "generative",
    "active",
    67,
    91,
    "Drafts a legally worded RERA or builder complaint letter within minutes from case details",
  ),
  fa(
    "f7-application-form",
    "Application Form AI",
    "F7",
    F7_CLUSTER,
    "Auto-fills home loan/booking/RERA forms from stored data",
    "generative",
    "active",
    345,
    95,
    "Auto-fills home loan, booking, and RERA forms using previously entered personal and property data",
  ),
  fa(
    "f7-visit-checklist",
    "Site Visit Checklist AI",
    "F7",
    F7_CLUSTER,
    "Custom pre-visit checklist based on property type and priorities",
    "generative",
    "active",
    234,
    94,
    "Generates a custom site visit checklist based on specific property type and user's stated priorities",
  ),
  fa(
    "f7-due-diligence",
    "Due Diligence AI",
    "F7",
    F7_CLUSTER,
    "Complete due diligence checklist and partial report per property",
    "generative",
    "active",
    156,
    93,
    "Complete due diligence checklist and preliminary report for any property transaction",
  ),
  fa(
    "f7-investment-memo",
    "Investment Memo AI",
    "F7",
    F7_CLUSTER,
    "Formal 1-page investment memo for investor clients",
    "generative",
    "active",
    89,
    91,
    "Generates a formal 1-page investment memo suitable for investor clients and portfolio reviews",
  ),
  fa(
    "f7-loan-pack",
    "Loan Application Pack AI",
    "F7",
    F7_CLUSTER,
    "Complete home loan document pack assembly with instructions",
    "generative",
    "active",
    234,
    94,
    "Assembles a complete home loan application document pack with step-by-step filing instructions",
  ),
  fa(
    "f7-tax-summary",
    "Tax Summary AI",
    "F7",
    F7_CLUSTER,
    "Plain-language tax implications for any transaction",
    "generative",
    "active",
    456,
    95,
    "All tax implications of any buy, sell, or rent transaction explained in plain, jargon-free language",
  ),
  fa(
    "f7-legal-summary",
    "Legal Summary AI",
    "F7",
    F7_CLUSTER,
    "Plain-language legal summary of any transaction stage",
    "generative",
    "active",
    312,
    94,
    "Plain-language summary of the legal aspects of any property transaction stage",
  ),
  fa(
    "f7-visit-report",
    "Site Visit Report AI",
    "F7",
    F7_CLUSTER,
    "Notes + photos → complete structured site visit report",
    "generative",
    "active",
    156,
    90,
    "Takes site visit notes and photos and generates a complete structured site visit report",
  ),
  fa(
    "f7-counter-offer",
    "Counter-Offer AI",
    "F7",
    F7_CLUSTER,
    "Optimal counter-offer with rationale from seller's offer",
    "generative",
    "active",
    145,
    88,
    "Given a seller's offer, generates the optimal counter-offer with supporting rationale and data",
  ),
  fa(
    "f7-demand-notice",
    "Demand Notice AI",
    "F7",
    F7_CLUSTER,
    "Formal demand notice for delayed possession",
    "generative",
    "active",
    34,
    92,
    "Generates a formal demand notice to builder for delayed possession with all legal references",
  ),
  fa(
    "f7-agreement-checklist",
    "Agreement Checklist AI",
    "F7",
    F7_CLUSTER,
    "Custom pre-signing agreement verification checklist",
    "generative",
    "active",
    189,
    95,
    "Generates a custom verification checklist for any agreement before signing — flags risks",
  ),
  fa(
    "f7-handover-checklist",
    "Handover Checklist AI",
    "F7",
    F7_CLUSTER,
    "Complete flat handover checklist for possession day",
    "generative",
    "active",
    67,
    94,
    "Generates a complete flat handover checklist covering every item to verify on possession day",
  ),
  fa(
    "f7-rental-agreement",
    "Rental Agreement AI",
    "F7",
    F7_CLUSTER,
    "Standard rental agreement draft for any property",
    "generative",
    "active",
    234,
    93,
    "Generates a standard Gujarat-compliant rental agreement draft for any residential property",
  ),
  fa(
    "f7-noc-request",
    "Society NOC Request AI",
    "F7",
    F7_CLUSTER,
    "Formal NOC request letter to housing society",
    "generative",
    "active",
    156,
    95,
    "Generates a formal NOC request letter to housing society for any transaction requiring approval",
  ),
  fa(
    "f7-poa",
    "Power of Attorney AI",
    "F7",
    F7_CLUSTER,
    "PoA necessity guide and template generation with guidance",
    "generative",
    "active",
    89,
    93,
    "Explains when a Power of Attorney is needed and generates a template with detailed guidance",
  ),
  fa(
    "f7-will-guide",
    "Will Draft Guide AI",
    "F7",
    F7_CLUSTER,
    "Basic will drafting guidance for property owners",
    "generative",
    "active",
    45,
    90,
    "Step-by-step guide helping property owners draft a basic will for property succession planning",
  ),
  fa(
    "f7-annual-review",
    "Annual Property Review AI",
    "F7",
    F7_CLUSTER,
    "Yearly review report: value, yield, condition per property",
    "generative",
    "active",
    23,
    91,
    "Generates annual review report for owned properties: current value, rental yield, and condition",
  ),
];

// ── CLUSTER F8: AI Predictive Display Layer (20 agents) ───────────────────────
const F8_CLUSTER = "AI Predictive Display Layer";
const F8_AGENTS: FrontendAgent[] = [
  fa(
    "f8-3yr-forecast",
    "3-Year Price Forecast AI",
    "F8",
    F8_CLUSTER,
    "Confidence band price forecast chart per listing/locality",
    "predictive",
    "active",
    456,
    85,
    "Confidence band chart showing 3-year price forecast for every listing and Ahmedabad locality",
  ),
  fa(
    "f8-rental-demand-forecast",
    "Rental Demand Forecast AI",
    "F8",
    F8_CLUSTER,
    "2-year rental demand change prediction per locality",
    "predictive",
    "active",
    234,
    84,
    "Predicted rental demand change over the next 2 years, visible on every locality and listing page",
  ),
  fa(
    "f8-infra-impact",
    "Infrastructure Impact AI",
    "F8",
    F8_CLUSTER,
    "Metro, highway, airport proximity and projected price impact",
    "predictive",
    "active",
    345,
    88,
    "Shows proximity to upcoming infrastructure and projected price uplift based on historical patterns",
  ),
  fa(
    "f8-rate-forecast",
    "Interest Rate Forecast AI",
    "F8",
    F8_CLUSTER,
    "Expected rate movement and EMI impact — updated monthly",
    "predictive",
    "active",
    30,
    83,
    "Expected interest rate movement and direct impact on EMI amount, updated every month",
  ),
  fa(
    "f8-market-cycle",
    "Market Cycle AI",
    "F8",
    F8_CLUSTER,
    "Ahmedabad market cycle phase identification",
    "predictive",
    "active",
    30,
    87,
    "Identifies current Ahmedabad market cycle phase: early growth / peak / correction / recovery",
  ),
  fa(
    "f8-best-buy-window",
    "Best Buy Window AI",
    "F8",
    F8_CLUSTER,
    "Above-average buying opportunity detection per locality",
    "predictive",
    "active",
    90,
    85,
    "Identifies and announces above-average buying windows: 'Next 90 days: ideal for buying in Satellite'",
  ),
  fa(
    "f8-appreciation-prob",
    "Appreciation Probability AI",
    "F8",
    F8_CLUSTER,
    "% probability of >10% appreciation in 3 years per listing",
    "predictive",
    "active",
    892,
    82,
    "'78% probability this property appreciates more than 10% in 3 years' — per listing",
  ),
  fa(
    "f8-liquidity-forecast",
    "Liquidity Forecast AI",
    "F8",
    F8_CLUSTER,
    "% chance of finding buyer within 60 days if sold in 2 years",
    "predictive",
    "active",
    234,
    83,
    "'91% chance of finding a buyer within 60 days if you sell in 2 years' — per property",
  ),
  fa(
    "f8-tenant-demand",
    "Tenant Demand AI",
    "F8",
    F8_CLUSTER,
    "Rental vacancy forecast per locality",
    "predictive",
    "active",
    345,
    84,
    "Forecasts rental vacancy trends for each Ahmedabad locality for the next 12 months",
  ),
  fa(
    "f8-supply-risk",
    "Supply Risk AI",
    "F8",
    F8_CLUSTER,
    "New project pipeline oversupply risk per locality",
    "predictive",
    "active",
    156,
    85,
    "Analyzes new projects under approval and flags localities at risk of oversupply",
  ),
  fa(
    "f8-builder-delivery",
    "Builder Delivery AI",
    "F8",
    F8_CLUSTER,
    "On-time possession probability for under-construction projects",
    "predictive",
    "active",
    456,
    86,
    "Calculates on-time possession probability for every under-construction project from builder history",
  ),
  fa(
    "f8-policy-impact",
    "Policy Impact AI",
    "F8",
    F8_CLUSTER,
    "Jantri revision, RERA rule change impact predictions",
    "predictive",
    "active",
    24,
    84,
    "Predicts market impact of upcoming policy changes: jantri revisions, RERA amendments, GST changes",
  ),
  fa(
    "f8-demand-surge",
    "Demand Surge AI",
    "F8",
    F8_CLUSTER,
    "Festival season enquiry surge prediction with % estimate",
    "predictive",
    "active",
    30,
    83,
    "'Expect 23% more enquiries next month' — festival season and seasonal demand surge predictions",
  ),
  fa(
    "f8-personal-wealth",
    "Personal Wealth AI",
    "F8",
    F8_CLUSTER,
    "Projected net worth from property asset in 10 years",
    "predictive",
    "active",
    345,
    82,
    "'If you buy this today, projected net worth from this asset in 10 years: ₹X crore'",
  ),
  fa(
    "f8-competitor-watch",
    "Competitor Watch AI",
    "F8",
    F8_CLUSTER,
    "Nearby competing projects and price impact analysis",
    "predictive",
    "active",
    48,
    82,
    "Tracks competing project launches nearby and analyzes potential impact on listing prices",
  ),
  fa(
    "f8-monsoon-risk",
    "Monsoon Risk AI",
    "F8",
    F8_CLUSTER,
    "Predicted waterlogging risk during next monsoon season",
    "predictive",
    "active",
    120,
    87,
    "Predicts waterlogging risk during next monsoon season based on 5-year historical flood data",
  ),
  fa(
    "f8-school-ranking-forecast",
    "School Ranking Forecast AI",
    "F8",
    F8_CLUSTER,
    "Predicted school quality changes in each locality",
    "predictive",
    "idle",
    60,
    80,
    "Predicts school quality and ranking changes in each Ahmedabad locality over the next 2 years",
  ),
  fa(
    "f8-employment-hub",
    "Employment Hub AI",
    "F8",
    F8_CLUSTER,
    "New employment hubs and rental demand impact",
    "predictive",
    "active",
    30,
    84,
    "Identifies upcoming employment hubs nearby and projects their positive impact on rental demand",
  ),
  fa(
    "f8-transit",
    "Transit AI",
    "F8",
    F8_CLUSTER,
    "Metro/BRT/ring road timeline and price impact forecast",
    "predictive",
    "active",
    90,
    86,
    "Upcoming metro, BRT, and ring road projects — distance, timeline, and projected price impact",
  ),
  fa(
    "f8-longterm-appreciation",
    "Long-Term Appreciation AI",
    "F8",
    F8_CLUSTER,
    "10-year locality appreciation model from historical trajectory",
    "predictive",
    "active",
    120,
    83,
    "10-year appreciation model for any Ahmedabad locality based on 15-year historical price trajectory",
  ),
];

// ── CLUSTER F9: AI Legal & Compliance Tools (20 agents) ───────────────────────
const F9_CLUSTER = "AI Legal & Compliance Tools";
const F9_AGENTS: FrontendAgent[] = [
  fa(
    "f9-doc-summarizer",
    "Document Summarizer AI",
    "F9",
    F9_CLUSTER,
    "Paste document → 5-bullet plain-language summary",
    "analytical",
    "active",
    234,
    93,
    "Paste any legal document and get an instant 5-bullet plain-language summary of material terms",
  ),
  fa(
    "f9-agreement-risk",
    "Agreement Risk AI",
    "F9",
    F9_CLUSTER,
    "Paste sale agreement → risky clauses highlighted in red",
    "analytical",
    "active",
    178,
    94,
    "Paste any sale agreement: risky clauses are highlighted in red with plain-language explanations",
  ),
  fa(
    "f9-contract-comparison",
    "Contract Comparison AI",
    "F9",
    F9_CLUSTER,
    "Two agreement versions → every difference highlighted",
    "analytical",
    "active",
    89,
    93,
    "Paste two agreement versions: AI highlights every difference and flags material changes",
  ),
  fa(
    "f9-rera-checker",
    "RERA Project Checker AI",
    "F9",
    F9_CLUSTER,
    "RERA number → full project status, complaints, approvals",
    "analytical",
    "active",
    456,
    96,
    "Enter any RERA number and get full project status, complaint history, and approval details",
  ),
  fa(
    "f9-title-chain",
    "Title Chain AI",
    "F9",
    F9_CLUSTER,
    "Ownership history trace with gap and anomaly flagging",
    "analytical",
    "active",
    156,
    92,
    "Traces complete ownership history, flags any gaps in the title chain or anomalies in transfer records",
  ),
  fa(
    "f9-ec-reader",
    "EC Reader AI",
    "F9",
    F9_CLUSTER,
    "Upload EC → AI extracts and explains all encumbrance entries",
    "analytical",
    "active",
    234,
    93,
    "Upload any encumbrance certificate: AI extracts all entries and explains each one in plain language",
  ),
  fa(
    "f9-sale-deed",
    "Sale Deed Analyzer AI",
    "F9",
    F9_CLUSTER,
    "Upload sale deed → material terms extracted and risk-flagged",
    "analytical",
    "active",
    178,
    94,
    "Upload sale deed: all material terms extracted, risk-flagged, and explained in plain language",
  ),
  fa(
    "f9-court-order",
    "Court Order AI",
    "F9",
    F9_CLUSTER,
    "Checks for court stay or attachment on any property",
    "analytical",
    "active",
    89,
    91,
    "Checks public records for any court-issued stay, attachment, or injunction on any property",
  ),
  fa(
    "f9-mutation-tracker",
    "Mutation Tracker AI",
    "F9",
    F9_CLUSTER,
    "Property mutation status tracker in AMC records",
    "analytical",
    "active",
    345,
    93,
    "Tracks property mutation status in Ahmedabad Municipal Corporation records in real time",
  ),
  fa(
    "f9-property-tax",
    "Property Tax AI",
    "F9",
    F9_CLUSTER,
    "Outstanding property tax dues check for any property",
    "analytical",
    "active",
    456,
    95,
    "Checks and displays outstanding property tax dues for any Ahmedabad property from AMC data",
  ),
  fa(
    "f9-fsi-calculator",
    "FSI Calculator AI",
    "F9",
    F9_CLUSTER,
    "Floor space index and TDR calculation for Ahmedabad plots",
    "analytical",
    "active",
    234,
    94,
    "Calculates applicable FSI and TDR (Transfer of Development Rights) for any Ahmedabad plot",
  ),
  fa(
    "f9-conversion-guide",
    "Conversion Guide AI",
    "F9",
    F9_CLUSTER,
    "Agricultural to non-agricultural conversion: process, cost, timeline",
    "generative",
    "active",
    89,
    91,
    "Complete guide for agricultural to non-agricultural land conversion: process, cost, and timeline",
  ),
  fa(
    "f9-dispute-guide",
    "Dispute Guide AI",
    "F9",
    F9_CLUSTER,
    "Step-by-step guide for any property dispute resolution",
    "generative",
    "active",
    67,
    90,
    "Step-by-step resolution guide for any property dispute: RERA tribunal, civil court, or consumer forum",
  ),
  fa(
    "f9-jargon-explainer",
    "Jargon Explainer AI",
    "F9",
    F9_CLUSTER,
    "Any legal term → plain-language definition with context",
    "conversational",
    "active",
    789,
    98,
    "Hover over any legal term anywhere on the site: instant plain-language definition appears",
  ),
  fa(
    "f9-benami-alert",
    "Benami Alert AI",
    "F9",
    F9_CLUSTER,
    "Potential Benami transaction risk flagging for any property",
    "analytical",
    "active",
    45,
    91,
    "Flags potential Benami transaction risk indicators for any property based on ownership patterns",
  ),
  fa(
    "f9-poa-risk",
    "PoA Risk AI",
    "F9",
    F9_CLUSTER,
    "Risks in any GPA-based transaction detected and explained",
    "analytical",
    "active",
    67,
    92,
    "Detects and clearly explains all risks associated with any General Power of Attorney transaction",
  ),
  fa(
    "f9-signature-checker",
    "Signature Checker AI",
    "F9",
    F9_CLUSTER,
    "Scanned agreement signature verification for all required signers",
    "analytical",
    "active",
    156,
    93,
    "Scans any agreement and verifies that all required signatures and witness signatures are present",
  ),
  fa(
    "f9-stamp-seal",
    "Stamp & Seal AI",
    "F9",
    F9_CLUSTER,
    "Verifies official stamps and seals appear genuine",
    "analytical",
    "active",
    134,
    90,
    "Verifies that official stamps and seals on uploaded documents appear genuine and correctly placed",
  ),
  fa(
    "f9-rera-complaint",
    "RERA Complaint History AI",
    "F9",
    F9_CLUSTER,
    "Full complaint history for any RERA-registered project",
    "analytical",
    "active",
    345,
    94,
    "Retrieves and displays the full RERA complaint history for any registered project in Gujarat",
  ),
  fa(
    "f9-legal-timeline",
    "Legal Timeline AI",
    "F9",
    F9_CLUSTER,
    "Exact legal steps and timeline ahead for any transaction stage",
    "generative",
    "active",
    234,
    95,
    "For any transaction stage, generates exact legal steps ahead with realistic timeline estimates",
  ),
];

// ── CLUSTER F10: Emotional Intelligence AI Layer (15 agents) ──────────────────
const F10_CLUSTER = "Emotional Intelligence AI Layer";
const F10_AGENTS: FrontendAgent[] = [
  fa(
    "f10-empathy-engine",
    "Empathy Engine AI",
    "F10",
    F10_CLUSTER,
    "Frustration/confusion/excitement detection and tone adaptation",
    "emotional",
    "active",
    2341,
    91,
    "Continuously reads visitor behavior for frustration, confusion, or excitement — adapts tone instantly",
  ),
  fa(
    "f10-anxiety-reducer",
    "Anxiety Reducer AI",
    "F10",
    F10_CLUSTER,
    "Property-buying stress detection with calming response",
    "emotional",
    "active",
    567,
    90,
    "Detects property-buying anxiety and responds with calming, reassuring, accurate content",
  ),
  fa(
    "f10-excitement",
    "Excitement Amplifier AI",
    "F10",
    F10_CLUSTER,
    "Genuine excitement detection and detail amplification",
    "emotional",
    "active",
    389,
    89,
    "Detects genuine user excitement and amplifies it with richer details and enthusiastic responses",
  ),
  fa(
    "f10-trust-builder",
    "Trust Builder AI",
    "F10",
    F10_CLUSTER,
    "Skepticism detection → transparency with real data response",
    "emotional",
    "active",
    678,
    92,
    "Detects visitor skepticism, responds with maximum transparency: real data, verified facts, citations",
  ),
  fa(
    "f10-patience",
    "Patience AI",
    "F10",
    F10_CLUSTER,
    "Slow/uncertain user detection with guided paced support",
    "emotional",
    "active",
    456,
    91,
    "Detects slow or uncertain users, slows down the experience and offers more step-by-step guidance",
  ),
  fa(
    "f10-confidence-builder",
    "Confidence Builder AI",
    "F10",
    F10_CLUSTER,
    "First-time buyer question validation without pressure",
    "emotional",
    "active",
    567,
    90,
    "Validates first-time buyer questions, encourages next steps, and builds confidence without pressure",
  ),
  fa(
    "f10-celebration",
    "Celebration AI",
    "F10",
    F10_CLUSTER,
    "Subtle celebration on first shortlist or enquiry submission",
    "emotional",
    "active",
    234,
    93,
    "Triggers a subtle, tasteful celebration when a user shortlists their first property or submits an enquiry",
  ),
  fa(
    "f10-loss-aversion",
    "Loss Aversion AI",
    "F10",
    F10_CLUSTER,
    "Factual urgency signals without manipulation",
    "emotional",
    "active",
    1234,
    88,
    "Displays factual urgency: 'This property had 3 enquiries today' — no artificial scarcity",
  ),
  fa(
    "f10-reassurance",
    "Reassurance AI",
    "F10",
    F10_CLUSTER,
    "Immediate post-action reassurance for high-stakes interactions",
    "emotional",
    "active",
    789,
    92,
    "On any high-stakes action (form submission, booking a visit): immediate and warm reassurance message",
  ),
  fa(
    "f10-tone-mirror",
    "Tone Mirror AI",
    "F10",
    F10_CLUSTER,
    "Communication style matching: formal/casual, brief/detailed",
    "emotional",
    "active",
    2341,
    90,
    "Mirrors the user's communication style: formal or casual, brief or detailed — naturally and invisibly",
  ),
  fa(
    "f10-fatigue",
    "Fatigue Detector AI",
    "F10",
    F10_CLUSTER,
    "Extended browsing fatigue detection and summary offer",
    "emotional",
    "active",
    456,
    87,
    "Detects when a user has been browsing too long and offers a summary or a break suggestion",
  ),
  fa(
    "f10-decision-support",
    "Decision Support AI",
    "F10",
    F10_CLUSTER,
    "Decision framework for users stuck between two properties",
    "emotional",
    "active",
    289,
    89,
    "Helps users stuck between two properties by structuring the decision with clear comparison criteria",
  ),
  fa(
    "f10-regret-reducer",
    "Regret Reducer AI",
    "F10",
    F10_CLUSTER,
    "Post-decision reinforcement: 'You made a great choice'",
    "emotional",
    "active",
    234,
    92,
    "After any major decision is made, AI reinforces it positively: 'You made a great choice'",
  ),
  fa(
    "f10-human-escalation",
    "Human Escalation AI",
    "F10",
    F10_CLUSTER,
    "AI insufficiency detection and seamless human contact transition",
    "emotional",
    "active",
    67,
    96,
    "Detects when AI is insufficient and seamlessly escalates to human contact with full context",
  ),
  fa(
    "f10-empathy-language",
    "Empathy Language AI",
    "F10",
    F10_CLUSTER,
    "Warm, human, culturally appropriate language enforcement",
    "emotional",
    "active",
    5678,
    97,
    "Ensures all AI-generated text uses warm, human, and culturally appropriate Gujarati/Indian language",
  ),
];

// ── Cluster Configuration ──────────────────────────────────────────────────────
export const FRONTEND_CLUSTERS: FrontendClusterConfig[] = [
  {
    code: "F1",
    name: "AI Reception & Welcome Layer",
    description:
      "Greets, profiles, and guides every visitor from the first second",
    agentCount: 20,
    primaryCategory: "receptive",
    color: "#c9a84c",
  },
  {
    code: "F2",
    name: "AI Chat Universe",
    description:
      "30 specialist AI personas handling every type of visitor query",
    agentCount: 30,
    primaryCategory: "conversational",
    color: "#3b82f6",
  },
  {
    code: "F3",
    name: "AI Property Experience Layer",
    description: "Real-time intelligence on every listing — 40 agents",
    agentCount: 40,
    primaryCategory: "analytical",
    color: "#10b981",
  },
  {
    code: "F4",
    name: "AI Market Intelligence Display",
    description: "Live Ahmedabad market data and predictive insights",
    agentCount: 20,
    primaryCategory: "analytical",
    color: "#f97316",
  },
  {
    code: "F5",
    name: "AI Finance & Calculator Tools",
    description:
      "25 fully functional financial calculators powered by real formulas",
    agentCount: 25,
    primaryCategory: "analytical",
    color: "#22c55e",
  },
  {
    code: "F6",
    name: "AI Content & Discovery Layer",
    description: "Fresh, personalized content and intelligent search",
    agentCount: 20,
    primaryCategory: "generative",
    color: "#a855f7",
  },
  {
    code: "F7",
    name: "AI Generative Tools",
    description: "25 AI document and communication generators",
    agentCount: 25,
    primaryCategory: "generative",
    color: "#ec4899",
  },
  {
    code: "F8",
    name: "AI Predictive Display Layer",
    description: "Forward-looking market and property predictions",
    agentCount: 20,
    primaryCategory: "predictive",
    color: "#06b6d4",
  },
  {
    code: "F9",
    name: "AI Legal & Compliance Tools",
    description: "Document analysis and legal intelligence tools",
    agentCount: 20,
    primaryCategory: "analytical",
    color: "#eab308",
  },
  {
    code: "F10",
    name: "Emotional Intelligence AI Layer",
    description: "Human-like emotional intelligence across every interaction",
    agentCount: 15,
    primaryCategory: "emotional",
    color: "#ef4444",
  },
];

export const ALL_FRONTEND_AGENTS: FrontendAgent[] = [
  ...F1_AGENTS,
  ...F2_AGENTS,
  ...F3_AGENTS,
  ...F4_AGENTS,
  ...F5_AGENTS,
  ...F6_AGENTS,
  ...F7_AGENTS,
  ...F8_AGENTS,
  ...F9_AGENTS,
  ...F10_AGENTS,
];

export const FRONTEND_CLUSTER_NAMES: Record<FrontendClusterCode, string> = {
  F1: "AI Reception & Welcome Layer",
  F2: "AI Chat Universe",
  F3: "AI Property Experience Layer",
  F4: "AI Market Intelligence Display",
  F5: "AI Finance & Calculator Tools",
  F6: "AI Content & Discovery Layer",
  F7: "AI Generative Tools",
  F8: "AI Predictive Display Layer",
  F9: "AI Legal & Compliance Tools",
  F10: "Emotional Intelligence AI Layer",
};

export const FRONTEND_CLUSTER_STATS: Record<
  string,
  { total: number; active: number; health: number }
> = Object.fromEntries(
  (Object.keys(FRONTEND_CLUSTER_NAMES) as FrontendClusterCode[]).map((code) => {
    const agents = ALL_FRONTEND_AGENTS.filter((a) => a.clusterCode === code);
    const active = agents.filter(
      (a) => a.status === "active" || a.status === "processing",
    ).length;
    const health = Math.round((active / agents.length) * 100);
    return [code, { total: agents.length, active, health }];
  }),
);
