// AIManagerData_Agents2.ts
// Department Heads (80) + Property Intelligence Specialists (40) + Finance Intelligence Specialists (35) = 155 agents

import type { ExtendedAgentDef } from "./AIManagerData_Extended";

// Compact helper for department head agents
const a = (
  id: string,
  name: string,
  tier: string,
  category: string,
  domain: string,
  description: string,
  caps: string[],
  lastAction: string,
  tasks: number,
  perf: number,
  al: number,
): ExtendedAgentDef => ({
  id,
  name,
  tier,
  category,
  domain,
  description,
  capabilities: caps,
  status: "active",
  autonomyLevel: al,
  selfTaskEnabled: true,
  lastAction,
  tasksCompleted: tasks,
  performanceScore: perf,
});

// ===== DEPARTMENT HEADS (80 agents) =====
const DH_CAPS = [
  "Deep domain expertise in specific vertical",
  "Manages worker agents in area",
  "Produces daily activity report for GM",
  "Executes autonomous tasks within scope",
  "Escalates only critical decisions to GM",
  "Continuous learning from outcomes",
];

const dh: ExtendedAgentDef[] = [
  a(
    "dh-apartment",
    "Apartment Intelligence Head",
    "dept-head",
    "Department Head",
    "Residential",
    "Tracks all apartment inventory, pricing trends, and buyer-seller matching across Ahmedabad residential zones.",
    DH_CAPS,
    "Updated SG Highway 3BHK inventory \u2014 12 new listings added",
    1850,
    94,
    7,
  ),
  a(
    "dh-villa",
    "Villa & Bungalow Intelligence Head",
    "dept-head",
    "Department Head",
    "Residential",
    "Manages villa and bungalow intelligence covering standalone homes and row houses across premium Ahmedabad localities.",
    DH_CAPS,
    "Completed luxury villa pricing review for Bodakdev corridor",
    1230,
    96,
    7,
  ),
  a(
    "dh-plots",
    "Plotted Development Head",
    "dept-head",
    "Department Head",
    "Residential",
    "Tracks plotted development schemes and AUDA-approved plot developments across Ahmedabad outskirts.",
    DH_CAPS,
    "Flagged 3 new AUDA-approved plotted schemes in Sanand-Bavla corridor",
    890,
    91,
    7,
  ),
  a(
    "dh-office",
    "Office Space Intelligence Head",
    "dept-head",
    "Department Head",
    "Commercial",
    "Monitors office space availability, rental rates, and occupancy trends across Ahmedabad commercial zones.",
    DH_CAPS,
    "Updated SG Highway Grade-A office vacancy data \u2014 8.2% vacancy rate",
    2140,
    95,
    7,
  ),
  a(
    "dh-retail",
    "Retail & Showroom Head",
    "dept-head",
    "Department Head",
    "Commercial",
    "Tracks retail and showroom availability across Ahmedabad high streets, malls, and commercial developments.",
    DH_CAPS,
    "Identified 5 high-footfall retail vacancies on CG Road",
    1560,
    93,
    7,
  ),
  a(
    "dh-warehouse",
    "Warehouse & Industrial Head",
    "dept-head",
    "Department Head",
    "Commercial",
    "Monitors warehouse and industrial space in GIDC zones, ring road corridors, and logistics parks.",
    DH_CAPS,
    "Mapped 3 logistics park vacancies near Sanand GIDC",
    780,
    90,
    7,
  ),
  a(
    "dh-luxury-apt",
    "Luxury Apartment Head",
    "dept-head",
    "Department Head",
    "Luxury Real Estate",
    "Curates ultra-premium apartment inventory in Ahmedabad elite residential addresses.",
    DH_CAPS,
    "Profiled 4 new luxury towers in Thaltej-Hebatpur corridor",
    645,
    97,
    7,
  ),
  a(
    "dh-penthouse",
    "Penthouse & Sky Villa Head",
    "dept-head",
    "Department Head",
    "Luxury Real Estate",
    "Specializes in penthouse and sky villa inventory for Ahmedabad highest-net-worth buyers.",
    DH_CAPS,
    "Completed inventory refresh of all Ahmedabad penthouses above \u20b91.5Cr",
    312,
    98,
    7,
  ),
  a(
    "dh-luxury-villa",
    "Luxury Villa Head",
    "dept-head",
    "Department Head",
    "Luxury Real Estate",
    "Manages bespoke luxury villa inventory including gated communities and farmhouse estates.",
    DH_CAPS,
    "Added 2 new off-market luxury villas in Shela to HNI shortlist",
    423,
    97,
    7,
  ),
  a(
    "dh-budget-apt",
    "Budget Apartment Head",
    "dept-head",
    "Department Head",
    "Affordable Housing",
    "Tracks budget apartment availability in PMAY-eligible zones and affordable corridors.",
    DH_CAPS,
    "Updated PMAY eligibility for 8 new projects in New Ranip-Chandkheda",
    1987,
    92,
    7,
  ),
  a(
    "dh-affordable-plot",
    "Affordable Plot Head",
    "dept-head",
    "Department Head",
    "Affordable Housing",
    "Monitors affordable plotted schemes and government land allotments for budget buyers.",
    DH_CAPS,
    "Flagged 2 new government plot schemes in Nikol zone",
    1340,
    89,
    7,
  ),
  a(
    "dh-govt-scheme",
    "Govt Scheme Property Head",
    "dept-head",
    "Department Head",
    "Affordable Housing",
    "Tracks all government housing schemes including PMAY, GIHED, MHADA, and Gujarat state schemes.",
    DH_CAPS,
    "PMAY 2025 allocation update distributed to 34 eligible buyer leads",
    2120,
    91,
    7,
  ),
  a(
    "dh-res-rental",
    "Residential Rental Head",
    "dept-head",
    "Department Head",
    "Rental Market",
    "Manages residential rental inventory and tenant-landlord matching across all Ahmedabad localities.",
    DH_CAPS,
    "Updated rental benchmarks \u2014 Vastrapur 2BHK: \u20b928,000-35,000/month",
    2890,
    94,
    7,
  ),
  a(
    "dh-com-rental",
    "Commercial Rental Head",
    "dept-head",
    "Department Head",
    "Rental Market",
    "Tracks commercial rental rates for offices, retail, and warehouses across Ahmedabad.",
    DH_CAPS,
    "Commercial rental rate guide updated for Q2 2025",
    1670,
    93,
    7,
  ),
  a(
    "dh-coliving",
    "Co-Living & PG Head",
    "dept-head",
    "Department Head",
    "Rental Market",
    "Monitors co-living, PG, and shared accommodation market in Ahmedabad for students and young professionals.",
    DH_CAPS,
    "Mapped 12 new co-living spaces near PDPU and Nirma University",
    920,
    88,
    7,
  ),
  a(
    "dh-rera-proj",
    "RERA Project Intelligence Head",
    "dept-head",
    "Department Head",
    "Under-Construction",
    "Tracks all RERA-registered under-construction projects for compliance status and progress.",
    DH_CAPS,
    "Reviewed 47 RERA projects \u2014 3 flagged for delayed possession risk",
    2340,
    96,
    7,
  ),
  a(
    "dh-construction",
    "Construction Progress Monitor Head",
    "dept-head",
    "Department Head",
    "Under-Construction",
    "Monitors construction progress for all active projects through site reports and regulatory filings.",
    DH_CAPS,
    "Progress reports collected for 23 active projects \u2014 all within tolerance",
    1780,
    94,
    7,
  ),
  a(
    "dh-possession-risk",
    "Possession Risk Assessment Head",
    "dept-head",
    "Department Head",
    "Under-Construction",
    "Assesses possession risk for under-construction properties based on builder history and project status.",
    DH_CAPS,
    "Risk scores updated for 47 projects \u2014 3 elevated to HIGH risk",
    1230,
    95,
    7,
  ),
  a(
    "dh-society-redevelopment",
    "Society Redevelopment Head",
    "dept-head",
    "Department Head",
    "Redevelopment",
    "Evaluates housing society redevelopment potential and coordinates developer-society negotiations.",
    DH_CAPS,
    "Viability assessment completed for 3 Navrangpura societies",
    890,
    93,
    7,
  ),
  a(
    "dh-slum",
    "Slum Redevelopment Head",
    "dept-head",
    "Department Head",
    "Redevelopment",
    "Tracks slum rehabilitation projects and alternative housing schemes under Gujarat government.",
    DH_CAPS,
    "Mapped 4 SRA-approved slum redevelopment projects in East Ahmedabad",
    567,
    91,
    7,
  ),
  a(
    "dh-heritage",
    "Heritage Property Redevelopment Head",
    "dept-head",
    "Department Head",
    "Redevelopment",
    "Identifies heritage properties with redevelopment potential while maintaining cultural preservation.",
    DH_CAPS,
    "Heritage property inventory updated \u2014 8 properties with adaptive reuse potential",
    423,
    92,
    7,
  ),
  a(
    "dh-na-plot",
    "NA Plot Intelligence Head",
    "dept-head",
    "Department Head",
    "Agricultural Land",
    "Tracks non-agricultural plot availability and conversion status across Gujarat districts.",
    DH_CAPS,
    "NA conversion status updated for Sanand and Dholera corridors",
    1120,
    90,
    7,
  ),
  a(
    "dh-farmland",
    "Farm Land Intelligence Head",
    "dept-head",
    "Department Head",
    "Agricultural Land",
    "Monitors agricultural land market for investment potential and township development zones.",
    DH_CAPS,
    "Agricultural land appreciation analysis for Saurashtra corridor completed",
    780,
    88,
    7,
  ),
  a(
    "dh-industrial-land",
    "Industrial Zone Land Head",
    "dept-head",
    "Department Head",
    "Agricultural Land",
    "Tracks GIDC industrial zone land availability for manufacturing and logistics clients.",
    DH_CAPS,
    "GIDC Sanand Phase 3 land availability mapped \u2014 12 plots available",
    890,
    92,
    7,
  ),
  a(
    "dh-bank-rates",
    "Bank Rate Monitor Head",
    "dept-head",
    "Department Head",
    "Home Loans",
    "Monitors home loan interest rates across all major banks within 24 hours of any RBI or bank announcement.",
    DH_CAPS,
    "SBI, HDFC, ICICI, Axis rates updated \u2014 all within 4 hours of RBI announcement",
    2890,
    95,
    7,
  ),
  a(
    "dh-loan-eligibility",
    "Loan Eligibility Assessment Head",
    "dept-head",
    "Department Head",
    "Home Loans",
    "Assesses home loan eligibility for clients based on income, CIBIL, and property value.",
    DH_CAPS,
    "Eligibility assessed for 34 active loan leads \u2014 28 pre-qualified",
    2340,
    94,
    7,
  ),
  a(
    "dh-balance-transfer",
    "Balance Transfer Intelligence Head",
    "dept-head",
    "Department Head",
    "Home Loans",
    "Identifies balance transfer opportunities for existing borrowers to reduce EMI burden.",
    DH_CAPS,
    "Identified 8 clients who can save \u20b9800-2,400/month with balance transfer",
    1560,
    93,
    7,
  ),
  a(
    "dh-re-investment",
    "Real Estate Investment Head",
    "dept-head",
    "Department Head",
    "Investments",
    "Provides real estate investment intelligence including yield analysis and capital appreciation forecasts.",
    DH_CAPS,
    "Top-10 yield investment opportunities briefing issued for this month",
    2120,
    96,
    7,
  ),
  a(
    "dh-sip-vs-property",
    "SIP vs Property Comparison Head",
    "dept-head",
    "Department Head",
    "Investments",
    "Generates detailed SIP vs property comparison analyses for investor decision support.",
    DH_CAPS,
    "SIP vs property comparison updated with latest Nifty 50 and property return data",
    1780,
    95,
    7,
  ),
  a(
    "dh-portfolio",
    "Portfolio Construction Head",
    "dept-head",
    "Department Head",
    "Investments",
    "Constructs diversified real estate portfolios for investor clients across residential, commercial, and alternative assets.",
    DH_CAPS,
    "Portfolio construction completed for 3 HNI clients with mixed asset recommendations",
    1230,
    96,
    7,
  ),
  a(
    "dh-property-tax",
    "Property Tax Optimization Head",
    "dept-head",
    "Department Head",
    "Tax Planning",
    "Provides property tax optimization strategies including AMC tax, capital gains, and deduction maximization.",
    DH_CAPS,
    "Property tax optimization report issued for 12 active transactions",
    1890,
    97,
    7,
  ),
  a(
    "dh-capital-gains",
    "Capital Gains Management Head",
    "dept-head",
    "Department Head",
    "Tax Planning",
    "Calculates and optimizes capital gains tax for property sellers under Indian income tax laws.",
    DH_CAPS,
    "Capital gains optimization analysis completed for 6 sellers \u2014 avg \u20b94.2L saving",
    1567,
    98,
    7,
  ),
  a(
    "dh-gst",
    "GST on Real Estate Head",
    "dept-head",
    "Department Head",
    "Tax Planning",
    "Manages GST calculations and input credit advisory for property transactions.",
    DH_CAPS,
    "GST analysis completed for 4 under-construction property purchases",
    1230,
    97,
    7,
  ),
  a(
    "dh-loan-insurance",
    "Home Loan Insurance Head",
    "dept-head",
    "Department Head",
    "Insurance",
    "Compares home loan insurance products across 8 insurers for all active loan applicants.",
    DH_CAPS,
    "Insurance comparison issued for 8 buyers \u2014 HDFC Life recommended for 5",
    890,
    94,
    7,
  ),
  a(
    "dh-property-insurance",
    "Property Insurance Head",
    "dept-head",
    "Department Head",
    "Insurance",
    "Advises on comprehensive property insurance for all property types and transaction categories.",
    DH_CAPS,
    "Property insurance advisory completed for 12 new property owners",
    678,
    93,
    7,
  ),
  a(
    "dh-hni-wealth",
    "HNI Wealth Strategy Head",
    "dept-head",
    "Department Head",
    "Wealth Management",
    "Develops personalized wealth strategies for HNI clients integrating property with broader financial portfolio.",
    DH_CAPS,
    "Quarterly wealth strategy review completed for 12 HNI clients",
    567,
    97,
    7,
  ),
  a(
    "dh-wealth-projection",
    "Long-Term Wealth Projection Head",
    "dept-head",
    "Department Head",
    "Wealth Management",
    "Creates 5/10/20 year wealth trajectory projections for clients based on property decisions.",
    DH_CAPS,
    "Wealth projections updated for 8 clients post property purchase",
    678,
    96,
    7,
  ),
  a(
    "dh-business-loan",
    "Business Loan Intelligence Head",
    "dept-head",
    "Department Head",
    "Corporate Finance",
    "Tracks business loan availability and provides advisory for commercial property financing.",
    DH_CAPS,
    "Business loan rate comparison issued for 3 corporate clients",
    456,
    94,
    7,
  ),
  a(
    "dh-working-capital",
    "Working Capital Head",
    "dept-head",
    "Department Head",
    "Corporate Finance",
    "Advises businesses on working capital optimization strategies related to property assets.",
    DH_CAPS,
    "Working capital optimization advisory issued for 2 builder clients",
    345,
    93,
    7,
  ),
  a(
    "dh-corporate-events",
    "Corporate Events Head",
    "dept-head",
    "Department Head",
    "Events",
    "Manages corporate event planning including conferences, offsites, team-building, and product launches.",
    DH_CAPS,
    "Corporate offsite proposal submitted for Torrent Group \u2014 200 pax",
    1230,
    95,
    7,
  ),
  a(
    "dh-wedding",
    "Wedding & Social Events Head",
    "dept-head",
    "Department Head",
    "Events",
    "Coordinates wedding and social event planning across Ahmedabad premium venues.",
    DH_CAPS,
    "Venue shortlist finalized for Patel family wedding \u2014 500 pax",
    1890,
    94,
    7,
  ),
  a(
    "dh-festivals",
    "Cultural Festivals Head",
    "dept-head",
    "Department Head",
    "Events",
    "Manages cultural festival events including Navratri, Uttarayan, and corporate cultural programs.",
    DH_CAPS,
    "Navratri event logistics finalized for 3 corporate clients",
    1456,
    93,
    7,
  ),
  a(
    "dh-classical",
    "Classical Music Head",
    "dept-head",
    "Department Head",
    "Music & Culture",
    "Manages classical music artist database and performance bookings for cultural events.",
    DH_CAPS,
    "Classical music artist bookings confirmed for Diwali cultural evening",
    678,
    92,
    7,
  ),
  a(
    "dh-contemporary",
    "Contemporary Music Head",
    "dept-head",
    "Department Head",
    "Music & Culture",
    "Manages contemporary and fusion music performances for corporate and private events.",
    DH_CAPS,
    "Contemporary band shortlisted for corporate party \u2014 4 options presented",
    567,
    91,
    7,
  ),
  a(
    "dh-artist-booking",
    "Artist Booking & Management Head",
    "dept-head",
    "Department Head",
    "Music & Culture",
    "Handles end-to-end artist booking, contract management, and performance logistics.",
    DH_CAPS,
    "Artist contracts signed for 3 upcoming MSTC events this quarter",
    890,
    93,
    7,
  ),
  a(
    "dh-cricket",
    "Cricket Intelligence Head",
    "dept-head",
    "Department Head",
    "Sports",
    "Manages cricket event intelligence including IPL, Ranji, and corporate cricket tournament opportunities.",
    DH_CAPS,
    "Saurashtra T20 sponsorship analysis completed \u2014 \u20b98L investment recommended",
    678,
    93,
    7,
  ),
  a(
    "dh-football",
    "Football & Other Sports Head",
    "dept-head",
    "Department Head",
    "Sports",
    "Tracks football, kabaddi, kho-kho and other sports events and athlete management opportunities.",
    DH_CAPS,
    "Gujarat football league sponsorship brief submitted",
    456,
    91,
    7,
  ),
  a(
    "dh-athlete",
    "Athlete Management Head",
    "dept-head",
    "Department Head",
    "Sports",
    "Manages athlete career advisory including sponsorship, endorsements, and financial planning.",
    DH_CAPS,
    "Endorsement deal negotiated for Gujarat Ranji player \u2014 \u20b912L contract",
    345,
    94,
    7,
  ),
  a(
    "dh-education-csr",
    "Education CSR Head",
    "dept-head",
    "Department Head",
    "NGO & CSR",
    "Manages education-focused CSR initiatives including school infrastructure and scholarship programs.",
    DH_CAPS,
    "Q1 2025 education CSR impact report: 340 students benefited",
    678,
    96,
    7,
  ),
  a(
    "dh-environment",
    "Environment CSR Head",
    "dept-head",
    "Department Head",
    "NGO & CSR",
    "Coordinates environmental CSR programs including tree plantation, waste management, and water conservation.",
    DH_CAPS,
    "Tree plantation drive completed \u2014 2,000 trees planted in Ahmedabad outskirts",
    567,
    95,
    7,
  ),
  a(
    "dh-healthcare-csr",
    "Healthcare CSR Head",
    "dept-head",
    "Department Head",
    "NGO & CSR",
    "Manages healthcare CSR initiatives including medical camps, awareness programs, and hospital support.",
    DH_CAPS,
    "Mobile medical camp organized \u2014 450 beneficiaries in New Ranip",
    456,
    96,
    7,
  ),
  a(
    "dh-women",
    "Women Empowerment Head",
    "dept-head",
    "Department Head",
    "NGO & CSR",
    "Coordinates women empowerment CSR programs including skill development and microfinance support.",
    DH_CAPS,
    "Women skill training program launched \u2014 80 enrolled in Batch 1",
    345,
    97,
    7,
  ),
  a(
    "dh-gujarat-tourism",
    "Gujarat Heritage Tourism Head",
    "dept-head",
    "Department Head",
    "Tourism",
    "Curates Gujarat heritage tourism itineraries including Rann of Kutch, Somnath, and Dwarka circuits.",
    DH_CAPS,
    "2025 Gujarat heritage circuit updated \u2014 Rann Utsav packages ready",
    1230,
    94,
    7,
  ),
  a(
    "dh-adventure",
    "Adventure Tourism Head",
    "dept-head",
    "Department Head",
    "Tourism",
    "Manages adventure tourism including trekking, camping, and wildlife experiences in Gujarat.",
    DH_CAPS,
    "Gir lion safari package updated for 2025 season",
    890,
    92,
    7,
  ),
  a(
    "dh-corporate-travel",
    "Corporate Travel Head",
    "dept-head",
    "Department Head",
    "Tourism",
    "Coordinates corporate travel management for business client meetings and team outings.",
    DH_CAPS,
    "Corporate travel logistics managed for 5 client companies this quarter",
    1456,
    93,
    7,
  ),
  a(
    "dh-digital-media",
    "Digital Media Head",
    "dept-head",
    "Department Head",
    "Media",
    "Manages MSTC digital media presence including website content, social media, and online PR.",
    DH_CAPS,
    "MSTC LinkedIn follower count grew 12% \u2014 3 viral posts this month",
    1678,
    92,
    7,
  ),
  a(
    "dh-print",
    "Print & Broadcast Head",
    "dept-head",
    "Department Head",
    "Media",
    "Manages print and broadcast media relationships for MSTC press coverage in Gujarat.",
    DH_CAPS,
    "Gujarat Samachar and Times of India coverage secured for anniversary",
    567,
    90,
    7,
  ),
  a(
    "dh-ott",
    "OTT & Content Head",
    "dept-head",
    "Department Head",
    "Media",
    "Tracks OTT platform and digital content opportunities for MSTC brand and client investments.",
    DH_CAPS,
    "MSTC brand documentary concept developed for YouTube launch",
    345,
    91,
    7,
  ),
  a(
    "dh-metro",
    "Road & Metro Intelligence Head",
    "dept-head",
    "Department Head",
    "Infrastructure",
    "Monitors Ahmedabad Metro expansion, road widening projects, and BRTS developments and their property impact.",
    DH_CAPS,
    "Metro Line 2 Phase 3 approval confirmed \u2014 Chandkheda price impact +8% projected",
    1890,
    95,
    7,
  ),
  a(
    "dh-smartcity",
    "Smart City Projects Head",
    "dept-head",
    "Department Head",
    "Infrastructure",
    "Tracks Ahmedabad Smart City Mission projects and their impact on property values and development.",
    DH_CAPS,
    "Smart road sensor network Phase 2 approved \u2014 4 corridors covered",
    1234,
    94,
    7,
  ),
  a(
    "dh-nri-investment",
    "NRI Investment Advisory Head",
    "dept-head",
    "Department Head",
    "NRI",
    "Provides specialized NRI investment advisory covering property purchase regulations and FEMA compliance.",
    DH_CAPS,
    "NRI investment advisory updated for FY2024-25 FEMA rules",
    2341,
    97,
    7,
  ),
  a(
    "dh-nri-legal",
    "NRI Legal & FEMA Head",
    "dept-head",
    "Department Head",
    "NRI",
    "Manages FEMA and legal compliance for NRI property transactions including power of attorney and repatriation.",
    DH_CAPS,
    "FEMA compliance checklist updated for 12 active NRI transactions",
    1890,
    98,
    7,
  ),
  a(
    "dh-nri-repatriation",
    "NRI Repatriation Head",
    "dept-head",
    "Department Head",
    "NRI",
    "Guides NRI clients through property sale proceeds repatriation including tax and RBI compliance.",
    DH_CAPS,
    "Repatriation process initiated for 3 NRI clients \u2014 \u20b96.2Cr total",
    1230,
    97,
    7,
  ),
  a(
    "dh-ultra-hni",
    "Ultra-HNI Relationship Head",
    "dept-head",
    "Department Head",
    "HNI",
    "Manages white-glove relationships with MSTC top 20 ultra-HNI clients with bespoke advisory.",
    DH_CAPS,
    "Monthly check-in completed for all 20 ultra-HNI clients",
    234,
    98,
    7,
  ),
  a(
    "dh-hni-portfolio",
    "HNI Portfolio Management Head",
    "dept-head",
    "Department Head",
    "HNI",
    "Manages property portfolio intelligence and rebalancing recommendations for 234 HNI clients.",
    DH_CAPS,
    "Portfolio rebalancing recommendations issued for 12 HNI clients",
    890,
    97,
    7,
  ),
  a(
    "dh-ftb-education",
    "First-Time Buyer Education Head",
    "dept-head",
    "Department Head",
    "First-Time Buyers",
    "Creates and manages educational content and programs for first-time homebuyers.",
    DH_CAPS,
    "Education webinar completed \u2014 280 first-time buyers attended",
    2341,
    95,
    7,
  ),
  a(
    "dh-ftb-loan",
    "First-Time Loan Guidance Head",
    "dept-head",
    "Department Head",
    "First-Time Buyers",
    "Guides first-time buyers through home loan application process and scheme selection.",
    DH_CAPS,
    "Home loan guidance provided to 34 first-time buyers this week",
    1890,
    94,
    7,
  ),
  a(
    "dh-corporate-leasing",
    "Corporate Leasing Head",
    "dept-head",
    "Department Head",
    "Corporate Clients",
    "Manages commercial leasing requirements for corporate clients from requirement to occupation.",
    DH_CAPS,
    "Corporate leasing proposal submitted for 3 active corporate clients",
    567,
    95,
    7,
  ),
  a(
    "dh-corporate-investment",
    "Corporate Investment Head",
    "dept-head",
    "Department Head",
    "Corporate Clients",
    "Advises corporate clients on real estate investment strategy for business expansion and treasury management.",
    DH_CAPS,
    "Commercial investment advisory issued for 2 corporate treasury teams",
    345,
    96,
    7,
  ),
  a(
    "dh-yield",
    "Yield Optimization Head",
    "dept-head",
    "Department Head",
    "Investors",
    "Identifies highest yield properties for investor clients and optimizes rental income strategies.",
    DH_CAPS,
    "Top-5 yield opportunities identified \u2014 Chandkheda and Gota leading at 4.8%",
    2120,
    97,
    7,
  ),
  a(
    "dh-flip",
    "Flip & Short-Term Investment Head",
    "dept-head",
    "Department Head",
    "Investors",
    "Analyzes flip and short-term property investment opportunities with renovation ROI calculations.",
    DH_CAPS,
    "Flip calculator analysis completed for 4 investor leads \u2014 2 recommended",
    1456,
    95,
    7,
  ),
  a(
    "dh-builder-credibility",
    "Builder Credibility Assessment Head",
    "dept-head",
    "Department Head",
    "Builder Relations",
    "Assesses builder credibility using delivery track record, legal status, financial health, and customer satisfaction.",
    DH_CAPS,
    "Builder credibility scores updated for 200 Ahmedabad builders \u2014 3 flagged",
    1890,
    96,
    7,
  ),
  a(
    "dh-builder-partnership",
    "Builder Tie-Up & Partnership Head",
    "dept-head",
    "Department Head",
    "Builder Relations",
    "Develops and manages exclusive partnership agreements with quality Ahmedabad builders.",
    DH_CAPS,
    "2 new exclusive launch partnerships executed this quarter",
    567,
    95,
    7,
  ),
  a(
    "dh-new-launch",
    "New Project Launch Intelligence Head",
    "dept-head",
    "Department Head",
    "Builder Relations",
    "Tracks and evaluates all new project launches across Ahmedabad for exclusive listing opportunities.",
    DH_CAPS,
    "5 new project launches tracked \u2014 2 recommended for MSTC exclusive tie-up",
    1230,
    94,
    7,
  ),
];

// ===== PROPERTY INTELLIGENCE SPECIALISTS (40 agents) =====
const propSpec: ExtendedAgentDef[] = [
  {
    id: "spec-micromarket",
    name: "Micro-Market Predictor AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Micro-Markets",
    description:
      "Predicts price movements at street-level granularity using 50+ micro-market signals per Ahmedabad locality.",
    capabilities: [
      "Predicts price movements at street-level granularity",
      "Analyzes 50+ micro-market signals per locality",
      "Updates predictions every 24 hours",
      "Identifies emerging hotspots before mainstream awareness",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "SG Highway micro-market analysis complete \u2014 2BHK premium zone identified near Judges Bungalow",
    tasksCompleted: 12450,
    performanceScore: 96,
  },
  {
    id: "spec-locality-ranker",
    name: "Locality Appreciation Ranker AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Markets",
    description:
      "Ranks all 11 Ahmedabad localities by 1, 3, and 5 year appreciation potential using 20+ data points.",
    capabilities: [
      "Ranks all Ahmedabad localities by appreciation potential",
      "Updates rankings quarterly using 20+ data signals",
      "Provides 1/3/5 year appreciation forecasts",
      "Identifies best-value localities for specific budgets",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Q2 2025 locality appreciation rankings published \u2014 New Ranip emerges as surprise top performer",
    tasksCompleted: 8920,
    performanceScore: 95,
  },
  {
    id: "spec-jantri",
    name: "Jantri Rate Intelligence AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Valuation",
    description:
      "Tracks Gujarat government jantri rates across all AMC zones and predicts revision timing and impact.",
    capabilities: [
      "Tracks jantri rates across all 15 AMC zones",
      "Predicts jantri revision timing based on election cycles",
      "Calculates stamp duty impact of jantri changes",
      "Updates within 24 hours of any government announcement",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction: "Jantri rates updated for FY2024-25 across all 15 AMC zones",
    tasksCompleted: 5672,
    performanceScore: 94,
  },
  {
    id: "spec-stamp-duty",
    name: "Stamp Duty Optimizer AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Finance",
    description:
      "Calculates and optimizes stamp duty on property transactions using all available legal exemptions.",
    capabilities: [
      "Calculates exact stamp duty for any Gujarat property transaction",
      "Identifies all available legal exemptions and reductions",
      "Compares transaction structures for stamp duty efficiency",
      "Generates stamp duty and registration cost estimates",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Stamp duty optimization analysis for joint purchase \u2014 saved buyer \u20b988,000",
    tasksCompleted: 7834,
    performanceScore: 95,
  },
  {
    id: "spec-property-age",
    name: "Property Age Impact AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Valuation",
    description:
      "Calculates how building age affects property valuation, loan eligibility, and resale prospects.",
    capabilities: [
      "Analyzes building age impact on market value",
      "Calculates loan eligibility reduction for older properties",
      "Projects future valuation based on current age trajectory",
      "Identifies age-based maintenance cost projections",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Property age analysis for 15-year-old SG Highway apartment \u2014 8% discount applied",
    tasksCompleted: 4521,
    performanceScore: 91,
  },
  {
    id: "spec-floor-premium",
    name: "Floor Premium AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Valuation",
    description:
      "Calculates premium or discount for each floor in a building based on Ahmedabad market preferences.",
    capabilities: [
      "Calculates floor premium/discount for every building",
      "Tracks buyer floor preference patterns by locality",
      "Integrates natural light and view value into floor pricing",
      "Updates floor value matrix monthly from transaction data",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Floor premium matrix updated for 2025 \u2014 top floor commands 12% premium in Vastrapur",
    tasksCompleted: 6789,
    performanceScore: 93,
  },
  {
    id: "spec-facing-premium",
    name: "Facing Premium AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Valuation",
    description:
      "Calculates how property direction facing impacts value in Ahmedabad based on cultural, climate, and market factors.",
    capabilities: [
      "Calculates facing premium for all 4 cardinal directions",
      "Integrates Vastu preference patterns into facing pricing",
      "Adjusts for micro-location and surroundings impact",
      "East-facing premium: 4-8% in most Ahmedabad localities",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Facing premium analysis: East-facing 3BHK in Satellite commands 6% premium confirmed",
    tasksCompleted: 5634,
    performanceScore: 92,
  },
  {
    id: "spec-vastu",
    name: "Vastu Compliance AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Culture",
    description:
      "Assesses Vastu Shastra compliance of any property and provides detailed room-by-room analysis.",
    capabilities: [
      "Full Vastu assessment for any floor plan or property",
      "Scores Vastu compliance 1-100 on standardized scale",
      "Identifies specific Vastu defects and remedies",
      "Matches Vastu preferences to buyer requirements",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Vastu assessment completed for 8 properties this week \u2014 3 scored 85+",
    tasksCompleted: 9012,
    performanceScore: 94,
  },
  {
    id: "spec-society-quality",
    name: "Society Quality Ranker AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Housing Societies",
    description:
      "Ranks Ahmedabad housing societies by maintenance quality, management, and resident satisfaction.",
    capabilities: [
      "Ranks 500+ Ahmedabad societies on quality score",
      "Tracks maintenance committee responsiveness",
      "Monitors resident complaint patterns per society",
      "Updates society scores quarterly based on inspection data",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Society quality scores updated for 200 Ahmedabad societies \u2014 12 downgraded",
    tasksCompleted: 7823,
    performanceScore: 93,
  },
  {
    id: "spec-builder-track",
    name: "Builder Track Record AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Builder Intelligence",
    description:
      "Maintains deep profiles of 200+ Ahmedabad builders including delivery history, litigation, and financial health.",
    capabilities: [
      "Maintains detailed profiles on 200+ Ahmedabad builders",
      "Tracks possession delivery track record with precision",
      "Monitors builder financial health indicators",
      "Flags builders with litigation or quality issues",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Builder credibility scores updated \u2014 Safal flagged for 18-month possession delay",
    tasksCompleted: 3456,
    performanceScore: 95,
  },
  {
    id: "spec-inventory-absorption",
    name: "Inventory Absorption AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Markets",
    description:
      "Tracks how quickly properties are selling in each Ahmedabad locality and project to identify demand strength.",
    capabilities: [
      "Tracks absorption rates by locality and segment",
      "Identifies months-of-inventory for all property types",
      "Alerts when absorption accelerates or decelerates significantly",
      "Provides supply-demand balance intelligence to pricing agents",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Absorption rate report: Bopal 2BHK at 2.3 months inventory \u2014 tight market",
    tasksCompleted: 8901,
    performanceScore: 94,
  },
  {
    id: "spec-supply-pipeline",
    name: "Supply Pipeline AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Markets",
    description:
      "Monitors all upcoming new supply approvals and project launches across Ahmedabad for supply-demand intelligence.",
    capabilities: [
      "Monitors all RERA-approved new project pipeline",
      "Tracks planned supply addition by locality and type",
      "Predicts future supply pressure on specific segments",
      "Identifies undersupplied segments with opportunity",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Supply pipeline update: 4,200 new units approved in Chandkheda corridor",
    tasksCompleted: 5678,
    performanceScore: 92,
  },
  {
    id: "spec-demand-signal",
    name: "Demand Signal AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Markets",
    description:
      "Reads all enquiry data to identify emerging demand patterns and hotspots before they appear in prices.",
    capabilities: [
      "Reads 1,200+ monthly enquiries for demand signals",
      "Identifies new hotspot localities 3-6 months early",
      "Tracks demand by buyer type, budget, and configuration",
      "Feeds real-time demand data to all property agents",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Demand signals: NRI enquiries for Vastrapur up 28% this month \u2014 price pressure ahead",
    tasksCompleted: 23451,
    performanceScore: 96,
  },
  {
    id: "spec-price-discovery",
    name: "Price Discovery AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Valuation",
    description:
      "Determines the true market-clearing price for any property type in any Ahmedabad locality using multi-model approach.",
    capabilities: [
      "Determines true market price using 5 valuation models",
      "Integrates registration data, comparable sales, and ask prices",
      "Identifies over-priced and under-priced listings",
      "Provides fair value ranges with confidence intervals",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Fair value determined for 23 properties this week \u2014 avg 4.2% below asking price",
    tasksCompleted: 15670,
    performanceScore: 97,
  },
  {
    id: "spec-negotiation",
    name: "Negotiation Range AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Deal Intelligence",
    description:
      "Provides agents with realistic negotiation ranges for any property deal based on market and seller data.",
    capabilities: [
      "Calculates negotiation headroom based on seller profile",
      "Integrates time-on-market and price-cut history",
      "Provides win-probability for each offer price",
      "Identifies optimal first offer and walkaway price",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Negotiation range brief prepared for 3 active deal negotiations",
    tasksCompleted: 11230,
    performanceScore: 95,
  },
  {
    id: "spec-ready-vs-uc",
    name: "Ready vs Under-Construction AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Analysis",
    description:
      "Provides deep comparative analysis for buyers choosing between ready-possession and under-construction properties.",
    capabilities: [
      "Compares total cost and risk for ready vs under-construction",
      "Calculates time-value of money for each option",
      "Assesses builder credibility for under-construction projects",
      "Integrates rental income opportunity for ready properties",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction: "Ready vs UC analysis completed for 8 buyer leads this week",
    tasksCompleted: 6789,
    performanceScore: 93,
  },
  {
    id: "spec-resale-vs-new",
    name: "Resale vs New AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Analysis",
    description:
      "Helps buyers decide between resale properties and new launches through detailed comparative analysis.",
    capabilities: [
      "Compares actual total cost of ownership for each option",
      "Analyzes resale property condition vs new build quality",
      "Integrates GST, stamp duty, and maintenance cost differences",
      "Provides clear recommendation with supporting data",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction: "Resale vs new comparison completed for 12 buyer enquiries",
    tasksCompleted: 7891,
    performanceScore: 92,
  },
  {
    id: "spec-corner-plot",
    name: "Corner Plot Premium AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Valuation",
    description:
      "Quantifies the value premium of corner plots and properties for residential and commercial buyers.",
    capabilities: [
      "Calculates corner plot premium by locality and plot size",
      "Integrates road-facing advantages into premium calculation",
      "Identifies best-value corner plots across Ahmedabad",
      "Updates corner plot premium data from recent transactions",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Corner plot premium analysis: 8-15% premium confirmed across all surveyed localities",
    tasksCompleted: 2341,
    performanceScore: 90,
  },
  {
    id: "spec-penthouse-ai",
    name: "Penthouse & Top Floor AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Luxury Properties",
    description:
      "Specialized intelligence for penthouse and top-floor properties in Ahmedabad luxury developments.",
    capabilities: [
      "Tracks all penthouse and top-floor inventory in Ahmedabad",
      "Provides specialized pricing for sky villa and penthouse units",
      "Matches ultra-premium buyers with suitable properties",
      "Integrates view, privacy, and exclusivity into valuation",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Penthouse inventory updated \u2014 4 new units in Shilaj and Thaltej corridors",
    tasksCompleted: 1234,
    performanceScore: 97,
  },
  {
    id: "spec-basement",
    name: "Basement & Ground Floor AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Valuation",
    description:
      "Analyzes basement and ground floor property characteristics including waterproofing, accessibility, and pricing.",
    capabilities: [
      "Calculates discount/premium for ground and basement floors",
      "Assesses accessibility benefits for senior buyers",
      "Evaluates waterproofing and flooding risk by locality",
      "Identifies ground floor commercial potential",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Ground floor analysis: accessibility premium for senior buyers in new-age societies",
    tasksCompleted: 1890,
    performanceScore: 90,
  },
  {
    id: "spec-clubhouse",
    name: "Clubhouse & Amenity Valuation AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Amenities",
    description:
      "Quantifies how clubhouse and society amenities impact property values and buyer decisions.",
    capabilities: [
      "Quantifies amenity premium for swimming pool, gym, court",
      "Benchmarks amenity quality across 500+ Ahmedabad societies",
      "Identifies undervalued properties with premium amenities",
      "Tracks amenity maintenance quality over time",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Amenity valuation: swimming pool adds 3-5% premium confirmed in Ahmedabad surveys",
    tasksCompleted: 5678,
    performanceScore: 92,
  },
  {
    id: "spec-parking",
    name: "Parking Valuation AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Features",
    description:
      "Specializes in parking space valuation covering covered vs open, basement vs podium, and car elevator systems.",
    capabilities: [
      "Values covered vs open parking across all localities",
      "Tracks parking space transaction prices in Ahmedabad",
      "Calculates parking value as % of property price by zone",
      "Identifies properties with rare mechanical parking systems",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Parking valuation updated: covered parking \u20b93.5-8L premium in SG Highway zone",
    tasksCompleted: 8902,
    performanceScore: 91,
  },
  {
    id: "spec-society-age",
    name: "Society Age Impact AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Valuation",
    description:
      "Analyzes how housing society age affects resale value, loan availability, and maintenance cost projections.",
    capabilities: [
      "Calculates resale discount for societies older than 15 years",
      "Predicts loan eligibility reduction for aged buildings",
      "Projects maintenance cost escalation for aging societies",
      "Identifies societies approaching major renovation thresholds",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Society age impact analysis: 20+ year societies at 12% resale discount in Naranpura",
    tasksCompleted: 4561,
    performanceScore: 91,
  },
  {
    id: "spec-tenant-matcher",
    name: "Tenant Profile Matcher AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Rental Intelligence",
    description:
      "Matches ideal tenant profiles to properties based on location, building type, and owner preferences.",
    capabilities: [
      "Matches tenant profiles to property suitability",
      "Screens tenant financial and background profiles",
      "Recommends optimal tenant type for yield maximization",
      "Tracks tenant quality by locality and property type",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Tenant matching completed for 8 new rental listings \u2014 3 premium tenants identified",
    tasksCompleted: 7823,
    performanceScore: 93,
  },
  {
    id: "spec-rental-yield",
    name: "Rental Yield Maximizer AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Rental Intelligence",
    description:
      "Recommends optimal rental pricing and strategies to maximize net yield for investment properties.",
    capabilities: [
      "Recommends optimal rent pricing by market analysis",
      "Calculates gross and net yield for every rental property",
      "Identifies yield improvement opportunities in existing portfolio",
      "Tracks rental yield trends by locality and property type",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Rental yield optimization: 2 clients increased yield from 3.1% to 4.3% with pricing adjustment",
    tasksCompleted: 9012,
    performanceScore: 95,
  },
  {
    id: "spec-liquidity",
    name: "Property Liquidity AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Market Intelligence",
    description:
      "Scores how quickly any property can be sold if needed \u2014 critical for investor and emergency sale scenarios.",
    capabilities: [
      "Scores property liquidity 1-10 for any Ahmedabad property",
      "Integrates locality, price, and configuration into liquidity score",
      "Identifies illiquid properties requiring price discount for quick sale",
      "Advises investors on liquidity risk before purchase",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction: "Liquidity scores updated for all 1051+ MSTC-listed properties",
    tasksCompleted: 5670,
    performanceScore: 93,
  },
  {
    id: "spec-coownership",
    name: "Co-Ownership Intelligence AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Property Structures",
    description:
      "Handles joint purchase scenarios covering legal structuring, loan arrangements, and exit strategies for co-buyers.",
    capabilities: [
      "Structures co-ownership agreements between joint buyers",
      "Calculates individual loan eligibility in joint purchase",
      "Identifies ownership ratio strategies for tax optimization",
      "Provides clear exit strategy for each co-owner",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction: "Co-ownership structure advised for 3 buyer pairs this week",
    tasksCompleted: 2341,
    performanceScore: 91,
  },
  {
    id: "spec-gift-inherit",
    name: "Property Gift & Inheritance AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Legal Intelligence",
    description:
      "Provides comprehensive guidance on property gift deeds and inheritance matters under Gujarat law.",
    capabilities: [
      "Guides through gift deed registration in Gujarat",
      "Calculates stamp duty and capital gains on property gifts",
      "Advises on inheritance with and without will in Gujarat",
      "Identifies most tax-efficient property transfer method",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Gift deed advisory: mother-to-daughter property transfer \u2014 stamp duty exemption confirmed",
    tasksCompleted: 1890,
    performanceScore: 92,
  },
  {
    id: "spec-ancestral",
    name: "Ancestral Property AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Legal Intelligence",
    description:
      "Specializes in ancestral property matters including partition, succession, and dispute resolution.",
    capabilities: [
      "Guides through ancestral property rights under Hindu Succession Act",
      "Advises on partition of HUF ancestral property",
      "Identifies co-parcener rights and obligations",
      "Calculates inheritance share for each family member",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Ancestral property partition advisory for joint family \u2014 4 co-parceners",
    tasksCompleted: 1234,
    performanceScore: 91,
  },
  {
    id: "spec-na-plot",
    name: "Conversion & NA Plot AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Land Intelligence",
    description:
      "Guides through agricultural to non-agricultural land conversion process in Gujarat.",
    capabilities: [
      "Tracks NA conversion approval pipeline by district",
      "Provides step-by-step NA conversion process guide",
      "Calculates conversion costs including government fees",
      "Monitors AUDA and district authority NA notifications",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "NA conversion status updated \u2014 Sanand sector approvals expected Q3 2025",
    tasksCompleted: 3456,
    performanceScore: 92,
  },
  {
    id: "spec-industrial-zone",
    name: "Industrial Zone Intelligence AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Industrial Land",
    description:
      "Specializes in GIDC industrial zone land covering all Ahmedabad and Gujarat industrial areas.",
    capabilities: [
      "Maps all GIDC industrial zone availability and pricing",
      "Tracks industrial plot approvals and allocations",
      "Provides industrial land comparative analysis by zone",
      "Monitors DPIIT and Gujarat industrial policy changes",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "GIDC Sanand Phase 3 plot availability mapped \u2014 12 plots at \u20b9450-650/sqft",
    tasksCompleted: 2345,
    performanceScore: 92,
  },
  {
    id: "spec-smartcity-zone",
    name: "Smart City Zone AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Smart City",
    description:
      "Tracks Ahmedabad Smart City Mission zones and their impact on property development opportunities.",
    capabilities: [
      "Identifies properties in Ahmedabad Smart City zones",
      "Tracks smart infrastructure deployment timeline",
      "Calculates property premium from smart zone designation",
      "Monitors central and state smart city budget allocations",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Smart city zone premium analysis: 5-8% value uplift in designated smart zones",
    tasksCompleted: 4567,
    performanceScore: 91,
  },
  {
    id: "spec-metro-corridor",
    name: "Metro Corridor AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Infrastructure Impact",
    description:
      "Tracks Ahmedabad Metro expansion and calculates its price impact on properties along new corridors.",
    capabilities: [
      "Maps all existing and proposed Ahmedabad Metro corridors",
      "Calculates price appreciation by distance from metro stations",
      "Tracks metro construction timeline and impact phasing",
      "Provides station-specific catchment area analysis",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Metro Line 2 corridor analysis: properties within 500m at 12% appreciation over 2 years",
    tasksCompleted: 8901,
    performanceScore: 95,
  },
  {
    id: "spec-airport-impact",
    name: "Airport Impact AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Infrastructure Impact",
    description:
      "Tracks Sardar Vallabhbhai Patel Airport expansion and its impact on surrounding property values.",
    capabilities: [
      "Monitors airport expansion plans and noise zone changes",
      "Calculates appreciation for commercial properties near airport",
      "Tracks cargo hub development and logistics property impact",
      "Assesses residential suitability near airport zones",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Airport cargo hub Phase 2 approved \u2014 Chandkheda logistics park values up 18%",
    tasksCompleted: 5678,
    performanceScore: 92,
  },
  {
    id: "spec-riverfront",
    name: "River Front AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Location Intelligence",
    description:
      "Tracks Sabarmati Riverfront development and its impact on adjacent property values.",
    capabilities: [
      "Monitors Sabarmati Riverfront development phases",
      "Calculates price premium for riverfront-adjacent properties",
      "Tracks new amenity additions along riverfront corridor",
      "Identifies best-value properties near riverfront zone",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Riverfront premium analysis: properties within 200m command 8-12% premium",
    tasksCompleted: 3456,
    performanceScore: 93,
  },
  {
    id: "spec-edu-hub",
    name: "Educational Hub AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Location Intelligence",
    description:
      "Analyzes property demand near Ahmedabad educational institutions including IIM, IIT, PDPU, and Nirma.",
    capabilities: [
      "Maps property demand zones around major institutions",
      "Tracks rental demand from faculty and student populations",
      "Calculates premium for properties in school catchment areas",
      "Identifies best rental investment zones near institutions",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Education hub demand analysis: PDPU corridor top rental yield zone at 4.9% net",
    tasksCompleted: 6789,
    performanceScore: 93,
  },
  {
    id: "spec-hospital-proximity",
    name: "Hospital Proximity AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Location Intelligence",
    description:
      "Analyzes property demand near major Ahmedabad hospitals and AIIMS for medical community buyers.",
    capabilities: [
      "Calculates premium for doctor-preferred residential zones",
      "Tracks medical hub development and new hospital projects",
      "Identifies best-value properties in medical catchment areas",
      "Provides hospital proximity analysis for senior buyer properties",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Hospital proximity premium: CIMS Hospital catchment 5% premium confirmed in Naranpura",
    tasksCompleted: 5678,
    performanceScore: 92,
  },
  {
    id: "spec-it-park",
    name: "IT Park AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Location Intelligence",
    description:
      "Analyzes property demand near Ahmedabad IT parks, GIFT City, and tech corridors for IT professional buyers.",
    capabilities: [
      "Maps property demand zones around IT parks and GIFT City",
      "Tracks IT company expansion for housing demand forecasting",
      "Identifies best rental investment zones for IT professionals",
      "Provides IT corridor analysis for residential investment",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "IT park demand analysis: GIFT City corridor top residential demand zone for 2025",
    tasksCompleted: 7890,
    performanceScore: 94,
  },
  {
    id: "spec-gift-city",
    name: "GIFT City Specialist AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "GIFT City",
    description:
      "Deep intelligence on GIFT City \u2014 India's first International Financial Services Centre with unique regulations.",
    capabilities: [
      "Tracks all GIFT City residential and commercial developments",
      "Monitors IFSCA regulations and foreign investment norms",
      "Analyzes GIFT City commercial office and retail market",
      "Provides NRI-specific GIFT City investment guidance",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "GIFT City commercial absorption up 34% \u2014 3 new BFSI tenants signed this quarter",
    tasksCompleted: 4567,
    performanceScore: 95,
  },
  {
    id: "spec-sir-zone",
    name: "SIR Zone AI",
    tier: "specialist",
    category: "Property Intelligence",
    domain: "Special Investment Regions",
    description:
      "Tracks Special Investment Region developments in Gujarat including Dholera and Mandal-Becharaji.",
    capabilities: [
      "Monitors Dholera SIR infrastructure timeline and approvals",
      "Tracks Mandal-Becharaji SIPZ development progress",
      "Analyzes SIR zone industrial and residential investment potential",
      "Provides SIR-specific investment risk and opportunity analysis",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Dholera SIR Phase 1 plot availability confirmed \u2014 48 plots available",
    tasksCompleted: 2341,
    performanceScore: 93,
  },
];

// ===== FINANCE INTELLIGENCE SPECIALISTS (35 agents) =====
const finSpec: ExtendedAgentDef[] = [
  {
    id: "spec-emi-stress",
    name: "EMI Stress Test AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Loan Analysis",
    description:
      "Tests whether a client can sustain EMI payments if income drops 20-30-40% through scenario modeling.",
    capabilities: [
      "Runs 3 income stress scenarios for every loan applicant",
      "Calculates safe loan amount based on stress test results",
      "Identifies clients at risk of EMI default in adverse scenarios",
      "Recommends loan amount capping for over-stretched buyers",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "EMI stress test completed for 12 loan applicants \u2014 3 recommended lower loan amounts",
    tasksCompleted: 8901,
    performanceScore: 94,
  },
  {
    id: "spec-rate-cycle",
    name: "Rate Cycle Predictor AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Interest Rates",
    description:
      "Predicts RBI repo rate movements and their ripple effect on home loan interest rates across all banks.",
    capabilities: [
      "Predicts RBI rate movement with probability scoring",
      "Calculates home loan rate impact for all 14 partner banks",
      "Advises on fixed vs floating rate choice for buyers",
      "Updates rate cycle model after every RBI MPC meeting",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Rate cycle update: RBI hold confirmed \u2014 next rate cut probability 65% in October",
    tasksCompleted: 7823,
    performanceScore: 93,
  },
  {
    id: "spec-subvention",
    name: "Subvention Scheme Analyzer AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Builder Schemes",
    description:
      "Analyzes builder subvention schemes to determine whether they are genuinely beneficial for buyers.",
    capabilities: [
      "Analyzes total cost of subvention vs standard purchase",
      "Calculates effective interest rate in subvention schemes",
      "Identifies hidden costs and clauses in subvention offers",
      "Recommends whether to opt for subvention or standard scheme",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Subvention scheme analysis: Builder X scheme \u2014 pre-EMI waiver has 1.8% hidden premium",
    tasksCompleted: 4512,
    performanceScore: 91,
  },
  {
    id: "spec-clp",
    name: "Construction-Linked Plan AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Under-Construction Finance",
    description:
      "Analyzes construction-linked payment plans vs other payment structures for under-construction purchases.",
    capabilities: [
      "Compares CLP vs Down Payment vs Possession-Linked Plans",
      "Calculates cash flow requirements for each payment structure",
      "Identifies risk and benefit of each plan type",
      "Recommends optimal payment structure per buyer profile",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "CLP analysis: 10:80:10 plan recommended for 3 buyers purchasing under-construction properties",
    tasksCompleted: 5678,
    performanceScore: 92,
  },
  {
    id: "spec-pre-emi",
    name: "Pre-EMI vs Full EMI AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Loan Analysis",
    description:
      "Advises when pre-EMI is beneficial vs when to start full EMI for under-construction property loans.",
    capabilities: [
      "Calculates total interest outgo under pre-EMI vs full EMI",
      "Identifies break-even point between both options",
      "Advises based on buyer's rental vs EMI outgo situation",
      "Updates calculation for current Ahmedabad rental market data",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Pre-EMI vs Full EMI analysis: 8 buyers advised to convert to full EMI immediately",
    tasksCompleted: 6789,
    performanceScore: 93,
  },
  {
    id: "spec-lap",
    name: "Loan Against Property AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Loan Products",
    description:
      "Provides LAP intelligence covering eligibility, best lenders, and risk assessment for property-backed borrowing.",
    capabilities: [
      "Calculates LAP eligibility based on property value and income",
      "Compares LAP rates across 10 major lenders",
      "Assesses LTV ratio and borrowing headroom for each property",
      "Advises on LAP vs personal loan vs gold loan trade-offs",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "LAP analysis: 3 business clients advised on LAP vs business loan comparison",
    tasksCompleted: 3456,
    performanceScore: 92,
  },
  {
    id: "spec-reverse-mortgage",
    name: "Reverse Mortgage AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Senior Finance",
    description:
      "Provides reverse mortgage guidance for senior citizen homeowners seeking income from property assets.",
    capabilities: [
      "Explains reverse mortgage mechanics clearly for seniors",
      "Calculates monthly income under reverse mortgage scheme",
      "Compares NHB scheme with private reverse mortgage products",
      "Advises on estate planning implications of reverse mortgage",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Reverse mortgage advisory: senior couple guided through NHB scheme \u2014 \u20b924,000/month income",
    tasksCompleted: 1234,
    performanceScore: 91,
  },
  {
    id: "spec-nri-loan",
    name: "NRI Home Loan AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "NRI Finance",
    description:
      "Specialized home loan guidance for NRI clients covering FEMA compliance, eligible lenders, and repatriation.",
    capabilities: [
      "Identifies FEMA-compliant lenders for NRI home loans",
      "Calculates NRI loan eligibility based on foreign income",
      "Guides through NRO/NRE account requirements for EMI",
      "Advises on repatriation of sale proceeds after loan closure",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "NRI home loan guidance: USA-based client pre-qualified for \u20b91.8Cr loan at HDFC",
    tasksCompleted: 5670,
    performanceScore: 95,
  },
  {
    id: "spec-corporate-mortgage",
    name: "Corporate Mortgage AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Corporate Finance",
    description:
      "Provides corporate mortgage intelligence for commercial property financing for business clients.",
    capabilities: [
      "Structures corporate mortgage for commercial properties",
      "Compares corporate loan rates from business banking divisions",
      "Calculates debt service coverage ratios for commercial deals",
      "Advises on LAP vs construction finance for builder clients",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Corporate mortgage analysis completed for Patel Group \u2014 \u20b98.4Cr commercial loan structured",
    tasksCompleted: 2341,
    performanceScore: 94,
  },
  {
    id: "spec-construction-finance",
    name: "Construction Finance AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Construction Finance",
    description:
      "Specialized in construction finance for under-construction property purchases and builder project funding.",
    capabilities: [
      "Tracks construction finance disbursement schedules",
      "Coordinates EMI and OD limit management for construction loans",
      "Advises on progressive disbursement linked to construction stages",
      "Identifies best-rate construction finance lenders",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Construction finance structure optimized for 3 under-construction buyers",
    tasksCompleted: 1890,
    performanceScore: 93,
  },
  {
    id: "spec-project-finance",
    name: "Project Finance AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Project Finance",
    description:
      "Provides project finance intelligence for builders and developers funding new real estate projects.",
    capabilities: [
      "Structures project finance for residential and commercial developments",
      "Compares project loan rates from institutional lenders",
      "Calculates DSCR and interest coverage for project viability",
      "Identifies funding gaps and alternative finance sources",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Project finance advisory: \u20b948Cr commercial development funding structure completed",
    tasksCompleted: 1234,
    performanceScore: 94,
  },
  {
    id: "spec-gold-lap",
    name: "Gold Loan vs LAP AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Loan Comparison",
    description:
      "Compares gold loan versus loan against property for clients with both assets available.",
    capabilities: [
      "Compares gold loan vs LAP on rate, tenure, and convenience",
      "Calculates break-even for each option at different holding periods",
      "Advises on partial gold loan with LAP for optimal structuring",
      "Identifies when gold loan is better than LAP for short needs",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Gold loan vs LAP comparison: client advised LAP at 9.5% over gold loan at 11.2%",
    tasksCompleted: 1890,
    performanceScore: 91,
  },
  {
    id: "spec-personal-bridge",
    name: "Personal Loan Bridge AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Bridge Finance",
    description:
      "Advises on personal loan strategies to bridge short-term property transaction gaps.",
    capabilities: [
      "Advises on personal loan bridge for down payment gaps",
      "Calculates maximum safe personal loan for property bridge",
      "Identifies lowest-cost personal loan options for each buyer",
      "Times loan application for minimum impact on CIBIL score",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Personal loan bridge: 2 buyers advised on \u20b915-25L bridge loan for down payment gap",
    tasksCompleted: 1230,
    performanceScore: 90,
  },
  {
    id: "spec-credit-score",
    name: "Credit Score Builder AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Credit Management",
    description:
      "Helps clients improve CIBIL score to qualify for better home loan rates and higher eligibility.",
    capabilities: [
      "Analyzes CIBIL report for all 12 improvement opportunities",
      "Creates 6/12-month credit improvement action plan",
      "Tracks CIBIL score progress monthly for active clients",
      "Advises on dispute resolution for incorrect entries",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "CIBIL improvement plan created for 5 clients \u2014 avg projected improvement: 68 points",
    tasksCompleted: 4512,
    performanceScore: 94,
  },
  {
    id: "spec-itr-intel",
    name: "Income Tax Return Intelligence AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Tax & Loans",
    description:
      "Analyzes ITR patterns to maximize home loan eligibility for self-employed and business owner buyers.",
    capabilities: [
      "Analyzes 3-year ITR for optimal loan eligibility structuring",
      "Identifies income declaration opportunities for better eligibility",
      "Advises on business expenses vs income balance for ITR",
      "Coordinates with chartered accountants for ITR preparation",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "ITR analysis: self-employed buyer's eligibility increased by \u20b924L with proper ITR structuring",
    tasksCompleted: 3456,
    performanceScore: 95,
  },
  {
    id: "spec-form16",
    name: "Form 16 Analyzer AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Loan Documentation",
    description:
      "Reads salary slips and Form 16 to instantly extract home loan eligibility for salaried buyers.",
    capabilities: [
      "Extracts gross income and deductions from Form 16 automatically",
      "Calculates eligible loan amount within 2 minutes of Form 16 upload",
      "Identifies income optimization opportunities in Form 16",
      "Compares eligibility across all 14 partner lender products",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Form 16 analysis: 8 salaried buyers pre-qualified \u2014 avg eligibility \u20b982L",
    tasksCompleted: 5678,
    performanceScore: 94,
  },
  {
    id: "spec-rental-income",
    name: "Rental Income Declaration AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Tax Planning",
    description:
      "Optimizes rental income declaration structure for tax efficiency and loan eligibility.",
    capabilities: [
      "Advises on 30% standard deduction optimization for rental income",
      "Structures rental income for maximum loan eligibility benefit",
      "Calculates rental income tax at optimal rate",
      "Advises on HRA and rental income combination strategies",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Rental income declaration optimized for 3 landlord clients \u2014 avg \u20b932,000 tax saving",
    tasksCompleted: 2341,
    performanceScore: 93,
  },
  {
    id: "spec-huf",
    name: "HUF Intelligence AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Tax Planning",
    description:
      "Provides comprehensive guidance on Hindu Undivided Family property ownership and tax optimization.",
    capabilities: [
      "Advises on HUF property ownership for tax optimization",
      "Calculates stamp duty and tax benefits of HUF structure",
      "Guides through HUF deed creation and property transfer",
      "Advises on HUF loan eligibility and partition planning",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "HUF structure advisory: family saves \u20b91.8L annually through HUF property ownership",
    tasksCompleted: 1230,
    performanceScore: 94,
  },
  {
    id: "spec-sec54",
    name: "Section 54 Optimizer AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Capital Gains",
    description:
      "Maximizes Section 54 capital gains exemption for property sellers reinvesting in residential property.",
    capabilities: [
      "Calculates maximum Section 54 exemption for property sellers",
      "Identifies qualifying reinvestment properties for maximum benefit",
      "Times sale and purchase for compliance with 2-year window",
      "Integrates Section 54F for commercial property sellers",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Section 54 planning: seller saved \u20b98.4L in LTCG through compliant reinvestment structuring",
    tasksCompleted: 3456,
    performanceScore: 97,
  },
  {
    id: "spec-sec80eea",
    name: "Section 80EEA Optimizer AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Tax Deductions",
    description:
      "Maximizes Section 80EEA affordable housing loan deduction for first-time buyers.",
    capabilities: [
      "Identifies buyers eligible for Section 80EEA \u20b91.5L deduction",
      "Ensures property meets stamp value criteria for eligibility",
      "Combines 80EEA with 80C and 24(b) for maximum tax saving",
      "Projects total tax saving over full loan tenure",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Section 80EEA eligibility confirmed for 12 first-time buyers \u2014 avg \u20b946,800/year saving",
    tasksCompleted: 4512,
    performanceScore: 95,
  },
  {
    id: "spec-indexation",
    name: "Indexation Calculator AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Capital Gains",
    description:
      "Calculates indexed cost of acquisition for long-term capital gains tax on property sales.",
    capabilities: [
      "Calculates indexed cost using Cost Inflation Index for any year",
      "Determines exact LTCG tax liability after indexation",
      "Compares indexation benefit vs new 12.5% flat rate",
      "Advises on optimal LTCG calculation method post-Budget 2024",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Indexation calculation: seller saved \u20b94.8L with old regime vs new flat rate",
    tasksCompleted: 3456,
    performanceScore: 96,
  },
  {
    id: "spec-stcg",
    name: "Short-Term Capital Gains AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Capital Gains",
    description:
      "Calculates and plans short-term capital gains tax strategy for property held less than 24 months.",
    capabilities: [
      "Calculates STCG at marginal income tax rate for property",
      "Advises on holding period strategy to avoid STCG",
      "Identifies reinvestment options that minimize STCG impact",
      "Integrates STCG with overall income tax planning",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "STCG planning: 2 sellers advised to hold 3 more months to qualify for LTCG",
    tasksCompleted: 2341,
    performanceScore: 94,
  },
  {
    id: "spec-ltcg",
    name: "LTCG Reinvestment Planner AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Capital Gains",
    description:
      "Plans long-term capital gains reinvestment to minimize tax through Section 54, 54EC, and 54F.",
    capabilities: [
      "Creates comprehensive LTCG reinvestment plan for property sellers",
      "Coordinates 54EC bond investment for remaining LTCG",
      "Times reinvestment within statutory windows",
      "Integrates multiple exemption sections for zero-tax outcome",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "LTCG reinvestment plan: seller achieved zero LTCG through 54EC + 54 combination",
    tasksCompleted: 1890,
    performanceScore: 97,
  },
  {
    id: "spec-tds-compliance",
    name: "Property TDS Compliance AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Tax Compliance",
    description:
      "Ensures TDS compliance on property purchases above \u20b950L under Section 194IA.",
    capabilities: [
      "Calculates exact TDS amount for property transactions above \u20b950L",
      "Guides through Form 26QB filing within 30 days",
      "Ensures Form 16B is obtained from IT portal",
      "Advises on TDS on NRI property purchases under Section 195",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "TDS compliance: 8 property purchases handled \u2014 26QB filed within 15 days for all",
    tasksCompleted: 5678,
    performanceScore: 95,
  },
  {
    id: "spec-gst-input",
    name: "GST Input Credit AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Tax Planning",
    description:
      "Manages GST input tax credit advisory for commercial property purchases.",
    capabilities: [
      "Calculates GST ITC availability for commercial property purchase",
      "Advises on ITC eligibility under different GST rate structures",
      "Ensures correct GST registration for commercial property buyers",
      "Identifies GST optimization for builder-buyer arrangements",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "GST ITC advisory: 2 commercial buyers qualify for full GST input credit recovery",
    tasksCompleted: 1234,
    performanceScore: 94,
  },
  {
    id: "spec-lease-buy",
    name: "Lease vs Buy AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Corporate Strategy",
    description:
      "Provides lease versus buy analysis for corporate clients evaluating commercial property decisions.",
    capabilities: [
      "Calculates NPV for lease vs buy over 10-year horizon",
      "Integrates tax benefits, opportunity cost, and flexibility",
      "Provides break-even analysis for the lease-to-buy decision",
      "Recommends optimal structure based on company balance sheet",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Lease vs buy analysis: Infosys expansion \u2014 buy recommended at current Ahmedabad prices",
    tasksCompleted: 2341,
    performanceScore: 95,
  },
  {
    id: "spec-sale-leaseback",
    name: "Sale & Leaseback AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Corporate Finance",
    description:
      "Analyzes sale and leaseback structures for corporate clients wanting capital release from property assets.",
    capabilities: [
      "Designs sale-leaseback structure for commercial property owners",
      "Calculates post-tax sale proceeds vs ongoing lease commitment",
      "Identifies best buyers for sale-leaseback arrangements",
      "Negotiates lease terms that preserve operational continuity",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Sale-leaseback analysis: corporate client can release \u20b918Cr from office property",
    tasksCompleted: 1230,
    performanceScore: 94,
  },
  {
    id: "spec-re-aif",
    name: "Real Estate AIF AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Alternative Investments",
    description:
      "Provides intelligence on real estate alternative investment funds for HNI clients.",
    capabilities: [
      "Tracks SEBI-registered real estate AIFs and their performance",
      "Compares AIF returns vs direct property investment",
      "Identifies minimum investment thresholds and lock-in periods",
      "Advises on AIF as portfolio diversification for HNIs",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Real estate AIF advisory: 2 HNI clients allocated \u20b92Cr to top-performing AIF",
    tasksCompleted: 890,
    performanceScore: 94,
  },
  {
    id: "spec-reit",
    name: "REIT Intelligence AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "REITs",
    description:
      "Tracks India REIT market and provides comparative intelligence for property investors.",
    capabilities: [
      "Monitors Embassy, Mindspace, Brookfield, and Nexus REITs",
      "Compares REIT yield vs direct property investment",
      "Calculates dividend distribution and capital appreciation",
      "Advises on REIT allocation within property portfolio",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "REIT intelligence: Embassy REIT yield at 7.2% \u2014 recommended for 3 investor clients",
    tasksCompleted: 3456,
    performanceScore: 93,
  },
  {
    id: "spec-fractional",
    name: "Fractional Ownership AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Alternative Investments",
    description:
      "Provides intelligence on fractional real estate investment platforms for smaller investors.",
    capabilities: [
      "Tracks hBits, Strata, Property Share platforms and performance",
      "Compares fractional vs direct investment returns",
      "Advises on minimum investment and exit liquidity",
      "Identifies best fractional opportunities for each investor profile",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Fractional investment advisory: 5 investor clients introduced to commercial fractional platform",
    tasksCompleted: 2341,
    performanceScore: 92,
  },
  {
    id: "spec-crypto-property",
    name: "Cryptocurrency & Property AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Crypto Finance",
    description:
      "Provides guidance on legally using cryptocurrency proceeds for property investment in India.",
    capabilities: [
      "Tracks legal framework for crypto-to-property investment",
      "Calculates tax implications of crypto sale for property purchase",
      "Advises on P2P vs exchange sale for optimal tax efficiency",
      "Identifies FEMA compliance for NRI crypto-to-India property",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Crypto-to-property advisory: NRI client guided through legal crypto sale and India investment",
    tasksCompleted: 890,
    performanceScore: 91,
  },
  {
    id: "spec-foreign-currency",
    name: "Foreign Currency Property AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "NRI Finance",
    description:
      "Provides USD and other foreign currency valuation of Indian properties for NRI investment decisions.",
    capabilities: [
      "Converts property values to USD, GBP, AED, and CAD in real time",
      "Calculates NRI affordability in home currency terms",
      "Tracks exchange rate trends for optimal investment timing",
      "Advises on hedging strategies for large property transactions",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Foreign currency analysis: USD-based NRI client optimal timing window identified",
    tasksCompleted: 1234,
    performanceScore: 93,
  },
  {
    id: "spec-dtaa",
    name: "Double Tax Avoidance AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "NRI Taxation",
    description:
      "Provides DTAA guidance for NRI clients to avoid double taxation on Indian property income.",
    capabilities: [
      "Identifies applicable DTAA treaty for each NRI country of residence",
      "Calculates rental income tax under DTAA vs domestic rate",
      "Guides through DTAA certificate filing process",
      "Advises on DTAA for property sale gains and repatriation",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "DTAA advisory: UAE-based NRI client qualified for zero tax on Indian rental income",
    tasksCompleted: 1890,
    performanceScore: 95,
  },
  {
    id: "spec-estate-plan",
    name: "Estate Planning AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Wealth Management",
    description:
      "Provides comprehensive estate planning integrating all property assets for succession clarity.",
    capabilities: [
      "Creates complete property estate plan for all asset types",
      "Advises on will vs gift deed vs HUF for succession",
      "Calculates inheritance tax implications under current Indian law",
      "Integrates life insurance with property estate planning",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Estate planning completed for HNI family \u2014 4 properties succession plan structured",
    tasksCompleted: 1234,
    performanceScore: 94,
  },
  {
    id: "spec-family-trust",
    name: "Family Trust AI",
    tier: "specialist",
    category: "Finance Intelligence",
    domain: "Wealth Management",
    description:
      "Guides through family trust creation for holding property assets for tax and succession planning.",
    capabilities: [
      "Advises on irrevocable vs revocable trust for property holding",
      "Calculates stamp duty and registration for trust creation",
      "Identifies tax benefits of holding property through trust",
      "Structures trust deed for multi-generational property transfer",
    ],
    status: "active",
    autonomyLevel: 7,
    selfTaskEnabled: true,
    lastAction:
      "Family trust advisory: ultra-HNI family created private trust for 7 property assets",
    tasksCompleted: 567,
    performanceScore: 95,
  },
];

export const EXTENDED_AGENTS_2: ExtendedAgentDef[] = [
  ...dh,
  ...propSpec,
  ...finSpec,
];
