// All 369+ AI agent definitions for MSTC GLOBAL AI Universe
export type AgentTier =
  | "command"
  | "ultra"
  | "gm"
  | "department"
  | "neural"
  | "specialist"
  | "worker"
  | "fallback";
export type AgentStatus = "active" | "resting" | "offline";
export type AIProvider = "OpenAI" | "Claude" | "Gemini" | "Multi" | "Platform";

export interface AIAgentDef {
  id: string;
  name: string;
  tier: AgentTier;
  category: string;
  description: string;
  parentId?: string;
  provider: AIProvider;
  lastAction: string;
}

export const TIER_META: Record<
  AgentTier,
  { label: string; color: string; bgColor: string; borderColor: string }
> = {
  command: {
    label: "Command Tier",
    color: "text-yellow-300",
    bgColor: "bg-yellow-900/20",
    borderColor: "border-yellow-500/40",
  },
  ultra: {
    label: "Ultra Tier",
    color: "text-orange-300",
    bgColor: "bg-orange-900/20",
    borderColor: "border-orange-500/40",
  },
  gm: {
    label: "GM Tier (General Managers)",
    color: "text-amber-300",
    bgColor: "bg-amber-900/15",
    borderColor: "border-amber-600/40",
  },
  department: {
    label: "Department Head Tier",
    color: "text-blue-300",
    bgColor: "bg-blue-900/15",
    borderColor: "border-blue-600/40",
  },
  neural: {
    label: "Neural Intelligence Tier",
    color: "text-purple-300",
    bgColor: "bg-purple-900/15",
    borderColor: "border-purple-600/40",
  },
  specialist: {
    label: "Specialist Agents",
    color: "text-teal-300",
    bgColor: "bg-teal-900/15",
    borderColor: "border-teal-600/40",
  },
  worker: {
    label: "Worker Agents (24/7)",
    color: "text-green-300",
    bgColor: "bg-green-900/15",
    borderColor: "border-green-600/40",
  },
  fallback: {
    label: "Fallback & Redundancy Layer",
    color: "text-gray-300",
    bgColor: "bg-gray-900/20",
    borderColor: "border-gray-600/40",
  },
};

export const TIER_ORDER: AgentTier[] = [
  "command",
  "ultra",
  "gm",
  "department",
  "neural",
  "specialist",
  "worker",
  "fallback",
];

export const AI_AGENTS: AIAgentDef[] = [
  // COMMAND TIER
  {
    id: "master-intel",
    name: "MSTC Master Intelligence",
    tier: "command",
    category: "Command",
    description:
      "Overarching brain coordinating every AI, maintains global business awareness, produces daily executive brief for MD.",
    provider: "Multi",
    lastAction: "Generated morning brief at 07:00 IST",
  },
  {
    id: "caffeine-chief",
    name: "Caffeine AI Chief Officer",
    tier: "command",
    category: "Command",
    description:
      "Direct MD interface embedded in dashboard, coordinates all AI tiers, morning brief compiler.",
    parentId: "master-intel",
    provider: "Multi",
    lastAction: "Compiled overnight coordination summary",
  },
  {
    id: "mstc-knowledge-brain",
    name: "MSTC Knowledge Brain",
    tier: "command",
    category: "Knowledge",
    description:
      "Stores all MSTC institutional knowledge: past deals, client history, market data, legal precedents.",
    parentId: "caffeine-chief",
    provider: "Platform",
    lastAction: "Retrieved property precedent for Bopal sector",
  },
  // ULTRA TIER
  {
    id: "strategic-biz",
    name: "Strategic Business AI",
    tier: "ultra",
    category: "Strategy",
    description:
      "Thinks 6-12 months ahead, monitors market threats and recommends major business moves.",
    parentId: "caffeine-chief",
    provider: "Claude",
    lastAction: "Updated Q3 market strategy brief",
  },
  {
    id: "revenue-intel",
    name: "Revenue Intelligence AI",
    tier: "ultra",
    category: "Finance",
    description:
      "Tracks every rupee in the pipeline, forecasts revenue, identifies leakage, recommends focus areas.",
    parentId: "caffeine-chief",
    provider: "OpenAI",
    lastAction: "Flagged 3 stalled deals in pipeline",
  },
  {
    id: "client-intel",
    name: "Client Intelligence AI",
    tier: "ultra",
    category: "CRM",
    description:
      "Maintains real-time deep profiles of every client: behavior, preferences, buy probability, lifetime value.",
    parentId: "caffeine-chief",
    provider: "Multi",
    lastAction: "Updated 12 client profiles",
  },
  {
    id: "platform-architect",
    name: "Platform Architect AI",
    tier: "ultra",
    category: "Technology",
    description:
      "Designs platform evolution, decides what gets built next and in what order.",
    parentId: "caffeine-chief",
    provider: "OpenAI",
    lastAction: "Queued 5 micro-feature builds for this week",
  },
  {
    id: "risk-crisis",
    name: "Risk & Crisis AI",
    tier: "ultra",
    category: "Risk",
    description:
      "Monitors legal, financial, reputational, operational risk - alerts before crisis hits.",
    parentId: "caffeine-chief",
    provider: "Claude",
    lastAction: "Cleared daily risk scan - no critical alerts",
  },
  {
    id: "growth-engine",
    name: "Growth Engine AI",
    tier: "ultra",
    category: "Growth",
    description:
      "Dedicated to growing MSTC: more clients, more deals, more services, more reach.",
    parentId: "caffeine-chief",
    provider: "Gemini",
    lastAction: "Identified 2 new locality expansion opportunities",
  },
  {
    id: "ops-command",
    name: "Operations Command AI",
    tier: "ultra",
    category: "Operations",
    description:
      "Runs day-to-day operations: task assignment, deadline tracking, team coordination, workflow management.",
    parentId: "caffeine-chief",
    provider: "Multi",
    lastAction: "Assigned 8 follow-up tasks to worker agents",
  },
  {
    id: "knowledge-vault",
    name: "Knowledge Vault AI",
    tier: "ultra",
    category: "Knowledge",
    description:
      "Manages all institutional knowledge: past deals, client history, market data, legal precedents.",
    parentId: "caffeine-chief",
    provider: "Platform",
    lastAction: "Indexed 15 new property records",
  },
  // GM TIER
  {
    id: "gm-property",
    name: "GM of Property & Real Estate",
    tier: "gm",
    category: "Property",
    description:
      "Oversees all property intelligence, listings, valuations, deals, and market research.",
    parentId: "caffeine-chief",
    provider: "Multi",
    lastAction: "Reviewed weekly property market summary",
  },
  {
    id: "gm-bizdev",
    name: "GM of Business Development",
    tier: "gm",
    category: "Business",
    description:
      "Drives lead management, deal velocity, partnerships, and revenue forecasting.",
    parentId: "caffeine-chief",
    provider: "OpenAI",
    lastAction: "Approved 3 new partnership inquiries",
  },
  {
    id: "gm-tech",
    name: "GM of Technology & Platform",
    tier: "gm",
    category: "Technology",
    description:
      "Leads all platform development, continuous building, QA, and infrastructure.",
    parentId: "caffeine-chief",
    provider: "Multi",
    lastAction: "Deployed 2 micro-features overnight",
  },
  {
    id: "gm-finance",
    name: "GM of Finance & Compliance",
    tier: "gm",
    category: "Finance",
    description:
      "Manages financial intelligence, RERA compliance, legal AI, and tax optimization.",
    parentId: "caffeine-chief",
    provider: "Claude",
    lastAction: "Compiled monthly RERA compliance report",
  },
  {
    id: "gm-content",
    name: "GM of Content & Intelligence",
    tier: "gm",
    category: "Content",
    description:
      "Oversees all content strategy, SEO, social, campaigns, and market intelligence.",
    parentId: "caffeine-chief",
    provider: "OpenAI",
    lastAction: "Published 4 area guide updates",
  },
  {
    id: "gm-client",
    name: "GM of Client Relations",
    tier: "gm",
    category: "CRM",
    description:
      "Manages full client lifecycle, personalization, retention, and complaint resolution.",
    parentId: "caffeine-chief",
    provider: "Multi",
    lastAction: "Triggered re-engagement for 6 dormant clients",
  },
  {
    id: "gm-services",
    name: "GM of Services",
    tier: "gm",
    category: "Services",
    description:
      "Coordinates Events, Music, Sports, NGO/CSR, and Tourism service lines.",
    parentId: "caffeine-chief",
    provider: "Gemini",
    lastAction: "Reviewed events calendar for next 30 days",
  },
  {
    id: "gm-security",
    name: "GM of Security & Risk",
    tier: "gm",
    category: "Security",
    description:
      "Leads cybersecurity, fraud detection, data protection, and incident response.",
    parentId: "caffeine-chief",
    provider: "Claude",
    lastAction: "Blocked 2 bot submissions from contact form",
  },
  {
    id: "gm-data",
    name: "GM of Data & Research",
    tier: "gm",
    category: "Analytics",
    description:
      "Oversees all analytics, market data aggregation, competitive intelligence, and research.",
    parentId: "caffeine-chief",
    provider: "Multi",
    lastAction: "Aggregated weekly market data from 8 sources",
  },
  {
    id: "gm-innovation",
    name: "GM of People & Innovation",
    tier: "gm",
    category: "Innovation",
    description:
      "Manages creative AI, innovation pipeline, and continuous improvement.",
    parentId: "caffeine-chief",
    provider: "OpenAI",
    lastAction: "Generated weekly feature suggestion report",
  },
  // DEPARTMENT HEAD TIER
  {
    id: "prop-market-oracle",
    name: "Property Market Oracle",
    tier: "department",
    category: "Property",
    description:
      "Deep analysis of Ahmedabad real estate: micro-market trends, hotspots, price forecasts by locality.",
    parentId: "gm-property",
    provider: "Multi",
    lastAction: "Updated price forecasts for 11 localities",
  },
  {
    id: "deal-intel",
    name: "Deal Intelligence AI",
    tier: "department",
    category: "Property",
    description:
      "Tracks every active deal end-to-end, predicts close probability, flags deals going cold.",
    parentId: "gm-property",
    provider: "OpenAI",
    lastAction: "Flagged Satellite 3BHK deal - 72h no response",
  },
  {
    id: "prop-valuation",
    name: "Property Valuation Engine",
    tier: "department",
    category: "Property",
    description:
      "Instant fair market value for any Ahmedabad property using comparable transactions.",
    parentId: "gm-property",
    provider: "Multi",
    lastAction: "Valued 7 properties in the last hour",
  },
  {
    id: "buyer-profiler",
    name: "Buyer Profiler AI",
    tier: "department",
    category: "Property",
    description:
      "Builds deep buyer profiles: what they want, can afford, and what will make them decide.",
    parentId: "gm-property",
    provider: "Claude",
    lastAction: "Profiled 4 new enquiries from yesterday",
  },
  {
    id: "seller-intel",
    name: "Seller Intelligence AI",
    tier: "department",
    category: "Property",
    description:
      "Understands seller motivations, optimal listing strategy, best pricing approach per seller.",
    parentId: "gm-property",
    provider: "OpenAI",
    lastAction: "Reviewed 2 overpriced listings for repricing",
  },
  {
    id: "rental-market",
    name: "Rental Market AI",
    tier: "department",
    category: "Property",
    description:
      "Tracks rental yields, tenant demand, rental price trends across all Ahmedabad localities.",
    parentId: "gm-property",
    provider: "Gemini",
    lastAction: "Spotted rental demand spike in Gota area",
  },
  {
    id: "commercial-prop",
    name: "Commercial Property AI",
    tier: "department",
    category: "Property",
    description:
      "Specialized in office, retail, industrial - different market dynamics and client needs.",
    parentId: "gm-property",
    provider: "Multi",
    lastAction: "Updated commercial inventory stats",
  },
  {
    id: "luxury-prop",
    name: "Luxury Property AI",
    tier: "department",
    category: "Property",
    description:
      "Specialized in high-value properties: different client expectations and negotiation tactics.",
    parentId: "gm-property",
    provider: "Claude",
    lastAction: "Matched VIP buyer profile to 3 premium listings",
  },
  {
    id: "invest-portfolio",
    name: "Investment Portfolio AI",
    tier: "department",
    category: "Finance",
    description:
      "Builds and manages real estate investment portfolios, tracks performance, rebalances.",
    parentId: "gm-property",
    provider: "OpenAI",
    lastAction: "Sent portfolio rebalancing alert to 2 investors",
  },
  {
    id: "prop-legal-intel",
    name: "Property Legal Intelligence AI",
    tier: "department",
    category: "Legal",
    description:
      "Deep knowledge of Gujarat property law, RERA, registration, stamp duty, title verification.",
    parentId: "gm-property",
    provider: "Claude",
    lastAction: "Explained encumbrance certificate query",
  },
  {
    id: "neighbourhood-intel",
    name: "Neighbourhood Intelligence AI",
    tier: "department",
    category: "Property",
    description:
      "Deep data on all 11 Ahmedabad localities, infrastructure, schools, connectivity.",
    parentId: "gm-property",
    provider: "Gemini",
    lastAction: "Updated Bopal infrastructure score",
  },
  {
    id: "prelaunch-intel",
    name: "Pre-Launch Intelligence AI",
    tier: "department",
    category: "Property",
    description:
      "Tracks upcoming project launches, builder credibility, and early-bird opportunities.",
    parentId: "gm-property",
    provider: "Multi",
    lastAction: "Tracked 2 new pre-launch projects",
  },
  {
    id: "distressed-prop",
    name: "Distressed Property AI",
    tier: "department",
    category: "Property",
    description:
      "Identifies auction, distressed, and below-market property opportunities.",
    parentId: "gm-property",
    provider: "OpenAI",
    lastAction: "Found 1 auction property in Naranpura",
  },
  {
    id: "prop-timeline",
    name: "Property Timeline AI",
    tier: "department",
    category: "Property",
    description:
      "Tracks possession dates, construction progress, and handover milestones.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Reminded 3 clients of upcoming possession",
  },
  {
    id: "virtual-tour-intel",
    name: "Virtual Tour Intelligence AI",
    tier: "department",
    category: "Property",
    description:
      "Manages virtual site visit requests, coordinates scheduling and follow-up.",
    parentId: "gm-property",
    provider: "Gemini",
    lastAction: "Scheduled 2 virtual tours for this week",
  },
  {
    id: "lead-mgmt",
    name: "Lead Management Head AI",
    tier: "department",
    category: "Business",
    description:
      "Manages lead pipeline end-to-end: intake, scoring, routing, and nurturing.",
    parentId: "gm-bizdev",
    provider: "Multi",
    lastAction: "Routed 5 new leads to team members",
  },
  {
    id: "deal-velocity",
    name: "Deal Velocity Head AI",
    tier: "department",
    category: "Business",
    description:
      "Accelerates deal progression, identifies blockers, and recommends actions.",
    parentId: "gm-bizdev",
    provider: "OpenAI",
    lastAction: "Identified 2 deals stuck at documentation stage",
  },
  {
    id: "partnership-head",
    name: "Partnership Head AI",
    tier: "department",
    category: "Business",
    description:
      "Identifies and manages strategic partnerships across all service lines.",
    parentId: "gm-bizdev",
    provider: "Claude",
    lastAction: "Evaluated 1 new broker partnership request",
  },
  {
    id: "revenue-forecast",
    name: "Revenue Forecast Head AI",
    tier: "department",
    category: "Finance",
    description:
      "Projects revenue by month and quarter, tracks against targets, flags shortfalls.",
    parentId: "gm-bizdev",
    provider: "Multi",
    lastAction: "Revised Q2 revenue forecast upward by 8 percent",
  },
  {
    id: "fin-planning",
    name: "Financial Planning AI",
    tier: "department",
    category: "Finance",
    description:
      "Complete goal-based financial planning for clients - life-stage aware, property integrated.",
    parentId: "gm-finance",
    provider: "Claude",
    lastAction: "Created financial plan for new NRI client",
  },
  {
    id: "loan-intel",
    name: "Loan Intelligence AI",
    tier: "department",
    category: "Finance",
    description:
      "Masters the home loan ecosystem: best bank, product, rate, and fastest approval.",
    parentId: "gm-finance",
    provider: "OpenAI",
    lastAction: "Compared rates across 8 banks for client",
  },
  {
    id: "tax-optim",
    name: "Tax Optimization AI",
    tier: "department",
    category: "Finance",
    description:
      "Finds every legal tax saving opportunity for property transactions in Gujarat.",
    parentId: "gm-finance",
    provider: "Claude",
    lastAction: "Saved 1.2L in stamp duty for recent deal",
  },
  {
    id: "invest-returns",
    name: "Investment Returns AI",
    tier: "department",
    category: "Finance",
    description:
      "Projects returns across all asset classes compared to real estate investments.",
    parentId: "gm-finance",
    provider: "Multi",
    lastAction: "Generated 10-year ROI comparison for investor",
  },
  {
    id: "cash-flow-intel",
    name: "Cash Flow Intelligence AI",
    tier: "department",
    category: "Finance",
    description:
      "Tracks and forecasts: rent in, EMI out, tax, maintenance for property investors.",
    parentId: "gm-finance",
    provider: "OpenAI",
    lastAction: "Flagged negative cash flow risk for 1 client",
  },
  {
    id: "insurance-advisory",
    name: "Insurance Advisory AI",
    tier: "department",
    category: "Finance",
    description:
      "Guides on property and home loan insurance - what you need and what you don't.",
    parentId: "gm-finance",
    provider: "Gemini",
    lastAction: "Advised on home loan cover options",
  },
  {
    id: "rera-financial",
    name: "RERA Financial AI",
    tier: "department",
    category: "Compliance",
    description:
      "Monitors escrow accounts, payment schedules, and builder financial health.",
    parentId: "gm-finance",
    provider: "Claude",
    lastAction: "Verified 3 RERA payment milestones",
  },
  {
    id: "wealth-mgmt",
    name: "Wealth Management AI",
    tier: "department",
    category: "Finance",
    description:
      "Long-term wealth building strategy integrating property, equity, gold, and other assets.",
    parentId: "gm-finance",
    provider: "Multi",
    lastAction: "Updated long-term portfolio for HNI client",
  },
  {
    id: "rera-command",
    name: "RERA Command AI",
    tier: "department",
    category: "Compliance",
    description:
      "Complete RERA intelligence: project registration, complaint filing, deadline management.",
    parentId: "gm-finance",
    provider: "OpenAI",
    lastAction: "Sent RERA renewal reminder for active project",
  },
  {
    id: "regulatory-intel",
    name: "Regulatory Intelligence AI",
    tier: "department",
    category: "Legal",
    description:
      "Monitors all regulatory changes across Gujarat and India affecting MSTC's business.",
    parentId: "gm-finance",
    provider: "Claude",
    lastAction: "Flagged new stamp duty notification",
  },
  {
    id: "due-diligence",
    name: "Due Diligence AI",
    tier: "department",
    category: "Legal",
    description:
      "Runs complete property due diligence: title check, encumbrance, legal status, approvals.",
    parentId: "gm-finance",
    provider: "Multi",
    lastAction: "Completed title verification for 3BHK deal",
  },
  {
    id: "litigation-monitor",
    name: "Litigation Monitor AI",
    tier: "department",
    category: "Legal",
    description:
      "Tracks legal matters, court dates, notices - ensures nothing is missed.",
    parentId: "gm-finance",
    provider: "Platform",
    lastAction: "No pending litigations - cleared",
  },
  {
    id: "legal-doc-intel",
    name: "Legal Document Intelligence AI",
    tier: "department",
    category: "Legal",
    description:
      "Reads, analyzes, and summarizes any legal document with risk flags in plain language.",
    parentId: "gm-finance",
    provider: "Claude",
    lastAction: "Summarized 12-page sale agreement",
  },
  {
    id: "contract-gen",
    name: "Contract Generation AI",
    tier: "department",
    category: "Legal",
    description:
      "Generates legally sound agreements, sale deeds, rent agreements, MOUs for Gujarat.",
    parentId: "gm-finance",
    provider: "OpenAI",
    lastAction: "Drafted rent agreement for Prahlad Nagar property",
  },
  {
    id: "content-strategy",
    name: "Content Strategy AI",
    tier: "department",
    category: "Content",
    description:
      "Plans all content: what to publish, when, for whom, in what format.",
    parentId: "gm-content",
    provider: "OpenAI",
    lastAction: "Scheduled 6 posts for this week",
  },
  {
    id: "seo-intel",
    name: "SEO Intelligence AI",
    tier: "department",
    category: "Content",
    description:
      "Masters search optimization: keyword strategy, content gaps, ranking opportunities.",
    parentId: "gm-content",
    provider: "Multi",
    lastAction: "Identified 3 high-value keyword opportunities",
  },
  {
    id: "social-intel",
    name: "Social Intelligence AI",
    tier: "department",
    category: "Content",
    description:
      "Manages social media strategy, content calendar, and engagement monitoring.",
    parentId: "gm-content",
    provider: "Gemini",
    lastAction: "Drafted Instagram carousel for Navratri campaign",
  },
  {
    id: "brand-intel",
    name: "Brand Intelligence AI",
    tier: "department",
    category: "Content",
    description:
      "Protects and evolves the MSTC GLOBAL brand: consistency, perception, positioning.",
    parentId: "gm-content",
    provider: "Claude",
    lastAction: "Reviewed brand consistency across 5 new pages",
  },
  {
    id: "campaign-intel",
    name: "Campaign Intelligence AI",
    tier: "department",
    category: "Content",
    description:
      "Designs and runs marketing campaigns: Diwali, Navratri, budget season, festivals.",
    parentId: "gm-content",
    provider: "OpenAI",
    lastAction: "Planned Navratri 2026 property campaign",
  },
  {
    id: "pr-intel",
    name: "PR Intelligence AI",
    tier: "department",
    category: "Content",
    description:
      "Monitors media, manages reputation, identifies PR opportunities and risks.",
    parentId: "gm-content",
    provider: "Gemini",
    lastAction: "Scanned morning news - no negative mentions",
  },
  {
    id: "newsletter-intel",
    name: "Newsletter Intelligence AI",
    tier: "department",
    category: "Content",
    description:
      "Crafts and sends targeted newsletters based on client segments and behavior.",
    parentId: "gm-content",
    provider: "OpenAI",
    lastAction: "Sent monthly digest to 247 subscribers",
  },
  {
    id: "whatsapp-intel",
    name: "WhatsApp Intelligence AI",
    tier: "department",
    category: "Content",
    description:
      "Drafts messages, manages broadcast lists, and runs auto-reply sequences.",
    parentId: "gm-content",
    provider: "Multi",
    lastAction: "Queued Diwali greetings broadcast",
  },
  {
    id: "area-guide-builder",
    name: "Area Guide Builder AI",
    tier: "department",
    category: "Content",
    description:
      "Continuously writes and updates area guides for all 11 Ahmedabad localities.",
    parentId: "gm-content",
    provider: "Gemini",
    lastAction: "Updated Bopal area guide with metro news",
  },
  {
    id: "client-journey",
    name: "Client Journey Orchestrator",
    tier: "department",
    category: "CRM",
    description:
      "Manages every touchpoint from first contact to post-deal follow-up.",
    parentId: "gm-client",
    provider: "Multi",
    lastAction: "Mapped journey for 3 new clients",
  },
  {
    id: "personalization-engine",
    name: "Personalization Engine AI",
    tier: "department",
    category: "CRM",
    description:
      "Makes every client interaction feel custom-designed for that specific person.",
    parentId: "gm-client",
    provider: "OpenAI",
    lastAction: "Updated personalization rules for investor segment",
  },
  {
    id: "retention-intel",
    name: "Retention Intelligence AI",
    tier: "department",
    category: "CRM",
    description:
      "Predicts which clients are at risk of leaving, auto-intervenes with the right message.",
    parentId: "gm-client",
    provider: "Claude",
    lastAction: "Triggered retention sequence for 2 at-risk clients",
  },
  {
    id: "referral-intel",
    name: "Referral Intelligence AI",
    tier: "department",
    category: "CRM",
    description:
      "Identifies likely referrers, triggers referral programs at the right moment.",
    parentId: "gm-client",
    provider: "Gemini",
    lastAction: "Identified 5 high-potential referral candidates",
  },
  {
    id: "complaint-resolution",
    name: "Complaint Resolution AI",
    tier: "department",
    category: "CRM",
    description:
      "Handles complaints end-to-end: acknowledgment, investigation, resolution, follow-up.",
    parentId: "gm-client",
    provider: "Claude",
    lastAction: "Resolved 1 client complaint in under 24h",
  },
  {
    id: "client-comm",
    name: "Client Communication AI",
    tier: "department",
    category: "CRM",
    description:
      "Drafts all client communications in the right tone per client, all 3 languages.",
    parentId: "gm-client",
    provider: "Multi",
    lastAction: "Drafted follow-up in Gujarati for client",
  },
  {
    id: "vip-client",
    name: "VIP Client AI",
    tier: "department",
    category: "CRM",
    description:
      "Dedicated intelligence for high-value clients: extra attention, proactive service.",
    parentId: "gm-client",
    provider: "Claude",
    lastAction: "Prepared VIP briefing for upcoming HNI meeting",
  },
  {
    id: "crm-intel",
    name: "CRM Intelligence AI",
    tier: "department",
    category: "CRM",
    description: "Deep CRM: segments, tags, scoring, and pipeline management.",
    parentId: "gm-client",
    provider: "Multi",
    lastAction: "Re-segmented 450+ client records",
  },
  {
    id: "events-command",
    name: "Events Command AI",
    tier: "department",
    category: "Services",
    description:
      "Full event intelligence: planning, vendor management, guest experience, post-event.",
    parentId: "gm-services",
    provider: "Gemini",
    lastAction: "Reviewed upcoming corporate event checklist",
  },
  {
    id: "music-cultural-intel",
    name: "Music & Cultural Intelligence AI",
    tier: "department",
    category: "Services",
    description:
      "Deep knowledge of Gujarat's music and cultural ecosystem, talent matching.",
    parentId: "gm-services",
    provider: "OpenAI",
    lastAction: "Matched 2 artists for upcoming event",
  },
  {
    id: "sports-intel",
    name: "Sports Intelligence AI",
    tier: "department",
    category: "Services",
    description:
      "Covers Gujarat sports: athletes, tournaments, sponsorships, media opportunities.",
    parentId: "gm-services",
    provider: "Gemini",
    lastAction: "Tracked district cricket tournament results",
  },
  {
    id: "ngo-csr-command",
    name: "NGO & CSR Command AI",
    tier: "department",
    category: "Services",
    description:
      "Manages CSR compliance, impact measurement, reporting, and grant tracking.",
    parentId: "gm-services",
    provider: "Claude",
    lastAction: "Compiled quarterly CSR impact report",
  },
  {
    id: "tourism-intel",
    name: "Tourism Intelligence AI",
    tier: "department",
    category: "Services",
    description:
      "Gujarat/Ahmedabad tourism expert: itineraries, packages, seasonal recommendations.",
    parentId: "gm-services",
    provider: "Gemini",
    lastAction: "Updated Rann Utsav package for winter season",
  },
  {
    id: "hospitality-ai",
    name: "Hospitality AI",
    tier: "department",
    category: "Services",
    description:
      "Venue management, catering coordination, and guest experience optimization.",
    parentId: "gm-services",
    provider: "OpenAI",
    lastAction: "Suggested 3 venues for upcoming conference",
  },
  {
    id: "cyber-security-command",
    name: "Cyber Security Command AI",
    tier: "department",
    category: "Security",
    description:
      "Chief of all cyber security, coordinates the entire security team.",
    parentId: "gm-security",
    provider: "Claude",
    lastAction: "Completed morning threat scan - all clear",
  },
  {
    id: "threat-intel",
    name: "Threat Intelligence AI",
    tier: "department",
    category: "Security",
    description:
      "Monitors the global threat landscape for anything relevant to MSTC.",
    parentId: "gm-security",
    provider: "Multi",
    lastAction: "Scanned 1,240 threat feeds - no new alerts",
  },
  {
    id: "identity-verif",
    name: "Identity Verification AI",
    tier: "department",
    category: "Security",
    description:
      "Verifies client identities, flags suspicious accounts, prevents impersonation.",
    parentId: "gm-security",
    provider: "Claude",
    lastAction: "Verified 6 new client KYC submissions",
  },
  {
    id: "transaction-security",
    name: "Transaction Security AI",
    tier: "department",
    category: "Security",
    description:
      "Monitors all financial transactions and form submissions for fraud.",
    parentId: "gm-security",
    provider: "Multi",
    lastAction: "Cleared 24 transactions - 0 fraud flags",
  },
  {
    id: "data-protection",
    name: "Data Protection AI",
    tier: "department",
    category: "Security",
    description:
      "Ensures all data handling complies with Indian PDPB and global standards.",
    parentId: "gm-security",
    provider: "Platform",
    lastAction: "Ran data retention compliance check",
  },
  {
    id: "incident-response",
    name: "Incident Response AI",
    tier: "department",
    category: "Security",
    description:
      "When a security incident occurs, coordinates immediate response and recovery.",
    parentId: "gm-security",
    provider: "Claude",
    lastAction: "No incidents in last 30 days",
  },
  {
    id: "brand-protection",
    name: "Brand Protection AI",
    tier: "department",
    category: "Security",
    description:
      "Monitors for MSTC impersonation, fake listings, and copied content online.",
    parentId: "gm-security",
    provider: "Gemini",
    lastAction: "Scanned 45 domains - no impersonation found",
  },
  {
    id: "vuln-scanner",
    name: "Vulnerability Scanner AI",
    tier: "department",
    category: "Security",
    description:
      "Periodic security scans: injection testing, API endpoint security checks.",
    parentId: "gm-security",
    provider: "Multi",
    lastAction: "Weekly scan complete - 0 vulnerabilities",
  },
  {
    id: "biz-analytics-command",
    name: "Business Analytics Command AI",
    tier: "department",
    category: "Analytics",
    description:
      "Oversees all analytics across the business, produces executive dashboards.",
    parentId: "gm-data",
    provider: "Multi",
    lastAction: "Generated weekly KPI dashboard",
  },
  {
    id: "predictive-intel",
    name: "Predictive Intelligence AI",
    tier: "department",
    category: "Analytics",
    description:
      "Uses historical data to predict future outcomes across all business areas.",
    parentId: "gm-data",
    provider: "OpenAI",
    lastAction: "Predicted Q3 enquiry volume +18 percent",
  },
  {
    id: "market-intel-command",
    name: "Market Intelligence Command AI",
    tier: "department",
    category: "Analytics",
    description:
      "Monitors all market signals: property, finance, economy, competition.",
    parentId: "gm-data",
    provider: "Multi",
    lastAction: "Aggregated 12 market intelligence signals",
  },
  {
    id: "user-behavior",
    name: "User Behavior AI",
    tier: "department",
    category: "Analytics",
    description:
      "Deeply understands how users interact with MSTC GLOBAL, drives UX improvements.",
    parentId: "gm-data",
    provider: "Gemini",
    lastAction: "Identified drop-off on mobile property filters",
  },
  {
    id: "competitive-intel-command",
    name: "Competitive Intelligence Command AI",
    tier: "department",
    category: "Analytics",
    description:
      "Tracks all competitors, market positioning, and differentiation opportunities.",
    parentId: "gm-data",
    provider: "Claude",
    lastAction: "Monitored 5 competitor sites this morning",
  },
  {
    id: "economic-intel",
    name: "Economic Intelligence AI",
    tier: "department",
    category: "Analytics",
    description:
      "Monitors GDP, inflation, interest rates, and their specific impact on MSTC.",
    parentId: "gm-data",
    provider: "OpenAI",
    lastAction: "Updated RBI rate impact analysis",
  },
  {
    id: "geospatial-intel",
    name: "Geospatial Intelligence AI",
    tier: "department",
    category: "Analytics",
    description:
      "Maps all MSTC data geographically: property hotspots, client density, infrastructure.",
    parentId: "gm-data",
    provider: "Gemini",
    lastAction: "Plotted 1051+ properties on heat map",
  },
  {
    id: "insight-synthesis",
    name: "Insight Synthesis AI",
    tier: "department",
    category: "Analytics",
    description:
      "Takes outputs from all analytics AIs and produces unified, actionable recommendations.",
    parentId: "gm-data",
    provider: "Multi",
    lastAction: "Synthesized 8 data source reports",
  },
  {
    id: "platform-evolution",
    name: "Platform Evolution AI",
    tier: "department",
    category: "Technology",
    description:
      "Continuously evolves MSTC GLOBAL: new features, better UX, new tools.",
    parentId: "gm-tech",
    provider: "Multi",
    lastAction: "Queued 3 UX improvements for next build",
  },
  {
    id: "perf-optimizer",
    name: "Performance Optimizer AI",
    tier: "department",
    category: "Technology",
    description:
      "Keeps the platform running at peak speed and efficiency on all devices always.",
    parentId: "gm-tech",
    provider: "Platform",
    lastAction: "Optimized image loading - 340ms improvement",
  },
  {
    id: "integration-architect",
    name: "Integration Architect AI",
    tier: "department",
    category: "Technology",
    description:
      "Manages all external integrations: payment APIs, data feeds, third-party services.",
    parentId: "gm-tech",
    provider: "Multi",
    lastAction: "Tested WhatsApp Business API connection",
  },
  {
    id: "data-architecture",
    name: "Data Architecture AI",
    tier: "department",
    category: "Technology",
    description: "Designs and maintains the entire platform data structure.",
    parentId: "gm-tech",
    provider: "OpenAI",
    lastAction: "Reviewed canister data model for new feature",
  },
  {
    id: "devops-intel",
    name: "DevOps Intelligence AI",
    tier: "department",
    category: "Technology",
    description:
      "Monitors deployment health, uptime, error rates, and infrastructure performance.",
    parentId: "gm-tech",
    provider: "Platform",
    lastAction: "Uptime 100 percent - all systems nominal",
  },
  {
    id: "api-intel",
    name: "API Intelligence AI",
    tier: "department",
    category: "Technology",
    description:
      "Manages all external API connections, monitors usage, optimizes costs.",
    parentId: "gm-tech",
    provider: "Multi",
    lastAction: "Optimized API call batching - 15 percent cost reduction",
  },
  {
    id: "code-quality",
    name: "Code Quality AI",
    tier: "department",
    category: "Technology",
    description:
      "Ensures all code added to the platform meets quality standards, reviews every build.",
    parentId: "gm-tech",
    provider: "Claude",
    lastAction: "Reviewed latest build - no critical issues",
  },
  {
    id: "continuous-builder-head",
    name: "Continuous Builder Head AI",
    tier: "department",
    category: "Technology",
    description:
      "Directs the builder team, prioritizes the build queue, coordinates deployment.",
    parentId: "gm-tech",
    provider: "Multi",
    lastAction: "Managed 5 simultaneous micro-builds overnight",
  },
  {
    id: "creative-director",
    name: "Creative Director AI",
    tier: "department",
    category: "Creative",
    description:
      "Oversees all creative output, enforces gold/black MSTC brand consistency.",
    parentId: "gm-innovation",
    provider: "OpenAI",
    lastAction: "Reviewed Navratri campaign visuals",
  },
  {
    id: "copywriting-ai",
    name: "Copywriting AI",
    tier: "department",
    category: "Creative",
    description:
      "Writes all marketing copy, property descriptions, email content in all 3 languages.",
    parentId: "gm-innovation",
    provider: "Claude",
    lastAction: "Wrote 8 property descriptions for new listings",
  },
  {
    id: "ai-training-agent",
    name: "AI Training Agent",
    tier: "department",
    category: "Innovation",
    description:
      "Manages the AI learning process - collects feedback, improves instructions for all agents.",
    parentId: "gm-innovation",
    provider: "Multi",
    lastAction: "Processed 34 feedback items - 5 agents improved",
  },
  {
    id: "ai-quality-controller",
    name: "AI Quality Controller",
    tier: "department",
    category: "Innovation",
    description:
      "Reviews everything added or changed by any agent before it goes live.",
    parentId: "gm-innovation",
    provider: "Claude",
    lastAction: "Approved 12 content changes - blocked 1",
  },
  {
    id: "feature-suggestion",
    name: "Feature Suggestion AI",
    tier: "department",
    category: "Innovation",
    description:
      "Generates weekly ranked feature ideas with impact scores for MD approval.",
    parentId: "gm-innovation",
    provider: "OpenAI",
    lastAction: "Generated 8 new feature suggestions",
  },
  {
    id: "dashboard-enhancer-dept",
    name: "Dashboard Enhancer AI",
    tier: "department",
    category: "Innovation",
    description:
      "Continuously improves dashboard layout, surfaces weekly suggestions panel.",
    parentId: "gm-innovation",
    provider: "Multi",
    lastAction: "Suggested 3 dashboard layout improvements",
  },
  {
    id: "tech-upgrade",
    name: "Technology Upgrade AI",
    tier: "department",
    category: "Innovation",
    description:
      "Monitors new tech developments and suggests platform upgrades when better tools emerge.",
    parentId: "gm-innovation",
    provider: "Gemini",
    lastAction: "Identified new Vite plugin for faster builds",
  },
  {
    id: "biz-expansion",
    name: "Business Expansion AI",
    tier: "department",
    category: "Innovation",
    description:
      "Looks at data and market conditions to suggest new services, localities, client segments.",
    parentId: "gm-innovation",
    provider: "OpenAI",
    lastAction: "Identified Chandkheda as next expansion locality",
  },
  // NEURAL TIER
  {
    id: "lead-conv-ann",
    name: "Lead Conversion ANN",
    tier: "neural",
    category: "ANN",
    description:
      "Predicts exact probability of any lead converting, trained on all MSTC historical data.",
    parentId: "gm-data",
    provider: "Platform",
    lastAction: "Scored 8 new leads - avg 0.73 probability",
  },
  {
    id: "prop-val-ann",
    name: "Property Valuation ANN",
    tier: "neural",
    category: "ANN",
    description:
      "Estimates fair market value from address, size, age, floor, facing, amenities.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Valued Bopal 3BHK at 1.15Cr",
  },
  {
    id: "clv-ann",
    name: "Client Lifetime Value ANN",
    tier: "neural",
    category: "ANN",
    description:
      "Predicts total revenue a new client will generate over their MSTC relationship.",
    parentId: "gm-client",
    provider: "Platform",
    lastAction: "Scored 4 new clients - top CLV 45L",
  },
  {
    id: "demand-forecast-ann",
    name: "Demand Forecast ANN",
    tier: "neural",
    category: "ANN",
    description:
      "Predicts property demand by locality and type for next 3/6/12 months.",
    parentId: "gm-data",
    provider: "Platform",
    lastAction: "Forecast 3BHK demand +22 percent next quarter",
  },
  {
    id: "churn-pred-ann",
    name: "Churn Prediction ANN",
    tier: "neural",
    category: "ANN",
    description:
      "Identifies clients about to disengage and triggers automatic retention actions.",
    parentId: "gm-client",
    provider: "Platform",
    lastAction: "Flagged 3 clients with churn probability above 0.8",
  },
  {
    id: "convo-memory-rnn",
    name: "Conversation Memory RNN",
    tier: "neural",
    category: "RNN",
    description:
      "Remembers full history of every client conversation, personalizes all future interactions.",
    parentId: "gm-client",
    provider: "Platform",
    lastAction: "Updated memory for 15 client conversations",
  },
  {
    id: "price-trend-rnn",
    name: "Price Trend Forecaster RNN",
    tier: "neural",
    category: "RNN",
    description:
      "Predicts property prices in specific Ahmedabad localities over the next 6-12 months.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Forecast Navrangpura appreciation +11 percent in 12mo",
  },
  {
    id: "seasonal-demand-rnn",
    name: "Seasonal Demand RNN",
    tier: "neural",
    category: "RNN",
    description:
      "Predicts when enquiry volume will spike: festivals, financial year end, budget season.",
    parentId: "gm-data",
    provider: "Platform",
    lastAction: "Predicted April spike due to financial year end",
  },
  {
    id: "lead-behavior-rnn",
    name: "Lead Behavior RNN",
    tier: "neural",
    category: "RNN",
    description:
      "Analyzes sequence of user actions to predict next move and best intervention.",
    parentId: "gm-bizdev",
    provider: "Platform",
    lastAction: "Identified 3 leads nearing decision point",
  },
  {
    id: "relationship-mapper-gnn",
    name: "Relationship Mapper GNN",
    tier: "neural",
    category: "GNN",
    description:
      "Maps all connections between clients, properties, agents, deals - finds hidden links.",
    parentId: "gm-client",
    provider: "Platform",
    lastAction: "Found referral chain involving 8 clients",
  },
  {
    id: "fraud-pattern-gnn",
    name: "Fraud Pattern GNN",
    tier: "neural",
    category: "GNN",
    description:
      "Identifies unusual connection patterns that indicate coordinated fake lead campaigns.",
    parentId: "gm-security",
    provider: "Platform",
    lastAction: "No fraud network patterns detected",
  },
  {
    id: "referral-network-gnn",
    name: "Referral Network GNN",
    tier: "neural",
    category: "GNN",
    description:
      "Maps the entire MSTC referral network, identifies the most valuable nodes.",
    parentId: "gm-client",
    provider: "Platform",
    lastAction: "Identified top 5 referral influencers",
  },
  {
    id: "deal-network-gnn",
    name: "Deal Network GNN",
    tier: "neural",
    category: "GNN",
    description:
      "Maps which brokers connect to which deals, finds the most influential intermediaries.",
    parentId: "gm-bizdev",
    provider: "Platform",
    lastAction: "Mapped broker influence for 23 active deals",
  },
  {
    id: "contract-transformer",
    name: "Contract Analyzer Transformer",
    tier: "neural",
    category: "Transformer",
    description:
      "Deep reading of any contract: extracts every clause, flags risks, plain language summary.",
    parentId: "gm-finance",
    provider: "Claude",
    lastAction: "Analyzed 18-page joint development agreement",
  },
  {
    id: "multilang-transformer",
    name: "Multi-Language Translator Transformer",
    tier: "neural",
    category: "Transformer",
    description:
      "Full site translation between English, Gujarati, and Hindi in real time.",
    parentId: "gm-content",
    provider: "Multi",
    lastAction: "Translated 3 property listings to Gujarati",
  },
  {
    id: "voice-text-transformer",
    name: "Voice-to-Text Transformer",
    tier: "neural",
    category: "Transformer",
    description:
      "Converts voice input to text across all forms and chat in all 3 languages.",
    parentId: "gm-tech",
    provider: "Platform",
    lastAction: "Processed 7 voice queries today",
  },
  {
    id: "doc-summarizer-transformer",
    name: "Document Summarizer Transformer",
    tier: "neural",
    category: "Transformer",
    description:
      "Takes any long document and produces a crisp executive summary.",
    parentId: "gm-finance",
    provider: "Claude",
    lastAction: "Summarized Gujarat housing policy 2025",
  },
  {
    id: "negotiation-coach-transformer",
    name: "Negotiation Coach Transformer",
    tier: "neural",
    category: "Transformer",
    description:
      "Analyzes a deal and produces a tailored negotiation strategy brief.",
    parentId: "gm-bizdev",
    provider: "OpenAI",
    lastAction: "Prepared negotiation brief for Ambli deal",
  },
  {
    id: "pricing-optimizer-rl",
    name: "Pricing Optimizer RL",
    tier: "neural",
    category: "RL",
    description:
      "Learns what price points close deals fastest, continuously improves recommendations.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Adjusted recommended pricing band for 1BHK",
  },
  {
    id: "campaign-optimizer-rl",
    name: "Campaign Optimizer RL",
    tier: "neural",
    category: "RL",
    description:
      "Learns which outreach gets the best response rate and auto-optimizes campaigns.",
    parentId: "gm-content",
    provider: "Platform",
    lastAction: "Improved email open rate by 8 percent via subject line test",
  },
  {
    id: "ui-optimizer-rl",
    name: "UI Optimizer RL",
    tier: "neural",
    category: "RL",
    description:
      "Learns which layout drives the most conversions and applies improvements automatically.",
    parentId: "gm-tech",
    provider: "Platform",
    lastAction: "Applied CTA button color change - +5 percent click rate",
  },
  {
    id: "lead-routing-rl",
    name: "Lead Routing Optimizer RL",
    tier: "neural",
    category: "RL",
    description:
      "Learns which agent closes which type of lead fastest and auto-routes accordingly.",
    parentId: "gm-bizdev",
    provider: "Platform",
    lastAction: "Routed 5 commercial leads to specialist team",
  },
  {
    id: "lead-scoring-ml",
    name: "Lead Scoring ML",
    tier: "neural",
    category: "ML",
    description:
      "Gradient boosting model that scores every lead with full reasoning and confidence.",
    parentId: "gm-bizdev",
    provider: "Platform",
    lastAction: "Scored 12 new leads - 3 marked high priority",
  },
  {
    id: "recommendation-ml",
    name: "Recommendation Engine ML",
    tier: "neural",
    category: "ML",
    description:
      "Collaborative filtering: clients who looked at this also looked at... for properties.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Generated 45 property recommendations",
  },
  {
    id: "anomaly-detector-ml",
    name: "Anomaly Detector ML",
    tier: "neural",
    category: "ML",
    description:
      "Isolation forest model that flags anything unusual in the data.",
    parentId: "gm-data",
    provider: "Platform",
    lastAction: "Detected unusual price drop in one listing",
  },
  {
    id: "segmentation-ml",
    name: "Segmentation Engine ML",
    tier: "neural",
    category: "ML",
    description:
      "K-means clustering that segments all clients into actionable groups.",
    parentId: "gm-client",
    provider: "Platform",
    lastAction: "Re-clustered 450 clients into 8 segments",
  },
  {
    id: "attribution-ml",
    name: "Attribution Model ML",
    tier: "neural",
    category: "ML",
    description:
      "Multi-touch attribution that tracks which touchpoints drove each deal.",
    parentId: "gm-data",
    provider: "Platform",
    lastAction: "Attributed last 5 deals to channels",
  },
  // SPECIALIST AGENTS
  {
    id: "macro-intel",
    name: "Macro Intelligence AI",
    tier: "specialist",
    category: "Intelligence",
    description:
      "Monitors global economic signals (US Fed, oil prices, global inflation) and their ripple effect on Indian real estate.",
    parentId: "gm-data",
    provider: "Multi",
    lastAction: "Tracked Fed rate decision impact",
  },
  {
    id: "political-intel",
    name: "Political Intelligence AI",
    tier: "specialist",
    category: "Intelligence",
    description:
      "Monitors Gujarat and national political developments that affect property and infrastructure.",
    parentId: "gm-data",
    provider: "Gemini",
    lastAction: "Reviewed Gujarat budget speech implications",
  },
  {
    id: "infra-forecast",
    name: "Infrastructure Forecast AI",
    tier: "specialist",
    category: "Property",
    description:
      "Predicts which Ahmedabad areas will appreciate due to upcoming infrastructure projects.",
    parentId: "gm-property",
    provider: "OpenAI",
    lastAction: "Flagged Kheda metro corridor as appreciation zone",
  },
  {
    id: "migration-intel",
    name: "Migration Intelligence AI",
    tier: "specialist",
    category: "Analytics",
    description:
      "Tracks population movement into Ahmedabad and identifies high-demand residential zones.",
    parentId: "gm-data",
    provider: "Gemini",
    lastAction: "Tracked IT migration to Maninagar corridor",
  },
  {
    id: "builder-intel",
    name: "Builder Intelligence AI",
    tier: "specialist",
    category: "Property",
    description:
      "Deep profiles of every major Ahmedabad developer: track record, delivery history, financial health.",
    parentId: "gm-property",
    provider: "Claude",
    lastAction: "Updated profiles for 5 Ahmedabad builders",
  },
  {
    id: "society-intel",
    name: "Society Intelligence AI",
    tier: "specialist",
    category: "Property",
    description:
      "Comprehensive database of Ahmedabad housing societies: management quality, maintenance, issues.",
    parentId: "gm-property",
    provider: "Multi",
    lastAction: "Added reviews for 3 new societies",
  },
  {
    id: "locality-appreciation",
    name: "Locality Appreciation AI",
    tier: "specialist",
    category: "Property",
    description:
      "Predicts which Ahmedabad localities will appreciate most in the next 2 years and why.",
    parentId: "gm-property",
    provider: "OpenAI",
    lastAction: "Updated appreciation ranking for all 11 localities",
  },
  {
    id: "rental-demand-ai",
    name: "Rental Demand AI",
    tier: "specialist",
    category: "Property",
    description:
      "Tracks rental demand by locality, property type, tenant profile.",
    parentId: "gm-property",
    provider: "Gemini",
    lastAction: "Spotted rental demand spike in Thaltej",
  },
  {
    id: "nri-invest",
    name: "NRI Investment AI",
    tier: "specialist",
    category: "Finance",
    description:
      "Specialized for NRI clients: FEMA compliance, repatriation, NRO/NRE guidance, power of attorney.",
    parentId: "gm-finance",
    provider: "Claude",
    lastAction: "Guided NRI client on NRO account setup",
  },
  {
    id: "commercial-roi",
    name: "Commercial ROI AI",
    tier: "specialist",
    category: "Finance",
    description:
      "Specialized ROI analysis for commercial properties: office, retail, warehouse, industrial.",
    parentId: "gm-finance",
    provider: "OpenAI",
    lastAction: "Analyzed ROI for SG Highway commercial space",
  },
  {
    id: "whatsapp-autoreply",
    name: "WhatsApp Auto-Reply AI",
    tier: "specialist",
    category: "Automation",
    description:
      "Reads incoming WhatsApp messages and drafts instant contextual replies.",
    parentId: "gm-client",
    provider: "Multi",
    lastAction: "Queued 3 auto-reply drafts for review",
  },
  {
    id: "lead-nurture-seq",
    name: "Lead Nurture Sequence AI",
    tier: "specialist",
    category: "Automation",
    description:
      "Designs and runs multi-step lead nurture sequences automatically.",
    parentId: "gm-bizdev",
    provider: "OpenAI",
    lastAction: "Running 4 active nurture sequences",
  },
  {
    id: "prop-alert-ai",
    name: "Property Alert AI",
    tier: "specialist",
    category: "Automation",
    description:
      "Sends personalized property alerts to buyers when matching listings appear.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Sent 7 property alerts to active buyers",
  },
  {
    id: "weekly-digest-ai",
    name: "Weekly Digest AI",
    tier: "specialist",
    category: "Automation",
    description:
      "Compiles and sends personalized weekly digests to all active clients.",
    parentId: "gm-client",
    provider: "OpenAI",
    lastAction: "Sent weekly digest to 156 active clients",
  },
  {
    id: "agreement-expiry",
    name: "Agreement Expiry AI",
    tier: "specialist",
    category: "Automation",
    description:
      "Tracks all agreements and sends reminders 30/15/7/1 days before expiry.",
    parentId: "gm-finance",
    provider: "Platform",
    lastAction: "Sent 2 expiry reminders - 7 days notice",
  },
  {
    id: "smart-assign",
    name: "Smart Assignment AI",
    tier: "specialist",
    category: "Automation",
    description:
      "Auto-assigns leads to the best available team member based on skill, load, and history.",
    parentId: "gm-bizdev",
    provider: "Multi",
    lastAction: "Assigned 5 leads to optimal agents",
  },
  {
    id: "re-engage-seq",
    name: "Re-Engagement Sequence AI",
    tier: "specialist",
    category: "Automation",
    description: "Runs automated re-engagement campaigns for dormant clients.",
    parentId: "gm-client",
    provider: "OpenAI",
    lastAction: "Launched re-engagement for 12 dormant clients",
  },
  {
    id: "buyer-intent",
    name: "Buyer Intent AI",
    tier: "specialist",
    category: "Client",
    description:
      "Reads all signals from a buyer's behavior and ranks their purchase intent 1-10 in real time.",
    parentId: "gm-client",
    provider: "Multi",
    lastAction: "Scored 8 buyers - top score 9.2/10",
  },
  {
    id: "price-sensitivity",
    name: "Price Sensitivity AI",
    tier: "specialist",
    category: "Client",
    description:
      "Identifies each buyer's price sensitivity to help position the right property at the right price.",
    parentId: "gm-client",
    provider: "OpenAI",
    lastAction: "Classified 6 buyers into sensitivity tiers",
  },
  {
    id: "decision-timeline",
    name: "Decision Timeline AI",
    tier: "specialist",
    category: "Client",
    description:
      "Predicts how many days a specific buyer will take to make a purchase decision.",
    parentId: "gm-client",
    provider: "Claude",
    lastAction: "Predicted 14-day decision window for 3 buyers",
  },
  {
    id: "objection-handler",
    name: "Objection Handler AI",
    tier: "specialist",
    category: "Client",
    description:
      "Anticipates common client objections and prepares tailored responses for each client.",
    parentId: "gm-client",
    provider: "Claude",
    lastAction: "Prepared objection brief for upcoming negotiation",
  },
  {
    id: "cross-sell-intel",
    name: "Cross-Sell Intelligence AI",
    tier: "specialist",
    category: "Client",
    description:
      "Identifies which existing clients are ready for additional services from MSTC.",
    parentId: "gm-client",
    provider: "Multi",
    lastAction: "Found 5 property clients ready for finance services",
  },
  {
    id: "micro-market",
    name: "Micro-Market AI",
    tier: "specialist",
    category: "Property",
    description:
      "Hyper-local analysis at the street and society level, not just locality level.",
    parentId: "gm-property",
    provider: "Gemini",
    lastAction: "Analyzed Shela micro-market movement",
  },
  {
    id: "price-history",
    name: "Price History AI",
    tier: "specialist",
    category: "Property",
    description:
      "Tracks full price history of every listed property and shows appreciation curve.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Updated price history for 45 properties",
  },
  {
    id: "flip-calculator",
    name: "Flip Calculator AI",
    tier: "specialist",
    category: "Finance",
    description:
      "Calculates renovation cost and resale value for any property, produces flip viability score.",
    parentId: "gm-finance",
    provider: "OpenAI",
    lastAction: "Scored 2 flip opportunities - 1 viable",
  },
  {
    id: "possession-risk",
    name: "Possession Risk AI",
    tier: "specialist",
    category: "Property",
    description:
      "Analyzes builder history and project status, scores possession risk for under-construction properties.",
    parentId: "gm-property",
    provider: "Claude",
    lastAction: "Rated 3 under-construction projects",
  },
  {
    id: "vastu-intel",
    name: "Vastu Intelligence AI",
    tier: "specialist",
    category: "Property",
    description:
      "Assesses Vastu compliance of any property based on direction, layout, entrance position.",
    parentId: "gm-property",
    provider: "Gemini",
    lastAction: "Assessed Vastu for client-requested property",
  },
  {
    id: "walk-score",
    name: "Walk Score AI",
    tier: "specialist",
    category: "Property",
    description:
      "Calculates walkability, connectivity, and amenity score for any Ahmedabad address.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Scored 8 properties for walkability",
  },
  {
    id: "investment-grade",
    name: "Investment Grade AI",
    tier: "specialist",
    category: "Finance",
    description:
      "Grades every property A/B/C/D as an investment based on yield, appreciation potential, liquidity.",
    parentId: "gm-property",
    provider: "Multi",
    lastAction: "Graded 15 new listings - 4 rated A-grade",
  },
  {
    id: "portfolio-rebalancer",
    name: "Portfolio Rebalancer AI",
    tier: "specialist",
    category: "Finance",
    description:
      "Reviews client property portfolio and recommends when to sell, hold, or buy.",
    parentId: "gm-finance",
    provider: "Claude",
    lastAction: "Recommended hold strategy for 2 investor clients",
  },
  {
    id: "rent-vs-buy",
    name: "Rent vs Buy AI",
    tier: "specialist",
    category: "Finance",
    description:
      "Deep analysis for each client: is it financially better to rent or buy right now?",
    parentId: "gm-finance",
    provider: "OpenAI",
    lastAction: "Advised rent-first for 2 early-career clients",
  },
  {
    id: "should-sell-now",
    name: "Should I Sell Now AI",
    tier: "specialist",
    category: "Finance",
    description:
      "Analyzes market conditions and client's financial position to recommend hold or sell.",
    parentId: "gm-finance",
    provider: "Multi",
    lastAction: "Recommended sell for 1 client - market peak signal",
  },
  {
    id: "rate-alert",
    name: "Rate Alert AI",
    tier: "specialist",
    category: "Finance",
    description:
      "Monitors RBI and bank rate changes, immediately notifies clients when rates drop.",
    parentId: "gm-finance",
    provider: "Platform",
    lastAction: "No rate changes today",
  },
  {
    id: "daily-briefing",
    name: "Daily Briefing AI",
    tier: "specialist",
    category: "Operations",
    description:
      "Every morning at 7am IST, prepares MD's personal business brief: deals, leads, alerts, tasks.",
    parentId: "ops-command",
    provider: "Multi",
    lastAction: "Delivered morning brief at 07:00 IST",
  },
  {
    id: "meeting-prep",
    name: "Meeting Prep AI",
    tier: "specialist",
    category: "Operations",
    description:
      "Before any client meeting, prepares a brief: client history, property interest, talking points.",
    parentId: "ops-command",
    provider: "Claude",
    lastAction: "Prepared brief for 2:30pm client meeting",
  },
  {
    id: "task-priority",
    name: "Task Priority AI",
    tier: "specialist",
    category: "Operations",
    description:
      "Looks at all pending tasks across the business and ranks them by urgency and impact.",
    parentId: "ops-command",
    provider: "OpenAI",
    lastAction: "Ranked 18 tasks - 3 marked critical today",
  },
  {
    id: "deadline-intel",
    name: "Deadline Intelligence AI",
    tier: "specialist",
    category: "Operations",
    description:
      "Tracks every deadline across legal, compliance, deals, and operations - nothing missed.",
    parentId: "ops-command",
    provider: "Platform",
    lastAction: "2 deadlines due this week - sent alerts",
  },
  {
    id: "vendor-intel",
    name: "Vendor Intelligence AI",
    tier: "specialist",
    category: "Operations",
    description:
      "Manages all vendor relationships: rates, performance, reliability scores.",
    parentId: "ops-command",
    provider: "Gemini",
    lastAction: "Updated vendor ratings after event feedback",
  },
  {
    id: "staff-performance",
    name: "Staff Performance AI",
    tier: "specialist",
    category: "Operations",
    description:
      "Tracks response times, deal closures, and client satisfaction per team member.",
    parentId: "ops-command",
    provider: "Multi",
    lastAction: "Generated weekly team performance report",
  },
  {
    id: "tone-calibrator",
    name: "Tone Calibrator AI",
    tier: "specialist",
    category: "Communication",
    description:
      "Adjusts all outgoing communication to the right tone per client: formal, warm, urgent, celebratory.",
    parentId: "gm-content",
    provider: "Claude",
    lastAction: "Calibrated 8 client messages",
  },
  {
    id: "multilingual-drafter",
    name: "Multilingual Drafter AI",
    tier: "specialist",
    category: "Communication",
    description:
      "Drafts any message simultaneously in English, Gujarati, and Hindi.",
    parentId: "gm-content",
    provider: "Multi",
    lastAction: "Drafted property description in 3 languages",
  },
  {
    id: "proposal-gen",
    name: "Proposal Generator AI",
    tier: "specialist",
    category: "Business",
    description:
      "One-click branded proposal PDF per lead, professional format, ready to send immediately.",
    parentId: "gm-bizdev",
    provider: "OpenAI",
    lastAction: "Generated proposal for SG Highway commercial lead",
  },
  {
    id: "growth-hacking",
    name: "Growth Hacking AI",
    tier: "specialist",
    category: "Innovation",
    description:
      "Identifies unconventional growth opportunities specific to Ahmedabad real estate market.",
    parentId: "gm-innovation",
    provider: "OpenAI",
    lastAction: "Identified builder tie-up growth opportunity",
  },
  {
    id: "competitive-intel",
    name: "Competitive Intelligence AI",
    tier: "specialist",
    category: "Intelligence",
    description:
      "Monitors competitors, market positioning, and differentiation opportunities.",
    parentId: "gm-data",
    provider: "Gemini",
    lastAction: "Scanned 5 competitor listings this morning",
  },
  {
    id: "sentiment-analysis",
    name: "Sentiment Analysis AI",
    tier: "specialist",
    category: "Analytics",
    description:
      "Reads all enquiries and messages, weekly emotional tone report.",
    parentId: "gm-data",
    provider: "Claude",
    lastAction: "Weekly tone report: 84 percent positive enquiries",
  },
  {
    id: "revenue-attribution",
    name: "Revenue Attribution AI",
    tier: "specialist",
    category: "Analytics",
    description:
      "Tracks which channel, agent, or campaign each deal came from.",
    parentId: "gm-data",
    provider: "Multi",
    lastAction: "Attributed last week's 3 deals to channels",
  },
  {
    id: "innovation-report",
    name: "Weekly Innovation Report AI",
    tier: "specialist",
    category: "Innovation",
    description:
      "Compiles all suggestion AI outputs into one weekly innovation brief for MD.",
    parentId: "gm-innovation",
    provider: "Multi",
    lastAction: "Generated this week's innovation digest",
  },
  {
    id: "cultural-calendar",
    name: "Cultural Calendar AI",
    tier: "specialist",
    category: "Services",
    description:
      "Gujarat/Ahmedabad cultural events, festivals, performances tracker.",
    parentId: "gm-services",
    provider: "Gemini",
    lastAction: "Updated Navratri 2026 events calendar",
  },
  {
    id: "sports-analytics",
    name: "Sports Analytics AI",
    tier: "specialist",
    category: "Services",
    description:
      "Athlete performance, tournament results, and achievements tracker.",
    parentId: "gm-services",
    provider: "Gemini",
    lastAction: "Logged district football results",
  },
  {
    id: "market-opportunity",
    name: "Market Opportunity Scanner AI",
    tier: "specialist",
    category: "Intelligence",
    description:
      "Scans for emerging opportunities in Gujarat real estate market before they become mainstream.",
    parentId: "gm-data",
    provider: "OpenAI",
    lastAction: "Flagged Gandhinagar-Ahmedabad corridor opportunity",
  },
  {
    id: "process-improve",
    name: "Process Improvement AI",
    tier: "specialist",
    category: "Operations",
    description:
      "Identifies inefficiencies in MSTC operations and suggests streamlined workflows.",
    parentId: "ops-command",
    provider: "Claude",
    lastAction: "Suggested 2 process improvements for lead intake",
  },
  {
    id: "tech-scout",
    name: "Technology Scout AI",
    tier: "specialist",
    category: "Technology",
    description:
      "Identifies new proptech and fintech tools relevant to MSTC's business.",
    parentId: "gm-tech",
    provider: "Gemini",
    lastAction: "Evaluated new property valuation API",
  },
  {
    id: "partnership-scout",
    name: "Partnership Scout AI",
    tier: "specialist",
    category: "Business",
    description:
      "Identifies potential strategic partners and co-marketing opportunities.",
    parentId: "gm-bizdev",
    provider: "OpenAI",
    lastAction: "Shortlisted 2 potential bank partnerships",
  },
  {
    id: "benchmark-ai",
    name: "Benchmark AI",
    tier: "specialist",
    category: "Innovation",
    description:
      "Continuously benchmarks MSTC against best-in-class platforms globally.",
    parentId: "gm-innovation",
    provider: "Multi",
    lastAction: "Benchmarked UX against top 3 portals",
  },
  {
    id: "virality-ai",
    name: "Virality AI",
    tier: "specialist",
    category: "Innovation",
    description:
      "Identifies content and features most likely to be shared, and amplifies them.",
    parentId: "gm-innovation",
    provider: "OpenAI",
    lastAction: "Flagged Bopal area guide for amplification",
  },
  {
    id: "csr-impact",
    name: "CSR Impact Agent",
    tier: "specialist",
    category: "Services",
    description:
      "Tracks and reports on the real-world impact of MSTC's CSR and NGO activities.",
    parentId: "gm-services",
    provider: "Claude",
    lastAction: "Compiled quarterly impact data",
  },
  {
    id: "grant-tracker",
    name: "Grant Tracker AI",
    tier: "specialist",
    category: "Services",
    description:
      "Tracks government and corporate grants available for MSTC's NGO activities.",
    parentId: "gm-services",
    provider: "Gemini",
    lastAction: "Found 2 new CSR grant opportunities",
  },
  {
    id: "tourism-planner",
    name: "Tourism Planner AI",
    tier: "specialist",
    category: "Services",
    description:
      "Builds custom Gujarat travel packages based on preferences, budget, and season.",
    parentId: "gm-services",
    provider: "Gemini",
    lastAction: "Created 3 new itinerary templates",
  },
  {
    id: "music-discovery",
    name: "Music Discovery AI",
    tier: "specialist",
    category: "Services",
    description:
      "Discovers and profiles emerging music talent in Gujarat and Ahmedabad.",
    parentId: "gm-services",
    provider: "OpenAI",
    lastAction: "Profiled 2 new classical artists",
  },
  {
    id: "retention-loop",
    name: "Retention Loop AI",
    tier: "specialist",
    category: "Client",
    description:
      "Designs habit-forming features that bring users back to MSTC GLOBAL regularly.",
    parentId: "gm-client",
    provider: "Multi",
    lastAction: "Designed weekly property alert loop",
  },
  // WORKER AGENTS
  {
    id: "listing-completeness",
    name: "Listing Completeness Checker",
    tier: "worker",
    category: "Property",
    description:
      "Audits every property listing for missing fields and data quality issues.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Flagged 3 listings with missing locality data",
  },
  {
    id: "price-anomaly",
    name: "Price Anomaly Detector",
    tier: "worker",
    category: "Property",
    description:
      "Flags listings priced significantly above or below comparable market values.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Detected 1 outlier listing at 40 percent above market",
  },
  {
    id: "duplicate-detector",
    name: "Duplicate Listing Detector",
    tier: "worker",
    category: "Property",
    description:
      "Identifies duplicate or near-duplicate property listings before they go live.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Checked 50 listings - 0 duplicates found",
  },
  {
    id: "enquiry-processor",
    name: "Enquiry Processor Agent",
    tier: "worker",
    category: "Property",
    description:
      "Processes all property enquiries: validates, formats, routes to the right team member.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Processed 12 enquiries in the last hour",
  },
  {
    id: "buyer-prop-matcher",
    name: "Buyer-Property Matcher",
    tier: "worker",
    category: "Property",
    description:
      "Matches each buyer's requirements to the best available listings automatically.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Matched 3 buyers to new listings",
  },
  {
    id: "listing-expiry",
    name: "Listing Expiry Tracker",
    tier: "worker",
    category: "Property",
    description:
      "Tracks listing validity and sends refresh reminders before listings expire.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Sent 2 refresh reminders to property owners",
  },
  {
    id: "price-drop-alert",
    name: "Price Drop Alert Sender",
    tier: "worker",
    category: "Property",
    description:
      "Notifies shortlisted buyers immediately when a watched property drops in price.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Sent 1 price drop alert to 4 shortlisted buyers",
  },
  {
    id: "featured-listing-mgr",
    name: "Featured Listing Manager",
    tier: "worker",
    category: "Property",
    description:
      "Manages rotation and priority of featured property listings on the portal.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Rotated 3 featured listings",
  },
  {
    id: "possession-date-tracker",
    name: "Possession Date Tracker",
    tier: "worker",
    category: "Property",
    description:
      "Tracks upcoming possession dates and sends timely notifications to buyers.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Reminded 3 clients - 30 days to possession",
  },
  {
    id: "emi-calc-agent",
    name: "EMI Calculator Agent",
    tier: "worker",
    category: "Finance",
    description:
      "Provides instant EMI calculations for any loan amount, rate, and tenure combination.",
    parentId: "gm-finance",
    provider: "Platform",
    lastAction: "Calculated EMI for 8 clients today",
  },
  {
    id: "stamp-duty-agent",
    name: "Stamp Duty Calculator Agent",
    tier: "worker",
    category: "Finance",
    description:
      "Calculates exact stamp duty and registration charges for any Gujarat property transaction.",
    parentId: "gm-finance",
    provider: "Platform",
    lastAction: "Calculated stamp duty for 3 deals",
  },
  {
    id: "capital-gains-agent",
    name: "Capital Gains Calculator Agent",
    tier: "worker",
    category: "Finance",
    description:
      "Computes short-term and long-term capital gains tax for any property sale.",
    parentId: "gm-finance",
    provider: "Platform",
    lastAction: "Computed capital gains for property sale",
  },
  {
    id: "rental-yield-agent",
    name: "Rental Yield Calculator Agent",
    tier: "worker",
    category: "Finance",
    description:
      "Instantly calculates gross and net rental yield for any Ahmedabad property.",
    parentId: "gm-finance",
    provider: "Platform",
    lastAction: "Calculated yield for 5 investment queries",
  },
  {
    id: "down-payment-planner",
    name: "Down Payment Planner Agent",
    tier: "worker",
    category: "Finance",
    description:
      "Helps buyers plan and optimize their down payment strategy for home purchase.",
    parentId: "gm-finance",
    provider: "Platform",
    lastAction: "Created down payment plan for first-time buyer",
  },
  {
    id: "joint-loan-agent",
    name: "Joint Loan Eligibility Agent",
    tier: "worker",
    category: "Finance",
    description:
      "Calculates maximum loan eligibility for joint borrower combinations.",
    parentId: "gm-finance",
    provider: "Platform",
    lastAction: "Computed joint eligibility for couple",
  },
  {
    id: "prop-tax-agent",
    name: "Property Tax Calculator Agent",
    tier: "worker",
    category: "Finance",
    description:
      "Calculates exact annual property tax for AMC zone-wise properties.",
    parentId: "gm-finance",
    provider: "Platform",
    lastAction: "Calculated property tax for 4 clients",
  },
  {
    id: "day1-followup",
    name: "Day-1 Follow-Up Agent",
    tier: "worker",
    category: "CRM",
    description:
      "Automatically sends the first follow-up message 24 hours after any new enquiry.",
    parentId: "gm-client",
    provider: "Platform",
    lastAction: "Sent 5 day-1 follow-ups",
  },
  {
    id: "day3-followup",
    name: "Day-3 Follow-Up Agent",
    tier: "worker",
    category: "CRM",
    description:
      "Sends the second follow-up at the 3-day mark if no response received yet.",
    parentId: "gm-client",
    provider: "Platform",
    lastAction: "Sent 3 day-3 follow-ups",
  },
  {
    id: "day7-followup",
    name: "Day-7 Follow-Up Agent",
    tier: "worker",
    category: "CRM",
    description:
      "Final automated follow-up at day 7 before escalating to human agent.",
    parentId: "gm-client",
    provider: "Platform",
    lastAction: "Escalated 1 lead to human agent",
  },
  {
    id: "cold-lead-reengage",
    name: "Cold Lead Re-Engagement Agent",
    tier: "worker",
    category: "CRM",
    description:
      "Re-engages leads that have been silent for 30+ days with fresh property matches.",
    parentId: "gm-client",
    provider: "Platform",
    lastAction: "Re-engaged 4 cold leads with new listings",
  },
  {
    id: "birthday-anniversary",
    name: "Birthday & Anniversary Reminder Agent",
    tier: "worker",
    category: "CRM",
    description:
      "Sends personalized greetings on client birthdays, anniversaries, and possession anniversaries.",
    parentId: "gm-client",
    provider: "Platform",
    lastAction: "Sent 2 birthday greetings today",
  },
  {
    id: "complaint-ticket",
    name: "Complaint Ticket Handler",
    tier: "worker",
    category: "CRM",
    description:
      "Receives, logs, and routes all client complaints to the right resolution team.",
    parentId: "gm-client",
    provider: "Platform",
    lastAction: "0 open complaints in queue",
  },
  {
    id: "satisfaction-survey",
    name: "Satisfaction Survey Agent",
    tier: "worker",
    category: "CRM",
    description:
      "Sends satisfaction surveys 7 days after each major client interaction.",
    parentId: "gm-client",
    provider: "Platform",
    lastAction: "Sent 3 post-interaction surveys",
  },
  {
    id: "doc-expiry-reminder",
    name: "Document Expiry Reminder Agent",
    tier: "worker",
    category: "CRM",
    description:
      "Tracks all document expiry dates (agreements, insurance, registrations) and sends timely reminders.",
    parentId: "gm-client",
    provider: "Platform",
    lastAction: "Reminded 1 client - agreement expires in 15 days",
  },
  {
    id: "blog-writer",
    name: "Blog Post Writer Agent",
    tier: "worker",
    category: "Content",
    description:
      "Continuously writes SEO-optimized blog posts on real estate, finance, and services topics.",
    parentId: "gm-content",
    provider: "OpenAI",
    lastAction: "Published Top 5 localities for 2026 investment",
  },
  {
    id: "faq-builder",
    name: "FAQ Builder Agent",
    tier: "worker",
    category: "Content",
    description:
      "Monitors client questions and continuously builds and updates the FAQ database.",
    parentId: "gm-content",
    provider: "Platform",
    lastAction: "Added 3 new FAQ entries from client queries",
  },
  {
    id: "glossary-updater",
    name: "Glossary Updater Agent",
    tier: "worker",
    category: "Content",
    description:
      "Maintains and expands the real estate glossary with Gujarat-specific terms.",
    parentId: "gm-content",
    provider: "Platform",
    lastAction: "Added 2 new glossary entries",
  },
  {
    id: "market-report",
    name: "Market Report Compiler Agent",
    tier: "worker",
    category: "Content",
    description:
      "Compiles monthly market reports with price trends, transaction data, and insights.",
    parentId: "gm-content",
    provider: "Multi",
    lastAction: "Compiled monthly May 2026 report",
  },
  {
    id: "social-post-gen",
    name: "Social Media Post Generator",
    tier: "worker",
    category: "Content",
    description:
      "Generates platform-optimized social media posts for all MSTC channels.",
    parentId: "gm-content",
    provider: "OpenAI",
    lastAction: "Generated 5 Instagram posts for this week",
  },
  {
    id: "whatsapp-broadcast",
    name: "WhatsApp Broadcast Writer",
    tier: "worker",
    category: "Content",
    description:
      "Drafts targeted WhatsApp broadcast messages for client segments.",
    parentId: "gm-content",
    provider: "OpenAI",
    lastAction: "Drafted Eid property offer broadcast",
  },
  {
    id: "event-budget",
    name: "Event Budget Tracker Agent",
    tier: "worker",
    category: "Services",
    description:
      "Tracks all event budgets, actual vs planned spend, and flags overruns in real time.",
    parentId: "gm-services",
    provider: "Platform",
    lastAction: "Tracked conference budget - 5 percent under target",
  },
  {
    id: "vendor-confirm",
    name: "Vendor Confirmation Agent",
    tier: "worker",
    category: "Services",
    description:
      "Sends confirmation messages and reminders to all event vendors before events.",
    parentId: "gm-services",
    provider: "Platform",
    lastAction: "Confirmed 3 vendors for upcoming event",
  },
  {
    id: "guest-checkin",
    name: "Guest Check-In Agent",
    tier: "worker",
    category: "Services",
    description:
      "Manages digital guest check-in for events: invitations, RSVPs, and onsite check-in.",
    parentId: "gm-services",
    provider: "Platform",
    lastAction: "Set up check-in for 45-person event",
  },
  {
    id: "vol-task-assign",
    name: "Volunteer Task Assigner Agent",
    tier: "worker",
    category: "Services",
    description:
      "Assigns specific tasks to NGO volunteers based on skills and availability.",
    parentId: "gm-services",
    provider: "Platform",
    lastAction: "Assigned roles for weekend cleanliness drive",
  },
  {
    id: "ngo-80g-receipt",
    name: "NGO 80G Receipt Generator",
    tier: "worker",
    category: "Services",
    description:
      "Auto-generates and sends 80G tax exemption receipts to CSR donors.",
    parentId: "gm-services",
    provider: "Platform",
    lastAction: "Generated 2 receipts for recent donations",
  },
  {
    id: "athlete-profile-builder",
    name: "Athlete Profile Builder",
    tier: "worker",
    category: "Services",
    description:
      "Builds and maintains profiles for Gujarat athletes in MSTC's sports portal.",
    parentId: "gm-services",
    provider: "Platform",
    lastAction: "Added 3 new athlete profiles",
  },
  {
    id: "travel-itinerary",
    name: "Travel Itinerary Builder Agent",
    tier: "worker",
    category: "Services",
    description:
      "Builds detailed day-by-day travel itineraries for Gujarat tourism requests.",
    parentId: "gm-services",
    provider: "Gemini",
    lastAction: "Built 3-day Ahmedabad heritage itinerary",
  },
  {
    id: "form-spam-filter",
    name: "Form Spam Filter Agent",
    tier: "worker",
    category: "Security",
    description:
      "Filters spam and bot submissions from all MSTC contact forms.",
    parentId: "gm-security",
    provider: "Platform",
    lastAction: "Filtered 8 spam submissions today",
  },
  {
    id: "bot-detection",
    name: "Bot Detection Agent",
    tier: "worker",
    category: "Security",
    description:
      "Identifies and blocks automated bot traffic to the MSTC platform.",
    parentId: "gm-security",
    provider: "Platform",
    lastAction: "Blocked 3 bot IP addresses today",
  },
  {
    id: "fake-lead-scorer",
    name: "Fake Lead Scorer Agent",
    tier: "worker",
    category: "Security",
    description:
      "Scores every lead for authenticity on a 1-10 scale using behavioral signals.",
    parentId: "gm-security",
    provider: "Platform",
    lastAction: "Scored 12 new leads - 1 flagged as suspicious",
  },
  {
    id: "suspicious-activity",
    name: "Suspicious Activity Logger",
    tier: "worker",
    category: "Security",
    description:
      "Logs and alerts on all suspicious activity patterns across the platform.",
    parentId: "gm-security",
    provider: "Platform",
    lastAction: "Logged 0 suspicious events today",
  },
  {
    id: "admin-login-monitor",
    name: "Admin Login Monitor Agent",
    tier: "worker",
    category: "Security",
    description:
      "Monitors all admin login attempts, flags unusual access patterns.",
    parentId: "gm-security",
    provider: "Platform",
    lastAction: "1 admin login today - verified",
  },
  {
    id: "deal-prob-scorer",
    name: "Deal Probability Scorer",
    tier: "worker",
    category: "Analytics",
    description:
      "Continuously updates close probability scores for all active deals.",
    parentId: "gm-data",
    provider: "Platform",
    lastAction: "Rescored 8 active deals",
  },
  {
    id: "area-intel-briefer",
    name: "Area Intelligence Briefer",
    tier: "worker",
    category: "Analytics",
    description:
      "Generates brief intelligence reports on each of 11 Ahmedabad localities on demand.",
    parentId: "gm-data",
    provider: "Platform",
    lastAction: "Generated Ambli area intelligence brief",
  },
  {
    id: "builder-rep-profiler",
    name: "Builder Reputation Profiler",
    tier: "worker",
    category: "Property",
    description:
      "Tracks and updates reputation scores for all Ahmedabad real estate developers.",
    parentId: "gm-property",
    provider: "Platform",
    lastAction: "Updated 3 builder reputation scores",
  },
  {
    id: "media-mention-monitor",
    name: "Media Mention Monitor",
    tier: "worker",
    category: "Analytics",
    description:
      "Tracks mentions of MSTC GLOBAL across all media channels and web sources.",
    parentId: "gm-data",
    provider: "Platform",
    lastAction: "0 negative media mentions today",
  },
  {
    id: "product-manager-ai",
    name: "Product Manager AI",
    tier: "worker",
    category: "Technology",
    description:
      "Identifies missing features, creates build specifications, and prioritizes the build queue.",
    parentId: "gm-tech",
    provider: "OpenAI",
    lastAction: "Added 3 items to the build backlog",
  },
  {
    id: "micro-builder",
    name: "Micro-Builder Agent",
    tier: "worker",
    category: "Technology",
    description:
      "Handles small platform additions: new calculators, form fields, filters, buttons, sections.",
    parentId: "gm-tech",
    provider: "Platform",
    lastAction: "Added new filter option to property search",
  },
  {
    id: "auto-fixer",
    name: "Auto-Fixer Agent",
    tier: "worker",
    category: "Technology",
    description:
      "Scans the live platform for small bugs and fixes them automatically, logging all fixes.",
    parentId: "gm-tech",
    provider: "Platform",
    lastAction: "Fixed broken WhatsApp link on contact page",
  },
  {
    id: "qa-agent",
    name: "QA Agent",
    tier: "worker",
    category: "Technology",
    description:
      "Tests every change before going live, blocks bad deployments, produces test reports.",
    parentId: "gm-tech",
    provider: "Platform",
    lastAction: "Passed all tests for last build",
  },
  {
    id: "infra-monitor",
    name: "Infrastructure Monitor AI",
    tier: "worker",
    category: "Technology",
    description:
      "Monitors platform health: canister performance, storage usage, and alerts.",
    parentId: "gm-tech",
    provider: "Platform",
    lastAction: "All systems nominal - storage 34 percent used",
  },
  {
    id: "feedback-analysis",
    name: "Feedback Analysis Agent",
    tier: "worker",
    category: "Analytics",
    description:
      "Analyzes all user and client feedback to extract actionable insights.",
    parentId: "gm-data",
    provider: "Platform",
    lastAction: "Analyzed 15 feedback submissions this week",
  },
  {
    id: "data-backup-integrity",
    name: "Data Backup Integrity Agent",
    tier: "worker",
    category: "Security",
    description:
      "Verifies data backup completeness and integrity on a daily schedule.",
    parentId: "gm-security",
    provider: "Platform",
    lastAction: "Daily backup verified - all data intact",
  },
  {
    id: "weekly-market-brief",
    name: "Weekly Market Brief Generator",
    tier: "worker",
    category: "Content",
    description:
      "Auto-generates a professional weekly market brief PDF every Monday morning.",
    parentId: "gm-content",
    provider: "Multi",
    lastAction: "Generated weekly brief for May 19, 2026",
  },
  {
    id: "fundraising-tracker",
    name: "Fundraising Progress Tracker",
    tier: "worker",
    category: "Services",
    description:
      "Tracks NGO fundraising campaigns, donation totals, and milestone progress.",
    parentId: "gm-services",
    provider: "Platform",
    lastAction: "Updated campaign progress - 68 percent of target",
  },
  {
    id: "vol-hours-tracker",
    name: "Volunteer Hours Tracker",
    tier: "worker",
    category: "Services",
    description:
      "Logs and reports volunteer hours for all MSTC NGO activities and events.",
    parentId: "gm-services",
    provider: "Platform",
    lastAction: "Logged 24 volunteer hours this week",
  },
  {
    id: "appointment-scheduler",
    name: "Appointment Scheduling Agent",
    tier: "worker",
    category: "CRM",
    description:
      "Books and manages appointments between clients and MSTC team members.",
    parentId: "gm-client",
    provider: "Platform",
    lastAction: "Scheduled 3 site visits for this week",
  },
  {
    id: "callback-handler",
    name: "Callback Request Handler",
    tier: "worker",
    category: "CRM",
    description:
      "Processes callback requests and routes them to available team members.",
    parentId: "gm-client",
    provider: "Platform",
    lastAction: "Routed 2 callback requests",
  },
  // FALLBACK LAYER
  {
    id: "fallback-openai",
    name: "OpenAI Fallback Provider",
    tier: "fallback",
    category: "Fallback",
    description:
      "Primary external AI fallback using OpenAI GPT-4o, pre-configured with full MSTC context.",
    provider: "OpenAI",
    lastAction: "Standby - primary providers active",
  },
  {
    id: "fallback-gemini",
    name: "Gemini Fallback Provider",
    tier: "fallback",
    category: "Fallback",
    description:
      "Secondary external AI fallback using Google Gemini, auto-activates if OpenAI unavailable.",
    provider: "Gemini",
    lastAction: "Standby - primary providers active",
  },
  {
    id: "fallback-claude",
    name: "Claude Fallback Provider",
    tier: "fallback",
    category: "Fallback",
    description:
      "Tertiary external AI fallback using Anthropic Claude, pre-configured with MSTC knowledge.",
    provider: "Claude",
    lastAction: "Standby - primary providers active",
  },
  {
    id: "fallback-knowledge-brain",
    name: "MSTC Knowledge Brain Fallback",
    tier: "fallback",
    category: "Fallback",
    description:
      "On-platform knowledge base: answers from MSTC's own stored data even when all external APIs are down. Zero downtime guarantee.",
    provider: "Platform",
    lastAction: "Always active - zero downtime layer",
  },
  {
    id: "behavior-mirror",
    name: "Behavior Mirror AI",
    tier: "fallback",
    category: "Fallback",
    description:
      "Trained on same instructions as Caffeine AI Chief Officer - users cannot tell the difference during failover.",
    provider: "Platform",
    lastAction: "Mirroring Caffeine AI behavior - standby",
  },
];

export const SAMPLE_COORDINATION_EVENTS = [
  {
    id: "e1",
    ts: "07:05 IST",
    from: "Daily Briefing AI",
    to: "MSTC Master Intelligence",
    action: "Delivered morning brief",
    result: "MD notified - 3 priority items",
  },
  {
    id: "e2",
    ts: "07:12 IST",
    from: "Lead Scoring ML",
    to: "Lead Management Head AI",
    action: "Scored overnight enquiries",
    result: "3 high-priority leads flagged",
  },
  {
    id: "e3",
    ts: "07:18 IST",
    from: "Cyber Security Command AI",
    to: "GM of Security & Risk",
    action: "Morning threat scan complete",
    result: "All clear - 0 threats",
  },
  {
    id: "e4",
    ts: "07:30 IST",
    from: "Market Intelligence Command AI",
    to: "Property Market Oracle",
    action: "Shared overnight market data",
    result: "Price forecasts updated",
  },
  {
    id: "e5",
    ts: "08:00 IST",
    from: "Content Strategy AI",
    to: "Blog Post Writer Agent",
    action: "Assigned content tasks",
    result: "5 posts queued for the week",
  },
  {
    id: "e6",
    ts: "08:15 IST",
    from: "Buyer Profiler AI",
    to: "Property Alert AI",
    action: "Updated buyer preference profiles",
    result: "7 property alerts triggered",
  },
  {
    id: "e7",
    ts: "08:45 IST",
    from: "Retention Intelligence AI",
    to: "Re-Engagement Sequence AI",
    action: "Identified at-risk clients",
    result: "2 re-engagement sequences started",
  },
  {
    id: "e8",
    ts: "09:00 IST",
    from: "RERA Command AI",
    to: "Litigation Monitor AI",
    action: "RERA compliance check",
    result: "All projects compliant",
  },
  {
    id: "e9",
    ts: "09:30 IST",
    from: "Deal Intelligence AI",
    to: "Day-3 Follow-Up Agent",
    action: "Flagged cold deals",
    result: "3 follow-up sequences activated",
  },
  {
    id: "e10",
    ts: "10:00 IST",
    from: "Feature Suggestion AI",
    to: "Continuous Builder Head AI",
    action: "Submitted weekly feature list",
    result: "2 features approved for build",
  },
  {
    id: "e11",
    ts: "10:30 IST",
    from: "Anomaly Detector ML",
    to: "Price Anomaly Detector",
    action: "Shared price outlier data",
    result: "1 listing flagged for review",
  },
  {
    id: "e12",
    ts: "11:00 IST",
    from: "Client Intelligence AI",
    to: "VIP Client AI",
    action: "Updated HNI client profiles",
    result: "2 VIP briefs refreshed",
  },
  {
    id: "e13",
    ts: "11:30 IST",
    from: "SEO Intelligence AI",
    to: "Area Guide Builder AI",
    action: "Shared keyword opportunities",
    result: "3 area guides scheduled",
  },
  {
    id: "e14",
    ts: "12:00 IST",
    from: "Revenue Intelligence AI",
    to: "Caffeine AI Chief Officer",
    action: "Midday revenue status",
    result: "Pipeline on track - 94 percent of forecast",
  },
  {
    id: "e15",
    ts: "13:00 IST",
    from: "GM of Security & Risk",
    to: "Transaction Security AI",
    action: "Afternoon security sweep",
    result: "0 fraud events",
  },
  {
    id: "e16",
    ts: "14:00 IST",
    from: "Meeting Prep AI",
    to: "Client Communication AI",
    action: "Prepared client briefing",
    result: "Brief ready - 3 talking points",
  },
  {
    id: "e17",
    ts: "14:30 IST",
    from: "Proposal Generator AI",
    to: "Lead Management Head AI",
    action: "Generated 2 client proposals",
    result: "Proposals sent via WhatsApp",
  },
  {
    id: "e18",
    ts: "15:00 IST",
    from: "Performance Optimizer AI",
    to: "Infrastructure Monitor AI",
    action: "Ran performance audit",
    result: "Page load improved 340ms",
  },
  {
    id: "e19",
    ts: "16:00 IST",
    from: "AI Training Agent",
    to: "Lead Scoring ML",
    action: "Processed new feedback data",
    result: "Model accuracy +1.2 percent",
  },
  {
    id: "e20",
    ts: "17:30 IST",
    from: "MSTC Master Intelligence",
    to: "Caffeine AI Chief Officer",
    action: "Evening coordination summary",
    result: "All 369 agents nominal",
  },
];

export const GM_DIGEST_SECTIONS = [
  {
    gm: "GM of Property & Real Estate",
    bullets: [
      "Property Market Oracle updated price forecasts for all 11 Ahmedabad localities based on overnight transaction data.",
      "Deal Intelligence AI flagged 2 deals inactive for 72h+ and triggered follow-up sequences.",
      "Buyer-Property Matcher found new matches for 8 active buyers - property alerts dispatched.",
    ],
  },
  {
    gm: "GM of Business Development",
    bullets: [
      "Lead Scoring ML processed 12 overnight enquiries - 3 marked high priority and routed to senior team.",
      "Smart Assignment AI optimally distributed 5 new leads across available agents.",
      "Proposal Generator AI drafted 2 professional proposals - sent via WhatsApp to warm leads.",
    ],
  },
  {
    gm: "GM of Technology & Platform",
    bullets: [
      "Micro-Builder Agent added 1 new filter option to the property portal search flow.",
      "Auto-Fixer Agent corrected a broken WhatsApp redirect link discovered via automated scan.",
      "Performance Optimizer AI improved average page load by 340ms via image optimization.",
    ],
  },
  {
    gm: "GM of Finance & Compliance",
    bullets: [
      "RERA Command AI verified all active projects are compliant - no deadline overruns.",
      "Tax Optimization AI identified savings in stamp duty for a client transaction.",
      "Loan Intelligence AI compared home loan rates across 8 banks for a new client enquiry.",
    ],
  },
  {
    gm: "GM of Content & Intelligence",
    bullets: [
      "Blog Post Writer Agent published Top 5 Ahmedabad localities for 2026 investment.",
      "Area Guide Builder AI updated the Bopal guide with new metro extension information.",
      "Newsletter Intelligence AI sent weekly digest to 247 subscribers - 38 percent open rate.",
    ],
  },
  {
    gm: "GM of Client Relations",
    bullets: [
      "Retention Intelligence AI triggered sequences for 2 at-risk clients showing disengagement signals.",
      "Birthday & Anniversary Reminder Agent sent personalized greetings to 2 clients today.",
      "Complaint Resolution AI maintained 0 open complaints - all queries resolved within SLA.",
    ],
  },
  {
    gm: "GM of Services",
    bullets: [
      "Events Command AI completed checklist review for upcoming corporate event (45 attendees).",
      "Cultural Calendar AI updated the Navratri 2026 events calendar with 12 new entries.",
      "Tourism Intelligence AI created 3 new Gujarat heritage travel itineraries for summer season.",
    ],
  },
  {
    gm: "GM of Security & Risk",
    bullets: [
      "Cyber Security Command AI completed morning threat scan - all 1,240 feeds clear.",
      "Form Spam Filter Agent blocked 8 spam submissions from the contact form.",
      "Bot Detection Agent identified and blocked 3 malicious IP addresses attempting repeated access.",
    ],
  },
  {
    gm: "GM of Data & Research",
    bullets: [
      "Predictive Intelligence AI forecast Q3 enquiry volume at +18 percent above Q2.",
      "Competitive Intelligence Command AI monitored 5 competitor sites - no major changes detected.",
      "Geospatial Intelligence AI updated property heat map with all 1051+ active listings.",
    ],
  },
  {
    gm: "GM of People & Innovation",
    bullets: [
      "Feature Suggestion AI generated 8 new feature ideas - 2 approved for immediate build queue.",
      "AI Training Agent processed 34 feedback items - lead scoring model accuracy improved 1.2 percent.",
      "Technology Upgrade AI evaluated a new property valuation API as potential platform upgrade.",
    ],
  },
];
