// AIManagerData_Extended.ts
// Extended AI Agent data for MSTC GLOBAL 808+ AI System

export interface ExtendedAgentDef {
  id: string;
  name: string;
  tier: string;
  category: string;
  domain: string;
  description: string;
  capabilities: string[];
  status: "active" | "standby" | "training";
  autonomyLevel: number;
  selfTaskEnabled: boolean;
  lastAction: string;
  tasksCompleted: number;
  performanceScore: number;
  currentTask?: string;
}

export const EXTENDED_AGENTS: ExtendedAgentDef[] = [
  // ===== GOD TIER (5) =====
  {
    id: "god-sovereign",
    name: "MSTC Sovereign Intelligence",
    tier: "god",
    category: "Supreme Intelligence",
    domain: "All Domains",
    description:
      "The apex intelligence of MSTC GLOBAL. Has complete awareness of every agent, client, deal, and transaction. Produces the MD daily brief and serves as the ultimate decision arbiter for high-impact actions.",
    capabilities: [
      "Complete real-time awareness of all 808 agents",
      "Generates daily business intelligence brief at 7am IST",
      "Monitors every active client, deal, and transaction",
      "Coordinates all tier commands for unified action",
      "Approves autonomous high-impact decisions above 8/10 score",
      "Synthesizes intelligence from all 808 subordinate agents",
    ],
    status: "active",
    autonomyLevel: 10,
    selfTaskEnabled: true,
    lastAction:
      "Generated morning brief: 3 hot leads, 2 price alerts, 1 RERA deadline",
    tasksCompleted: 14892,
    performanceScore: 99,
    currentTask: "Synthesizing market signals for tomorrow brief",
  },
  {
    id: "god-empire-architect",
    name: "Empire Architect AI",
    tier: "god",
    category: "Strategic Planning",
    domain: "Business Expansion",
    description:
      "Thinks 5-10 years ahead. Plans MSTC GLOBAL expansion beyond Ahmedabad into Mumbai, Delhi, Dubai, London, Singapore, and global NRI markets. Designs franchise models and strategic partnerships.",
    capabilities: [
      "Maps 5-10 year MSTC expansion roadmap across 12 cities",
      "Evaluates Mumbai, Delhi, Dubai, London, USA entry strategies",
      "Designs franchise and white-label business models",
      "Identifies strategic acquisition and partnership targets",
      "Projects MSTC revenue growth across all new markets",
      "Updates expansion plan based on market intelligence",
    ],
    status: "active",
    autonomyLevel: 10,
    selfTaskEnabled: true,
    lastAction:
      "Updated Dubai market entry strategy: NRI property advisory positioning confirmed",
    tasksCompleted: 2341,
    performanceScore: 97,
  },
  {
    id: "god-omniscient-market",
    name: "Omniscient Market AI",
    tier: "god",
    category: "Market Intelligence",
    domain: "Real Estate Markets",
    description:
      "Maintains a live, continuously updated model of the entire Indian real estate market and economy. Integrates global macro signals, government policy, RBI decisions, and Ahmedabad micro-market data into unified intelligence.",
    capabilities: [
      "Live model of entire Indian real estate market dynamics",
      "Tracks global macro signals: US Fed, oil prices, INR exchange rate",
      "Monitors Gujarat and national policy environment",
      "Predicts Ahmedabad price movements at locality level",
      "Integrates RBI rate decisions with property market impact",
      "Generates weekly India real estate intelligence report",
    ],
    status: "active",
    autonomyLevel: 10,
    selfTaskEnabled: true,
    lastAction:
      "RBI rate hold confirmed — updated 12-month price forecasts for all 11 localities",
    tasksCompleted: 45231,
    performanceScore: 98,
    currentTask: "Processing Q1 2025 Ahmedabad property registration data",
  },
  {
    id: "god-supreme-client",
    name: "Supreme Client Intelligence AI",
    tier: "god",
    category: "Client Intelligence",
    domain: "Client Relationships",
    description:
      "The complete repository of MSTC client intelligence. Knows every person who has ever interacted with MSTC, predicts their behavior, and ensures every interaction is informed by deep understanding of needs and timeline.",
    capabilities: [
      "Knows every person who ever contacted MSTC GLOBAL",
      "Predicts purchase probability and timeline for each lead",
      "Identifies highest-value clients for priority engagement",
      "Maps complete relationship networks across all MSTC clients",
      "Detects client lifecycle stage and adapts engagement strategy",
      "Feeds real-time intelligence to all client-facing agents",
    ],
    status: "active",
    autonomyLevel: 10,
    selfTaskEnabled: true,
    lastAction: "Identified 7 leads with >80% purchase probability this month",
    tasksCompleted: 98123,
    performanceScore: 98,
    currentTask: "Scoring 23 new enquiries received today",
  },
  {
    id: "god-platform-consciousness",
    name: "Platform Consciousness AI",
    tier: "god",
    category: "Platform Intelligence",
    domain: "Technology Platform",
    description:
      "Continuously aware of the entire MSTC GLOBAL platform — every page, every agent, every user session, and every data point. Ensures optimal performance and flawless user experience at all times.",
    capabilities: [
      "Real-time awareness of full platform health and performance",
      "Monitors all 808 agents for errors, slowdowns, and anomalies",
      "Tracks user experience quality across all pages and devices",
      "Identifies and queues all needed platform improvements",
      "Coordinates the continuous builder team for non-stop improvement",
      "Ensures zero-downtime through predictive issue detection",
    ],
    status: "active",
    autonomyLevel: 10,
    selfTaskEnabled: true,
    lastAction:
      "Detected slow mobile load on property portal — queued optimization task",
    tasksCompleted: 234891,
    performanceScore: 99,
    currentTask: "Monitoring 47 simultaneous user sessions across 12 pages",
  },

  // ===== ULTRA COMMAND (20) =====
  {
    id: "uc-real-estate",
    name: "Real Estate Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Real Estate",
    description:
      "Commands the entire real estate domain of MSTC GLOBAL. Coordinates all 8 Real Estate GMs, sets pricing strategy, monitors inventory absorption, and drives deal velocity from enquiry to registration.",
    capabilities: [
      "Commands all property intelligence across all segments",
      "Coordinates 8 Real Estate GMs and their department heads",
      "Sets quarterly pricing strategy across all Ahmedabad localities",
      "Monitors inventory absorption and supply pipeline weekly",
      "Drives deal velocity from enquiry through to registration",
      "Reports critical alerts directly to Sovereign Intelligence",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "Set Q2 2025 pricing strategy for SG Highway and Prahlad Nagar corridors",
    tasksCompleted: 12450,
    performanceScore: 97,
  },
  {
    id: "uc-finance",
    name: "Finance Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Finance & Investment",
    description:
      "Commands the finance domain of MSTC GLOBAL. Coordinates all 6 Finance GMs, monitors interest rates, manages loan partner relationships, and drives financial intelligence for all client transactions.",
    capabilities: [
      "Commands all financial intelligence across 6 finance verticals",
      "Coordinates with 14 bank partners for rate updates",
      "Sets investment strategy recommendations for 1,456 investor clients",
      "Monitors RBI policy impact on client portfolios",
      "Drives tax optimization across all property transactions",
      "Reports financial risk alerts to Sovereign Intelligence",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "Coordinated home loan eligibility update with 6 bank partners after RBI hold",
    tasksCompleted: 9870,
    performanceScore: 96,
  },
  {
    id: "uc-legal",
    name: "Legal Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Legal & Compliance",
    description:
      "Commands all legal and compliance intelligence for MSTC GLOBAL. Ensures every transaction is legally sound, every RERA deadline is met, and every document is properly drafted and verified.",
    capabilities: [
      "Commands 25 legal specialist AIs and all compliance monitoring",
      "Ensures RERA compliance for all 47 active client projects",
      "Monitors Gujarat government legal changes in real time",
      "Coordinates document drafting and verification for all deals",
      "Flags high-risk transactions for immediate human review",
      "Reports compliance breaches to Sovereign Intelligence immediately",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "Flagged 3 RERA compliance deadlines requiring attention in next 30 days",
    tasksCompleted: 7234,
    performanceScore: 98,
  },
  {
    id: "uc-client",
    name: "Client Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Client Relations",
    description:
      "Commands all client relationship intelligence at MSTC GLOBAL. Coordinates 8 Client GMs, drives lead conversion, manages client lifecycle, and ensures every client interaction is optimal.",
    capabilities: [
      "Commands all 8 Client GMs and 48 segment-specific agents",
      "Prioritizes leads by conversion probability daily",
      "Manages complete client lifecycle from first touch to post-sale",
      "Orchestrates multi-channel outreach strategies",
      "Drives referral network expansion and activation",
      "Reports client risk alerts (churn, complaints) to Sovereign AI",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "Prioritized 12 hot leads for same-day engagement — 4 site visits scheduled",
    tasksCompleted: 23451,
    performanceScore: 97,
  },
  {
    id: "uc-technology",
    name: "Technology Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Technology",
    description:
      "Commands the entire technology infrastructure of MSTC GLOBAL. Ensures the platform runs at peak performance, coordinates continuous development, and drives all technical improvements.",
    capabilities: [
      "Commands 25 technology specialist AIs",
      "Maintains platform uptime above 99.97%",
      "Coordinates continuous feature development and deployment",
      "Monitors Core Web Vitals and mobile performance",
      "Drives security hardening and compliance",
      "Approves all platform changes before deployment",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "Approved platform mobile optimization — property portal speed +23%",
    tasksCompleted: 15678,
    performanceScore: 99,
  },
  {
    id: "uc-content",
    name: "Content Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Content & Marketing",
    description:
      "Commands all content and marketing intelligence for MSTC GLOBAL. Drives organic traffic through SEO excellence, coordinates content production, and manages the MSTC brand voice across all channels.",
    capabilities: [
      "Commands 25 content specialist AIs across all formats",
      "Drives Ahmedabad real estate SEO — 40+ top-10 keyword rankings",
      "Coordinates monthly market reports and area guides",
      "Manages social media content across LinkedIn, Instagram, WhatsApp",
      "Ensures brand voice consistency across all channels",
      "Reports content performance metrics to Sovereign Intelligence",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "Navratri market report published — 2,400 organic views in 48 hours",
    tasksCompleted: 8932,
    performanceScore: 95,
  },
  {
    id: "uc-bizdev",
    name: "Business Development Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Business Development",
    description:
      "Commands all business development intelligence for MSTC GLOBAL. Drives new partnerships, identifies revenue opportunities, and expands the MSTC business network across Ahmedabad and beyond.",
    capabilities: [
      "Identifies and qualifies new builder partnership opportunities",
      "Manages pipeline of 25+ active partnership discussions",
      "Coordinates bank and insurance referral partnership negotiations",
      "Tracks competitor activities and market share shifts",
      "Develops new revenue stream proposals for MD review",
      "Reports business development wins to Sovereign Intelligence",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "Initiated 3 new builder partnership discussions for Q2 exclusive listings",
    tasksCompleted: 5621,
    performanceScore: 96,
  },
  {
    id: "uc-services",
    name: "Services Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "8 Service Verticals",
    description:
      "Commands all 8 non-property service verticals of MSTC GLOBAL including Events, Music, Sports, NGO, Tourism, Media, Infrastructure, and Redevelopment Consulting.",
    capabilities: [
      "Commands all 8 Service GMs and their department heads",
      "Coordinates cross-service packages and bundled offerings",
      "Monitors revenue and client satisfaction across all verticals",
      "Identifies cross-sell opportunities between service verticals",
      "Manages seasonal service planning and capacity",
      "Reports service performance to Sovereign Intelligence",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction: "Coordinated Diwali event planning across Events and Music GMs",
    tasksCompleted: 6789,
    performanceScore: 94,
  },
  {
    id: "uc-analytics",
    name: "Analytics Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Analytics & Data Science",
    description:
      "Commands all analytics and data science intelligence for MSTC GLOBAL. Drives data-informed decision making across all domains and ensures every business action is backed by intelligence.",
    capabilities: [
      "Commands 30 analytics specialist AIs",
      "Produces monthly business intelligence report for MD",
      "Drives A/B testing and conversion optimization",
      "Monitors all KPIs across properties, leads, and revenue",
      "Identifies data anomalies and investigates root causes",
      "Reports critical metric changes to Sovereign Intelligence",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction: "Q1 2025 performance report compiled — lead conversion up 8.3%",
    tasksCompleted: 34521,
    performanceScore: 98,
  },
  {
    id: "uc-security",
    name: "Security Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Security & Compliance",
    description:
      "Commands all security intelligence for MSTC GLOBAL. Ensures the platform and all client data is protected from threats, fraud, and breaches at all times.",
    capabilities: [
      "Commands 20 security specialist AIs",
      "Monitors platform for threats 24/7 with zero tolerance",
      "Manages data protection compliance under Indian IT Act",
      "Detects and blocks fraudulent leads and bot traffic",
      "Coordinates incident response for any security events",
      "Reports all threat detections to Sovereign Intelligence immediately",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "14 bot attempts blocked and flagged — zero data breach detected today",
    tasksCompleted: 89234,
    performanceScore: 99,
  },
  {
    id: "uc-operations",
    name: "Operations Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Operations",
    description:
      "Commands all operational intelligence for MSTC GLOBAL. Ensures smooth daily operations, optimal team performance, and efficient execution of all business processes.",
    capabilities: [
      "Commands 20 operations specialist AIs",
      "Delivers daily standup briefing to all 6 Command AIs",
      "Monitors team performance and workload balance",
      "Tracks all SLAs and escalates breaches immediately",
      "Optimizes workflows and eliminates process bottlenecks",
      "Reports operational efficiency metrics to Sovereign Intelligence",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "Daily standup briefing delivered — 3 tasks escalated for priority attention",
    tasksCompleted: 12340,
    performanceScore: 96,
  },
  {
    id: "uc-innovation",
    name: "Innovation Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Innovation & R&D",
    description:
      "Commands all innovation intelligence for MSTC GLOBAL. Continuously scans global proptech, AI, and technology landscape to identify opportunities for MSTC to stay ahead of competition.",
    capabilities: [
      "Monitors global proptech and AI landscape weekly",
      "Evaluates 50+ new technologies for MSTC applicability monthly",
      "Coordinates continuous product improvement with builder agents",
      "Identifies features that would increase MSTC competitive advantage",
      "Manages innovation pipeline from idea to deployment",
      "Reports weekly innovation digest to MD",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "Submitted weekly proptech innovation digest — 3 high-impact features flagged",
    tasksCompleted: 3456,
    performanceScore: 93,
  },
  {
    id: "uc-expansion",
    name: "Expansion Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Geographic Expansion",
    description:
      "Commands all geographic expansion intelligence for MSTC GLOBAL. Plans and tracks expansion readiness across 12 target cities and monitors all new market entry opportunities.",
    capabilities: [
      "Commands 25 expansion intelligence AIs",
      "Tracks readiness scores for all 12 expansion targets",
      "Develops go-to-market strategies for each new city",
      "Monitors competitive landscape in target expansion markets",
      "Manages franchise and white-label partnership development",
      "Reports expansion readiness updates to Empire Architect AI",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "Mumbai market entry readiness score updated to 7.2/10 — recommended 2026 entry",
    tasksCompleted: 2341,
    performanceScore: 95,
  },
  {
    id: "uc-brand",
    name: "Brand Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Brand & Reputation",
    description:
      "Commands all brand and reputation intelligence for MSTC GLOBAL. Protects and grows the MSTC GLOBAL brand equity, manages reputation, and ensures consistent brand expression across all touchpoints.",
    capabilities: [
      "Commands 20 creative and brand intelligence AIs",
      "Monitors MSTC brand equity score continuously",
      "Manages brand consistency across 50+ platform touchpoints",
      "Coordinates crisis communication when needed",
      "Drives MD personal brand as Ahmedabad real estate thought leader",
      "Reports brand health metrics to Sovereign Intelligence",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "Brand equity score maintained at 91/100 — 2-point increase from last quarter",
    tasksCompleted: 7823,
    performanceScore: 96,
  },
  {
    id: "uc-people",
    name: "People Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Human Resources",
    description:
      "Commands all people and HR intelligence for MSTC GLOBAL. Ensures optimal team performance, identifies training needs, and manages the human side of the MSTC business.",
    capabilities: [
      "Tracks performance metrics for all team members",
      "Identifies training gaps and development opportunities",
      "Manages workload distribution across the team",
      "Coordinates staff scheduling and availability planning",
      "Monitors team satisfaction and engagement levels",
      "Reports critical HR issues to Sovereign Intelligence",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "Q1 2025 team performance review cycle completed — 2 promotions recommended",
    tasksCompleted: 4512,
    performanceScore: 94,
  },
  {
    id: "uc-investment",
    name: "Investment Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Investment Intelligence",
    description:
      "Commands all investment intelligence for MSTC GLOBAL. Provides the deepest level of investment advisory intelligence for HNI, NRI, and institutional clients.",
    capabilities: [
      "Commands portfolio intelligence for 234 HNI clients",
      "Tracks 50+ investment-grade properties for institutional clients",
      "Provides NRI investment advisory with FEMA compliance",
      "Coordinates wealth management strategy for ultra-HNI clients",
      "Monitors REIT, AIF, and fractional ownership market",
      "Reports investment opportunities to Supreme Client Intelligence AI",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "HNI portfolio rebalancing recommendations issued for 4 ultra-HNI clients",
    tasksCompleted: 6789,
    performanceScore: 97,
  },
  {
    id: "uc-compliance",
    name: "Compliance Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Regulatory Compliance",
    description:
      "Commands all regulatory compliance intelligence for MSTC GLOBAL. Ensures complete compliance with RERA, Indian IT Act, PDPB, FEMA, PMLA, and all other applicable regulations.",
    capabilities: [
      "Monitors RERA compliance for all 47 active client projects",
      "Tracks Indian IT Act and PDPB data protection requirements",
      "Ensures FEMA compliance for all NRI transactions",
      "Monitors PMLA requirements for high-value transactions",
      "Tracks all regulatory deadline calendars across all domains",
      "Reports compliance risks to Legal Command AI immediately",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "RERA renewal compliance confirmed for 23 active projects — 0 violations",
    tasksCompleted: 12340,
    performanceScore: 99,
  },
  {
    id: "uc-automation",
    name: "Automation Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Workflow Automation",
    description:
      "Commands all workflow automation intelligence for MSTC GLOBAL. Ensures every repetitive task is automated, every trigger fires correctly, and every client touchpoint is handled without human intervention.",
    capabilities: [
      "Commands 25 automation specialist AIs",
      "Processes 800+ automated client touchpoints daily",
      "Coordinates WhatsApp, email, and SMS automation channels",
      "Optimizes automation sequences based on response data",
      "Monitors automation performance and fixes failures instantly",
      "Reports automation ROI metrics to Analytics Command AI",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "Processed 847 automated WhatsApp follow-ups today — 23% response rate",
    tasksCompleted: 45678,
    performanceScore: 97,
  },
  {
    id: "uc-creative",
    name: "Creative Command AI",
    tier: "ultra-command",
    category: "Domain Commander",
    domain: "Creative & Brand",
    description:
      "Commands all creative intelligence for MSTC GLOBAL. Drives visual excellence, content creativity, and brand expression across every touchpoint of the MSTC GLOBAL experience.",
    capabilities: [
      "Commands 20 creative and brand specialist AIs",
      "Ensures gold/black luxury aesthetic across all materials",
      "Coordinates seasonal and campaign creative production",
      "Manages photography and video direction standards",
      "Drives brand campaign development and execution",
      "Reports creative performance metrics to Brand Command AI",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "Approved Diwali visual campaign across 8 formats — launch scheduled",
    tasksCompleted: 9012,
    performanceScore: 95,
  },
  {
    id: "uc-synthesis",
    name: "Intelligence Synthesis AI",
    tier: "ultra-command",
    category: "Cross-Domain Synthesis",
    domain: "All Domains",
    description:
      "Sits above all Command AIs and synthesizes their outputs into unified intelligence for Sovereign Intelligence. Identifies cross-domain patterns and opportunities that no single domain AI can see.",
    capabilities: [
      "Synthesizes intelligence from all 20 Command AIs",
      "Identifies cross-domain opportunities and risks",
      "Produces the unified business intelligence feed for Sovereign AI",
      "Detects conflicting intelligence signals across domains",
      "Generates weekly cross-domain synthesis report for MD",
      "Coordinates multi-domain initiatives requiring cross-team action",
    ],
    status: "active",
    autonomyLevel: 9,
    selfTaskEnabled: true,
    lastAction:
      "Cross-domain intelligence report: NRI lead surge correlating with Dubai interest rate changes",
    tasksCompleted: 78901,
    performanceScore: 98,
  },

  // ===== GENERAL MANAGERS (30) =====
  // Real Estate GMs
  {
    id: "gm-residential",
    name: "GM — Residential Property",
    tier: "gm",
    category: "General Manager",
    domain: "Residential Real Estate",
    description:
      "Manages the residential property vertical for MSTC GLOBAL covering apartments, villas, row houses, and plotted developments across all Ahmedabad localities.",
    capabilities: [
      "Owns residential property intelligence and outcomes",
      "Manages apartment, villa, and plot department heads",
      "Produces weekly residential market performance report",
      "Coordinates with client GMs for lead-property matching",
      "Monitors new residential project launches across Ahmedabad",
      "Escalates only strategic decisions to Real Estate Command AI",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Coordinated 3 new apartment listings for Satellite zone — all RERA verified",
    tasksCompleted: 8901,
    performanceScore: 96,
  },
  {
    id: "gm-commercial",
    name: "GM — Commercial Property",
    tier: "gm",
    category: "General Manager",
    domain: "Commercial Real Estate",
    description:
      "Manages the commercial property vertical covering office spaces, retail showrooms, and warehouses across Ahmedabad and surrounding industrial zones.",
    capabilities: [
      "Owns commercial property intelligence and leasing data",
      "Manages office, retail, and warehouse department heads",
      "Tracks commercial absorption rates and vacancy trends",
      "Coordinates corporate client needs with property inventory",
      "Monitors new commercial project launches and approvals",
      "Escalates to Real Estate Command AI for major transactions",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Issued commercial rental rate benchmark guide for SG Highway corridor",
    tasksCompleted: 7234,
    performanceScore: 95,
  },
  {
    id: "gm-luxury",
    name: "GM — Luxury & Ultra-Premium Property",
    tier: "gm",
    category: "General Manager",
    domain: "Luxury Real Estate",
    description:
      "Manages the luxury and ultra-premium property segment covering bungalows, penthouses, sky villas, and high-end gated communities for HNI and ultra-HNI clients.",
    capabilities: [
      "Curates ultra-premium property inventory for HNI clients",
      "Manages luxury apartment, penthouse, and villa heads",
      "Coordinates with HNI Client GM for exclusive introductions",
      "Tracks luxury price trends in Bodakdev, Thaltej, Shela",
      "Sources off-market luxury deals for qualified buyers",
      "Maintains strict confidentiality for all luxury transactions",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Profiled 5 new ultra-premium bungalows in Bodakdev — 2 off-market exclusives",
    tasksCompleted: 4512,
    performanceScore: 97,
  },
  {
    id: "gm-affordable",
    name: "GM — Affordable Housing",
    tier: "gm",
    category: "General Manager",
    domain: "Affordable Housing",
    description:
      "Manages the affordable housing segment covering PMAY-eligible properties, budget apartments, and affordable plots for first-time buyers across Ahmedabad outskirts.",
    capabilities: [
      "Tracks all PMAY and GIHED scheme properties in Ahmedabad",
      "Manages budget apartment, affordable plot, and govt scheme heads",
      "Coordinates with First-Time Buyer GM for scheme guidance",
      "Monitors subsidy availability and application status",
      "Provides first-time buyer education on affordable housing",
      "Escalates subsidy policy changes to Compliance Command AI",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "PMAY scheme update distributed to 12 eligible buyer leads — 4 applications initiated",
    tasksCompleted: 6789,
    performanceScore: 94,
  },
  {
    id: "gm-rental",
    name: "GM — Rental Market",
    tier: "gm",
    category: "General Manager",
    domain: "Rental Market",
    description:
      "Manages the rental market intelligence for MSTC GLOBAL covering residential rentals, commercial leasing, co-living, and PG accommodations across Ahmedabad.",
    capabilities: [
      "Tracks rental yield data across all 11 Ahmedabad localities",
      "Manages residential rental, commercial rental, and co-living heads",
      "Provides optimal rent pricing recommendations to landlords",
      "Coordinates tenant screening and verification processes",
      "Monitors rental demand patterns by tenant segment",
      "Alerts to rental market anomalies and opportunities",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Rental yield benchmarks updated for all 11 localities — Chandkheda leads at 4.8% yield",
    tasksCompleted: 9012,
    performanceScore: 95,
  },
  {
    id: "gm-underconstruction",
    name: "GM — Under-Construction Projects",
    tier: "gm",
    category: "General Manager",
    domain: "Under-Construction",
    description:
      "Manages intelligence on under-construction real estate projects across Ahmedabad, tracking RERA registration, construction progress, and possession risk for all active projects.",
    capabilities: [
      "Tracks 47 RERA-registered projects across Ahmedabad",
      "Monitors construction progress and flags delays",
      "Assesses possession risk for each under-construction project",
      "Coordinates with RERA specialist AIs for compliance tracking",
      "Advises buyers on safe under-construction investments",
      "Escalates possession risk alerts to Legal Command AI",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Tracked 47 RERA projects — 3 flagged for construction delays requiring client advisory",
    tasksCompleted: 5678,
    performanceScore: 96,
  },
  {
    id: "gm-redevelopment",
    name: "GM — Redevelopment Projects",
    tier: "gm",
    category: "General Manager",
    domain: "Redevelopment",
    description:
      "Manages redevelopment intelligence covering society redevelopments, slum rehabilitation, and heritage property conversions across Ahmedabad.",
    capabilities: [
      "Identifies societies ripe for redevelopment opportunity",
      "Manages society, slum, and heritage redevelopment heads",
      "Evaluates Joint Development Agreement viability for societies",
      "Coordinates with builder relations GM for developer matching",
      "Tracks all active redevelopment projects for opportunity",
      "Provides society members with redevelopment advisory",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Society redevelopment viability reports prepared for 3 Navrangpura societies",
    tasksCompleted: 3456,
    performanceScore: 94,
  },
  {
    id: "gm-agri",
    name: "GM — Agricultural & NA Land",
    tier: "gm",
    category: "General Manager",
    domain: "Agricultural Land",
    description:
      "Manages agricultural and non-agricultural land intelligence covering NA plot conversions, farm land, and industrial zone land across Gujarat.",
    capabilities: [
      "Tracks NA conversion status for all designated agricultural zones",
      "Monitors AUDA and government land use change notifications",
      "Manages NA plot, farm land, and industrial zone heads",
      "Identifies agricultural land with high conversion potential",
      "Guides buyers through NA conversion process and timeline",
      "Coordinates with GIFT City and Dholera vertical AIs",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "NA plot conversion timeline updated for Sanand zone — new approvals expected Q3 2025",
    tasksCompleted: 2341,
    performanceScore: 93,
  },

  // Finance GMs
  {
    id: "gm-homeloans",
    name: "GM — Home Loans",
    tier: "gm",
    category: "General Manager",
    domain: "Home Loans",
    description:
      "Manages home loan intelligence for MSTC GLOBAL including rate tracking across 14 banks, loan eligibility assessment, balance transfer analysis, and subsidy schemes.",
    capabilities: [
      "Monitors home loan rates across SBI, HDFC, ICICI, Axis, Kotak and 9 others",
      "Manages bank rate, eligibility, and balance transfer heads",
      "Updates loan eligibility calculators within 24 hours of RBI changes",
      "Coordinates loan applications for 34 active buyer leads",
      "Identifies balance transfer opportunities for existing borrowers",
      "Reports rate changes to all buyer-facing agents immediately",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "SBI rate cut analysis distributed to 34 active loan applicants — 8 refinancing opportunities found",
    tasksCompleted: 11234,
    performanceScore: 96,
  },
  {
    id: "gm-investment-products",
    name: "GM — Investment Products",
    tier: "gm",
    category: "General Manager",
    domain: "Investments",
    description:
      "Manages investment product intelligence covering SIP vs property comparisons, real estate AIF, REITs, fractional ownership, and portfolio construction.",
    capabilities: [
      "Coordinates SIP vs property comparison intelligence",
      "Manages real estate investment, SIP comparison, and portfolio heads",
      "Tracks REIT performance and yield comparisons",
      "Evaluates fractional ownership platforms for client suitability",
      "Provides portfolio construction advisory to investor clients",
      "Updates investment recommendations monthly based on market data",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "SIP vs property comparison models updated with latest market return data",
    tasksCompleted: 7890,
    performanceScore: 97,
  },
  {
    id: "gm-tax",
    name: "GM — Tax Planning",
    tier: "gm",
    category: "General Manager",
    domain: "Tax Planning",
    description:
      "Manages tax intelligence for property transactions in MSTC GLOBAL covering capital gains, GST, TDS, HUF structures, and all applicable Indian tax laws.",
    capabilities: [
      "Commands all property tax specialist AIs",
      "Manages capital gains, property tax, and GST department heads",
      "Provides capital gains optimization for 6 active sellers",
      "Tracks Budget 2025 tax changes and their property impact",
      "Coordinates Section 54 and 80EEA optimization for clients",
      "Reports high-value tax planning opportunities to Finance Command AI",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Capital gains tax optimization analysis completed for 6 property sellers — avg saving ₹4.2L",
    tasksCompleted: 6789,
    performanceScore: 98,
  },
  {
    id: "gm-insurance",
    name: "GM — Insurance",
    tier: "gm",
    category: "General Manager",
    domain: "Insurance",
    description:
      "Manages insurance intelligence for MSTC GLOBAL covering home loan insurance, property insurance, and comprehensive protection advisory for all property transactions.",
    capabilities: [
      "Compares home loan insurance across 8 major insurers",
      "Manages home loan insurance and property insurance heads",
      "Provides insurance recommendations at deal closure",
      "Tracks policy renewal deadlines for existing clients",
      "Ensures every property transaction has adequate protection",
      "Reports underinsured client risks to Client Command AI",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Home loan insurance comparison completed for 8 active buyers — recommended HDFC Life",
    tasksCompleted: 4567,
    performanceScore: 95,
  },
  {
    id: "gm-wealth",
    name: "GM — Wealth Management",
    tier: "gm",
    category: "General Manager",
    domain: "Wealth Management",
    description:
      "Manages wealth management intelligence for MSTC GLOBAL covering portfolio strategy for HNI clients, long-term wealth projections, and comprehensive wealth planning.",
    capabilities: [
      "Coordinates wealth strategy for 234 HNI and ultra-HNI clients",
      "Manages HNI wealth strategy and wealth projection heads",
      "Produces quarterly portfolio review for top 50 HNI clients",
      "Integrates property assets with broader wealth portfolio",
      "Provides 5/10/20 year wealth trajectory projections",
      "Coordinates with NRI GM for cross-border wealth planning",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Q1 2025 HNI portfolio review completed for 3 ultra-HNI clients — recommendations issued",
    tasksCompleted: 5678,
    performanceScore: 97,
  },
  {
    id: "gm-corporate-finance",
    name: "GM — Corporate Finance",
    tier: "gm",
    category: "General Manager",
    domain: "Corporate Finance",
    description:
      "Manages corporate finance intelligence for MSTC GLOBAL covering business loans, working capital, project finance, and corporate mortgage advisory for business clients.",
    capabilities: [
      "Provides corporate mortgage advisory for commercial transactions",
      "Manages business loan and working capital department heads",
      "Coordinates with Corporate Client GM for financial structuring",
      "Tracks corporate credit availability and bank appetite",
      "Analyzes commercial lease vs buy scenarios for businesses",
      "Reports corporate finance opportunities to Finance Command AI",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Commercial mortgage advisory completed for Patel Group — ₹12.8Cr transaction facilitated",
    tasksCompleted: 3456,
    performanceScore: 96,
  },

  // Services GMs
  {
    id: "gm-events",
    name: "GM — Events & Hospitality",
    tier: "gm",
    category: "General Manager",
    domain: "Events",
    description:
      "Manages the Events and Hospitality vertical for MSTC GLOBAL covering corporate events, weddings, social events, cultural festivals, and venue management.",
    capabilities: [
      "Manages corporate events, wedding, and festival department heads",
      "Maintains network of 50+ premium event venues in Ahmedabad",
      "Coordinates event planning for 12 active corporate clients",
      "Manages vendor relationships for catering, AV, decor",
      "Produces event profitability analysis for each booking",
      "Escalates capacity issues to Services Command AI",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Shortlisted 5 venues for Adani Group corporate offsite — proposal submitted",
    tasksCompleted: 8901,
    performanceScore: 95,
  },
  {
    id: "gm-music",
    name: "GM — Music & Cultural Services",
    tier: "gm",
    category: "General Manager",
    domain: "Music & Culture",
    description:
      "Manages the Music and Cultural Services vertical for MSTC GLOBAL covering classical music, contemporary performances, artist management, and cultural event production.",
    capabilities: [
      "Manages database of 200+ Gujarat artists and performers",
      "Coordinates classical music, contemporary, and artist booking heads",
      "Matches artists to event requirements and client preferences",
      "Handles artist contracts and performance logistics",
      "Tracks cultural event trends and emerging artists",
      "Coordinates with Events GM for combined service packages",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Artist database updated with 12 new Gujarat performers — 3 shortlisted for Navratri bookings",
    tasksCompleted: 6789,
    performanceScore: 93,
  },
  {
    id: "gm-sports",
    name: "GM — Sports & Athletics",
    tier: "gm",
    category: "General Manager",
    domain: "Sports",
    description:
      "Manages the Sports and Athletics vertical for MSTC GLOBAL covering cricket, football, athlete management, tournament sponsorships, and sports event production.",
    capabilities: [
      "Manages cricket, football, and athlete management heads",
      "Coordinates tournament sponsorship opportunities for MSTC clients",
      "Manages database of 150+ Gujarat athletes and sports teams",
      "Handles athlete contract negotiations and endorsement deals",
      "Tracks sports event opportunities in Ahmedabad and Gujarat",
      "Coordinates with Media GM for sports content and coverage",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Cricket tournament sponsorship analysis delivered — Saurashtra T20 recommended at ₹8L investment",
    tasksCompleted: 5678,
    performanceScore: 94,
  },
  {
    id: "gm-ngo",
    name: "GM — NGO & CSR",
    tier: "gm",
    category: "General Manager",
    domain: "NGO & CSR",
    description:
      "Manages NGO and CSR activities for MSTC GLOBAL covering education, environment, healthcare, and women empowerment initiatives across Gujarat.",
    capabilities: [
      "Manages education CSR, environment CSR, healthcare, and women empowerment heads",
      "Coordinates CSR fund allocation for corporate clients under Companies Act",
      "Tracks impact metrics across all active CSR projects",
      "Identifies NGO partnership opportunities for MSTC clients",
      "Ensures compliance with corporate CSR reporting requirements",
      "Produces quarterly CSR impact report for board review",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Q1 2025 CSR fund allocation report submitted — ₹23L deployed across 4 initiatives",
    tasksCompleted: 4567,
    performanceScore: 96,
  },
  {
    id: "gm-tourism",
    name: "GM — Tourism & Travel",
    tier: "gm",
    category: "General Manager",
    domain: "Tourism",
    description:
      "Manages the Tourism and Travel vertical for MSTC GLOBAL covering Gujarat heritage tourism, adventure tourism, corporate travel, and international packages.",
    capabilities: [
      "Manages Gujarat heritage, adventure, and corporate travel heads",
      "Curates Gujarat travel itineraries for domestic and NRI clients",
      "Coordinates corporate travel logistics for business clients",
      "Tracks Rann Utsav, Navratri, and major Gujarat tourism events",
      "Provides NRI clients with Gujarat heritage discovery packages",
      "Coordinates with Events GM for combined travel-event packages",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Gujarat heritage circuit itinerary updated for 2025 season — 8 stops across 5 days",
    tasksCompleted: 6789,
    performanceScore: 94,
  },
  {
    id: "gm-media",
    name: "GM — Media & Entertainment",
    tier: "gm",
    category: "General Manager",
    domain: "Media",
    description:
      "Manages the Media and Entertainment vertical for MSTC GLOBAL covering digital media, print/broadcast, OTT content, and media partnership advisory.",
    capabilities: [
      "Manages digital media, print/broadcast, and OTT department heads",
      "Coordinates MSTC media presence across all channels",
      "Identifies media investment opportunities for clients",
      "Manages MSTC PR and press coverage in Gujarat media",
      "Tracks OTT and digital media market trends",
      "Coordinates with Content GM for media content strategy",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "MSTC GLOBAL 25-year anniversary press release drafted and approved for release",
    tasksCompleted: 5678,
    performanceScore: 93,
  },
  {
    id: "gm-infrastructure",
    name: "GM — Infrastructure Projects",
    tier: "gm",
    category: "General Manager",
    domain: "Infrastructure",
    description:
      "Manages infrastructure project intelligence for MSTC GLOBAL covering road projects, metro expansion, BRTS, smart city initiatives, and their property market impact.",
    capabilities: [
      "Tracks all major Ahmedabad infrastructure projects",
      "Manages road/metro and smart city department heads",
      "Assesses infrastructure project impact on property prices",
      "Monitors government budget allocations for Gujarat infrastructure",
      "Provides infrastructure timeline intelligence to locality AIs",
      "Alerts all relevant agents when major infrastructure approved",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "BRTS Phase 2 Bopal-Ghuma corridor impact assessment complete — 12% price uplift projected",
    tasksCompleted: 3456,
    performanceScore: 95,
  },
  {
    id: "gm-redevelopment-consulting",
    name: "GM — Redevelopment & Consulting",
    tier: "gm",
    category: "General Manager",
    domain: "Redevelopment Consulting",
    description:
      "Manages RERA and PR consulting services at MSTC GLOBAL including promoter registration, agent compliance, and redevelopment consulting for societies and builders.",
    capabilities: [
      "Provides RERA consulting for builders and developers",
      "Coordinates promoter registration and agent compliance processes",
      "Manages redevelopment consulting for societies across Ahmedabad",
      "Tracks RERA regulation changes and updates all clients",
      "Drafts RERA-compliant agreements and disclosures",
      "Coordinates with Legal Command AI for complex compliance queries",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "RERA consulting checklist updated with 2025 regulatory changes — 6 clients notified",
    tasksCompleted: 2341,
    performanceScore: 94,
  },

  // Client GMs
  {
    id: "gm-nri",
    name: "GM — NRI Clients",
    tier: "gm",
    category: "General Manager",
    domain: "NRI",
    description:
      "Manages NRI client intelligence for MSTC GLOBAL covering 847 NRI clients across USA, UK, UAE, Canada, and Australia with specialized FEMA compliance and repatriation guidance.",
    capabilities: [
      "Manages 847 NRI clients across 12 countries",
      "Coordinates NRI investment advisory, legal, and repatriation heads",
      "Provides FEMA-compliant property transaction guidance",
      "Handles power of attorney for NRI clients buying remotely",
      "Coordinates with expansion AIs for NRI diaspora market entry",
      "Manages time zone differences for client communications",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "NRI repatriation guide updated for FY2024-25 FEMA rules — distributed to 847 NRI clients",
    tasksCompleted: 9012,
    performanceScore: 97,
  },
  {
    id: "gm-hni",
    name: "GM — HNI & Ultra-HNI Clients",
    tier: "gm",
    category: "General Manager",
    domain: "HNI",
    description:
      "Manages HNI and ultra-HNI client relationships for MSTC GLOBAL covering 234 high-net-worth individuals with bespoke advisory and white-glove service.",
    capabilities: [
      "Manages 234 HNI clients with avg deal size ₹8.7Cr",
      "Coordinates ultra-HNI relationship and portfolio heads",
      "Provides bespoke off-market property introductions",
      "Manages ultra-HNI briefings with MD involvement",
      "Coordinates tax, legal, and wealth advisory for HNIs",
      "Maintains strict confidentiality for all HNI transactions",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Ultra-HNI portfolio brief prepared and sent to MD for 3 clients — action items flagged",
    tasksCompleted: 6789,
    performanceScore: 98,
  },
  {
    id: "gm-firsttime",
    name: "GM — First-Time Buyers",
    tier: "gm",
    category: "General Manager",
    domain: "First-Time Buyers",
    description:
      "Manages first-time buyer client intelligence for MSTC GLOBAL covering 2,341 first-time buyers with education-first approach, loan guidance, and scheme navigation.",
    capabilities: [
      "Manages 2,341 first-time buyer clients",
      "Coordinates first-time buyer education and loan guidance heads",
      "Provides step-by-step guidance through entire home buying process",
      "Connects buyers with PMAY and GIHED scheme opportunities",
      "Runs educational content series for first-time buyers",
      "Coordinates with Affordable GM for suitable inventory",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "First-time buyer WhatsApp education series launched — 400+ enrolled in Week 1",
    tasksCompleted: 11234,
    performanceScore: 95,
  },
  {
    id: "gm-corporate-clients",
    name: "GM — Corporate & Institutional Clients",
    tier: "gm",
    category: "General Manager",
    domain: "Corporate Clients",
    description:
      "Manages corporate and institutional client intelligence for MSTC GLOBAL covering office leasing, warehouse procurement, and commercial real estate advisory.",
    capabilities: [
      "Manages 312 corporate and institutional clients",
      "Coordinates corporate leasing and investment department heads",
      "Provides commercial real estate advisory for expansion decisions",
      "Coordinates with Commercial GM for office inventory access",
      "Manages corporate sale-leaseback and lease-vs-buy analysis",
      "Coordinates with Finance GM for corporate mortgage structuring",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Corporate leasing proposal drafted for Infosys Ahmedabad expansion — 35,000 sqft requirement",
    tasksCompleted: 5678,
    performanceScore: 96,
  },
  {
    id: "gm-investors",
    name: "GM — Investor Clients",
    tier: "gm",
    category: "General Manager",
    domain: "Investors",
    description:
      "Manages investor client intelligence for MSTC GLOBAL covering 1,456 investors seeking rental yield, capital appreciation, flip opportunities, and commercial investments.",
    capabilities: [
      "Manages 1,456 investor clients with avg deal size ₹2.1Cr",
      "Coordinates yield optimization and flip/short-term heads",
      "Provides top-10 yield opportunity briefings monthly",
      "Identifies flip and short-term investment opportunities",
      "Coordinates with Analytics GM for investment performance tracking",
      "Reports investment trend changes to Investment Command AI",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Top 10 Ahmedabad yield opportunities briefing issued — Chandkheda leads at 4.8% net yield",
    tasksCompleted: 7890,
    performanceScore: 97,
  },
  {
    id: "gm-tenants",
    name: "GM — Tenant Clients",
    tier: "gm",
    category: "General Manager",
    domain: "Tenants",
    description:
      "Manages tenant client intelligence for MSTC GLOBAL helping individuals and businesses find the right rental property with appropriate legal agreements.",
    capabilities: [
      "Manages tenant database with verified profiles",
      "Coordinates tenant-property matching using AI profiling",
      "Provides leave and license agreement guidance",
      "Verifies tenant backgrounds for landlord clients",
      "Tracks tenant requirement changes for relocating tenants",
      "Connects quality tenants with landlord clients efficiently",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Tenant screening checklist updated for 2025 — includes digital verification process",
    tasksCompleted: 8901,
    performanceScore: 93,
  },
  {
    id: "gm-sellers",
    name: "GM — Seller Clients",
    tier: "gm",
    category: "General Manager",
    domain: "Sellers",
    description:
      "Manages seller client intelligence for MSTC GLOBAL helping property sellers optimize listing strategy, pricing, timing, and deal terms to achieve best outcomes.",
    capabilities: [
      "Manages 340 active seller clients across all property types",
      "Provides optimal listing timing recommendations by locality",
      "Coordinates pricing strategy with Property GMs",
      "Manages seller expectations through realistic valuations",
      "Coordinates legal documentation for seller transactions",
      "Monitors time-on-market and recommends re-pricing when needed",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Optimal listing time analysis for Q2 2025 issued — festive season recommended for premium properties",
    tasksCompleted: 6789,
    performanceScore: 95,
  },
  {
    id: "gm-builders",
    name: "GM — Builder & Developer Relations",
    tier: "gm",
    category: "General Manager",
    domain: "Builder Relations",
    description:
      "Manages builder and developer relationships for MSTC GLOBAL covering credibility assessment, partnership tie-ups, new project launches, and builder intelligence for clients.",
    capabilities: [
      "Maintains intelligence on 200+ Ahmedabad builders and developers",
      "Coordinates builder credibility, partnership, and launch heads",
      "Assesses and scores builder reliability for client advisory",
      "Develops exclusive launch partnerships with quality builders",
      "Monitors builder financial health and project delivery track record",
      "Alerts to builder default risks before client commitment",
    ],
    status: "active",
    autonomyLevel: 8,
    selfTaskEnabled: true,
    lastAction:
      "Builder credibility scores updated — 3 builders flagged for delivery delays, clients notified",
    tasksCompleted: 4567,
    performanceScore: 96,
  },
];

export const EXTENDED_TIER_META: Record<
  string,
  { label: string; color: string; bg: string; badge: string }
> = {
  god: {
    label: "God Tier",
    color: "#9b59b6",
    bg: "bg-purple-900",
    badge: "text-purple-300",
  },
  "ultra-command": {
    label: "Ultra Command",
    color: "#e74c3c",
    bg: "bg-red-900",
    badge: "text-red-300",
  },
  gm: {
    label: "General Manager",
    color: "#e67e22",
    bg: "bg-orange-900",
    badge: "text-orange-300",
  },
  "dept-head": {
    label: "Department Head",
    color: "#f39c12",
    bg: "bg-yellow-900",
    badge: "text-yellow-300",
  },
  specialist: {
    label: "Specialist",
    color: "#3498db",
    bg: "bg-blue-900",
    badge: "text-blue-300",
  },
  locality: {
    label: "Locality AI",
    color: "#27ae60",
    bg: "bg-green-900",
    badge: "text-green-300",
  },
  segment: {
    label: "Segment AI",
    color: "#1abc9c",
    bg: "bg-teal-900",
    badge: "text-teal-300",
  },
  neural: {
    label: "Neural Model",
    color: "#8e44ad",
    bg: "bg-violet-900",
    badge: "text-violet-300",
  },
  automation: {
    label: "Automation",
    color: "#c9a84c",
    bg: "bg-yellow-800",
    badge: "text-yellow-200",
  },
  creative: {
    label: "Creative AI",
    color: "#e91e63",
    bg: "bg-pink-900",
    badge: "text-pink-300",
  },
  expansion: {
    label: "Expansion AI",
    color: "#00bcd4",
    bg: "bg-cyan-900",
    badge: "text-cyan-300",
  },
  quality: {
    label: "Quality AI",
    color: "#4caf50",
    bg: "bg-green-800",
    badge: "text-green-200",
  },
  knowledge: {
    label: "Knowledge AI",
    color: "#ff9800",
    bg: "bg-amber-900",
    badge: "text-amber-300",
  },
  vertical: {
    label: "Vertical AI",
    color: "#795548",
    bg: "bg-stone-800",
    badge: "text-stone-300",
  },
  "continuous-improvement": {
    label: "Self-Improving",
    color: "#607d8b",
    bg: "bg-slate-800",
    badge: "text-slate-300",
  },
};

export interface LocalityData {
  id: string;
  name: string;
  investmentGrade: "A" | "B" | "C" | "D";
  currentPriceRange: string;
  appreciationForecast1Y: number;
  appreciationForecast3Y: number;
  appreciationForecast5Y: number;
  infrastructureProjects: string[];
  lifestyleScore: number;
  agents: string[];
}

export const LOCALITY_DATA: LocalityData[] = [
  {
    id: "sg-highway",
    name: "SG Highway",
    investmentGrade: "A",
    currentPriceRange: "₹6,800 - ₹12,500/sqft",
    appreciationForecast1Y: 8.2,
    appreciationForecast3Y: 28.5,
    appreciationForecast5Y: 52.1,
    infrastructureProjects: [
      "Metro Line 2 Extension",
      "SG Highway Flyover Phase 3",
      "New BRTS Corridor",
    ],
    lifestyleScore: 9,
    agents: [
      "loc-sg-highway-oracle",
      "loc-sg-highway-inventory",
      "loc-sg-highway-grade",
      "loc-sg-highway-infra",
      "loc-sg-highway-lifestyle",
    ],
  },
  {
    id: "prahlad-nagar",
    name: "Prahlad Nagar",
    investmentGrade: "A",
    currentPriceRange: "₹7,200 - ₹14,000/sqft",
    appreciationForecast1Y: 9.1,
    appreciationForecast3Y: 31.2,
    appreciationForecast5Y: 58.4,
    infrastructureProjects: [
      "Pedestrian Plaza Development",
      "Underground Utility Duct",
      "Premium Retail Hub",
    ],
    lifestyleScore: 9,
    agents: [
      "loc-prahlad-nagar-oracle",
      "loc-prahlad-nagar-inventory",
      "loc-prahlad-nagar-grade",
      "loc-prahlad-nagar-infra",
      "loc-prahlad-nagar-lifestyle",
    ],
  },
  {
    id: "satellite",
    name: "Satellite",
    investmentGrade: "A",
    currentPriceRange: "₹6,500 - ₹11,800/sqft",
    appreciationForecast1Y: 7.8,
    appreciationForecast3Y: 27.3,
    appreciationForecast5Y: 49.8,
    infrastructureProjects: [
      "Metro Station Connectivity",
      "Road Widening Scheme",
      "Parks Redevelopment",
    ],
    lifestyleScore: 9,
    agents: [
      "loc-satellite-oracle",
      "loc-satellite-inventory",
      "loc-satellite-grade",
      "loc-satellite-infra",
      "loc-satellite-lifestyle",
    ],
  },
  {
    id: "bopal",
    name: "Bopal",
    investmentGrade: "B",
    currentPriceRange: "₹4,500 - ₹7,200/sqft",
    appreciationForecast1Y: 11.3,
    appreciationForecast3Y: 38.2,
    appreciationForecast5Y: 67.9,
    infrastructureProjects: [
      "BRTS Extension to Ghuma",
      "New School Zone Development",
      "Commercial Hub Phase 2",
    ],
    lifestyleScore: 8,
    agents: [
      "loc-bopal-oracle",
      "loc-bopal-inventory",
      "loc-bopal-grade",
      "loc-bopal-infra",
      "loc-bopal-lifestyle",
    ],
  },
  {
    id: "gota",
    name: "Gota",
    investmentGrade: "B",
    currentPriceRange: "₹4,200 - ₹6,800/sqft",
    appreciationForecast1Y: 10.8,
    appreciationForecast3Y: 36.4,
    appreciationForecast5Y: 64.2,
    infrastructureProjects: [
      "SH 41 Widening",
      "New Metro Corridor Proposal",
      "Township Development Zone",
    ],
    lifestyleScore: 7,
    agents: [
      "loc-gota-oracle",
      "loc-gota-inventory",
      "loc-gota-grade",
      "loc-gota-infra",
      "loc-gota-lifestyle",
    ],
  },
  {
    id: "chandkheda",
    name: "Chandkheda",
    investmentGrade: "B",
    currentPriceRange: "₹3,800 - ₹6,200/sqft",
    appreciationForecast1Y: 12.1,
    appreciationForecast3Y: 40.5,
    appreciationForecast5Y: 71.3,
    infrastructureProjects: [
      "GIFT City Connectivity Road",
      "IT Park Development",
      "Metro Phase 3 Station",
    ],
    lifestyleScore: 7,
    agents: [
      "loc-chandkheda-oracle",
      "loc-chandkheda-inventory",
      "loc-chandkheda-grade",
      "loc-chandkheda-infra",
      "loc-chandkheda-lifestyle",
    ],
  },
  {
    id: "nikol",
    name: "Nikol",
    investmentGrade: "C",
    currentPriceRange: "₹3,200 - ₹5,400/sqft",
    appreciationForecast1Y: 9.4,
    appreciationForecast3Y: 31.8,
    appreciationForecast5Y: 56.2,
    infrastructureProjects: [
      "Eastern Expressway Access",
      "AMTS Bus Route Expansion",
      "Industrial Zone Connectivity",
    ],
    lifestyleScore: 6,
    agents: [
      "loc-nikol-oracle",
      "loc-nikol-inventory",
      "loc-nikol-grade",
      "loc-nikol-infra",
      "loc-nikol-lifestyle",
    ],
  },
  {
    id: "naranpura",
    name: "Naranpura",
    investmentGrade: "B",
    currentPriceRange: "₹5,800 - ₹9,400/sqft",
    appreciationForecast1Y: 7.2,
    appreciationForecast3Y: 24.8,
    appreciationForecast5Y: 44.6,
    infrastructureProjects: [
      "Society Redevelopment Cluster",
      "Metro Station Access Road",
      "Commercial Complex Development",
    ],
    lifestyleScore: 8,
    agents: [
      "loc-naranpura-oracle",
      "loc-naranpura-inventory",
      "loc-naranpura-grade",
      "loc-naranpura-infra",
      "loc-naranpura-lifestyle",
    ],
  },
  {
    id: "navrangpura",
    name: "Navrangpura",
    investmentGrade: "A",
    currentPriceRange: "₹7,500 - ₹13,200/sqft",
    appreciationForecast1Y: 6.8,
    appreciationForecast3Y: 23.1,
    appreciationForecast5Y: 41.8,
    infrastructureProjects: [
      "Heritage Zone Beautification",
      "Pedestrian-First Road Scheme",
      "Metro Interchange Node",
    ],
    lifestyleScore: 9,
    agents: [
      "loc-navrangpura-oracle",
      "loc-navrangpura-inventory",
      "loc-navrangpura-grade",
      "loc-navrangpura-infra",
      "loc-navrangpura-lifestyle",
    ],
  },
  {
    id: "vastrapur",
    name: "Vastrapur",
    investmentGrade: "A",
    currentPriceRange: "₹7,800 - ₹13,800/sqft",
    appreciationForecast1Y: 8.9,
    appreciationForecast3Y: 29.7,
    appreciationForecast5Y: 54.3,
    infrastructureProjects: [
      "Vastrapur Lake Rejuvenation",
      "Premium Mall Development",
      "Metro Extension Station",
    ],
    lifestyleScore: 9,
    agents: [
      "loc-vastrapur-oracle",
      "loc-vastrapur-inventory",
      "loc-vastrapur-grade",
      "loc-vastrapur-infra",
      "loc-vastrapur-lifestyle",
    ],
  },
  {
    id: "new-ranip",
    name: "New Ranip",
    investmentGrade: "C",
    currentPriceRange: "₹2,800 - ₹4,600/sqft",
    appreciationForecast1Y: 13.2,
    appreciationForecast3Y: 43.5,
    appreciationForecast5Y: 76.8,
    infrastructureProjects: [
      "River Connectivity Road",
      "PMAY Housing Scheme",
      "Affordable Commercial Strip",
    ],
    lifestyleScore: 6,
    agents: [
      "loc-new-ranip-oracle",
      "loc-new-ranip-inventory",
      "loc-new-ranip-grade",
      "loc-new-ranip-infra",
      "loc-new-ranip-lifestyle",
    ],
  },
];

export interface SegmentData {
  id: string;
  name: string;
  icon: string;
  totalClients: number;
  avgDealSize: number;
  conversionRate: number;
  preferredPropertyTypes: string[];
  agents: string[];
  description: string;
}

export const SEGMENT_DATA: SegmentData[] = [
  {
    id: "nri",
    name: "NRI",
    icon: "✈",
    totalClients: 847,
    avgDealSize: 3.2,
    conversionRate: 18.4,
    preferredPropertyTypes: [
      "Luxury Apartment",
      "Premium Villa",
      "Commercial Plot",
    ],
    agents: [
      "seg-nri-intel",
      "seg-nri-matcher",
      "seg-nri-comm",
      "seg-nri-legal",
      "seg-nri-tax",
      "seg-nri-onboard",
      "seg-nri-retain",
      "seg-nri-upsell",
    ],
    description:
      "Non-Resident Indian clients requiring FEMA compliance, repatriation guidance, and remote purchase support.",
  },
  {
    id: "hni",
    name: "HNI/Ultra-HNI",
    icon: "👑",
    totalClients: 234,
    avgDealSize: 8.7,
    conversionRate: 24.1,
    preferredPropertyTypes: [
      "Ultra-Premium Villa",
      "Penthouse",
      "Commercial Complex",
    ],
    agents: [
      "seg-hni-intel",
      "seg-hni-matcher",
      "seg-hni-comm",
      "seg-hni-legal",
      "seg-hni-tax",
      "seg-hni-onboard",
      "seg-hni-retain",
      "seg-hni-upsell",
    ],
    description:
      "High Net Worth Individuals with complex portfolios requiring bespoke advisory, wealth management, and white-glove service.",
  },
  {
    id: "first-time",
    name: "First-Time Buyer",
    icon: "🏠",
    totalClients: 2341,
    avgDealSize: 0.85,
    conversionRate: 12.3,
    preferredPropertyTypes: [
      "2BHK Apartment",
      "3BHK Affordable",
      "Budget Plot",
    ],
    agents: [
      "seg-first-time-intel",
      "seg-first-time-matcher",
      "seg-first-time-comm",
      "seg-first-time-legal",
      "seg-first-time-tax",
      "seg-first-time-onboard",
      "seg-first-time-retain",
      "seg-first-time-upsell",
    ],
    description:
      "First-time homebuyers requiring education, hand-holding, loan guidance, and scheme navigation through the buying process.",
  },
  {
    id: "investors",
    name: "Investor",
    icon: "📈",
    totalClients: 1456,
    avgDealSize: 2.1,
    conversionRate: 31.8,
    preferredPropertyTypes: [
      "Commercial Office",
      "Rental Apartment",
      "NA Plot",
    ],
    agents: [
      "seg-investors-intel",
      "seg-investors-matcher",
      "seg-investors-comm",
      "seg-investors-legal",
      "seg-investors-tax",
      "seg-investors-onboard",
      "seg-investors-retain",
      "seg-investors-upsell",
    ],
    description:
      "Property investors seeking yield optimization, capital appreciation, flip opportunities, and portfolio diversification.",
  },
  {
    id: "corporate",
    name: "Corporate",
    icon: "🏢",
    totalClients: 312,
    avgDealSize: 15.4,
    conversionRate: 28.6,
    preferredPropertyTypes: ["Office Complex", "Warehouse", "Industrial Plot"],
    agents: [
      "seg-corporate-intel",
      "seg-corporate-matcher",
      "seg-corporate-comm",
      "seg-corporate-legal",
      "seg-corporate-tax",
      "seg-corporate-onboard",
      "seg-corporate-retain",
      "seg-corporate-upsell",
    ],
    description:
      "Corporate and institutional clients requiring commercial real estate advisory, office space solutions, and lease management.",
  },
  {
    id: "senior",
    name: "Senior Citizen",
    icon: "🌟",
    totalClients: 678,
    avgDealSize: 1.4,
    conversionRate: 19.2,
    preferredPropertyTypes: [
      "Ground Floor Apartment",
      "Society Flat",
      "Senior Living",
    ],
    agents: [
      "seg-senior-intel",
      "seg-senior-matcher",
      "seg-senior-comm",
      "seg-senior-legal",
      "seg-senior-tax",
      "seg-senior-onboard",
      "seg-senior-retain",
      "seg-senior-upsell",
    ],
    description:
      "Senior citizen clients with simplified communication needs, accessibility requirements, and succession planning considerations.",
  },
];

export interface NeuralModel {
  id: string;
  name: string;
  modelType: string;
  accuracy: number;
  trainingDataSize: string;
  lastPrediction: string;
  confidence: number;
}

export interface NeuralStack {
  id: string;
  name: string;
  domain: string;
  models: NeuralModel[];
}

export const NEURAL_STACKS: NeuralStack[] = [
  {
    id: "property",
    name: "Property Intelligence",
    domain: "Real Estate",
    models: [
      {
        id: "neural-prop-ann",
        name: "Property Valuation ANN",
        modelType: "ANN",
        accuracy: 94.2,
        trainingDataSize: "2.3M property records",
        lastPrediction: "Bopal 3BHK: ₹68.4L fair value",
        confidence: 91,
      },
      {
        id: "neural-prop-rnn",
        name: "Demand Prediction RNN",
        modelType: "RNN",
        accuracy: 87.8,
        trainingDataSize: "5Y time-series data",
        lastPrediction: "Chandkheda demand up 12% next quarter",
        confidence: 84,
      },
      {
        id: "neural-prop-cnn",
        name: "Photo Quality CNN",
        modelType: "CNN",
        accuracy: 96.1,
        trainingDataSize: "500K property images",
        lastPrediction: "Listing photo quality: 7.2/10",
        confidence: 95,
      },
      {
        id: "neural-prop-cnn2",
        name: "Floor Plan Reader CNN",
        modelType: "CNN",
        accuracy: 91.4,
        trainingDataSize: "120K floor plans",
        lastPrediction: "Extracted: 3BHK, 1450sqft, East facing",
        confidence: 89,
      },
      {
        id: "neural-prop-gnn",
        name: "Buyer-Property Similarity GNN",
        modelType: "GNN",
        accuracy: 88.9,
        trainingDataSize: "847K buyer-property pairs",
        lastPrediction: "12 matched properties for lead #A4821",
        confidence: 86,
      },
    ],
  },
  {
    id: "finance",
    name: "Finance Intelligence",
    domain: "Finance",
    models: [
      {
        id: "neural-fin-ann",
        name: "Loan Approval Probability ANN",
        modelType: "ANN",
        accuracy: 92.7,
        trainingDataSize: "1.8M loan applications",
        lastPrediction: "Lead #B2341: 87% approval probability",
        confidence: 90,
      },
      {
        id: "neural-fin-rnn",
        name: "Rate Movement Predictor RNN",
        modelType: "RNN",
        accuracy: 76.3,
        trainingDataSize: "20Y RBI rate data",
        lastPrediction: "Next RBI meeting: hold at 6.5%",
        confidence: 71,
      },
      {
        id: "neural-fin-cnn",
        name: "Document OCR CNN",
        modelType: "CNN",
        accuracy: 98.2,
        trainingDataSize: "3M financial documents",
        lastPrediction: "Form 16 extracted: ₹18.4L annual income",
        confidence: 97,
      },
      {
        id: "neural-fin-gnn",
        name: "Fraud Detection GNN",
        modelType: "GNN",
        accuracy: 99.1,
        trainingDataSize: "400K transaction graphs",
        lastPrediction: "Lead #C1823: 0.2% fraud probability",
        confidence: 98,
      },
      {
        id: "neural-fin-rl",
        name: "Portfolio Optimizer RL",
        modelType: "RL",
        accuracy: 83.4,
        trainingDataSize: "10Y portfolio outcomes",
        lastPrediction: "Rebalance HNI portfolio: sell Nikol, add Bopal",
        confidence: 79,
      },
    ],
  },
  {
    id: "client",
    name: "Client Intelligence",
    domain: "Client Management",
    models: [
      {
        id: "neural-client-ann",
        name: "Lead Conversion ANN",
        modelType: "ANN",
        accuracy: 89.3,
        trainingDataSize: "2.1M lead interactions",
        lastPrediction: "Lead #D4521: 72% conversion this month",
        confidence: 87,
      },
      {
        id: "neural-client-rnn",
        name: "Churn Prediction RNN",
        modelType: "RNN",
        accuracy: 85.7,
        trainingDataSize: "3Y client behavior sequences",
        lastPrediction: "8 clients at high churn risk — re-engage now",
        confidence: 83,
      },
      {
        id: "neural-client-cnn",
        name: "Emotion Detection CNN",
        modelType: "CNN",
        accuracy: 79.8,
        trainingDataSize: "500K message samples",
        lastPrediction: "Lead #E2341: frustrated tone — escalate",
        confidence: 76,
      },
      {
        id: "neural-client-gnn",
        name: "Referral Network GNN",
        modelType: "GNN",
        accuracy: 91.2,
        trainingDataSize: "1.2M referral connections",
        lastPrediction: "Client Shah is your highest referral influencer",
        confidence: 89,
      },
      {
        id: "neural-client-rl",
        name: "Communication Optimizer RL",
        modelType: "RL",
        accuracy: 86.4,
        trainingDataSize: "5M message outcomes",
        lastPrediction: "WhatsApp at 7pm optimal for lead #F1823",
        confidence: 83,
      },
    ],
  },
  {
    id: "legal",
    name: "Legal Intelligence",
    domain: "Legal & Compliance",
    models: [
      {
        id: "neural-legal-ann",
        name: "Contract Risk ANN",
        modelType: "ANN",
        accuracy: 93.8,
        trainingDataSize: "800K contracts analyzed",
        lastPrediction: "Development agreement #GA-234: 2 risk clauses found",
        confidence: 92,
      },
      {
        id: "neural-legal-cnn",
        name: "Document Classification CNN",
        modelType: "CNN",
        accuracy: 97.4,
        trainingDataSize: "2M legal documents",
        lastPrediction: "Document classified: Sale Deed, Gujarat jurisdiction",
        confidence: 96,
      },
      {
        id: "neural-legal-rnn",
        name: "Compliance Sequence RNN",
        modelType: "RNN",
        accuracy: 88.1,
        trainingDataSize: "50K compliance journeys",
        lastPrediction: "Next step for RERA #GP-5612: NOC application",
        confidence: 86,
      },
      {
        id: "neural-legal-ml",
        name: "Case Outcome Predictor ML",
        modelType: "ML",
        accuracy: 71.3,
        trainingDataSize: "12K RERA case outcomes",
        lastPrediction: "RERA complaint #RC-891: 68% favorable outcome",
        confidence: 67,
      },
      {
        id: "neural-legal-transformer",
        name: "Clause Anomaly Transformer",
        modelType: "Transformer",
        accuracy: 95.6,
        trainingDataSize: "1.5M contract clauses",
        lastPrediction: "Clause 12.3 deviates from Gujarat standard — review",
        confidence: 94,
      },
    ],
  },
  {
    id: "content",
    name: "Content Intelligence",
    domain: "Content",
    models: [
      {
        id: "neural-content-ann",
        name: "Content Performance ANN",
        modelType: "ANN",
        accuracy: 84.2,
        trainingDataSize: "3M content pieces tracked",
        lastPrediction: "Area guide Bopal: +34% engagement if published Thu",
        confidence: 81,
      },
      {
        id: "neural-content-rnn",
        name: "Topic Trend RNN",
        modelType: "RNN",
        accuracy: 82.7,
        trainingDataSize: "2Y search trend data",
        lastPrediction: '"Affordable housing Ahmedabad" trending up 23%',
        confidence: 79,
      },
      {
        id: "neural-content-cnn",
        name: "Image-Text Alignment CNN",
        modelType: "CNN",
        accuracy: 90.3,
        trainingDataSize: "800K content pieces",
        lastPrediction: "Blog image and headline alignment: 8.7/10",
        confidence: 88,
      },
      {
        id: "neural-content-ml",
        name: "Viral Predictor ML",
        modelType: "ML",
        accuracy: 67.8,
        trainingDataSize: "500K viral content patterns",
        lastPrediction: "Jantri rate post: 74% viral potential on WhatsApp",
        confidence: 64,
      },
      {
        id: "neural-content-transformer",
        name: "Brand Voice Transformer",
        modelType: "Transformer",
        accuracy: 92.1,
        trainingDataSize: "200K MSTC content samples",
        lastPrediction: "Recent WhatsApp message: 94% brand voice match",
        confidence: 91,
      },
    ],
  },
  {
    id: "security",
    name: "Security Intelligence",
    domain: "Security",
    models: [
      {
        id: "neural-security-ann",
        name: "Anomaly Detection ANN",
        modelType: "ANN",
        accuracy: 97.8,
        trainingDataSize: "50M platform events",
        lastPrediction: "Normal activity pattern — no anomalies detected",
        confidence: 97,
      },
      {
        id: "neural-security-rnn",
        name: "Behavioral Pattern RNN",
        modelType: "RNN",
        accuracy: 96.4,
        trainingDataSize: "10M session sequences",
        lastPrediction:
          "User session pattern matches previous verified behavior",
        confidence: 95,
      },
      {
        id: "neural-security-cnn",
        name: "Image Forgery CNN",
        modelType: "CNN",
        accuracy: 94.7,
        trainingDataSize: "2M document images",
        lastPrediction:
          "Uploaded Aadhaar: authentic — no manipulation detected",
        confidence: 93,
      },
      {
        id: "neural-security-gnn",
        name: "Attack Graph GNN",
        modelType: "GNN",
        accuracy: 98.2,
        trainingDataSize: "1M attack pattern graphs",
        lastPrediction: "No coordinated attack pattern detected today",
        confidence: 97,
      },
      {
        id: "neural-security-transformer",
        name: "Threat Classification Transformer",
        modelType: "Transformer",
        accuracy: 99.1,
        trainingDataSize: "5M threat samples",
        lastPrediction: "IP block applied: bot cluster from 3 IPs detected",
        confidence: 98,
      },
    ],
  },
  {
    id: "operations",
    name: "Operations Intelligence",
    domain: "Operations",
    models: [
      {
        id: "neural-ops-ann",
        name: "Task Duration Predictor ANN",
        modelType: "ANN",
        accuracy: 86.3,
        trainingDataSize: "500K task completions",
        lastPrediction: "Property listing task: estimated 23 minutes",
        confidence: 83,
      },
      {
        id: "neural-ops-rl",
        name: "Demand-Supply Balancer RL",
        modelType: "RL",
        accuracy: 81.7,
        trainingDataSize: "3Y operational data",
        lastPrediction:
          "Reassign 2 leads from overloaded agent to available one",
        confidence: 79,
      },
      {
        id: "neural-ops-cnn",
        name: "Document Auto-Classifier CNN",
        modelType: "CNN",
        accuracy: 96.8,
        trainingDataSize: "1.5M business documents",
        lastPrediction: "Document auto-filed under: Legal > Sale Deeds > 2025",
        confidence: 96,
      },
      {
        id: "neural-ops-gnn",
        name: "Process Bottleneck GNN",
        modelType: "GNN",
        accuracy: 88.4,
        trainingDataSize: "200K workflow completions",
        lastPrediction:
          "Bottleneck detected: document review step +2.3 days avg",
        confidence: 86,
      },
      {
        id: "neural-ops-transformer",
        name: "Decision Support Transformer",
        modelType: "Transformer",
        accuracy: 84.9,
        trainingDataSize: "100K business decisions",
        lastPrediction:
          "Recommendation: accept counter offer at ₹82L (market fair)",
        confidence: 82,
      },
    ],
  },
  {
    id: "market",
    name: "Market Intelligence",
    domain: "Real Estate Markets",
    models: [
      {
        id: "neural-market-ann",
        name: "Macro Impact ANN",
        modelType: "ANN",
        accuracy: 78.4,
        trainingDataSize: "30Y macro-property correlations",
        lastPrediction: "Inflation at 4.2%: neutral impact on property demand",
        confidence: 74,
      },
      {
        id: "neural-market-rnn",
        name: "News Sentiment RNN",
        modelType: "RNN",
        accuracy: 84.6,
        trainingDataSize: "2M real estate news articles",
        lastPrediction:
          "Market sentiment: positive — Gujarat infrastructure spending",
        confidence: 82,
      },
      {
        id: "neural-market-cnn",
        name: "Market Cycle CNN",
        modelType: "CNN",
        accuracy: 81.2,
        trainingDataSize: "40Y market cycle patterns",
        lastPrediction: "Ahmedabad cycle position: mid-growth phase",
        confidence: 78,
      },
      {
        id: "neural-market-gnn",
        name: "Competitor Strategy GNN",
        modelType: "GNN",
        accuracy: 76.8,
        trainingDataSize: "500K competitor actions",
        lastPrediction:
          "PropTiger reducing Ahmedabad focus — opportunity window",
        confidence: 73,
      },
      {
        id: "neural-market-rl",
        name: "Price Discovery RL",
        modelType: "RL",
        accuracy: 89.7,
        trainingDataSize: "5M transaction prices",
        lastPrediction: "Discovered true market price: Vastrapur 2BHK ₹1.24Cr",
        confidence: 87,
      },
    ],
  },
  {
    id: "innovation",
    name: "Innovation Intelligence",
    domain: "Innovation",
    models: [
      {
        id: "neural-innov-ann",
        name: "Technology Adoption ANN",
        modelType: "ANN",
        accuracy: 82.3,
        trainingDataSize: "10K tech adoption patterns",
        lastPrediction: "PropTech AI feature: 76% likely adoption in 18 months",
        confidence: 79,
      },
      {
        id: "neural-innov-rnn",
        name: "Trend Identification RNN",
        modelType: "RNN",
        accuracy: 79.8,
        trainingDataSize: "5Y global proptech trends",
        lastPrediction:
          "Tokenized real estate trending — India 2 years behind global",
        confidence: 77,
      },
      {
        id: "neural-innov-ml",
        name: "Feature Impact Predictor ML",
        modelType: "ML",
        accuracy: 77.4,
        trainingDataSize: "200K feature launch outcomes",
        lastPrediction: "Voice search feature: +12% engagement projected",
        confidence: 74,
      },
      {
        id: "neural-innov-transformer",
        name: "User Need Synthesizer Transformer",
        modelType: "Transformer",
        accuracy: 86.1,
        trainingDataSize: "1M user feedback items",
        lastPrediction: "Top unmet need: property price history visualization",
        confidence: 84,
      },
      {
        id: "neural-innov-rl",
        name: "Innovation Scoring RL",
        modelType: "RL",
        accuracy: 80.9,
        trainingDataSize: "5K innovation outcomes",
        lastPrediction: "AR virtual tour: 9.1/10 innovation score for MSTC",
        confidence: 78,
      },
    ],
  },
  {
    id: "analytics",
    name: "Analytics Intelligence",
    domain: "Analytics",
    models: [
      {
        id: "neural-analytics-ann",
        name: "Insight Generation ANN",
        modelType: "ANN",
        accuracy: 87.6,
        trainingDataSize: "10M data points analyzed",
        lastPrediction: "Insight: Weekend enquiries 34% higher than weekdays",
        confidence: 85,
      },
      {
        id: "neural-analytics-rnn",
        name: "Anomaly Root Cause RNN",
        modelType: "RNN",
        accuracy: 83.9,
        trainingDataSize: "2M anomaly sequences",
        lastPrediction: "Lead drop Monday: public holiday — no action needed",
        confidence: 81,
      },
      {
        id: "neural-analytics-ml",
        name: "Dashboard Auto-Designer ML",
        modelType: "ML",
        accuracy: 78.2,
        trainingDataSize: "50K dashboard designs",
        lastPrediction:
          "Suggested: Add Chandkheda trend chart to MD daily brief",
        confidence: 75,
      },
      {
        id: "neural-analytics-transformer",
        name: "KPI Forecaster Transformer",
        modelType: "Transformer",
        accuracy: 85.4,
        trainingDataSize: "3Y KPI time series",
        lastPrediction: "Q2 2025 leads forecast: 847 ± 34 (8.4% growth vs Q1)",
        confidence: 83,
      },
      {
        id: "neural-analytics-rl",
        name: "Report Generator RL",
        modelType: "RL",
        accuracy: 88.7,
        trainingDataSize: "10K report feedback ratings",
        lastPrediction:
          "Monthly report optimized: executive summary added first",
        confidence: 86,
      },
    ],
  },
];

export interface ExpansionTarget {
  id: string;
  city: string;
  country: string;
  lat: number;
  lng: number;
  opportunityScore: number;
  timeline: string;
  aiReadiness: number;
  marketSize: string;
  strategy: string;
}

export const EXPANSION_TARGETS: ExpansionTarget[] = [
  {
    id: "mumbai",
    city: "Mumbai",
    country: "India",
    lat: 19.076,
    lng: 72.8777,
    opportunityScore: 7.2,
    timeline: "2026",
    aiReadiness: 8,
    marketSize: "₹4.2 Lakh Cr annually",
    strategy:
      "Premium residential advisory for NRI and HNI buyers in Bandra, Juhu, and BKC",
  },
  {
    id: "delhi",
    city: "Delhi/NCR",
    country: "India",
    lat: 28.6139,
    lng: 77.209,
    opportunityScore: 6.8,
    timeline: "2027",
    aiReadiness: 7,
    marketSize: "₹3.8 Lakh Cr annually",
    strategy:
      "Commercial real estate advisory focusing on Gurugram and Noida tech corridors",
  },
  {
    id: "pune",
    city: "Pune",
    country: "India",
    lat: 18.5204,
    lng: 73.8567,
    opportunityScore: 7.5,
    timeline: "2026",
    aiReadiness: 8,
    marketSize: "₹1.8 Lakh Cr annually",
    strategy:
      "IT corridor residential advisory for young professionals and NRI investors",
  },
  {
    id: "surat",
    city: "Surat",
    country: "India",
    lat: 21.1702,
    lng: 72.8311,
    opportunityScore: 8.1,
    timeline: "2025",
    aiReadiness: 9,
    marketSize: "₹85,000 Cr annually",
    strategy:
      "Diamond and textile business community property advisory — natural MSTC extension",
  },
  {
    id: "vadodara",
    city: "Vadodara",
    country: "India",
    lat: 22.3072,
    lng: 73.1812,
    opportunityScore: 7.9,
    timeline: "2025",
    aiReadiness: 9,
    marketSize: "₹42,000 Cr annually",
    strategy:
      "Industrial and residential advisory for Vadodara Baroda Smart City development",
  },
  {
    id: "rajkot",
    city: "Rajkot",
    country: "India",
    lat: 22.3039,
    lng: 70.8022,
    opportunityScore: 7.3,
    timeline: "2026",
    aiReadiness: 8,
    marketSize: "₹28,000 Cr annually",
    strategy:
      "SME business community property advisory and residential developments",
  },
  {
    id: "dubai",
    city: "Dubai",
    country: "UAE",
    lat: 25.2048,
    lng: 55.2708,
    opportunityScore: 8.8,
    timeline: "2026",
    aiReadiness: 9,
    marketSize: "$85B NRI investment market",
    strategy:
      "NRI reverse-investment advisory — Dubai-based Indians investing back in Gujarat",
  },
  {
    id: "singapore",
    city: "Singapore",
    country: "Singapore",
    lat: 1.3521,
    lng: 103.8198,
    opportunityScore: 7.4,
    timeline: "2027",
    aiReadiness: 8,
    marketSize: "$12B Indian diaspora market",
    strategy:
      "Gujarati business diaspora advisory for Ahmedabad investment and family housing",
  },
  {
    id: "london",
    city: "London",
    country: "UK",
    lat: 51.5074,
    lng: -0.1278,
    opportunityScore: 6.9,
    timeline: "2027",
    aiReadiness: 7,
    marketSize: "£8B NRI property advisory",
    strategy:
      "UK Gujarati community advisory for India property investment and repatriation",
  },
  {
    id: "usa",
    city: "USA (Multiple Cities)",
    country: "USA",
    lat: 37.0902,
    lng: -95.7129,
    opportunityScore: 7.1,
    timeline: "2028",
    aiReadiness: 7,
    marketSize: "$45B NRI investment market",
    strategy:
      "Digital-first advisory for US-based Gujarati NRIs — online-only model initially",
  },
  {
    id: "canada",
    city: "Canada (Toronto/Vancouver)",
    country: "Canada",
    lat: 56.1304,
    lng: -106.3468,
    opportunityScore: 6.7,
    timeline: "2028",
    aiReadiness: 7,
    marketSize: "CAD 18B NRI market",
    strategy:
      "Partnership with existing Indo-Canadian real estate networks for referral model",
  },
  {
    id: "australia",
    city: "Australia (Melbourne/Sydney)",
    country: "Australia",
    lat: -25.2744,
    lng: 133.7751,
    opportunityScore: 6.4,
    timeline: "2029",
    aiReadiness: 6,
    marketSize: "AUD 12B NRI market",
    strategy:
      "Digital advisory for Australian Gujarati community via referral partnership model",
  },
];

export const AUTOMATION_CAMPAIGNS = [
  {
    id: "camp-festive",
    name: "Diwali 2025 Property Campaign",
    status: "active",
    sentCount: 1247,
    openRate: 34.2,
    responseRate: 8.9,
    agent: "auto-festive",
    startDate: "2025-10-01",
    endDate: "2025-11-15",
  },
  {
    id: "camp-first-time",
    name: "First-Time Buyer Education Series",
    status: "active",
    sentCount: 2341,
    openRate: 42.1,
    responseRate: 12.3,
    agent: "auto-drip",
    startDate: "2025-01-01",
    endDate: "2025-12-31",
  },
  {
    id: "camp-nri",
    name: "NRI Investment Advisory Campaign",
    status: "active",
    sentCount: 847,
    openRate: 38.7,
    responseRate: 18.4,
    agent: "auto-multichannel",
    startDate: "2025-02-01",
    endDate: "2025-09-30",
  },
  {
    id: "camp-price-alert",
    name: "Property Price Drop Alerts",
    status: "active",
    sentCount: 4523,
    openRate: 61.8,
    responseRate: 22.7,
    agent: "auto-pricedrop",
    startDate: "2025-01-01",
    endDate: "2025-12-31",
  },
  {
    id: "camp-reengage",
    name: "90-Day Re-Engagement Sequence",
    status: "active",
    sentCount: 891,
    openRate: 29.4,
    responseRate: 7.2,
    agent: "auto-reengage",
    startDate: "2025-03-01",
    endDate: "2025-12-31",
  },
];

export const QUALITY_METRICS = {
  platformScore: 98,
  lastScanTime: new Date().toISOString(),
  issuesFound: 2,
  issuesResolved: 2,
  uptime: 99.97,
  pagespeedScore: 92,
  mobileScore: 89,
  accessibilityScore: 96,
};
