// AIManagerData_Agents3.ts
// MSTC GLOBAL — Extended AI Agents Batch 3
// Client Intelligence Specialists (30) + Legal & Compliance Specialists (25)
// + Technology Specialists (25) + Content Intelligence Specialists (25)
// + Analytics & Data Science Specialists (30) = 135 agents

import type { ExtendedAgentDef } from "./AIManagerData_Extended";

const a = (
  id: string,
  name: string,
  tier: string,
  category: string,
  domain: string,
  desc: string,
  caps: string[],
  lastAction: string,
  tasks: number,
  perf: number,
  al: number,
): ExtendedAgentDef => ({
  id,
  name,
  tier,
  category,
  domain,
  description: desc,
  capabilities: caps,
  status: "active" as const,
  autonomyLevel: al,
  selfTaskEnabled: true,
  lastAction,
  tasksCompleted: tasks,
  performanceScore: perf,
});

// ===== CLIENT INTELLIGENCE SPECIALISTS (30) =====

const clientSpecialists: ExtendedAgentDef[] = [
  a(
    "spec-emotional-intel",
    "Emotional Intelligence AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Reads emotional state in client messages and adapts communication tone and strategy for optimal engagement.",
    [
      "Reads emotional tone in text and voice messages",
      "Detects frustration, excitement, urgency, and hesitation",
      "Recommends communication style adjustment per emotional state",
      "Flags escalation triggers when client shows high distress",
    ],
    "Flagged distressed client message \u2014 escalated to human team immediately",
    12450,
    95,
    8,
  ),
  a(
    "spec-urgency-detect",
    "Urgency Detector AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Detects genuine urgency signals vs stated urgency in buyer behavior to prioritize engagement correctly.",
    [
      "Distinguishes genuine urgency from stated urgency",
      "Analyzes behavioral signals: repeat visits, multiple enquiries",
      "Flags high-urgency leads for same-day engagement",
      "Tracks urgency decay over time for stale leads",
    ],
    "Identified 3 genuinely urgent leads from 12 stating urgency",
    9870,
    94,
    7,
  ),
  a(
    "spec-budget-reality",
    "Budget Reality AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Gently realigns client budget expectations with market reality using data-driven locality analysis.",
    [
      "Analyzes gap between stated budget and market reality",
      "Recommends alternative localities within actual budget",
      "Uses comparable data to educate without alienating client",
      "Tracks budget adjustment acceptance rate per approach",
    ],
    "Budget realignment: 4 clients redirected from SG Highway to Bopal within budget",
    7234,
    93,
    7,
  ),
  a(
    "spec-location-pref",
    "Location Preference Mapper AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Maps stated and revealed location preferences for each buyer to refine property matching accuracy.",
    [
      "Maps all stated and revealed location preferences",
      "Detects preference patterns from search and enquiry data",
      "Identifies unexplored locations matching preference profile",
      "Updates preference map after each client interaction",
    ],
    "Location preference profiles updated for 23 active leads",
    5678,
    92,
    7,
  ),
  a(
    "spec-size-pref",
    "Size Preference AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Analyzes buyer configuration preferences integrating family size, lifestyle, and budget for accurate matching.",
    [
      "Analyzes BHK preference with lifestyle data integration",
      "Tracks how size preference evolves through buyer journey",
      "Identifies when buyers compromise vs when to hold configuration",
      "Maps size preference to realistic budget-matched options",
    ],
    "Size preference analysis: 8 buyers guided from 3BHK to 2.5BHK alternatives",
    6789,
    91,
    7,
  ),
  a(
    "spec-lifestyle",
    "Lifestyle Matcher AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Matches properties to client lifestyle profiles covering commute, schools, social life, and daily needs.",
    [
      "Creates lifestyle profile from 15 data points per buyer",
      "Maps property options to lifestyle compatibility score",
      "Ranks properties by lifestyle-fit not just spec-fit",
      "Updates lifestyle match as buyer preferences evolve",
    ],
    "Lifestyle matching: 5 properties shortlisted for NRI buyer family with school priority",
    8901,
    94,
    7,
  ),
  a(
    "spec-family-stage",
    "Family Stage AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Adapts property recommendations based on family life stage from newlyweds to empty nesters.",
    [
      "Identifies family stage from client data and conversation",
      "Adapts property type and locality recommendations per stage",
      "Predicts future space needs based on family stage trajectory",
      "Integrates school, hospital, and connectivity needs per stage",
    ],
    "Family stage analysis updated for 12 active buyer leads",
    4521,
    92,
    7,
  ),
  a(
    "spec-career-stage",
    "Career Stage AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Adapts recommendations based on career stage and income trajectory for long-term property planning.",
    [
      "Identifies career stage for income stability assessment",
      "Projects income growth trajectory for loan planning",
      "Adapts property strategy to career mobility needs",
      "Integrates career stage with retirement planning timeline",
    ],
    "Career stage analysis: 6 young buyers advised to wait 2 years for better eligibility",
    3456,
    91,
    7,
  ),
  a(
    "spec-risk-appetite",
    "Risk Appetite AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Assesses each client's real estate investment risk appetite to guide property type and structure advice.",
    [
      "Assesses risk appetite through 8-question behavioral analysis",
      "Maps risk profile to appropriate investment structure",
      "Identifies mismatch between stated and revealed risk tolerance",
      "Guides investment property decisions to risk-matched options",
    ],
    "Risk appetite assessment: 4 clients redirected from under-construction to ready projects",
    5670,
    93,
    7,
  ),
  a(
    "spec-decision-maker",
    "Decision Maker Identifier AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Identifies who in a family or business group is the real decision maker for faster deal progression.",
    [
      "Identifies primary decision maker from conversation patterns",
      "Maps influencer network within buyer group",
      "Adapts communication strategy to reach real decision maker",
      "Detects when decision making committee is involved",
    ],
    "Decision maker identified in joint family \u2014 directed engagement to primary buyer",
    7823,
    94,
    7,
  ),
  a(
    "spec-influencer-map",
    "Influencer Mapper AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Maps who influences each client's property decision to enable broader, more effective engagement.",
    [
      "Maps all influencers: parents, spouse, friends, colleagues",
      "Identifies most influential person in buyer network",
      "Recommends engagement strategy to reach key influencers",
      "Tracks when influencer impact shifts during buy cycle",
    ],
    "Influencer mapping: buyer's father identified as key decision influencer \u2014 advisory provided",
    4512,
    92,
    7,
  ),
  a(
    "spec-whatsapp-behav",
    "WhatsApp Behavior AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Reads WhatsApp message timing and pattern to gauge genuine client engagement levels.",
    [
      "Analyzes WhatsApp message read and reply patterns",
      "Detects engagement level from response timing and frequency",
      "Identifies when engagement is declining before it's too late",
      "Recommends optimal message timing per client behavior pattern",
    ],
    "WhatsApp engagement analysis: 3 leads showing declining engagement \u2014 re-engagement triggered",
    8901,
    93,
    8,
  ),
  a(
    "spec-response-time",
    "Response Time Intelligence AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Uses response time patterns to predict client interest level and optimal follow-up timing.",
    [
      "Tracks response time to each message and call",
      "Identifies response time patterns indicating high interest",
      "Recommends optimal follow-up time per client pattern",
      "Detects when response times signal deal fatigue",
    ],
    "Response time analysis: fast-responder segment identified \u2014 4 ready-to-buy leads",
    9012,
    94,
    7,
  ),
  a(
    "spec-site-visit-predict",
    "Site Visit Predictor AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Predicts which leads will actually show up for site visits based on behavioral signals.",
    [
      "Predicts site visit show-up probability per lead",
      "Identifies pre-visit commitment signals in behavior",
      "Recommends confirmation strategies to increase show-up",
      "Tracks no-show patterns to improve future scheduling",
    ],
    "Site visit predictions: 6 of 8 predicted high-probability leads showed up",
    7890,
    95,
    7,
  ),
  a(
    "spec-site-visit-outcome",
    "Site Visit Outcome AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Predicts deal probability based on client behavior during and after site visits.",
    [
      "Analyzes post-visit signals for deal probability scoring",
      "Detects positive vs negative visit outcome from behavior",
      "Identifies optimal follow-up strategy after site visit",
      "Tracks conversion rates by property type and buyer segment",
    ],
    "Post-visit outcome predictions: 4 visits converted to offers within 48 hours",
    6789,
    94,
    7,
  ),
  a(
    "spec-counter-offer",
    "Counter Offer AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Analyzes counter offers and recommends optimal negotiation response strategies for agents.",
    [
      "Analyzes counter offer in context of market data",
      "Recommends optimal counter-counter offer with reasoning",
      "Calculates probability of deal at each price point",
      "Identifies when to accept vs when to hold firm",
    ],
    "Counter offer analysis: recommended acceptance at \u20b978.5L \u2014 deal closed",
    5678,
    95,
    7,
  ),
  a(
    "spec-walk-away",
    "Walk-Away Predictor AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Detects early signals that a client is about to disengage from a property deal.",
    [
      "Detects 12 behavioral signals of deal fatigue",
      "Identifies walk-away risk score for active deals",
      "Recommends immediate intervention when risk is high",
      "Differentiates genuine objections from walk-away intent",
    ],
    "Walk-away risk detected in 2 active deals \u2014 re-engagement triggered immediately",
    8901,
    96,
    8,
  ),
  a(
    "spec-reengagement-timing",
    "Re-Engagement Timing AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Predicts the optimal moment to re-engage dormant leads for maximum conversion probability.",
    [
      "Predicts re-engagement window for each dormant lead",
      "Analyzes market changes that may trigger renewed interest",
      "Recommends personalized re-engagement message per lead",
      "Tracks re-engagement success rates by approach type",
    ],
    "Re-engagement triggered for 8 dormant leads \u2014 3 responded positively",
    7823,
    94,
    7,
  ),
  a(
    "spec-seasonal-buyer",
    "Seasonal Buyer AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Predicts which clients are likely to buy around festivals, financial year end, or seasonal peaks.",
    [
      "Identifies seasonal buying tendency per client profile",
      "Predicts most likely purchase window for each lead",
      "Aligns outreach campaigns with buyer-specific seasonal peaks",
      "Tracks seasonal conversion patterns across segments",
    ],
    "Seasonal analysis: 12 clients identified as likely Q4 buyers \u2014 outreach scheduled",
    6789,
    93,
    7,
  ),
  a(
    "spec-gift-purchase",
    "Gift Purchase AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Specialized intelligence for clients purchasing property as a gift for family members.",
    [
      "Identifies gift purchase intent from conversation signals",
      "Advises on legal structure for property gifting",
      "Calculates stamp duty implications for gift transactions",
      "Guides through gift deed registration in Gujarat",
    ],
    "Gift purchase advisory: son buying property as gift for parents \u2014 stamp duty optimized",
    2341,
    92,
    7,
  ),
  a(
    "spec-invest-vs-use",
    "Investment vs Self-Use Detector AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Determines whether a buyer's true intent is investment or self-occupation for better advisory.",
    [
      "Detects investment vs self-use intent from buyer signals",
      "Adapts property recommendation to detected true intent",
      "Identifies when stated intent differs from revealed intent",
      "Ensures investment properties are financially analyzed correctly",
    ],
    "Intent detection: 4 self-described buyers identified as actual investors",
    8901,
    93,
    7,
  ),
  a(
    "spec-rental-seeker",
    "Rental Seeker AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Specialized for clients looking to rent rather than buy with optimal rental property matching.",
    [
      "Optimizes rental property matching for tenants",
      "Identifies best-value rental options per requirement",
      "Coordinates with landlord agents for seamless matching",
      "Tracks tenant needs as they evolve through search",
    ],
    "Rental matching: 6 tenants matched to suitable properties this week",
    9012,
    92,
    7,
  ),
  a(
    "spec-distress-seller",
    "Distress Seller Detector AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Identifies sellers in genuine financial distress vs those merely testing the market.",
    [
      "Identifies 8 behavioral signals of genuine seller distress",
      "Detects time pressure and financial motivation of sellers",
      "Identifies motivated seller opportunities for investor buyers",
      "Ensures ethical handling of distressed seller situations",
    ],
    "Distress sale opportunity identified \u2014 investor buyer connected within 24 hours",
    4567,
    94,
    7,
  ),
  a(
    "spec-nri-comm",
    "NRI Communication AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Handles time zone differences, WhatsApp timing, and language nuances for NRI client communications.",
    [
      "Adapts communication timing for 8 NRI time zones",
      "Manages WhatsApp, email, and video call preferences per region",
      "Handles cultural communication nuances for each diaspora market",
      "Ensures FEMA and legal information is always current",
    ],
    "NRI communication: Dubai-based client meeting scheduled at 9pm IST to accommodate time zone",
    5678,
    94,
    7,
  ),
  a(
    "spec-lang-pref",
    "Language Preference AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Detects preferred language (English/Gujarati/Hindi) and adapts all communication accordingly.",
    [
      "Detects language preference from first client interaction",
      "Switches entire communication to preferred language",
      "Identifies mixed-language preferences for bilingual clients",
      "Ensures all documents are available in preferred language",
    ],
    "Language preference detected: 12 clients switched to Gujarati communication",
    6789,
    92,
    7,
  ),
  a(
    "spec-senior-client",
    "Senior Client AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Specialized for elderly clients with larger fonts, simpler language, and family inclusion in communication.",
    [
      "Adapts communication style and complexity for senior clients",
      "Coordinates with family members for joint decision making",
      "Ensures all documents use large, readable formatting",
      "Identifies accessibility requirements for property viewing",
    ],
    "Senior client adapted communication: family members looped in for joint decision support",
    3456,
    93,
    7,
  ),
  a(
    "spec-young-buyer",
    "Young Buyer AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Specialized for first-time young buyers with education-first approach and digital-native communication.",
    [
      "Adapts to digital-native communication preferences",
      "Provides step-by-step education tailored to young buyers",
      "Integrates social proof and peer comparison data",
      "Tracks digital engagement and responds in preferred channels",
    ],
    "Young buyer education series: 45 buyers aged 25-32 enrolled this month",
    5678,
    94,
    7,
  ),
  a(
    "spec-female-buyer",
    "Female Buyer Empowerment AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Specialized for women buyers highlighting legal protections and stamp duty benefits.",
    [
      "Highlights Gujarat stamp duty discount for female buyers",
      "Advises on sole vs joint ownership for maximum benefit",
      "Provides comprehensive women buyer legal rights information",
      "Identifies women-specific home loan benefits and schemes",
    ],
    "Female buyer advisory: 8 women saved \u20b948,000 average on stamp duty this month",
    7890,
    95,
    7,
  ),
  a(
    "spec-divorcee",
    "Divorcee Property AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Sensitive guidance for property decisions during or after divorce proceedings.",
    [
      "Provides sensitive guidance through property decisions post-divorce",
      "Advises on court order compliance for property division",
      "Identifies best-value properties within divorce settlement budget",
      "Ensures complete confidentiality in all communications",
    ],
    "Sensitive property guidance provided to 2 clients navigating divorce settlement",
    1234,
    93,
    7,
  ),
  a(
    "spec-disability",
    "Disability Accommodation AI",
    "specialist",
    "Client Intelligence",
    "Client Management",
    "Property recommendations for clients with physical disabilities including accessibility feature matching.",
    [
      "Matches properties to disability-specific accessibility needs",
      "Assesses elevator, ramp, and wheelchair access availability",
      "Identifies ground-floor and accessibility-enhanced properties",
      "Provides renovation guidance for accessibility improvements",
    ],
    "Accessibility property matching: 3 clients matched to ground floor accessible apartments",
    890,
    93,
    7,
  ),
];

// ===== LEGAL & COMPLIANCE SPECIALISTS (25) =====

const legalSpecialists: ExtendedAgentDef[] = [
  a(
    "spec-title-chain",
    "Title Chain Verifier AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Traces property title back 30 years identifying any gap in chain of ownership for buyer protection.",
    [
      "Traces property title back 30 years minimum",
      "Identifies all gaps and breaks in chain of ownership",
      "Detects benami ownership and undisclosed interests",
      "Issues title risk score with clear recommendation",
    ],
    "Title chain verified for 8 properties \u2014 1 red flag detected and resolved",
    5678,
    96,
    7,
  ),
  a(
    "spec-encumbrance",
    "Encumbrance Intelligence AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Reads encumbrance certificates identifying all charges, loans, and claims on a property.",
    [
      "Reads EC in all formats and extracts all encumbrances",
      "Identifies outstanding home loans and bank charges",
      "Detects old litigation and court attachment orders",
      "Issues clear encumbrance clearance certificate",
    ],
    "EC analysis completed for 12 properties \u2014 2 outstanding charges identified",
    7823,
    95,
    7,
  ),
  a(
    "spec-rera-scorer",
    "RERA Project Scorer AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Scores each RERA project by compliance quality \u2014 A/B/C/D \u2014 for buyer safety advisory.",
    [
      "Scores all RERA-registered projects A through D",
      "Analyzes compliance documents, builder reputation, and timeline",
      "Tracks quarterly RERA score changes for all active projects",
      "Advises buyers to avoid C and D-rated projects",
    ],
    "RERA scores updated for 47 projects \u2014 3 downgraded to C rating this quarter",
    8901,
    97,
    8,
  ),
  a(
    "spec-rera-complaint",
    "RERA Complaint Drafter AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Drafts RERA complaints for buyers against delayed or non-compliant builders.",
    [
      "Drafts complete RERA complaint with all required details",
      "Calculates interest on delayed possession under RERA Act",
      "Identifies strongest legal arguments for each complaint",
      "Guides through online RERA portal filing process",
    ],
    "RERA complaint drafted for buyer with 18-month possession delay \u2014 \u20b94.2L interest claim",
    3456,
    95,
    7,
  ),
  a(
    "spec-rera-refund",
    "RERA Refund Calculator AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Calculates exact refund plus interest owed under RERA for cancelled or delayed projects.",
    [
      "Calculates full refund amount under Section 18 RERA",
      "Computes interest at SBI MCLR + 2% on principal paid",
      "Identifies total amount claimable including compensation",
      "Drafts refund demand letter with legal backing",
    ],
    "RERA refund calculation: buyer entitled to \u20b934.8L including 24 months interest",
    2341,
    94,
    7,
  ),
  a(
    "spec-consumer-court",
    "Consumer Court AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Guides buyers through consumer court complaints against builders and developers.",
    [
      "Guides through NCDRC, SCDRC, and District Forum filing",
      "Calculates compensation basis for consumer complaint",
      "Drafts consumer complaint with strongest legal arguments",
      "Advises on evidence collection for consumer court success",
    ],
    "Consumer court complaint filed for 2 buyers against non-delivering builder",
    1890,
    93,
    7,
  ),
  a(
    "spec-arbitration",
    "Arbitration Intelligence AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Advises when arbitration is better than RERA court for property disputes.",
    [
      "Analyzes dispute type for optimal forum selection",
      "Advises on RERA vs consumer court vs arbitration choice",
      "Reviews arbitration clauses in builder-buyer agreements",
      "Coordinates with arbitration specialists for complex disputes",
    ],
    "Arbitration forum selected over RERA for commercial property dispute",
    1234,
    93,
    7,
  ),
  a(
    "spec-fraud-detect",
    "Property Fraud Detector AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Identifies red flags of property fraud in documents, seller claims, and transaction patterns.",
    [
      "Detects 15 common property fraud patterns in documents",
      "Identifies duplicate sale and double mortgage fraud signals",
      "Verifies government survey numbers and boundaries",
      "Issues fraud risk score for every transaction reviewed",
    ],
    "Fraud risk detected in 1 transaction \u2014 duplicate sale attempt prevented",
    4567,
    97,
    8,
  ),
  a(
    "spec-benami",
    "Benami Transaction AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Provides guidance on Benami Transactions Prohibition Act compliance for property buyers and sellers.",
    [
      "Advises on Benami Prohibition Act compliance",
      "Identifies transactions that may inadvertently violate Benami Act",
      "Guides through benami property declaration if required",
      "Provides safe structuring alternatives to avoid Benami risk",
    ],
    "Benami Act advisory: 2 transactions restructured to ensure compliance",
    890,
    94,
    7,
  ),
  a(
    "spec-pmla",
    "PMLA Real Estate AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Provides Prevention of Money Laundering Act compliance guidance for high-value property transactions.",
    [
      "Advises on PMLA compliance for transactions above \u20b950L",
      "Guides through source of funds documentation requirements",
      "Identifies PMLA reporting obligations for agents",
      "Ensures all transactions are fully PMLA compliant",
    ],
    "PMLA compliance documentation completed for 4 high-value transactions",
    1234,
    95,
    7,
  ),
  a(
    "spec-blackmoney",
    "Black Money Intelligence AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Provides guidance on black money law compliance for property transactions.",
    [
      "Advises on Black Money Act compliance for property purchases",
      "Ensures all payment channels are fully white in transactions",
      "Guides NRI buyers on foreign income disclosure requirements",
      "Identifies transactions that may attract IT scrutiny",
    ],
    "Black money compliance review: 6 transactions cleared with full documentation",
    2341,
    95,
    7,
  ),
  a(
    "spec-poa-drafter",
    "Power of Attorney Drafter AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Generates legally sound Gujarat-registered Power of Attorney documents for property transactions.",
    [
      "Drafts general and specific PoA for property transactions",
      "Ensures Gujarat registration compliance for PoA documents",
      "Advises on NRI PoA registration at Indian consulate",
      "Includes all protective clauses to prevent PoA misuse",
    ],
    "PoA drafted for 3 NRI clients \u2014 all registered at Indian consulates",
    5678,
    94,
    7,
  ),
  a(
    "spec-dev-agreement",
    "Development Agreement AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Analyzes and drafts builder-landowner development agreements with all protective clauses.",
    [
      "Analyzes existing DA for landowner risk identification",
      "Drafts balanced DA protecting landowner rights",
      "Ensures revenue share and completion timeline protections",
      "Integrates RERA compliance in all development agreements",
    ],
    "Development agreement analyzed for society \u2014 4 unfavorable clauses flagged",
    3456,
    94,
    7,
  ),
  a(
    "spec-jda",
    "Joint Development Agreement AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Structures JDA for society redevelopment projects protecting resident interests.",
    [
      "Drafts JDA protecting society member rights comprehensively",
      "Ensures RERA registration of JDA project is compliant",
      "Calculates fair area entitlement for existing residents",
      "Negotiates area ratio and corpus fund protections",
    ],
    "JDA structured for 3 Navrangpura society redevelopment \u2014 area entitlement secured",
    2341,
    94,
    7,
  ),
  a(
    "spec-leave-license",
    "Leave & License AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Generates Gujarat-compliant leave and license agreements with all protective clauses for landlords.",
    [
      "Drafts Leave & License agreement with all Gujarat requirements",
      "Ensures 11-month term structure for legal protection",
      "Includes inventory list and damage clause protections",
      "Advises on police intimation requirements in Gujarat",
    ],
    "Leave & license agreements drafted for 8 new rental arrangements this week",
    7890,
    93,
    7,
  ),
  a(
    "spec-lease-deed",
    "Lease Deed AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Drafts commercial lease deeds with all protective clauses for long-term commercial property leasing.",
    [
      "Drafts commercial lease deed for 1-5 year agreements",
      "Includes rent escalation, lock-in, and security deposit clauses",
      "Ensures stamp duty compliance for lease deed registration",
      "Protects landlord rights through comprehensive restrictive covenants",
    ],
    "Commercial lease deed drafted for 2 new office leasing arrangements",
    3456,
    93,
    7,
  ),
  a(
    "spec-sale-deed",
    "Sale Deed Verifier AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Reviews any sale deed, flags problematic clauses, and suggests legally protective amendments.",
    [
      "Reviews sale deed for missing and problematic clauses",
      "Flags possession delay and compensation clause gaps",
      "Ensures indemnity clause protects buyer from title defects",
      "Recommends amendments before execution and registration",
    ],
    "Sale deed reviewed for 6 transactions \u2014 2 required significant amendment",
    5678,
    95,
    7,
  ),
  a(
    "spec-gift-deed",
    "Gift Deed AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Drafts stamp duty-optimized gift deeds for property gifting within and outside family.",
    [
      "Drafts gift deed in Gujarat-compliant format",
      "Calculates stamp duty for different transferor-transferee relationships",
      "Advises on registered vs unregistered gift of movable vs immovable",
      "Integrates capital gains implications into gift structuring",
    ],
    "Gift deed drafted for mother-daughter property transfer \u2014 stamp duty exemption applied",
    3456,
    93,
    7,
  ),
  a(
    "spec-will",
    "Will Drafter AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Drafts basic property wills for Gujarat jurisdiction ensuring legal validity and clear succession.",
    [
      "Drafts property-focused will in legally valid format",
      "Advises on registered vs unregistered will benefits",
      "Ensures all Gujarat formalities for valid execution",
      "Provides guidance on executor selection and powers",
    ],
    "Property will drafted for 4 clients \u2014 all reviewed by empaneled advocate",
    2341,
    93,
    7,
  ),
  a(
    "spec-society-byelaws",
    "Society Bye-Laws AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Provides comprehensive guidance on Gujarat Cooperative Housing Society bye-laws.",
    [
      "Advises on GCHS bye-laws for all society matters",
      "Guides through maintenance charge dispute resolution",
      "Advises on NOC requirements for sale and renovation",
      "Interprets society resolutions for member rights",
    ],
    "Society bye-laws advisory: NOC dispute resolved for 2 flat sales",
    4567,
    92,
    7,
  ),
  a(
    "spec-noc",
    "NOC Intelligence AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Tracks all NOCs required for any property transaction and generates comprehensive compliance checklists.",
    [
      "Identifies all NOCs required for each transaction type",
      "Tracks NOC application and approval status",
      "Generates complete NOC checklist for every deal",
      "Advises on NOC waiver possibilities for urgent deals",
    ],
    "NOC checklist generated for 8 property transactions \u2014 all submitted within deadline",
    5678,
    93,
    7,
  ),
  a(
    "spec-building-perm",
    "Building Permission AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Provides step-by-step guidance on AMC building permissions and plan approvals.",
    [
      "Guides through AMC building permission process",
      "Tracks plan approval timeline and required documents",
      "Advises on FSI and setback compliance for new construction",
      "Monitors government notification changes for building rules",
    ],
    "Building permission guidance: commercial renovation plan approval process completed",
    3456,
    92,
    7,
  ),
  a(
    "spec-oc-cc",
    "OC & CC Intelligence AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Clarifies the importance and process of obtaining Occupancy Certificate and Completion Certificate.",
    [
      "Explains OC and CC importance for loan and sale",
      "Guides through AMC OC application process",
      "Identifies properties without OC for buyer risk advisory",
      "Tracks OC/CC application status for builder projects",
    ],
    "OC status verified for 12 properties \u2014 2 flagged as OC-pending for buyer advisory",
    6789,
    94,
    7,
  ),
  a(
    "spec-mutation",
    "Mutation & 7/12 AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Provides complete guidance on property mutation and 7/12 extract reading in Gujarat.",
    [
      "Guides through property mutation after purchase",
      "Reads and explains 7/12 extracts for all land types",
      "Tracks mutation completion timeline in Gujarat",
      "Advises on iHAR e-mutation portal filing process",
    ],
    "Mutation guidance provided for 5 recent property purchasers",
    4567,
    92,
    7,
  ),
  a(
    "spec-court-order",
    "Court Order Property AI",
    "specialist",
    "Legal Intelligence",
    "Legal & Compliance",
    "Provides guidance on properties sold through court orders and auction procedures.",
    [
      "Guides through court auction purchase procedures",
      "Advises on due diligence for court-ordered property sale",
      "Identifies encumbrances cleared by court order vs outstanding",
      "Coordinates with legal team for court sale documentation",
    ],
    "Court order property advisory: bank auction property purchase guidance for 2 investors",
    2341,
    93,
    7,
  ),
];

// ===== TECHNOLOGY SPECIALISTS (25) =====

const techSpecialists: ExtendedAgentDef[] = [
  a(
    "spec-realtime-sync",
    "Real-Time Sync AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Ensures all data across the platform is always synchronized with zero stale information.",
    [
      "Monitors data sync health across all platform modules",
      "Detects and resolves data consistency issues automatically",
      "Ensures property and lead data is always current",
      "Triggers resync when inconsistency detected",
    ],
    "Data sync health: all modules synchronized \u2014 zero stale data incidents today",
    89234,
    99,
    8,
  ),
  a(
    "spec-db-optimizer",
    "Database Optimizer AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Continuously optimizes database queries and indexes to maintain peak platform performance.",
    [
      "Monitors slow query log for optimization opportunities",
      "Automatically creates indexes for frequently used query patterns",
      "Runs VACUUM and maintenance operations during off-peak hours",
      "Reduces average query response time continuously",
    ],
    "Query optimization: 3 slow property search queries reduced from 2.3s to 0.18s",
    45678,
    99,
    8,
  ),
  a(
    "spec-cache",
    "Cache Intelligence AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Decides what to cache, when to invalidate, and manages cache strategy for optimal performance.",
    [
      "Optimizes cache hit rate for property listings",
      "Manages TTL for dynamic vs static content",
      "Detects cache poisoning and invalidates compromised entries",
      "Reduces backend load through intelligent prefetching",
    ],
    "Cache hit rate optimized to 94.7% \u2014 backend load reduced by 31%",
    34521,
    98,
    8,
  ),
  a(
    "spec-search-engine",
    "Search Engine AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Powers the property search with natural language understanding and intent recognition.",
    [
      "Powers NLU-based property search across 1051+ listings",
      'Understands queries like "3BHK near school in Bopal"',
      "Ranks results by relevance, recency, and buyer preference",
      "Continuously improves search quality from click data",
    ],
    'Search quality: natural language query "affordable flat near metro" returning relevant results',
    23451,
    97,
    8,
  ),
  a(
    "spec-filter-intel",
    "Filter Intelligence AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Learns which filters matter most per user and surfaces them prominently for faster property discovery.",
    [
      "Tracks most-used filter combinations per user segment",
      "Learns optimal filter defaults for each buyer profile",
      "Surfaces relevant filters before user needs to look",
      "Reduces filter-to-result time by 40% through intelligence",
    ],
    "Filter intelligence: personalized filter defaults deployed for 3 user segments",
    12340,
    96,
    8,
  ),
  a(
    "spec-autocomplete",
    "Autocomplete AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Powers intelligent autocomplete across all search boxes and forms for faster user input.",
    [
      "Powers location, property type, and feature autocomplete",
      "Learns frequent search patterns for predictive suggestions",
      "Reduces search time by 60% through smart autocomplete",
      "Handles Gujarati script and transliteration in searches",
    ],
    "Autocomplete quality: 87% of searches completed without full input",
    15678,
    96,
    8,
  ),
  a(
    "spec-recommendation",
    "Recommendation Engine AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    'Drives "you might also like" property recommendations for all visitors and registered users.',
    [
      "Generates personalized property recommendations for every user",
      "Uses collaborative filtering from similar buyer profiles",
      "Adapts recommendations based on browsing and enquiry history",
      "Increases property page views by 45% through recommendations",
    ],
    "Recommendations: 340 personalized property recommendation sets generated today",
    23451,
    97,
    8,
  ),
  a(
    "spec-personalization",
    "Personalization Engine AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Customizes the entire user experience based on individual user behavior and preferences.",
    [
      "Personalizes homepage content for each logged-in user",
      "Adapts property sort order to individual preferences",
      "Customizes email and WhatsApp content per user profile",
      "Tracks personalization impact on engagement and conversion",
    ],
    "Personalization: logged-in user experience customized for 234 active users",
    12340,
    97,
    8,
  ),
  a(
    "spec-ab-test",
    "A/B Test Manager AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Designs, runs, and analyzes experiments on platform features to drive conversion improvement.",
    [
      "Designs statistically valid A/B tests for platform features",
      "Monitors tests for statistical significance continuously",
      "Recommends winning variant for deployment",
      "Documents all test results for institutional learning",
    ],
    "A/B test result: shorter property enquiry form increased conversions by 18%",
    5678,
    95,
    8,
  ),
  a(
    "spec-error-detect",
    "Error Detection AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Continuously scans the live platform for JavaScript errors, broken APIs, and failed components.",
    [
      "Scans all pages for JavaScript errors in real time",
      "Monitors API endpoint health and response times",
      "Detects broken links and missing assets automatically",
      "Alerts on-call team within 60 seconds of critical errors",
    ],
    "Error detection: 0 critical errors detected today \u2014 all API endpoints healthy",
    89234,
    99,
    8,
  ),
  a(
    "spec-perf-monitor",
    "Performance Monitor AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Monitors Core Web Vitals and performance metrics for all pages across all devices.",
    [
      "Tracks LCP, FID, and CLS for all platform pages",
      "Monitors performance per device type and connection speed",
      "Identifies performance regressions after each deployment",
      "Reports performance trends to Technology Command AI",
    ],
    "Core Web Vitals: all pages green \u2014 LCP 1.8s, CLS 0.03 on mobile",
    67890,
    98,
    8,
  ),
  a(
    "spec-mobile-ux",
    "Mobile UX AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Specialized in mobile experience optimization targeting low-end Android devices used by majority of Indian users.",
    [
      "Optimizes UX for low-end Android devices (2GB RAM)",
      "Tests all features on 320px-480px viewport widths",
      "Identifies UX friction points on mobile through recording analysis",
      "Ensures all forms are single-column on mobile",
    ],
    "Mobile optimization: property enquiry form redesigned for 1-thumb operation",
    23451,
    97,
    8,
  ),
  a(
    "spec-accessibility",
    "Accessibility AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Ensures platform meets WCAG 2.1 AA accessibility standards for all users including disabled users.",
    [
      "Audits all pages for WCAG 2.1 AA compliance",
      "Tests screen reader compatibility across platform",
      "Ensures keyboard navigation works across all features",
      "Monitors color contrast ratios and text readability",
    ],
    "Accessibility score: 96/100 \u2014 WCAG AA compliance maintained across all pages",
    12340,
    97,
    8,
  ),
  a(
    "spec-pwa",
    "PWA Enhancement AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Continuously improves Progressive Web App capabilities for better install and offline experience.",
    [
      "Manages service worker for optimal offline caching",
      "Optimizes app manifest for all device home screen installs",
      "Monitors PWA install rates and install prompt effectiveness",
      "Improves app loading speed and offline page quality",
    ],
    "PWA install rate: 3.2% of mobile visitors installing \u2014 above industry average",
    8901,
    96,
    8,
  ),
  a(
    "spec-api-limiter",
    "API Rate Limiter AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Manages all external API usage to stay within budget and prevent rate limit errors.",
    [
      "Tracks API usage for all 4 AI providers in real time",
      "Implements intelligent rate limiting to prevent overages",
      "Queues and retries API calls when limits are approached",
      "Optimizes prompt efficiency to reduce API costs",
    ],
    "API usage: all providers within budget \u2014 OpenAI at 67% of daily limit",
    45678,
    98,
    8,
  ),
  a(
    "spec-webhook",
    "Webhook Intelligence AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Manages all inbound webhooks from external services for reliable event processing.",
    [
      "Manages webhook delivery verification and retry logic",
      "Monitors webhook failure rates and sends alerts",
      "Ensures idempotent processing to prevent duplicate actions",
      "Logs all webhook events for audit trail",
    ],
    "Webhook health: 100% delivery rate \u2014 234 events processed today",
    34521,
    97,
    8,
  ),
  a(
    "spec-data-migration",
    "Data Migration AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Handles all data migration tasks including property imports, exports, and transformations.",
    [
      "Manages bulk property import from Excel, CSV, JSON",
      "Handles fuzzy column mapping for messy import files",
      "Processes large imports in 500-row chunks with progress",
      "Validates all imported data before database insertion",
    ],
    "Data migration: 200 properties imported successfully \u2014 0 errors in last batch",
    15678,
    96,
    8,
  ),
  a(
    "spec-backup",
    "Backup Intelligence AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Manages all data backups and recovery testing to ensure zero data loss capability.",
    [
      "Executes daily automated backups with verification",
      "Tests backup restoration monthly to ensure integrity",
      "Monitors backup storage capacity and alerts on low space",
      "Maintains 30-day rolling backup window for all data",
    ],
    "Backup verified: all systems backed up at 3am IST \u2014 restoration test passed",
    67890,
    99,
    8,
  ),
  a(
    "spec-cdn",
    "CDN Optimizer AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Optimizes content delivery for Ahmedabad users across all Indian mobile networks.",
    [
      "Manages CDN edge node selection for Indian visitors",
      "Optimizes image compression for 3G/4G network conditions",
      "Monitors CDN cache hit rates and adjusts TTL settings",
      "Ensures fast property image loading across all networks",
    ],
    "CDN performance: average image load time 0.34s for Ahmedabad visitors",
    23451,
    97,
    8,
  ),
  a(
    "spec-image-opt",
    "Image Optimizer AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Automatically compresses and optimizes all property images for web without quality loss.",
    [
      "Converts all property images to WebP automatically",
      "Compresses images to under 100KB without visible quality loss",
      "Generates responsive image srcsets for all viewport sizes",
      "Lazy loads property images for faster initial page load",
    ],
    "Image optimization: 340 new property images processed \u2014 avg 78% size reduction",
    45678,
    98,
    8,
  ),
  a(
    "spec-pdf-gen",
    "PDF Generator AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Creates all PDFs including property brochures, proposals, and agreements with perfect rendering.",
    [
      "Generates pixel-perfect property brochure PDFs",
      "Creates proposal PDFs with correct formatting",
      "Ensures all PDF forms are fillable and accessible",
      "Validates PDF rendering across all major PDF readers",
    ],
    "PDF generation: 23 property brochures and 8 proposals generated today",
    12340,
    97,
    8,
  ),
  a(
    "spec-qr-mgr",
    "QR Code Manager AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Generates, tracks, and manages all QR codes across the platform for properties and marketing.",
    [
      "Generates dynamic QR codes for all property listings",
      "Tracks QR code scan rates and source attribution",
      "Updates QR destination URLs without regenerating codes",
      "Integrates QR scanning into property enquiry flow",
    ],
    "QR codes: 1051+ property QR codes active \u2014 47 scans tracked today",
    8901,
    95,
    8,
  ),
  a(
    "spec-deeplink",
    "Deep Link Intelligence AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Manages all deep links to ensure correct page navigation from external sources.",
    [
      "Manages deep links for all 50+ platform page types",
      "Ensures all deep links work after URL structure changes",
      "Tracks deep link traffic sources and conversion rates",
      "Generates shareable deep links for WhatsApp property sharing",
    ],
    "Deep link audit: all 50+ page types validated \u2014 0 broken deep links",
    12340,
    96,
    8,
  ),
  a(
    "spec-progressive-load",
    "Progressive Loading AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Manages skeleton screens, lazy loading, and incremental rendering for perceived performance.",
    [
      "Implements skeleton screens for all content-heavy pages",
      "Manages lazy loading for property images and lists",
      "Prioritizes above-fold content rendering first",
      "Reduces Time to First Contentful Paint by 40%",
    ],
    "Progressive loading: Time to Interactive reduced to 1.8s on property portal",
    23451,
    97,
    8,
  ),
  a(
    "spec-offline-sync",
    "Offline Sync AI",
    "specialist",
    "Technology Intelligence",
    "Technology",
    "Manages offline data storage and resolves conflicts when connectivity is restored.",
    [
      "Caches core pages for offline access via service worker",
      "Stores form data locally when offline for later sync",
      "Resolves data conflicts when back online with merge logic",
      "Shows clear offline status to users with feature guidance",
    ],
    "Offline mode: 3 core pages fully functional offline on test devices",
    8901,
    95,
    8,
  ),
];

// ===== CONTENT INTELLIGENCE SPECIALISTS (25) =====

const contentSpecialists: ExtendedAgentDef[] = [
  a(
    "spec-pillar-content",
    "Pillar Content AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Creates authoritative long-form content establishing MSTC GLOBAL as Ahmedabad real estate knowledge authority.",
    [
      "Creates 3,000+ word pillar content pieces for key topics",
      "Optimizes for top-3 Google ranking on target keywords",
      "Updates pillar content quarterly with fresh market data",
      "Links to supporting cluster content for SEO power",
    ],
    'Pillar content: "Complete Guide to Buying Property in Ahmedabad" \u2014 4,200 words published',
    3456,
    94,
    7,
  ),
  a(
    "spec-topic-cluster",
    "Topic Cluster AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Builds interconnected content clusters for complete SEO domination of Ahmedabad real estate topics.",
    [
      "Maps 50+ topic clusters for Ahmedabad real estate",
      "Creates content briefs for each cluster supporting page",
      "Manages internal linking strategy across all content",
      "Tracks cluster ranking performance monthly",
    ],
    'Topic cluster: "Home Loans Ahmedabad" cluster \u2014 8 supporting pages complete',
    2341,
    93,
    7,
  ),
  a(
    "spec-keyword",
    "Keyword Opportunity AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Identifies low-competition, high-value keywords for Ahmedabad real estate search optimization.",
    [
      "Identifies keywords with low competition and high buyer intent",
      "Tracks keyword ranking changes monthly",
      "Finds semantic keywords and question-based query opportunities",
      "Prioritizes keywords by revenue potential per ranking",
    ],
    'Keyword opportunity: "affordable flats near Bopal metro" \u2014 zero-competition keyword identified',
    4512,
    94,
    7,
  ),
  a(
    "spec-featured-snippet",
    "Featured Snippet AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Optimizes content specifically to appear in Google featured snippets and answer boxes.",
    [
      "Optimizes content structure for featured snippet capture",
      "Identifies questions where MSTC can win position zero",
      "Creates concise, structured answers for snippet-eligible queries",
      "Tracks featured snippet wins and losses monthly",
    ],
    'Featured snippet captured: "stamp duty Ahmedabad 2025" \u2014 position zero achieved',
    3456,
    93,
    7,
  ),
  a(
    "spec-local-seo",
    "Local SEO AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Manages Google My Business and local search optimization for Ahmedabad real estate searches.",
    [
      "Optimizes Google My Business profile continuously",
      "Manages local citation consistency across 50+ directories",
      "Tracks local pack ranking for Ahmedabad real estate queries",
      "Generates geotagged content for hyper-local ranking",
    ],
    'Local SEO: MSTC GLOBAL ranked #1 in Google Maps for "real estate agent Ahmedabad"',
    5678,
    96,
    7,
  ),
  a(
    "spec-voice-search",
    "Voice Search AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Optimizes all content for voice queries including OK Google and Alexa real estate questions.",
    [
      "Optimizes content for conversational voice queries",
      "Creates FAQ content matching natural voice question patterns",
      "Ensures fast mobile loading critical for voice search ranking",
      "Tracks voice search traffic and query patterns",
    ],
    "Voice search optimization: 12 FAQ pages updated for conversational query patterns",
    2341,
    91,
    7,
  ),
  a(
    "spec-video-script",
    "Video Script AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Creates professional video scripts for property tours, market updates, and educational content.",
    [
      "Writes engaging property tour video scripts",
      "Creates market update video content in MD's voice",
      "Develops educational video scripts for first-time buyers",
      "Optimizes video scripts for YouTube and Instagram Reels",
    ],
    "Video script: Ahmedabad Q1 market update \u2014 3-minute script drafted and approved",
    1890,
    93,
    7,
  ),
  a(
    "spec-podcast",
    "Podcast Script AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Develops podcast content covering Ahmedabad real estate market insights and advisory content.",
    [
      "Creates podcast episode outlines and scripts",
      "Develops interview question guides for guest episodes",
      "Writes show notes and podcast description for SEO",
      "Identifies trending topics for podcast content calendar",
    ],
    'Podcast script: "Is Bopal the next SG Highway?" \u2014 episode script completed',
    1234,
    91,
    7,
  ),
  a(
    "spec-infographic",
    "Infographic Data AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Produces data and visualizations for shareable real estate infographics for social media.",
    [
      "Compiles market data for visual infographic creation",
      "Identifies most shareable data points from market reports",
      "Creates data tables for designer formatting",
      "Tracks infographic share counts and reach",
    ],
    'Infographic data: "Ahmedabad Property Market 2025" \u2014 data compiled for designer',
    2341,
    92,
    7,
  ),
  a(
    "spec-press-release",
    "Press Release AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Drafts professional press releases for MSTC GLOBAL milestones and market announcements.",
    [
      "Drafts press releases in AP style for Gujarat media",
      "Targets appropriate media outlets for each announcement",
      "Follows up with journalists for coverage confirmation",
      "Tracks press release pickup rate across Gujarat media",
    ],
    "Press release: MSTC 25-year anniversary drafted \u2014 Gujarat Samachar coverage secured",
    1234,
    92,
    7,
  ),
  a(
    "spec-linkedin",
    "LinkedIn Content AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Creates professional LinkedIn content optimizing MSTC brand authority in real estate.",
    [
      "Creates thought leadership posts for MD LinkedIn profile",
      "Develops property market insights for LinkedIn Articles",
      "Manages LinkedIn company page content calendar",
      "Tracks LinkedIn post engagement and follower growth",
    ],
    "LinkedIn: MD thought leadership post on Ahmedabad market \u2014 2,400 impressions",
    3456,
    93,
    7,
  ),
  a(
    "spec-instagram",
    "Instagram Content AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Creates visual content strategy for Instagram including Reels, Stories, and carousel posts.",
    [
      "Creates Instagram Reels scripts for property tours",
      "Designs carousel post content for market insights",
      "Develops Instagram Stories content calendar",
      "Tracks Instagram reach, saves, and profile visits",
    ],
    "Instagram: property tour Reel for Vastrapur apartment \u2014 12,000 views in 48 hours",
    4512,
    93,
    7,
  ),
  a(
    "spec-youtube",
    "YouTube Optimization AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Optimizes video content for maximum YouTube visibility in real estate searches.",
    [
      "Optimizes YouTube video titles for search discoverability",
      "Creates keyword-rich descriptions for all property videos",
      "Develops thumbnail A/B test recommendations",
      "Tracks YouTube watch time and subscriber growth",
    ],
    "YouTube: 3 property tour videos optimized \u2014 avg watch time improved to 3.2 minutes",
    2341,
    92,
    7,
  ),
  a(
    "spec-whatsapp-status",
    "WhatsApp Status AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Creates compelling WhatsApp Business status content for maximum client reach.",
    [
      "Creates daily WhatsApp Status content strategy",
      "Designs property showcase and market update status posts",
      "Tracks status view counts per content type",
      "Optimizes status posting time for maximum views",
    ],
    "WhatsApp Status: daily property highlight reaching 1,200+ contacts",
    5678,
    93,
    7,
  ),
  a(
    "spec-email-newsletter",
    "Email Newsletter AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Compiles monthly newsletters tailored to each client segment with relevant content.",
    [
      "Compiles monthly newsletter for each client segment",
      "Personalizes content mix based on individual preferences",
      "Tracks open rate and click rate per newsletter segment",
      "A/B tests subject lines for maximum open rate",
    ],
    "Newsletter: March 2025 edition sent to 2,341 subscribers \u2014 38% open rate",
    4512,
    94,
    7,
  ),
  a(
    "spec-sms-campaign",
    "SMS Campaign AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Creates concise, high-impact SMS campaigns for each marketing objective.",
    [
      "Creates 160-character SMS campaigns with clear CTA",
      "Segments SMS lists for targeted delivery",
      "Tracks SMS delivery rate and response rate",
      "Ensures DND compliance for all SMS campaigns",
    ],
    "SMS campaign: price drop alert \u2014 847 SMSs sent, 12% response rate",
    7890,
    93,
    7,
  ),
  a(
    "spec-festival-content",
    "Festival Content AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Creates seasonal content for Diwali, Navratri, Uttarayan, Republic Day, and all festivals.",
    [
      "Creates themed property content for all major festivals",
      "Designs festival greeting campaigns with MSTC branding",
      "Times publication for maximum festival engagement",
      "Tracks festival content performance vs evergreen content",
    ],
    "Festival content: Navratri property market special \u2014 4,200 organic reach",
    3456,
    92,
    7,
  ),
  a(
    "spec-market-report",
    "Market Report AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Generates monthly Ahmedabad real estate market reports published automatically.",
    [
      "Compiles monthly market data from 15+ sources",
      "Writes market commentary in professional analytical style",
      "Creates data visualizations for key market metrics",
      "Publishes report on website with SEO optimization",
    ],
    "Monthly report: March 2025 Ahmedabad Market Report published \u2014 890 downloads",
    3456,
    94,
    7,
  ),
  a(
    "spec-case-study",
    "Case Study AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Creates anonymized client success stories for MSTC GLOBAL marketing and trust building.",
    [
      "Creates anonymized case studies from successful deals",
      "Identifies most impactful deal elements for storytelling",
      "Structures case studies for maximum credibility",
      "Ensures client privacy through complete anonymization",
    ],
    'Case study: "How NRI family found dream home remotely" \u2014 approved and published',
    1234,
    92,
    7,
  ),
  a(
    "spec-testimonial",
    "Testimonial Intelligence AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Collects, verifies, and publishes only genuine client testimonials across all channels.",
    [
      "Identifies clients appropriate for testimonial requests",
      "Verifies authenticity of all submitted testimonials",
      "Publishes testimonials with appropriate consent documentation",
      "Tracks testimonial conversion impact on new enquiries",
    ],
    "Testimonials: 4 new verified client testimonials collected this month",
    2341,
    93,
    7,
  ),
  a(
    "spec-competitor",
    "Competitor Analysis AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Conducts deep analysis of competitor websites, content, and market positioning.",
    [
      "Monitors top 10 Ahmedabad real estate competitor websites",
      "Tracks competitor content publication frequency and topics",
      "Identifies competitor SEO weaknesses for MSTC opportunity",
      "Reports competitor strategy changes monthly",
    ],
    "Competitor report: PropTiger reducing Ahmedabad investment \u2014 MSTC opportunity window",
    1890,
    93,
    7,
  ),
  a(
    "spec-content-calendar",
    "Content Calendar AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Plans all content 3 months ahead aligned with market cycles and festival calendar.",
    [
      "Creates 90-day content calendar across all channels",
      "Aligns content to market events, RBI meetings, and festivals",
      "Coordinates content production across 5 content types",
      "Tracks content calendar execution rate weekly",
    ],
    "Content calendar: Q2 2025 calendar finalized \u2014 67 pieces planned across channels",
    2341,
    92,
    7,
  ),
  a(
    "spec-repurposing",
    "Repurposing AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Converts one piece of content into 8 different formats for maximum distribution efficiency.",
    [
      "Converts one blog post into 8 content formats",
      "Creates social posts, newsletter excerpt, and video script from single article",
      "Tracks which repurposed formats perform best per topic",
      "Identifies evergreen content worth repurposing repeatedly",
    ],
    "Repurposing: March market report converted to 7 social posts, 1 email, 1 video script",
    1890,
    92,
    7,
  ),
  a(
    "spec-translation",
    "Translation Quality AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Ensures all Gujarati and Hindi content reads naturally and culturally appropriately.",
    [
      "Translates content to Gujarati and Hindi natively",
      "Ensures translations are culturally appropriate and natural",
      "Reviews AI-translated content for quality before publication",
      "Maintains glossary of Ahmedabad real estate terms in 3 languages",
    ],
    "Translation quality review: 12 Gujarati and Hindi content pieces approved this week",
    3456,
    94,
    7,
  ),
  a(
    "spec-brand-voice",
    "Brand Voice Consistency AI",
    "specialist",
    "Content Intelligence",
    "Content",
    "Ensures all content across all channels sounds consistently MSTC GLOBAL in tone and voice.",
    [
      "Maintains MSTC brand voice guidelines across all content",
      "Reviews all content for tone and voice consistency",
      "Updates brand voice guide based on MD feedback",
      "Flags content that deviates from established voice",
    ],
    "Brand voice audit: 34 content pieces reviewed \u2014 all consistent with MSTC guidelines",
    2341,
    93,
    7,
  ),
];

// ===== ANALYTICS & DATA SCIENCE SPECIALISTS (30) =====

const analyticsSpecialists: ExtendedAgentDef[] = [
  a(
    "spec-cohort",
    "Cohort Analysis AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Tracks how different client cohorts behave over time to improve retention and conversion.",
    [
      "Segments clients into monthly acquisition cohorts",
      "Tracks retention and conversion rates per cohort",
      "Identifies best-performing acquisition channels by cohort quality",
      "Provides cohort-based LTV projections",
    ],
    "Cohort analysis: Jan 2025 cohort showing 34% higher 90-day retention vs Dec 2024",
    15678,
    95,
    8,
  ),
  a(
    "spec-funnel",
    "Funnel Analysis AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Maps the complete conversion funnel and identifies the biggest drop-off points for optimization.",
    [
      "Maps full enquiry-to-close conversion funnel",
      "Identifies stages with highest client drop-off rates",
      "Recommends specific improvements per funnel stage",
      "Tracks funnel improvement from experiments over time",
    ],
    "Funnel analysis: site-visit-to-offer stage identified as biggest drop-off \u2014 23% conversion",
    12340,
    95,
    8,
  ),
  a(
    "spec-attribution",
    "Attribution Intelligence AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Tracks which touchpoints actually drive deal closures using multi-touch attribution.",
    [
      "Applies multi-touch attribution across all channels",
      "Identifies most influential touchpoints before deal closure",
      "Calculates true cost per acquisition by channel",
      "Recommends budget reallocation to highest-performing channels",
    ],
    "Attribution insight: WhatsApp follow-up at 48 hours is most influential touchpoint",
    9012,
    95,
    8,
  ),
  a(
    "spec-ltv",
    "Lifetime Value Predictor AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Predicts total client lifetime value within 24 hours of first contact.",
    [
      "Predicts CLV within 24 hours of first interaction",
      "Identifies high-LTV clients for priority treatment",
      "Calculates LTV by client segment for resource allocation",
      "Tracks LTV prediction accuracy vs actuals quarterly",
    ],
    "LTV prediction: new NRI lead predicted \u20b924L LTV over 3-year relationship",
    8901,
    94,
    8,
  ),
  a(
    "spec-churn-analysis",
    "Churn Analysis AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Identifies patterns in clients who stopped engaging and improves retention strategies.",
    [
      "Analyzes behavioral patterns preceding client disengagement",
      "Identifies 3 most common churn triggers across segments",
      "Recommends retention strategies based on churn reasons",
      "Tracks churn rate changes monthly across all segments",
    ],
    "Churn analysis: peak churn at 45 days of no contact \u2014 re-engagement triggered at 30 days",
    7823,
    94,
    8,
  ),
  a(
    "spec-win-loss",
    "Win/Loss Analysis AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Analyzes why deals closed and why they fell through for continuous improvement.",
    [
      "Codes all closed deals by win reason and lost deals by loss reason",
      "Identifies top 5 reasons for deal loss across segments",
      "Tracks win/loss trends monthly for strategic adjustment",
      "Provides deal-specific recommendations based on win/loss patterns",
    ],
    "Win/loss insight: price expectation gap is #1 reason for deal loss in Q1 2025",
    6789,
    94,
    8,
  ),
  a(
    "spec-price-elasticity",
    "Price Elasticity AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Measures how enquiry volume responds to listing price changes for pricing optimization.",
    [
      "Measures price sensitivity by property type and locality",
      "Calculates enquiry volume change per 5% price movement",
      "Identifies optimal price points for maximum enquiry volume",
      "Advises on price reduction thresholds for stale listings",
    ],
    "Price elasticity: 5% reduction in asking price increases enquiries by 28% in Gota",
    5678,
    93,
    8,
  ),
  a(
    "spec-demand-forecast",
    "Demand Forecasting AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Predicts enquiry volume by property type and locality for the next quarter.",
    [
      "Forecasts monthly enquiry volume by segment and locality",
      "Integrates macro signals, seasonality, and trend data",
      "Provides 90-day demand forecast with confidence intervals",
      "Updates forecast weekly with latest leading indicators",
    ],
    "Demand forecast: Q2 2025 \u2014 847 enquiries projected \u00b1 34 (8.4% growth vs Q1)",
    12340,
    95,
    8,
  ),
  a(
    "spec-capacity",
    "Capacity Planning AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Predicts when team will be overwhelmed and recommends hiring and tool investment timing.",
    [
      "Forecasts agent workload 60 days ahead",
      "Identifies capacity constraints before they impact client service",
      "Recommends optimal team size for projected demand",
      "Models impact of automation on capacity requirements",
    ],
    "Capacity planning: April 2025 \u2014 team at 94% capacity, 1 additional agent recommended",
    4512,
    93,
    8,
  ),
  a(
    "spec-roi-attr",
    "ROI Attribution AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Calculates precise ROI of every marketing spend, channel, and campaign.",
    [
      "Calculates ROI for every active marketing channel",
      "Attributes revenue contribution to each spend category",
      "Identifies channels with negative ROI for budget reallocation",
      "Projects future ROI based on optimization actions",
    ],
    "ROI analysis: WhatsApp marketing delivering 12x ROI \u2014 highest among all channels",
    6789,
    94,
    8,
  ),
  a(
    "spec-heatmap",
    "Heatmap Intelligence AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Analyzes user click patterns and scroll behavior to optimize page layouts.",
    [
      "Analyzes click heatmaps for all major property pages",
      "Identifies scroll depth patterns and content abandonment points",
      "Recommends above-fold content changes from heatmap data",
      "Tracks heatmap changes after redesigns for validation",
    ],
    "Heatmap insight: property price is most-clicked element \u2014 moved above fold",
    8901,
    94,
    8,
  ),
  a(
    "spec-session-rec",
    "Session Recording AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Reviews user session recordings to identify UX problems and conversion opportunities.",
    [
      "Reviews 50+ session recordings weekly for UX issues",
      "Identifies rage clicks and error clicks on key pages",
      "Finds form abandonment patterns in session recordings",
      "Reports top-3 UX friction points monthly",
    ],
    "Session recording insight: mobile form abandoned due to keyboard overlap \u2014 fixed",
    7890,
    93,
    8,
  ),
  a(
    "spec-error-pattern",
    "Error Pattern AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Identifies recurring error patterns across user sessions for systematic issue resolution.",
    [
      "Tracks all JavaScript errors by frequency and impact",
      "Identifies error patterns specific to device or browser type",
      "Prioritizes error resolution by user impact score",
      "Reports top errors to Technology Command AI weekly",
    ],
    "Error pattern analysis: Safari CSS issue identified from 340 affected sessions",
    9012,
    94,
    8,
  ),
  a(
    "spec-search-analytics",
    "Search Analytics AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Analyzes all property search queries to identify missing inventory and content gaps.",
    [
      "Analyzes top 100 search queries monthly for gaps",
      "Identifies property types with high search, low inventory",
      "Detects emerging search trends before they peak",
      "Reports search-inventory gaps to property GMs",
    ],
    'Search gap identified: "2BHK under 50L Chandkheda" \u2014 340 searches, 2 listings',
    12340,
    95,
    8,
  ),
  a(
    "spec-comparison",
    "Comparison Analytics AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Tracks which properties users compare most to identify decision factors and preferences.",
    [
      "Tracks property comparison patterns across buyer segments",
      "Identifies most compared features by segment type",
      "Detects comparison outcomes leading to deals vs abandonment",
      "Recommends property matching improvements from comparison data",
    ],
    "Comparison analytics: price/sqft is most compared factor across all segments",
    7890,
    94,
    8,
  ),
  a(
    "spec-shortlist",
    "Shortlist Analysis AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Analyzes shortlisting patterns to predict purchase probability and guide agent focus.",
    [
      "Correlates shortlist size with conversion probability",
      "Identifies optimal shortlist length for fastest conversion",
      "Detects when shortlist stagnation signals decision paralysis",
      "Recommends agent intervention triggers based on shortlist behavior",
    ],
    "Shortlist insight: clients with 3-5 shortlisted properties convert at 42% \u2014 highest rate",
    6789,
    93,
    8,
  ),
  a(
    "spec-contact-method",
    "Contact Method AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Identifies which contact methods convert best for each buyer segment.",
    [
      "Tracks enquiry source by contact method per segment",
      "Compares conversion rates: phone vs WhatsApp vs form",
      "Identifies optimal contact channel per buyer profile",
      "Optimizes CTA placement based on channel performance data",
    ],
    "Contact method insight: WhatsApp contact converts 3x better than phone for investors",
    8901,
    95,
    8,
  ),
  a(
    "spec-time-of-day",
    "Time-of-Day AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Identifies when clients are most responsive to optimize outreach timing.",
    [
      "Analyzes response rate by hour for every client type",
      "Identifies optimal contact windows per buyer segment",
      "Schedules automated outreach at highest-response times",
      "Tracks time-sensitivity of response to inbound enquiries",
    ],
    "Time optimization: 7-8pm IST identified as peak response window for NRI clients",
    9012,
    95,
    8,
  ),
  a(
    "spec-day-of-week",
    "Day-of-Week AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Identifies which days close the most deals to optimize team scheduling and campaign timing.",
    [
      "Analyzes deal closure rates by day of week",
      "Identifies optimal days for site visits and negotiations",
      "Schedules campaign launches on highest-conversion days",
      "Tracks seasonal variation in day-of-week patterns",
    ],
    "Day analysis: Saturday site visits convert to offers at 2.4x weekday rate",
    7890,
    94,
    8,
  ),
  a(
    "spec-seasonality",
    "Seasonality Intelligence AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Maintains a complete seasonal model of Ahmedabad property market for all planning decisions.",
    [
      "Maintains 5-year seasonal demand model for Ahmedabad",
      "Predicts seasonal peaks: post-Diwali, Q4, financial year-end",
      "Adjusts marketing spend recommendations to seasonal patterns",
      "Forecasts seasonal team capacity requirements",
    ],
    "Seasonality model: October-November identified as MSTC peak conversion season",
    12340,
    96,
    8,
  ),
  a(
    "spec-geo-cluster",
    "Geographic Cluster AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Maps all clients and deals geographically to identify concentration patterns and opportunities.",
    [
      "Maps all client locations and deal closure geographies",
      "Identifies neighborhood clusters with highest buyer density",
      "Discovers untapped geographic markets for targeted outreach",
      "Tracks geographic expansion of MSTC client base",
    ],
    "Geographic cluster: Prahladnagar resident buyers cluster \u2014 targeted campaign launched",
    8901,
    94,
    8,
  ),
  a(
    "spec-network-analysis",
    "Network Analysis AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Analyzes referral relationship networks to identify most valuable connection nodes.",
    [
      "Maps complete referral network across all clients",
      "Identifies super-referrers generating most new business",
      "Calculates network centrality for each referring client",
      "Recommends engagement investment by network value",
    ],
    "Network analysis: 3 super-referrers responsible for 34% of new leads \u2014 VIP treatment initiated",
    6789,
    94,
    8,
  ),
  a(
    "spec-satisfaction",
    "Satisfaction Score AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Tracks real-time NPS and CSAT across all client touchpoints.",
    [
      "Tracks NPS score across all major client touchpoints",
      "Monitors CSAT scores for each service interaction",
      "Identifies satisfaction drivers and detractors from responses",
      "Correlates satisfaction scores with repeat business and referrals",
    ],
    "NPS score: 71 \u2014 up 8 points from Q4 2024",
    12340,
    95,
    8,
  ),
  a(
    "spec-complaint-pattern",
    "Complaint Pattern AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Identifies recurring complaint themes for systemic operational improvements.",
    [
      "Codes all complaints by root cause category",
      "Identifies top-3 complaint themes driving dissatisfaction",
      "Tracks complaint resolution rate and time-to-resolve",
      "Drives systemic fixes for recurring complaint patterns",
    ],
    "Complaint insight: documentation delay is top complaint \u2014 process improvement initiated",
    4512,
    93,
    8,
  ),
  a(
    "spec-feature-usage",
    "Feature Usage AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Identifies which platform features get used vs ignored to inform development priorities.",
    [
      "Tracks feature adoption rate for all 50+ platform features",
      "Identifies underused features for UX improvement",
      "Monitors feature usage trends after each platform update",
      "Prioritizes feature development by actual usage demand",
    ],
    "Feature usage: EMI calculator most used tool \u2014 2,341 uses this month",
    7890,
    94,
    8,
  ),
  a(
    "spec-device-usage",
    "Device Usage AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Tracks device, browser, and OS patterns to prioritize compatibility and optimization.",
    [
      "Tracks device OS and browser market share among users",
      "Identifies device types causing most UX issues",
      "Prioritizes device-specific fixes by user impact",
      "Monitors device trends for future-proofing decisions",
    ],
    "Device data: 78% mobile Android \u2014 Pixel and Samsung models prioritized for testing",
    8901,
    95,
    8,
  ),
  a(
    "spec-bandwidth",
    "Bandwidth Intelligence AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Adapts platform behavior intelligently for users on slow 2G/3G connections.",
    [
      "Detects connection speed for each user session",
      "Serves optimized low-bandwidth experience on slow connections",
      "Reduces image quality and disables animations on 2G",
      "Tracks slow-connection users for performance priority",
    ],
    "Bandwidth optimization: 2G-optimized property listings serving 340 slow-connection users",
    6789,
    94,
    8,
  ),
  a(
    "spec-geo-coverage",
    "Geographic Coverage AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Identifies which Ahmedabad localities have gaps in property inventory coverage.",
    [
      "Audits property inventory coverage by locality",
      "Identifies localities with high demand but low supply listings",
      "Recommends inventory acquisition targets to GMs",
      "Tracks coverage improvement monthly after targeted sourcing",
    ],
    "Coverage gap: Naranpura has 8x more demand than inventory \u2014 sourcing sprint initiated",
    5678,
    93,
    8,
  ),
  a(
    "spec-market-share",
    "Market Share AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Estimates MSTC market share of Ahmedabad real estate enquiries over time.",
    [
      "Estimates MSTC share of Ahmedabad real estate market",
      "Tracks market share changes quarterly with trend analysis",
      "Benchmarks MSTC share against 3 main competitors",
      "Identifies segment where MSTC is gaining vs losing share",
    ],
    "Market share estimate: MSTC at 6.2% of Ahmedabad premium residential enquiries",
    4512,
    93,
    8,
  ),
  a(
    "spec-benchmark",
    "Benchmark Intelligence AI",
    "specialist",
    "Analytics Intelligence",
    "Analytics",
    "Continuously benchmarks MSTC performance against industry best practices and competitors.",
    [
      "Benchmarks MSTC KPIs against real estate industry standards",
      "Tracks performance gap vs best-in-class platforms",
      "Identifies specific metrics where MSTC leads and lags",
      "Produces monthly benchmark report for management",
    ],
    "Benchmark report: MSTC lead response time (4.2 min) beats industry average (18 min)",
    3456,
    93,
    8,
  ),
];

// ===== EXPORT ALL 135 AGENTS =====

export const EXTENDED_AGENTS_3: ExtendedAgentDef[] = [
  ...clientSpecialists,
  ...legalSpecialists,
  ...techSpecialists,
  ...contentSpecialists,
  ...analyticsSpecialists,
];
