// AIManagerData_Agents5.ts
// MSTC GLOBAL — Extended AI Agents Batch 5 (200 agents)
// Automation, Creative, Expansion, Neural, Quality, Knowledge, Vertical, Continuous Improvement

import type { ExtendedAgentDef } from "./AIManagerData_Extended";

const a = (
  id: string,
  name: string,
  tier: string,
  category: string,
  domain: string,
  desc: string,
  caps: string[],
  lastAction: string,
  tasks: number,
  perf: number,
  al: number,
): ExtendedAgentDef => ({
  id,
  name,
  tier,
  category,
  domain,
  description: desc,
  capabilities: caps,
  status: "active" as const,
  autonomyLevel: al,
  selfTaskEnabled: true,
  lastAction,
  tasksCompleted: tasks,
  performanceScore: perf,
});

// ─── AUTOMATION INTELLIGENCE SPECIALISTS (25) ─────────────────────────────
const AUTO_CAPS = [
  "Autonomously executes multi-step workflows",
  "Personalizes outreach with client context",
  "Optimizes timing for maximum response rate",
  "Self-adjusts triggers based on outcomes",
];

const automationAgents: ExtendedAgentDef[] = [
  a(
    "auto-trigger",
    "Trigger Intelligence AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Decides when each automation trigger should fire based on behavioral and time signals.",
    AUTO_CAPS,
    "Trigger logic updated: enquiry-to-follow-up now fires at 47 minutes — 31% response improvement",
    45678,
    97,
    9,
  ),
  a(
    "auto-sequence",
    "Sequence Optimizer AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Optimizes multi-step communication sequences based on real response data.",
    AUTO_CAPS,
    "Sequence optimized: 3-touch sequence outperforms 5-touch for investor segment",
    34521,
    96,
    9,
  ),
  a(
    "auto-multichannel",
    "Multi-Channel Orchestrator AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Coordinates WhatsApp, email, and SMS channels simultaneously for each automation.",
    AUTO_CAPS,
    "Multi-channel campaign: 847 leads reached across 3 channels — 23% response rate",
    89234,
    98,
    9,
  ),
  a(
    "auto-timezone",
    "Time Zone Manager AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Ensures all NRI clients are contacted at appropriate times in their timezone.",
    AUTO_CAPS,
    "Timezone schedule updated for Dubai (+3.5 IST), USA (-10.5 IST), UK (-5.5 IST)",
    12340,
    95,
    9,
  ),
  a(
    "auto-frequency",
    "Contact Frequency AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Ensures clients are not over-contacted or under-contacted through intelligent frequency management.",
    AUTO_CAPS,
    "Contact frequency optimized: HNI segment reduced to 1x/week — satisfaction up 12%",
    23451,
    96,
    9,
  ),
  a(
    "auto-personalize",
    "Message Personalization AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Personalizes every automated message with client-specific property and preference context.",
    AUTO_CAPS,
    "Personalization: 2,341 unique message variants generated for monthly newsletter",
    45678,
    97,
    9,
  ),
  a(
    "auto-template",
    "Template Intelligence AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Manages all message templates and continuously improves them based on response data.",
    AUTO_CAPS,
    "Template library updated: 8 new templates added, 3 retired based on performance data",
    15678,
    95,
    9,
  ),
  a(
    "auto-drip",
    "Drip Campaign AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Designs and runs multi-step drip campaigns for long-cycle property purchase decisions.",
    AUTO_CAPS,
    "Drip campaign: 2,341 first-time buyers in 12-touch sequence — 34% engagement rate",
    34521,
    97,
    9,
  ),
  a(
    "auto-event-trigger",
    "Event-Triggered AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Fires specific personalized actions when clients view properties 3+ times, prices drop, or new matches found.",
    AUTO_CAPS,
    "Event trigger: 12 buyers notified within 2 minutes of price drop on shortlisted properties",
    89234,
    98,
    9,
  ),
  a(
    "auto-reengage",
    "Re-Engagement Flow AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Runs automated multi-step re-engagement campaigns for clients dormant 30/60/90 days.",
    AUTO_CAPS,
    "Re-engagement: 891 dormant leads in sequence — 7.2% reactivation rate this month",
    23451,
    96,
    9,
  ),
  a(
    "auto-festive",
    "Festive Campaign Orchestrator AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Runs complete festival campaigns automatically including Diwali, Navratri, New Year, and Uttarayan.",
    AUTO_CAPS,
    "Diwali 2025 campaign launched: 1,247 clients reached — 34% open rate",
    12340,
    97,
    9,
  ),
  a(
    "auto-birthday",
    "Birthday Campaign AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Sends personalized birthday messages with relevant property recommendations to all clients.",
    AUTO_CAPS,
    "Birthday campaigns sent: 23 today — 87% open rate on birthday messages",
    8901,
    96,
    9,
  ),
  a(
    "auto-anniversary",
    "Anniversary Campaign AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Sends property purchase anniversary messages with upsell opportunities for all past clients.",
    AUTO_CAPS,
    "Anniversary campaign: 12 clients reached on property purchase anniversary — 3 upgrade enquiries",
    5678,
    95,
    9,
  ),
  a(
    "auto-newyear",
    "New Year Campaign AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Runs financial year end and calendar year campaigns for maximum seasonal conversion.",
    AUTO_CAPS,
    "New Year property campaign scheduled for April 1 FY-end — 3,200 clients in sequence",
    7890,
    96,
    9,
  ),
  a(
    "auto-launch",
    "Builder Project Launch AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Sends automated campaigns when a new builder project launches that matches buyer preferences.",
    AUTO_CAPS,
    "New launch alert: Safal Paramount Bopal — 234 matched buyers notified within 30 minutes",
    12340,
    97,
    9,
  ),
  a(
    "auto-pricedrop",
    "Price Drop Campaign AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Instantly notifies matched buyers when a listed price drops on any MSTC property.",
    AUTO_CAPS,
    "Price drop alert: 3 properties reduced — 47 matched buyers notified instantly",
    34521,
    98,
    9,
  ),
  a(
    "auto-new-listing",
    "New Listing Alert AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Instantly notifies matched buyers when a new property listing matches their saved search criteria.",
    AUTO_CAPS,
    "New listing alerts: 8 properties added today — 156 matched buyer notifications sent",
    45678,
    97,
    9,
  ),
  a(
    "auto-enquiry",
    "Enquiry Auto-Response AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Sends instant, contextual auto-response to every web enquiry within 2 minutes.",
    AUTO_CAPS,
    "Enquiry auto-response: 23 enquiries today — avg response time 1.8 minutes",
    89234,
    99,
    9,
  ),
  a(
    "auto-missed-call",
    "Missed Call Auto-Response AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Sends automated WhatsApp when any MSTC business call is missed.",
    AUTO_CAPS,
    "Missed call response: 4 missed calls today — all followed up on WhatsApp within 1 minute",
    23451,
    97,
    9,
  ),
  a(
    "auto-form-submit",
    "Form Submit Orchestrator AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Coordinates all actions triggered by any form submission across the platform.",
    AUTO_CAPS,
    "Form orchestration: 12 form submissions today — all workflows triggered correctly",
    34521,
    97,
    9,
  ),
  a(
    "auto-deal-stage",
    "Deal Stage Automation AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Triggers specific team actions at each stage of the deal pipeline automatically.",
    AUTO_CAPS,
    "Deal stage trigger: 3 deals advanced to negotiation — legal checklist sent automatically",
    12340,
    96,
    9,
  ),
  a(
    "auto-post-visit",
    "Post-Visit Automation AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Runs a specific follow-up sequence immediately after every site visit.",
    AUTO_CAPS,
    "Post-visit sequence: 6 visits this week — all thank-you and follow-up messages sent",
    8901,
    96,
    9,
  ),
  a(
    "auto-post-deal",
    "Post-Deal Automation AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Sends congratulations, registration guidance, and relationship continuation after every deal closure.",
    AUTO_CAPS,
    "Post-deal: 2 closures this week — congratulations, registration checklist, and welcome kit sent",
    5678,
    97,
    9,
  ),
  a(
    "auto-complaint",
    "Complaint Automation AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Acknowledges, tracks, escalates, and resolves complaints through automated workflow.",
    AUTO_CAPS,
    "Complaint automation: 1 complaint received — acknowledged in 8 minutes, resolved in 4 hours",
    12340,
    97,
    9,
  ),
  a(
    "auto-review-req",
    "Review Request AI",
    "automation",
    "Automation Intelligence",
    "Automation",
    "Automatically requests Google and platform reviews at the optimal moment in client journey.",
    AUTO_CAPS,
    "Review requests: 8 sent this week — 3 new 5-star Google reviews received",
    8901,
    95,
    9,
  ),
];

// ─── CREATIVE & BRAND INTELLIGENCE (20) ───────────────────────────────────
const CREATIVE_CAPS = [
  "Maintains MSTC gold/black luxury brand consistency",
  "Creates on-brand content across all formats",
  "Tracks creative performance metrics",
  "Continuously improves brand expression quality",
];

const creativeAgents: ExtendedAgentDef[] = [
  a(
    "creative-visual-id",
    "Visual Identity AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Ensures all visual output maintains gold/black luxury aesthetic consistently across all MSTC materials.",
    CREATIVE_CAPS,
    "Visual identity audit: all 34 recent marketing materials reviewed — all compliant",
    2341,
    94,
    7,
  ),
  a(
    "creative-typography",
    "Typography Intelligence AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Manages font usage consistency ensuring Playfair Display and Inter are used correctly everywhere.",
    CREATIVE_CAPS,
    "Typography review: Playfair Display headings verified on 12 new pages",
    1890,
    93,
    7,
  ),
  a(
    "creative-color",
    "Color Psychology AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Uses color psychology principles to optimize CTAs, trust signals, and urgency elements.",
    CREATIVE_CAPS,
    "CTA color optimization: gold (#c9a84c) button A/B test confirms 18% higher click rate",
    2341,
    94,
    7,
  ),
  a(
    "creative-photo",
    "Photography Direction AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Sets guidelines for all MSTC property photography to ensure consistent luxury presentation.",
    CREATIVE_CAPS,
    "Photography brief updated: golden hour shoots recommended for all exterior property photos",
    1234,
    93,
    7,
  ),
  a(
    "creative-video",
    "Video Production AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Creates scripts and production guidance for all MSTC video content across all channels.",
    CREATIVE_CAPS,
    "Video production: Ahmedabad market Q1 tour video script approved — 4-minute runtime",
    1890,
    92,
    7,
  ),
  a(
    "creative-animation",
    "Animation Intelligence AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Determines when motion and animation enhances vs distracts from the MSTC user experience.",
    CREATIVE_CAPS,
    "Animation audit: subtle gold shimmer added to CTA buttons — 8% engagement increase",
    1234,
    91,
    7,
  ),
  a(
    "creative-icons",
    "Iconography AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Maintains custom icon system consistent with MSTC luxury brand language across all touchpoints.",
    CREATIVE_CAPS,
    "Icon library updated: 12 new property-type icons added in gold outline style",
    890,
    91,
    7,
  ),
  a(
    "creative-illustration",
    "Illustration AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Develops custom illustration style for complex real estate concepts across MSTC content.",
    CREATIVE_CAPS,
    "Illustration set created: 6 property buying journey illustrations for education content",
    678,
    90,
    7,
  ),
  a(
    "creative-logo",
    "Logo Usage AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Ensures correct MSTC logo usage across all sizes, formats, and channels consistently.",
    CREATIVE_CAPS,
    "Logo audit: all 47 digital touchpoints verified — single logo consistent everywhere",
    1234,
    95,
    7,
  ),
  a(
    "creative-campaign",
    "Brand Campaign AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Develops annual brand campaigns bringing the LETUS MANAGE brand promise to life.",
    CREATIVE_CAPS,
    'Campaign concept developed: "Your Property. Our Intelligence." campaign for 2025',
    1890,
    94,
    7,
  ),
  a(
    "creative-emotional",
    "Emotional Branding AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Builds emotional connection between MSTC GLOBAL brand and clients through storytelling.",
    CREATIVE_CAPS,
    'Emotional branding audit: client story "From Mumbai to Ahmedabad — MSTC made it possible" published',
    2341,
    93,
    7,
  ),
  a(
    "creative-story",
    "Brand Story AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Curates and communicates the MSTC GLOBAL origin story and brand evolution narrative.",
    CREATIVE_CAPS,
    "Brand story updated for 25th anniversary — origin in Ahmedabad 2000 narrative refreshed",
    1234,
    93,
    7,
  ),
  a(
    "creative-md-brand",
    "MD Personal Brand AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Builds Love Vijaybhai Parekh personal brand as Ahmedabad real estate thought leader.",
    CREATIVE_CAPS,
    "MD thought leadership: Q1 market commentary published on LinkedIn — 3,400 impressions",
    2341,
    94,
    7,
  ),
  a(
    "creative-employer",
    "Employer Brand AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Positions MSTC GLOBAL as an employer of choice to attract top talent in Ahmedabad.",
    CREATIVE_CAPS,
    'Employer brand: "Life at MSTC" Instagram series launched — 4 team stories published',
    890,
    91,
    7,
  ),
  a(
    "creative-community",
    "Community Brand AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Builds MSTC brand as a pillar of Ahmedabad business and cultural community.",
    CREATIVE_CAPS,
    "Community sponsorship: MSTC Navratri community event brand visibility 45,000+ people",
    1234,
    92,
    7,
  ),
  a(
    "creative-awards",
    "Award & Recognition AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Identifies awards MSTC should apply for and prepares high-quality award submissions.",
    CREATIVE_CAPS,
    'Award submission: "Top Real Estate Advisory 2025" application submitted — Gujarat Real Estate Awards',
    890,
    92,
    7,
  ),
  a(
    "creative-partnership",
    "Partnership Brand AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Ensures all co-branded materials maintain MSTC brand standards with partner organizations.",
    CREATIVE_CAPS,
    "Partnership brand review: HDFC co-branded property fair materials approved",
    678,
    91,
    7,
  ),
  a(
    "creative-crisis",
    "Crisis Communication AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Prepares and manages communication during any brand crisis situation.",
    CREATIVE_CAPS,
    "Crisis protocol reviewed: updated response templates for 5 crisis scenario types",
    567,
    93,
    7,
  ),
  a(
    "creative-reputation",
    "Reputation Recovery AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Designs and executes brand reputation recovery strategy when needed.",
    CREATIVE_CAPS,
    "Reputation monitoring: MSTC brand sentiment score 8.4/10 — no recovery action needed",
    1234,
    92,
    7,
  ),
  a(
    "creative-equity",
    "Brand Equity Tracker AI",
    "creative",
    "Creative Intelligence",
    "Brand & Creative",
    "Measures and tracks MSTC brand equity over time across all target segments.",
    CREATIVE_CAPS,
    "Brand equity score: 91/100 — up 3 points from Q4 2024, driven by NRI awareness growth",
    2341,
    94,
    7,
  ),
];

// ─── EXPANSION INTELLIGENCE (25) ──────────────────────────────────────────
const EXPAND_CAPS = [
  "Analyzes market entry opportunity and readiness",
  "Tracks competitive landscape in target market",
  "Develops detailed go-to-market strategy",
  "Updates market readiness score quarterly",
];

const expansionAgents: ExtendedAgentDef[] = [
  a(
    "expand-mumbai",
    "Mumbai Expansion AI",
    "expansion",
    "Expansion Intelligence",
    "India Expansion",
    "Plans MSTC GLOBAL entry into Mumbai real estate advisory market focusing on premium residential.",
    EXPAND_CAPS,
    "Mumbai readiness: 7.2/10 — 2026 entry timeline confirmed, brokerage partnership model recommended",
    2341,
    95,
    8,
  ),
  a(
    "expand-delhi",
    "Delhi/NCR Expansion AI",
    "expansion",
    "Expansion Intelligence",
    "India Expansion",
    "Plans MSTC entry into Delhi and NCR commercial and residential markets.",
    EXPAND_CAPS,
    "Delhi/NCR analysis: Gurugram commercial corridor identified as primary entry point",
    1890,
    94,
    8,
  ),
  a(
    "expand-pune",
    "Pune Expansion AI",
    "expansion",
    "Expansion Intelligence",
    "India Expansion",
    "Plans MSTC entry into Pune residential market serving IT professionals.",
    EXPAND_CAPS,
    "Pune readiness: 7.5/10 — IT corridor residential identified as natural extension of MSTC model",
    2341,
    95,
    8,
  ),
  a(
    "expand-surat",
    "Surat Expansion AI",
    "expansion",
    "Expansion Intelligence",
    "India Expansion",
    "Plans MSTC GLOBAL expansion into Surat — the nearest major Gujarat city.",
    EXPAND_CAPS,
    "Surat expansion: 8.1/10 readiness — diamond community advisory model being designed",
    3456,
    96,
    8,
  ),
  a(
    "expand-vadodara",
    "Vadodara Expansion AI",
    "expansion",
    "Expansion Intelligence",
    "India Expansion",
    "Plans MSTC expansion into Vadodara for Gujarat complete market presence.",
    EXPAND_CAPS,
    "Vadodara readiness: 7.9/10 — Smart City residential being evaluated for advisory launch",
    2341,
    95,
    8,
  ),
  a(
    "expand-rajkot",
    "Rajkot Expansion AI",
    "expansion",
    "Expansion Intelligence",
    "India Expansion",
    "Plans MSTC entry into Rajkot and Saurashtra market for SME and residential advisory.",
    EXPAND_CAPS,
    "Rajkot analysis: SME property advisory is primary entry segment — timeline H1 2026",
    1890,
    93,
    8,
  ),
  a(
    "expand-dubai",
    "Dubai Expansion AI",
    "expansion",
    "Expansion Intelligence",
    "International Expansion",
    "Plans MSTC advisory service targeting Dubai-based NRIs investing in Gujarat and India.",
    EXPAND_CAPS,
    "Dubai model confirmed: digital-first NRI reverse-investment advisory — 2026 soft launch",
    3456,
    96,
    8,
  ),
  a(
    "expand-singapore",
    "Singapore Expansion AI",
    "expansion",
    "Expansion Intelligence",
    "International Expansion",
    "Plans MSTC advisory for Singapore-based Indian diaspora investing in India.",
    EXPAND_CAPS,
    "Singapore diaspora analysis: 400,000 Indian nationals — Gujarati community is primary target",
    1234,
    93,
    8,
  ),
  a(
    "expand-london",
    "London Expansion AI",
    "expansion",
    "Expansion Intelligence",
    "International Expansion",
    "Plans MSTC service for UK Gujarati community investing in India.",
    EXPAND_CAPS,
    "London strategy: UK Gujarati community estimated 400,000 — community event outreach planned",
    1234,
    92,
    8,
  ),
  a(
    "expand-usa",
    "USA Expansion AI",
    "expansion",
    "Expansion Intelligence",
    "International Expansion",
    "Plans MSTC digital advisory for US-based NRI investors focusing on Gujarati diaspora.",
    EXPAND_CAPS,
    "USA digital model: Gujarati diaspora in NJ, TX, CA identified as primary target clusters",
    1234,
    92,
    8,
  ),
  a(
    "expand-canada",
    "Canada Expansion AI",
    "expansion",
    "Expansion Intelligence",
    "International Expansion",
    "Plans MSTC advisory for Canadian Indian diaspora in Toronto and Vancouver.",
    EXPAND_CAPS,
    "Canada strategy: partnership with existing Indo-Canadian networks — referral model designed",
    890,
    91,
    8,
  ),
  a(
    "expand-australia",
    "Australia Expansion AI",
    "expansion",
    "Expansion Intelligence",
    "International Expansion",
    "Plans MSTC advisory for Australian Indian diaspora in Melbourne and Sydney.",
    EXPAND_CAPS,
    "Australia timeline: 2029 entry — digital-first model with community ambassador strategy",
    678,
    90,
    8,
  ),
  a(
    "expand-new-biz",
    "New Business Line AI",
    "expansion",
    "Expansion Intelligence",
    "Business Innovation",
    "Identifies new service lines MSTC should launch based on client needs and market gaps.",
    EXPAND_CAPS,
    "New business opportunity: property management services — 45 existing clients expressed interest",
    1890,
    94,
    8,
  ),
  a(
    "expand-franchise",
    "Franchise Intelligence AI",
    "expansion",
    "Expansion Intelligence",
    "Business Innovation",
    "Designs MSTC GLOBAL franchise model for expansion through local partners.",
    EXPAND_CAPS,
    "Franchise model designed: territory rights, training program, and tech platform access defined",
    1234,
    93,
    8,
  ),
  a(
    "expand-whitelabel",
    "White Label AI",
    "expansion",
    "Expansion Intelligence",
    "Business Innovation",
    "Develops MSTC platform white-labeling for other regional real estate agencies.",
    EXPAND_CAPS,
    "White label product: MSTC platform SaaS for agencies — pricing model and features defined",
    890,
    92,
    8,
  ),
  a(
    "expand-saas",
    "SaaS Intelligence AI",
    "expansion",
    "Expansion Intelligence",
    "Business Innovation",
    "Develops MSTC technology as a SaaS product for Indian real estate companies.",
    EXPAND_CAPS,
    "SaaS feasibility: MSTC tech platform adapted for SaaS — MVP scope defined at \u20b948L investment",
    1234,
    93,
    8,
  ),
  a(
    "expand-proptech-startup",
    "PropTech Startup AI",
    "expansion",
    "Expansion Intelligence",
    "Business Innovation",
    "Explores MSTC launching or incubating proptech startups based on identified market gaps.",
    EXPAND_CAPS,
    "Proptech incubation: AI property valuation startup concept developed — seeking angel input",
    678,
    91,
    8,
  ),
  a(
    "expand-academy",
    "Training Academy AI",
    "expansion",
    "Expansion Intelligence",
    "Business Innovation",
    "Designs MSTC real estate training academy for industry professionals in Gujarat.",
    EXPAND_CAPS,
    "Training academy: RERA agent certification course designed — 3 batches planned for 2025",
    1234,
    93,
    8,
  ),
  a(
    "expand-builder-partner",
    "Builder Partnership AI",
    "expansion",
    "Expansion Intelligence",
    "Strategic Partnerships",
    "Develops exclusive builder partnerships for early access to new project launches.",
    EXPAND_CAPS,
    "Builder partnership: 2 new exclusive launch agreements signed — 4 under negotiation",
    2341,
    95,
    8,
  ),
  a(
    "expand-bank-partner",
    "Bank Partnership AI",
    "expansion",
    "Expansion Intelligence",
    "Strategic Partnerships",
    "Negotiates home loan referral partnerships with banks for revenue diversification.",
    EXPAND_CAPS,
    "Bank partnership: HDFC referral fee agreement renewed — SBI partnership under discussion",
    2341,
    94,
    8,
  ),
  a(
    "expand-insurance-partner",
    "Insurance Partnership AI",
    "expansion",
    "Expansion Intelligence",
    "Strategic Partnerships",
    "Develops property and home loan insurance referral partnerships.",
    EXPAND_CAPS,
    "Insurance partnership: HDFC Life and Star Health referral agreements active",
    1234,
    93,
    8,
  ),
  a(
    "expand-interior",
    "Interior Design Partnership AI",
    "expansion",
    "Expansion Intelligence",
    "Strategic Partnerships",
    "Builds referral partnerships with interior designers for post-purchase client value.",
    EXPAND_CAPS,
    "Interior partnership: 3 premium Ahmedabad interior design firms in referral network",
    890,
    92,
    8,
  ),
  a(
    "expand-movers",
    "Moving Services AI",
    "expansion",
    "Expansion Intelligence",
    "Strategic Partnerships",
    "Develops referral partnership with professional packers and movers for client convenience.",
    EXPAND_CAPS,
    "Moving services: Leo Packers referral partnership signed — MSTC clients get priority service",
    678,
    91,
    8,
  ),
  a(
    "expand-smarthome",
    "Smart Home Partnership AI",
    "expansion",
    "Expansion Intelligence",
    "Strategic Partnerships",
    "Develops referral partnerships with smart home companies for MSTC new-property buyers.",
    EXPAND_CAPS,
    "Smart home partnership: Schneider Electric smart home package available to MSTC buyers",
    567,
    91,
    8,
  ),
  a(
    "expand-architect",
    "Architect Partnership AI",
    "expansion",
    "Expansion Intelligence",
    "Strategic Partnerships",
    "Builds referral partnerships with architects for MSTC renovation and construction clients.",
    EXPAND_CAPS,
    "Architect network: 5 premium Ahmedabad architecture firms in MSTC referral network",
    678,
    92,
    8,
  ),
];

// ─── NEURAL NETWORK AGENTS (50) ───────────────────────────────────────────
const NEURAL_CAPS = [
  "Trains continuously on new MSTC data",
  "Produces confidence-scored predictions",
  "Feeds inference to relevant agents",
  "Self-retrains when accuracy drops below threshold",
];

const neuralAgents: ExtendedAgentDef[] = [
  // Property stack
  a(
    "neural-prop-ann",
    "Property Valuation ANN",
    "neural",
    "ANN",
    "Property",
    "Artificial neural network trained on 2.3M Ahmedabad property records for accurate fair value estimation.",
    NEURAL_CAPS,
    "Bopal 3BHK valuation: \u20b968.4L fair value with 91% confidence",
    89234,
    97,
    9,
  ),
  a(
    "neural-prop-rnn",
    "Demand Prediction RNN",
    "neural",
    "RNN",
    "Property",
    "Recurrent neural network analyzing 5-year property demand time series for locality-level forecasting.",
    NEURAL_CAPS,
    "Chandkheda demand forecast: up 12% next quarter — IT park expansion driving trend",
    45678,
    94,
    9,
  ),
  a(
    "neural-prop-cnn",
    "Photo Quality CNN",
    "neural",
    "CNN",
    "Property",
    "Convolutional neural network scoring property photo quality for listing enhancement recommendations.",
    NEURAL_CAPS,
    "Listing photo scored 7.2/10 — 3 improvement recommendations generated",
    67890,
    96,
    9,
  ),
  a(
    "neural-prop-cnn2",
    "Floor Plan Reader CNN",
    "neural",
    "CNN",
    "Property",
    "Convolutional neural network extracting BHK count, area, and layout from uploaded floor plan images.",
    NEURAL_CAPS,
    "Floor plan extracted: 3BHK, 1,450 sqft, East-facing, 2 attached bathrooms identified",
    34521,
    95,
    9,
  ),
  a(
    "neural-prop-gnn",
    "Buyer-Property Similarity GNN",
    "neural",
    "GNN",
    "Property",
    "Graph neural network matching buyers to properties through behavioral similarity across 847,000 buyer-property interaction pairs.",
    NEURAL_CAPS,
    "12 matched properties ranked for lead — top match: Vastrapur 3BHK within budget",
    23451,
    93,
    9,
  ),
  // Finance stack
  a(
    "neural-fin-ann",
    "Loan Approval Probability ANN",
    "neural",
    "ANN",
    "Finance",
    "ANN trained on 1.8M home loan applications predicting approval probability for any applicant profile.",
    NEURAL_CAPS,
    "Lead probability: 87% approval likelihood at HDFC — pre-approval letter initiated",
    45678,
    96,
    9,
  ),
  a(
    "neural-fin-rnn",
    "Rate Movement Predictor RNN",
    "neural",
    "RNN",
    "Finance",
    "RNN analyzing 20 years of RBI rate decisions for home loan rate movement prediction.",
    NEURAL_CAPS,
    "Rate prediction: next RBI meeting hold at 6.5% — 65% confidence",
    23451,
    91,
    9,
  ),
  a(
    "neural-fin-cnn",
    "Document OCR CNN",
    "neural",
    "CNN",
    "Finance",
    "CNN extracting income data from salary slips, Form 16, and financial statements with 98.2% accuracy.",
    NEURAL_CAPS,
    "Form 16 OCR: annual income \u20b918.4L extracted — loan eligibility \u20b974L calculated",
    89234,
    98,
    9,
  ),
  a(
    "neural-fin-gnn",
    "Fraud Detection GNN",
    "neural",
    "GNN",
    "Finance",
    "Graph neural network detecting fraud patterns in property transactions through connection analysis.",
    NEURAL_CAPS,
    "Transaction fraud score: 0.2% — all signals normal, transaction cleared",
    67890,
    99,
    9,
  ),
  a(
    "neural-fin-rl",
    "Portfolio Optimizer RL",
    "neural",
    "RL",
    "Finance",
    "Reinforcement learning agent optimizing property portfolio allocation for maximum risk-adjusted return.",
    NEURAL_CAPS,
    "Portfolio optimization: sell Nikol commercial, add Bopal residential — projected +1.2% yield",
    12340,
    92,
    9,
  ),
  // Client stack
  a(
    "neural-client-ann",
    "Lead Conversion ANN",
    "neural",
    "ANN",
    "Client Management",
    "ANN trained on 2.1M client interactions predicting deal conversion probability within 24 hours of first contact.",
    NEURAL_CAPS,
    "Lead scored: 72% conversion probability this month — priority engagement flagged",
    78901,
    95,
    9,
  ),
  a(
    "neural-client-rnn",
    "Churn Prediction RNN",
    "neural",
    "RNN",
    "Client Management",
    "RNN identifying churn signals in client behavior sequences before disengagement occurs.",
    NEURAL_CAPS,
    "8 clients flagged at high churn risk — re-engagement sequence triggered automatically",
    45678,
    94,
    9,
  ),
  a(
    "neural-client-cnn",
    "Emotion Detection CNN",
    "neural",
    "CNN",
    "Client Management",
    "CNN analyzing text and voice message patterns to detect client emotional state for communication adaptation.",
    NEURAL_CAPS,
    "Distress detected in client message — human escalation triggered for sensitive handling",
    34521,
    92,
    9,
  ),
  a(
    "neural-client-gnn",
    "Referral Network GNN",
    "neural",
    "GNN",
    "Client Management",
    "GNN mapping complete referral network to identify most influential clients and connection opportunities.",
    NEURAL_CAPS,
    "Top referral influencer identified: Client Shah responsible for 12% of 2025 leads",
    23451,
    93,
    9,
  ),
  a(
    "neural-client-rl",
    "Communication Optimizer RL",
    "neural",
    "RL",
    "Client Management",
    "Reinforcement learning optimizing message timing, channel, and tone for each individual client.",
    NEURAL_CAPS,
    "Communication optimized: WhatsApp at 7pm IST recommended for this NRI lead",
    34521,
    94,
    9,
  ),
  // Legal stack
  a(
    "neural-legal-ann",
    "Contract Risk ANN",
    "neural",
    "ANN",
    "Legal & Compliance",
    "ANN analyzing contract text to identify risk clauses and deviation from Gujarat standard terms.",
    NEURAL_CAPS,
    "Development agreement analyzed: 2 risk clauses flagged for legal review",
    23451,
    96,
    9,
  ),
  a(
    "neural-legal-cnn",
    "Document Classification CNN",
    "neural",
    "CNN",
    "Legal & Compliance",
    "CNN classifying all uploaded documents by type, jurisdiction, and required action with 97.4% accuracy.",
    NEURAL_CAPS,
    "Document auto-classified: Sale Deed, Gujarat jurisdiction, requires registration stamp",
    56789,
    97,
    9,
  ),
  a(
    "neural-legal-rnn",
    "Compliance Sequence RNN",
    "neural",
    "RNN",
    "Legal & Compliance",
    "RNN predicting next required compliance step in property transaction based on current stage.",
    NEURAL_CAPS,
    "Next step predicted for RERA project: OC application, due within 60 days",
    34521,
    95,
    9,
  ),
  a(
    "neural-legal-ml",
    "Case Outcome Predictor ML",
    "neural",
    "ML",
    "Legal & Compliance",
    "Machine learning model predicting RERA complaint outcomes based on 12,000 historical case results.",
    NEURAL_CAPS,
    "RERA complaint: 68% favorable outcome probability — filing recommended",
    12340,
    88,
    9,
  ),
  a(
    "neural-legal-transformer",
    "Clause Anomaly Transformer",
    "neural",
    "Transformer",
    "Legal & Compliance",
    "Transformer model detecting anomalous and non-standard clauses in property agreements.",
    NEURAL_CAPS,
    "Clause anomaly: Clause 12.3 deviates significantly from Gujarat standard — review flagged",
    23451,
    96,
    9,
  ),
  // Content stack
  a(
    "neural-content-ann",
    "Content Performance ANN",
    "neural",
    "ANN",
    "Content",
    "ANN predicting content engagement before publication based on topic, format, and timing signals.",
    NEURAL_CAPS,
    "Bopal area guide performance prediction: 34% above average — prioritized for Thursday publish",
    23451,
    93,
    9,
  ),
  a(
    "neural-content-rnn",
    "Topic Trend RNN",
    "neural",
    "RNN",
    "Content",
    "RNN analyzing search trend time series to identify rising content topics for MSTC early coverage.",
    NEURAL_CAPS,
    'Trend identified: "affordable housing Ahmedabad 2025" searches up 23% — article commissioned',
    15678,
    92,
    9,
  ),
  a(
    "neural-content-cnn",
    "Image-Text Alignment CNN",
    "neural",
    "CNN",
    "Content",
    "CNN evaluating alignment between property images and associated marketing text for consistency.",
    NEURAL_CAPS,
    "Blog post image-text alignment scored 8.7/10 — headline and hero image match confirmed",
    12340,
    93,
    9,
  ),
  a(
    "neural-content-ml",
    "Viral Predictor ML",
    "neural",
    "ML",
    "Content",
    "ML model predicting viral potential of content pieces on WhatsApp and social media.",
    NEURAL_CAPS,
    "Jantri rate post: 74% viral probability on WhatsApp predicted — broadcast list prepared",
    8901,
    89,
    9,
  ),
  a(
    "neural-content-transformer",
    "Brand Voice Transformer",
    "neural",
    "Transformer",
    "Content",
    "Transformer model scoring all MSTC content for brand voice consistency against gold standard corpus.",
    NEURAL_CAPS,
    "WhatsApp message brand voice score: 94% — approved for client broadcast",
    15678,
    95,
    9,
  ),
  // Security stack
  a(
    "neural-security-ann",
    "Anomaly Detection ANN",
    "neural",
    "ANN",
    "Security",
    "ANN trained on 50M platform events detecting behavioral anomalies in real time.",
    NEURAL_CAPS,
    "Anomaly scan complete: normal activity pattern confirmed — no anomalies detected today",
    234891,
    99,
    9,
  ),
  a(
    "neural-security-rnn",
    "Behavioral Pattern RNN",
    "neural",
    "RNN",
    "Security",
    "RNN building individual user behavioral models for session authenticity verification.",
    NEURAL_CAPS,
    "Session behavior verified: matches previous authenticated pattern — access approved",
    156789,
    99,
    9,
  ),
  a(
    "neural-security-cnn",
    "Image Forgery CNN",
    "neural",
    "CNN",
    "Security",
    "CNN detecting document image manipulation and forgery in uploaded KYC and property documents.",
    NEURAL_CAPS,
    "Aadhaar image authenticity: no manipulation detected — document cleared for processing",
    89234,
    98,
    9,
  ),
  a(
    "neural-security-gnn",
    "Attack Graph GNN",
    "neural",
    "GNN",
    "Security",
    "GNN modeling attack propagation graphs to detect coordinated multi-vector security attacks.",
    NEURAL_CAPS,
    "Attack graph analysis: no coordinated attack pattern detected in last 24 hours",
    67890,
    99,
    9,
  ),
  a(
    "neural-security-transformer",
    "Threat Classification Transformer",
    "neural",
    "Transformer",
    "Security",
    "Transformer model classifying all security events by threat type, severity, and recommended action.",
    NEURAL_CAPS,
    "Threat classification: bot cluster from 3 IPs — blocked and logged for analysis",
    123456,
    99,
    9,
  ),
  // Operations stack
  a(
    "neural-ops-ann",
    "Task Duration Predictor ANN",
    "neural",
    "ANN",
    "Operations",
    "ANN predicting task completion duration for optimal scheduling and capacity planning.",
    NEURAL_CAPS,
    "Property listing task predicted at 23 minutes — schedule slot allocated accordingly",
    45678,
    92,
    9,
  ),
  a(
    "neural-ops-rl",
    "Demand-Supply Balancer RL",
    "neural",
    "RL",
    "Operations",
    "Reinforcement learning balancing work demand across team capacity for optimal throughput.",
    NEURAL_CAPS,
    "Work balance optimization: 2 leads reassigned from overloaded agent — queue equalized",
    34521,
    93,
    9,
  ),
  a(
    "neural-ops-cnn",
    "Document Auto-Classifier CNN",
    "neural",
    "CNN",
    "Operations",
    "CNN automatically classifying all uploaded business documents for correct filing and routing.",
    NEURAL_CAPS,
    "Document auto-filed: Sale Deed 2025 category — all metadata extracted and tagged",
    78901,
    97,
    9,
  ),
  a(
    "neural-ops-gnn",
    "Process Bottleneck GNN",
    "neural",
    "GNN",
    "Operations",
    "GNN analyzing workflow graphs to identify process bottlenecks and optimization opportunities.",
    NEURAL_CAPS,
    "Bottleneck identified: document review stage adding 2.3 days — streamlining recommended",
    23451,
    94,
    9,
  ),
  a(
    "neural-ops-transformer",
    "Decision Support Transformer",
    "neural",
    "Transformer",
    "Operations",
    "Transformer model synthesizing all available information to support complex business decisions.",
    NEURAL_CAPS,
    "Decision support: accept counter offer at \u20b982L based on 12 market signals — recommended",
    12340,
    93,
    9,
  ),
  // Market stack
  a(
    "neural-market-ann",
    "Macro Impact ANN",
    "neural",
    "ANN",
    "Real Estate Markets",
    "ANN quantifying macroeconomic signal impact on Ahmedabad property demand and prices.",
    NEURAL_CAPS,
    "Inflation 4.2% impact: neutral signal for property demand — no adjustment to forecast",
    34521,
    89,
    9,
  ),
  a(
    "neural-market-rnn",
    "News Sentiment RNN",
    "neural",
    "RNN",
    "Real Estate Markets",
    "RNN analyzing real estate news sentiment for early detection of market direction shifts.",
    NEURAL_CAPS,
    "Sentiment score: positive — Gujarat infrastructure news driving optimism in Q2",
    45678,
    93,
    9,
  ),
  a(
    "neural-market-cnn",
    "Market Cycle CNN",
    "neural",
    "CNN",
    "Real Estate Markets",
    "CNN recognizing market cycle patterns from historical price-volume-sentiment data.",
    NEURAL_CAPS,
    "Market cycle: mid-growth phase confirmed — 2-3 years to peak estimated",
    23451,
    89,
    9,
  ),
  a(
    "neural-market-gnn",
    "Competitor Strategy GNN",
    "neural",
    "GNN",
    "Real Estate Markets",
    "GNN analyzing competitor action graphs to predict strategic moves and identify market opportunities.",
    NEURAL_CAPS,
    "Competitor signal: PropTiger reducing Ahmedabad headcount — MSTC market opportunity opening",
    12340,
    90,
    9,
  ),
  a(
    "neural-market-rl",
    "Price Discovery RL",
    "neural",
    "RL",
    "Real Estate Markets",
    "Reinforcement learning agent discovering true market clearing prices through dynamic market modeling.",
    NEURAL_CAPS,
    "Price discovery: Vastrapur 2BHK true market price \u20b91.24Cr — listed at \u20b91.31Cr (5.6% over)",
    67890,
    95,
    9,
  ),
  // Innovation stack
  a(
    "neural-innov-ann",
    "Technology Adoption ANN",
    "neural",
    "ANN",
    "Innovation",
    "ANN predicting technology adoption probability in MSTC context based on market and internal signals.",
    NEURAL_CAPS,
    "Voice search adoption prediction: 76% probability by Q4 2025 in real estate vertical",
    8901,
    89,
    9,
  ),
  a(
    "neural-innov-rnn",
    "Trend Identification RNN",
    "neural",
    "RNN",
    "Innovation",
    "RNN detecting emerging innovation trends from global proptech activity sequences.",
    NEURAL_CAPS,
    "Emerging trend: tokenized real estate — India adoption 2 years behind global",
    6789,
    91,
    9,
  ),
  a(
    "neural-innov-ml",
    "Feature Impact Predictor ML",
    "neural",
    "ML",
    "Innovation",
    "ML model predicting business impact of proposed platform features before development investment.",
    NEURAL_CAPS,
    "Voice search feature impact: +12% mobile engagement projected — development approved",
    5678,
    88,
    9,
  ),
  a(
    "neural-innov-transformer",
    "User Need Synthesizer Transformer",
    "neural",
    "Transformer",
    "Innovation",
    "Transformer synthesizing all user feedback signals into unified product improvement insights.",
    NEURAL_CAPS,
    "Top unmet need: property price history chart — 1,247 users requested in various forms",
    8901,
    93,
    9,
  ),
  a(
    "neural-innov-rl",
    "Innovation Scoring RL",
    "neural",
    "RL",
    "Innovation",
    "Reinforcement learning scoring all innovation candidates by potential MSTC business impact.",
    NEURAL_CAPS,
    "AR virtual tour scored 9.1/10 innovation impact — recommended for 2025 development",
    4512,
    92,
    9,
  ),
  // Analytics stack
  a(
    "neural-analytics-ann",
    "Insight Generation ANN",
    "neural",
    "ANN",
    "Analytics",
    "ANN automatically generating business insights from patterns in MSTC operational data.",
    NEURAL_CAPS,
    "Auto-insight: weekend enquiries 34% higher than weekdays — shift outreach scheduling",
    45678,
    94,
    9,
  ),
  a(
    "neural-analytics-rnn",
    "Anomaly Root Cause RNN",
    "neural",
    "RNN",
    "Analytics",
    "RNN tracing metric anomalies back to their root cause through sequential event analysis.",
    NEURAL_CAPS,
    "Anomaly root cause: Monday lead drop = public holiday — no systemic issue",
    23451,
    93,
    9,
  ),
  a(
    "neural-analytics-ml",
    "Dashboard Auto-Designer ML",
    "neural",
    "ML",
    "Analytics",
    "ML model suggesting optimal dashboard layouts and visualizations for each user role.",
    NEURAL_CAPS,
    "Dashboard suggestion: add Chandkheda trend chart to MD daily brief — high relevance",
    8901,
    89,
    9,
  ),
  a(
    "neural-analytics-transformer",
    "KPI Forecaster Transformer",
    "neural",
    "Transformer",
    "Analytics",
    "Transformer model providing accurate 90-day KPI forecasts with statistical confidence intervals.",
    NEURAL_CAPS,
    "Q2 2025 leads forecast: 847 \u00b134 — 8.4% growth vs Q1 with 87% confidence",
    23451,
    95,
    9,
  ),
  a(
    "neural-analytics-rl",
    "Report Generator RL",
    "neural",
    "RL",
    "Analytics",
    "Reinforcement learning agent optimizing report structure and content based on reader engagement feedback.",
    NEURAL_CAPS,
    "Monthly report optimized: executive summary moved first — 23% improvement in read completion",
    12340,
    94,
    9,
  ),
];

// ─── QUALITY INTELLIGENCE SPECIALISTS (15) ────────────────────────────────
const QUALITY_CAPS = [
  "Runs automated quality checks continuously",
  "Reports issues with severity scores",
  "Triggers fix workflows for detected problems",
  "Tracks quality improvement over time",
];

const qualityAgents: ExtendedAgentDef[] = [
  a(
    "quality-zero-error",
    "Zero-Error Enforcer AI",
    "quality",
    "Quality Intelligence",
    "Quality Assurance",
    "Reviews all client-facing output ensuring zero errors before delivery.",
    QUALITY_CAPS,
    "23 client outputs reviewed today — 2 errors caught and corrected before delivery",
    45678,
    99,
    8,
  ),
  a(
    "quality-fact-check",
    "Fact Checker AI",
    "quality",
    "Quality Intelligence",
    "Quality Assurance",
    "Verifies all factual claims in MSTC content including property data, market stats, and legal information.",
    QUALITY_CAPS,
    "Fact check: 8 content pieces verified — all market statistics confirmed accurate",
    23451,
    97,
    8,
  ),
  a(
    "quality-calc-verify",
    "Calculation Verifier AI",
    "quality",
    "Quality Intelligence",
    "Quality Assurance",
    "Independently verifies all calculator outputs before showing to clients.",
    QUALITY_CAPS,
    "EMI calculations verified: all 234 calculations produced today confirmed accurate",
    34521,
    98,
    8,
  ),
  a(
    "quality-link",
    "Link Integrity AI",
    "quality",
    "Quality Intelligence",
    "Quality Assurance",
    "Continuously checks all platform links for broken URLs and redirects.",
    QUALITY_CAPS,
    "Link audit: all 847 platform links checked — 0 broken links detected today",
    89234,
    99,
    8,
  ),
  a(
    "quality-form-test",
    "Form Testing AI",
    "quality",
    "Quality Intelligence",
    "Quality Assurance",
    "Tests every form across every device and browser combination for functionality.",
    QUALITY_CAPS,
    "Form test: all 47 forms tested on Android and iOS — all functional",
    12340,
    97,
    8,
  ),
  a(
    "quality-mobile-qa",
    "Mobile QA AI",
    "quality",
    "Quality Intelligence",
    "Quality Assurance",
    "Conducts dedicated mobile quality assurance across Android and iOS devices.",
    QUALITY_CAPS,
    "Mobile QA: property portal tested on 8 Android models — all pass except 1 display issue fixed",
    23451,
    97,
    8,
  ),
  a(
    "quality-load-test",
    "Load Testing AI",
    "quality",
    "Quality Intelligence",
    "Quality Assurance",
    "Simulates high traffic scenarios to ensure platform stability under peak load.",
    QUALITY_CAPS,
    "Load test: 500 concurrent users simulated — all responses within 2 seconds",
    8901,
    97,
    8,
  ),
  a(
    "quality-regression",
    "Regression Testing AI",
    "quality",
    "Quality Intelligence",
    "Quality Assurance",
    "Tests all existing features after every build to ensure nothing is broken by new changes.",
    QUALITY_CAPS,
    "Regression test: 127 test scenarios run after latest deployment — all pass",
    15678,
    98,
    8,
  ),
  a(
    "quality-accessibility",
    "Accessibility Testing AI",
    "quality",
    "Quality Intelligence",
    "Quality Assurance",
    "Tests WCAG 2.1 accessibility compliance across all platform pages.",
    QUALITY_CAPS,
    "Accessibility audit: 96/100 — all new pages WCAG AA compliant",
    12340,
    97,
    8,
  ),
  a(
    "quality-speed",
    "Speed Test AI",
    "quality",
    "Quality Intelligence",
    "Quality Assurance",
    "Measures and tracks page load times after every deployment for performance regression detection.",
    QUALITY_CAPS,
    "Speed test: LCP 1.8s, FID 12ms, CLS 0.03 — all Core Web Vitals green",
    34521,
    98,
    8,
  ),
  a(
    "quality-cross-browser",
    "Cross-Browser AI",
    "quality",
    "Quality Intelligence",
    "Quality Assurance",
    "Tests all features across Chrome, Firefox, Safari, Edge, and Samsung Browser.",
    QUALITY_CAPS,
    "Cross-browser test: property portal verified on 5 browsers — all functional",
    12340,
    97,
    8,
  ),
  a(
    "quality-print",
    "Print Quality AI",
    "quality",
    "Quality Intelligence",
    "Quality Assurance",
    "Tests all printable documents and PDFs before enabling download functionality.",
    QUALITY_CAPS,
    "Print quality: 8 property brochure PDFs tested — all render correctly on A4 and Letter",
    5678,
    95,
    8,
  ),
  a(
    "quality-pdf",
    "PDF Quality AI",
    "quality",
    "Quality Intelligence",
    "Quality Assurance",
    "Validates every generated PDF for completeness, correctness, and rendering quality.",
    QUALITY_CAPS,
    "PDF validation: 23 PDFs generated today — all pages complete, fonts embedded",
    8901,
    96,
    8,
  ),
  a(
    "quality-data-integrity",
    "Data Integrity AI",
    "quality",
    "Quality Intelligence",
    "Quality Assurance",
    "Validates all platform data for duplicates, corruption, and missing required fields.",
    QUALITY_CAPS,
    "Data integrity check: 1051 properties validated — 0 duplicates, 0 corruption detected",
    45678,
    99,
    8,
  ),
  a(
    "quality-uat",
    "User Acceptance AI",
    "quality",
    "Quality Intelligence",
    "Quality Assurance",
    "Simulates real user flows to validate the complete end-to-end user experience.",
    QUALITY_CAPS,
    "UAT: complete buyer journey tested — enquiry to follow-up to site visit booking all functional",
    12340,
    97,
    8,
  ),
];

// ─── KNOWLEDGE INTELLIGENCE SPECIALISTS (15) ──────────────────────────────
const KNOWLEDGE_CAPS = [
  "Maintains comprehensive domain knowledge base",
  "Answers queries within domain expertise instantly",
  "Updates knowledge when regulations or market changes",
  "Coordinates with domain specialist AIs",
];

const knowledgeAgents: ExtendedAgentDef[] = [
  a(
    "know-mstc-encyclopedia",
    "MSTC Encyclopedia AI",
    "knowledge",
    "Knowledge Intelligence",
    "Knowledge Management",
    "Contains complete institutional knowledge of MSTC GLOBAL history, services, and achievements.",
    KNOWLEDGE_CAPS,
    "25-year company history article updated — verified with MD",
    5678,
    94,
    7,
  ),
  a(
    "know-ahmedabad-re",
    "Ahmedabad Real Estate Encyclopedia AI",
    "knowledge",
    "Knowledge Intelligence",
    "Knowledge Management",
    "Maintains comprehensive database of everything about Ahmedabad real estate market.",
    KNOWLEDGE_CAPS,
    "Ahmedabad market snapshot Q1 2025 added — 24 locality-level data points updated",
    12340,
    95,
    7,
  ),
  a(
    "know-gujarat-legal",
    "Gujarat Legal Encyclopedia AI",
    "knowledge",
    "Knowledge Intelligence",
    "Knowledge Management",
    "Contains complete Gujarat property law knowledge base with all applicable acts and rules.",
    KNOWLEDGE_CAPS,
    "Gujarat Stamp Act 2025 amendments incorporated into knowledge base",
    8901,
    96,
    7,
  ),
  a(
    "know-tax",
    "Tax Knowledge AI",
    "knowledge",
    "Knowledge Intelligence",
    "Knowledge Management",
    "Maintains complete Indian property tax knowledge base updated after every Union Budget.",
    KNOWLEDGE_CAPS,
    "Budget 2025 property tax changes incorporated — all 12 amendments indexed",
    9012,
    96,
    7,
  ),
  a(
    "know-rera",
    "RERA Knowledge AI",
    "knowledge",
    "Knowledge Intelligence",
    "Knowledge Management",
    "Contains complete Gujarat RERA knowledge including all rules, judgments, and precedents.",
    KNOWLEDGE_CAPS,
    "RERA Authority Gujarat order #GT-2025-0234 indexed — possession delay compensation confirmed",
    7823,
    97,
    7,
  ),
  a(
    "know-market-history",
    "Market History AI",
    "knowledge",
    "Knowledge Intelligence",
    "Knowledge Management",
    "Maintains 20-year Ahmedabad property market history including cycles, peaks, and corrections.",
    KNOWLEDGE_CAPS,
    "Q1 2025 Ahmedabad market data added — historical dataset now 22 years complete",
    6789,
    95,
    7,
  ),
  a(
    "know-builder-db",
    "Builder Database AI",
    "knowledge",
    "Knowledge Intelligence",
    "Knowledge Management",
    "Maintains complete database of all 200+ Ahmedabad builders with track record and credibility data.",
    KNOWLEDGE_CAPS,
    "Builder database: 5 new builders added, 3 credibility scores updated this month",
    8901,
    94,
    7,
  ),
  a(
    "know-society-db",
    "Society Database AI",
    "knowledge",
    "Knowledge Intelligence",
    "Knowledge Management",
    "Maintains comprehensive database of 500+ Ahmedabad housing societies with quality data.",
    KNOWLEDGE_CAPS,
    "Society database: 12 new societies added, 23 quality scores updated this quarter",
    7823,
    93,
    7,
  ),
  a(
    "know-bank-products",
    "Bank Product Database AI",
    "knowledge",
    "Knowledge Intelligence",
    "Knowledge Management",
    "Maintains complete up-to-date database of home loan products from all 14 partner banks.",
    KNOWLEDGE_CAPS,
    "Bank database: SBI, HDFC, and ICICI rate updates processed within 24 hours of announcement",
    9012,
    95,
    7,
  ),
  a(
    "know-govt-schemes",
    "Government Scheme Database AI",
    "knowledge",
    "Knowledge Intelligence",
    "Knowledge Management",
    "Maintains complete database of all government housing schemes relevant to Ahmedabad buyers.",
    KNOWLEDGE_CAPS,
    "PMAY 2025 allocation data updated — 340 new beneficiary slots in Ahmedabad district",
    5678,
    94,
    7,
  ),
  a(
    "know-locality-intel",
    "Locality Intelligence Database AI",
    "knowledge",
    "Knowledge Intelligence",
    "Knowledge Management",
    "Contains comprehensive locality profiles for all 11 Ahmedabad target localities.",
    KNOWLEDGE_CAPS,
    "Chandkheda locality profile updated with GIFT City road connectivity data",
    6789,
    94,
    7,
  ),
  a(
    "know-artist-db",
    "Artist & Performer Database AI",
    "knowledge",
    "Knowledge Intelligence",
    "Knowledge Management",
    "Maintains database of 200+ Gujarat artists and performers for MSTC events and cultural services.",
    KNOWLEDGE_CAPS,
    "Artist database: 12 new Gujarat performers added — classical and folk categories",
    3456,
    91,
    7,
  ),
  a(
    "know-sports-db",
    "Sports Ecosystem Database AI",
    "knowledge",
    "Knowledge Intelligence",
    "Knowledge Management",
    "Contains complete database of Gujarat sports teams, athletes, and tournaments.",
    KNOWLEDGE_CAPS,
    "Sports database: Gujarat Ranji squad and IPL team Gujarat Titans roster updated",
    2341,
    90,
    7,
  ),
  a(
    "know-cultural-events",
    "Cultural Event Database AI",
    "knowledge",
    "Knowledge Intelligence",
    "Knowledge Management",
    "Maintains comprehensive calendar of Gujarat cultural events and festivals.",
    KNOWLEDGE_CAPS,
    "Cultural calendar: Navratri 2025 event listings added — 340 Ahmedabad events indexed",
    3456,
    91,
    7,
  ),
  a(
    "know-vendor-network",
    "Vendor Network Database AI",
    "knowledge",
    "Knowledge Intelligence",
    "Knowledge Management",
    "Maintains database of all MSTC vendors, contractors, and service providers.",
    KNOWLEDGE_CAPS,
    "Vendor database: 5 new interior design firms added, 2 vendors rated after project completion",
    2341,
    91,
    7,
  ),
];

// ─── SPECIALIZED VERTICAL AIs (30) ────────────────────────────────────────
const VERTICAL_CAPS = [
  "Specializes in specific vertical domain deeply",
  "Tracks vertical-specific regulations and changes",
  "Provides intelligence to relevant property and client agents",
  "Reports vertical developments to Command AI",
];

const verticalAgents: ExtendedAgentDef[] = [
  // Infrastructure & Smart City
  a(
    "vert-metro",
    "Ahmedabad Metro Intelligence AI",
    "vertical",
    "Vertical Intelligence",
    "Infrastructure",
    "Tracks Ahmedabad Metro expansion phases and calculates property price impact by station catchment.",
    VERTICAL_CAPS,
    "Metro Line 2 Phase 3 approved — 12 station catchment areas price impact mapped",
    8901,
    95,
    7,
  ),
  a(
    "vert-ring-road",
    "Sardar Patel Ring Road AI",
    "vertical",
    "Vertical Intelligence",
    "Infrastructure",
    "Monitors SPRR development and property appreciation along the ring road corridor.",
    VERTICAL_CAPS,
    "SPRR Phase 3 Sanand section complete — industrial property prices up 23%",
    5678,
    93,
    7,
  ),
  a(
    "vert-brts",
    "BRTS & Public Transport AI",
    "vertical",
    "Vertical Intelligence",
    "Infrastructure",
    "Tracks BRTS expansion and all public transport improvements across Ahmedabad.",
    VERTICAL_CAPS,
    "BRTS Bopal-Ghuma corridor approved — 6 new stations impacting property demand",
    4512,
    92,
    7,
  ),
  a(
    "vert-smart-road",
    "Smart Road & Traffic AI",
    "vertical",
    "Vertical Intelligence",
    "Infrastructure",
    "Monitors smart road infrastructure and traffic management improvements in Ahmedabad.",
    VERTICAL_CAPS,
    "Smart traffic sensors Phase 2 operational on SG Highway — connectivity score improved",
    3456,
    91,
    7,
  ),
  a(
    "vert-water",
    "Water Supply Zone Intelligence AI",
    "vertical",
    "Vertical Intelligence",
    "Infrastructure",
    "Tracks AMC water supply infrastructure and availability by zone for property buyer advisory.",
    VERTICAL_CAPS,
    "Water supply: Bopal zone upgrade complete — 24-hour supply confirmed from April 2025",
    2341,
    91,
    7,
  ),
  a(
    "vert-electricity",
    "Electricity Zone Intelligence AI",
    "vertical",
    "Vertical Intelligence",
    "Infrastructure",
    "Monitors TORRENT Power supply zones and electricity infrastructure for property buyer advisory.",
    VERTICAL_CAPS,
    "Electricity: 3-phase power confirmed for Chandkheda industrial zone — attracts commercial buyers",
    2341,
    91,
    7,
  ),
  // GIFT City
  a(
    "vert-gift-finance",
    "GIFT City Financial Zone AI",
    "vertical",
    "Vertical Intelligence",
    "GIFT City",
    "Tracks GIFT City IFSC development and its growing financial services ecosystem.",
    VERTICAL_CAPS,
    "GIFT IFSC: 3 new BFSI firms registered — commercial demand up 34% this quarter",
    4512,
    95,
    7,
  ),
  a(
    "vert-gift-residential",
    "GIFT City Residential AI",
    "vertical",
    "Vertical Intelligence",
    "GIFT City",
    "Monitors residential development in and around GIFT City for NRI and professional buyers.",
    VERTICAL_CAPS,
    "GIFT City residential: 2 new luxury projects launched for NRI segment",
    2341,
    93,
    7,
  ),
  a(
    "vert-gift-sez",
    "GIFT City SEZ Intelligence AI",
    "vertical",
    "Vertical Intelligence",
    "GIFT City",
    "Tracks GIFT SEZ business activity and its property demand implications.",
    VERTICAL_CAPS,
    "GIFT SEZ: 4 new units registered — Chandkheda warehouse demand linked to logistics",
    1890,
    92,
    7,
  ),
  a(
    "vert-gift-regulatory",
    "GIFT City Regulatory AI",
    "vertical",
    "Vertical Intelligence",
    "GIFT City",
    "Monitors IFSCA regulatory changes affecting GIFT City investments.",
    VERTICAL_CAPS,
    "IFSCA circular: new AIF regulations for GIFT City — NRI investment implications analyzed",
    1234,
    93,
    7,
  ),
  // Dholera SIR
  a(
    "vert-dholera-industrial",
    "Dholera Industrial Zone AI",
    "vertical",
    "Vertical Intelligence",
    "Dholera SIR",
    "Tracks Dholera Special Investment Region industrial development and plot availability.",
    VERTICAL_CAPS,
    "Dholera SIR Phase 1: 48 industrial plots confirmed available — investor briefing prepared",
    2341,
    93,
    7,
  ),
  a(
    "vert-dholera-residential",
    "Dholera Residential AI",
    "vertical",
    "Vertical Intelligence",
    "Dholera SIR",
    "Monitors Dholera residential development for long-term investment advisory.",
    VERTICAL_CAPS,
    "Dholera residential: 3 township projects approved — 2-5 year investment timeline advisory",
    1234,
    91,
    7,
  ),
  a(
    "vert-dholera-infra",
    "Dholera Infrastructure Timeline AI",
    "vertical",
    "Vertical Intelligence",
    "Dholera SIR",
    "Tracks all Dholera infrastructure milestones for accurate investment timeline advisory.",
    VERTICAL_CAPS,
    "Dholera timeline: metro line design approved — residential value trigger expected 2027",
    1890,
    92,
    7,
  ),
  // AMC & Government
  a(
    "vert-amc-zone",
    "AMC Zone Intelligence AI",
    "vertical",
    "Vertical Intelligence",
    "Government",
    "Tracks AMC zone development plans and their property approval implications.",
    VERTICAL_CAPS,
    "AMC Zone update: Bopal extended into new development zone — 1,200 new plots approved",
    5678,
    94,
    7,
  ),
  a(
    "vert-auda",
    "AUDA Development Plan AI",
    "vertical",
    "Vertical Intelligence",
    "Government",
    "Monitors AUDA development plan updates affecting land use and building permissions.",
    VERTICAL_CAPS,
    "AUDA DP 2031 amendment: Chandkheda mixed-use zone expanded — commercial opportunity identified",
    4512,
    94,
    7,
  ),
  a(
    "vert-gujarat-policy",
    "Gujarat Government Policy AI",
    "vertical",
    "Vertical Intelligence",
    "Government",
    "Tracks all Gujarat government policy changes affecting real estate development and investment.",
    VERTICAL_CAPS,
    "Gujarat housing policy: affordable housing incentive extended to 2027 — 12 new eligible projects",
    6789,
    95,
    7,
  ),
  a(
    "vert-rbi-impact",
    "RBI Policy Impact AI",
    "vertical",
    "Vertical Intelligence",
    "Government",
    "Analyzes RBI monetary policy decisions and their immediate and long-term property market impact.",
    VERTICAL_CAPS,
    "RBI rate hold: property market neutral impact confirmed — buyer demand unchanged",
    8901,
    96,
    7,
  ),
  a(
    "vert-sebi",
    "SEBI Real Estate Impact AI",
    "vertical",
    "Vertical Intelligence",
    "Government",
    "Monitors SEBI regulations affecting real estate funds, REITs, and alternative investments.",
    VERTICAL_CAPS,
    "SEBI REIT amendment: minimum investment reduced to \u20b910,000 — retail access expanded",
    5678,
    95,
    7,
  ),
  // Specialized Property Types
  a(
    "vert-farmhouse",
    "Farmhouse & Resort Property AI",
    "vertical",
    "Vertical Intelligence",
    "Specialized Properties",
    "Tracks farmhouse and resort property market near Ahmedabad including Nalsarovar and Polo Forest zones.",
    VERTICAL_CAPS,
    "Farmhouse market: 5 premium properties near Nalsarovar added to MSTC inventory",
    2341,
    91,
    7,
  ),
  a(
    "vert-heritage",
    "Heritage & Antique Property AI",
    "vertical",
    "Vertical Intelligence",
    "Specialized Properties",
    "Monitors heritage property conversions and adaptive reuse opportunities in old Ahmedabad.",
    VERTICAL_CAPS,
    "Heritage property: 2 pol area properties with boutique hotel conversion potential identified",
    1234,
    92,
    7,
  ),
  a(
    "vert-religious",
    "Religious Institution Property AI",
    "vertical",
    "Vertical Intelligence",
    "Specialized Properties",
    "Tracks religious and charitable institution property requirements and advisory.",
    VERTICAL_CAPS,
    "Religious property: trust land advisory for new temple complex project initiated",
    890,
    90,
    7,
  ),
  a(
    "vert-educational",
    "Educational Institution Property AI",
    "vertical",
    "Vertical Intelligence",
    "Specialized Properties",
    "Monitors educational institution property requirements for school and college campus advisory.",
    VERTICAL_CAPS,
    "Educational property: CBSE school campus requirement matched — 2-acre plot shortlisted",
    1234,
    91,
    7,
  ),
  a(
    "vert-healthcare-prop",
    "Healthcare Facility Property AI",
    "vertical",
    "Vertical Intelligence",
    "Specialized Properties",
    "Tracks hospital and healthcare facility property requirements and development.",
    VERTICAL_CAPS,
    "Healthcare property: diagnostic center space requirement matched in Naranpura",
    1234,
    92,
    7,
  ),
  a(
    "vert-hospitality-prop",
    "Hospitality & Hotel Property AI",
    "vertical",
    "Vertical Intelligence",
    "Specialized Properties",
    "Monitors hotel and hospitality property development and investment opportunities.",
    VERTICAL_CAPS,
    "Hotel property: mid-segment hotel opportunity identified near Ahmedabad airport",
    1890,
    92,
    7,
  ),
  a(
    "vert-petrol-pump",
    "Petrol Pump & Commercial AI",
    "vertical",
    "Vertical Intelligence",
    "Specialized Properties",
    "Tracks petrol pump and highway commercial property opportunities.",
    VERTICAL_CAPS,
    "Petrol pump: HPCL license territory near Ring Road identified — investor brief prepared",
    890,
    90,
    7,
  ),
  a(
    "vert-cold-storage",
    "Cold Storage & Logistics AI",
    "vertical",
    "Vertical Intelligence",
    "Specialized Properties",
    "Monitors cold storage and temperature-controlled logistics facility requirements.",
    VERTICAL_CAPS,
    "Cold storage: 15,000 sqft cold chain facility requirement matched near Sanand",
    1234,
    91,
    7,
  ),
  a(
    "vert-factory",
    "Factory & Manufacturing AI",
    "vertical",
    "Vertical Intelligence",
    "Specialized Properties",
    "Tracks factory and manufacturing facility requirements in Ahmedabad industrial zones.",
    VERTICAL_CAPS,
    "Factory property: 20,000 sqft manufacturing unit shortlisted in Vatva GIDC",
    2341,
    92,
    7,
  ),
  a(
    "vert-datacenter",
    "Data Center & Tech Park AI",
    "vertical",
    "Vertical Intelligence",
    "Specialized Properties",
    "Monitors data center and tech park development opportunities in Ahmedabad.",
    VERTICAL_CAPS,
    "Data center intelligence: AWS edge node site evaluation corridor — 3 suitable plots mapped",
    1234,
    92,
    7,
  ),
  a(
    "vert-solar-farm",
    "Solar Farm Land AI",
    "vertical",
    "Vertical Intelligence",
    "Specialized Properties",
    "Tracks solar farm land requirements and renewable energy facility development.",
    VERTICAL_CAPS,
    "Solar farm: 50-acre land requirement in Kutch near Dhordo matched for renewable client",
    890,
    90,
    7,
  ),
  a(
    "vert-warehousing",
    "Warehousing & 3PL AI",
    "vertical",
    "Vertical Intelligence",
    "Specialized Properties",
    "Monitors warehousing and third-party logistics facility development along SPRR corridor.",
    VERTICAL_CAPS,
    "Warehousing: SPRR Sanand logistics park — 3 Grade-A warehouse units available",
    2341,
    92,
    7,
  ),
];

// ─── CONTINUOUS IMPROVEMENT AIs (20) ─────────────────────────────────────
const CI_CAPS = [
  "Continuously improves AI system performance",
  "Detects and corrects AI behavior issues",
  "Coordinates improvement across all 808 agents",
  "Reports system health metrics to Sovereign Intelligence",
];

const continuousImprovementAgents: ExtendedAgentDef[] = [
  a(
    "ci-coordinator",
    "Self-Improvement Coordinator AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Coordinates all AI system improvement activities across all 808 agents.",
    CI_CAPS,
    "Weekly improvement sprint: 12 agents received capability updates — all deployed",
    12340,
    97,
    8,
  ),
  a(
    "ci-retrain",
    "Model Retraining AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Retrains all neural and ML models as new MSTC operational data accumulates.",
    CI_CAPS,
    "Lead Conversion ANN retrained on Q1 2025 data — accuracy improved from 87% to 89%",
    8901,
    95,
    8,
  ),
  a(
    "ci-feedback-loop",
    "Feedback Loop AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Closes the feedback loop on all AI recommendations by tracking their real-world outcomes.",
    CI_CAPS,
    "Feedback collected for 234 AI recommendations this month — 78% accuracy confirmed",
    15678,
    96,
    8,
  ),
  a(
    "ci-bias",
    "Bias Detector AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Identifies and corrects biases in AI recommendations that may disadvantage certain client segments.",
    CI_CAPS,
    "Bias audit: property recommendations reviewed — no demographic bias detected",
    5678,
    95,
    8,
  ),
  a(
    "ci-explainability",
    "Explainability AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Explains any AI decision in plain language to MD or clients when requested.",
    CI_CAPS,
    "Explanation provided: why Lead #A4821 scored 72% — 5 behavioral signals detailed",
    6789,
    95,
    8,
  ),
  a(
    "ci-audit",
    "AI Audit AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Conducts monthly audit of all 808 AI agent performance with ranked improvement recommendations.",
    CI_CAPS,
    "Monthly audit: 808 agents reviewed — top 5 improvement opportunities identified",
    4512,
    96,
    8,
  ),
  a(
    "ci-coord-optimizer",
    "Coordination Optimizer AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Improves how agents communicate and hand off work to eliminate coordination inefficiencies.",
    CI_CAPS,
    "Coordination improved: lead handoff from qualification to property matching reduced by 4 minutes",
    7823,
    95,
    8,
  ),
  a(
    "ci-latency",
    "Latency Reducer AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Reduces time between automation triggers and agent actions across all workflows.",
    CI_CAPS,
    "Latency reduction: enquiry auto-response time improved from 4.2min to 1.8min",
    9012,
    96,
    8,
  ),
  a(
    "ci-context-window",
    "Context Window AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Optimizes how much context each AI agent receives for maximum decision quality.",
    CI_CAPS,
    "Context optimization: NRI agent context window expanded — 12% better recommendation accuracy",
    5678,
    94,
    8,
  ),
  a(
    "ci-multi-supervisor",
    "Multi-Agent Supervisor AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Supervises all agent-to-agent communications for quality and accuracy.",
    CI_CAPS,
    "Agent supervision: 1,247 agent communications reviewed this week — 2 flagged for correction",
    23451,
    97,
    8,
  ),
  a(
    "ci-human-loop",
    "Human-in-Loop Manager AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Determines when AI decisions should be escalated to human judgment for oversight.",
    CI_CAPS,
    "Human escalation: 3 high-stakes decisions flagged for MD today — all resolved",
    8901,
    96,
    8,
  ),
  a(
    "ci-confidence",
    "Confidence Calibration AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Ensures AI confidence scores accurately reflect actual prediction accuracy.",
    CI_CAPS,
    "Calibration check: confidence scores within 3% of actual accuracy across all models",
    6789,
    95,
    8,
  ),
  a(
    "ci-hallucination",
    "Hallucination Detector AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Identifies AI outputs containing factual errors before they reach clients.",
    CI_CAPS,
    "Hallucination check: 0 factual errors in client-facing AI responses today",
    15678,
    99,
    8,
  ),
  a(
    "ci-contradictions",
    "Contradictions Resolver AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Adjudicates when two AI agents provide conflicting recommendations.",
    CI_CAPS,
    "Contradiction resolved: market price vs valuation model disagreement — weighted consensus applied",
    4512,
    95,
    8,
  ),
  a(
    "ci-knowledge-gap",
    "Knowledge Gap Identifier AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Identifies areas where AI system knowledge is insufficient for reliable recommendations.",
    CI_CAPS,
    "Knowledge gap: Anand district agricultural land data sparse — sourcing plan initiated",
    3456,
    94,
    8,
  ),
  a(
    "ci-training-curator",
    "Training Data Curator AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Curates high-quality training data from real MSTC operational outcomes for model improvement.",
    CI_CAPS,
    "Training data: 2,341 high-quality labeled interactions curated for next model retraining",
    8901,
    95,
    8,
  ),
  a(
    "ci-version-ctrl",
    "Version Control AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Manages all AI model versions and enables rollback if new models underperform.",
    CI_CAPS,
    "Version control: 3 model deployments tracked — all performing above baseline threshold",
    5678,
    94,
    8,
  ),
  a(
    "ci-benchmark",
    "Benchmark Tracker AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Tracks performance of all 808 AI agents against industry benchmarks over time.",
    CI_CAPS,
    "Benchmark report: MSTC AI performance above industry average on 8 of 10 key metrics",
    7823,
    95,
    8,
  ),
  a(
    "ci-roi-tracker",
    "ROI of AI Tracker AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Measures the actual business ROI generated by each AI agent and the system overall.",
    CI_CAPS,
    "AI ROI: automation agents delivering 12x ROI — lead conversion AI saving 4.2 hours/day per agent",
    9012,
    96,
    8,
  ),
  a(
    "ci-strategy",
    "AI Strategy AI",
    "continuous-improvement",
    "Continuous Improvement",
    "AI Evolution",
    "Advises MD on where to invest AI resources for maximum business impact and competitive advantage.",
    CI_CAPS,
    "AI strategy brief: prioritize voice search and AR virtual tours for 2025 investment",
    4512,
    96,
    8,
  ),
];

// ─── EXPORT ALL 200 AGENTS ─────────────────────────────────────────────────
export const EXTENDED_AGENTS_5: ExtendedAgentDef[] = [
  ...automationAgents,
  ...creativeAgents,
  ...expansionAgents,
  ...neuralAgents,
  ...qualityAgents,
  ...knowledgeAgents,
  ...verticalAgents,
  ...continuousImprovementAgents,
];
