// MSTC GLOBAL — Complete AI Staff Organization (493 staff members)

export interface AIStaffMember {
  id: string;
  name: string;
  type: "human" | "ai";
  role: string;
  department: string;
  tier: "executive" | "gm" | "dept-head" | "specialist" | "worker";
  reportsTo: string | null;
  directReports: string[];
  avatarColor: string;
  avatarInitials: string;
  specialty: string;
  tasksToday: number;
  tasksThisWeek: number;
  performanceScore: number;
  status: "working" | "in-meeting" | "on-break" | "offline";
  statusNote: string;
  chatEnabled: boolean;
}

// India time status calculation
export function getIndiaTimeStatus(
  staffMember: AIStaffMember,
): "working" | "in-meeting" | "on-break" | "offline" {
  if (staffMember.type === "human") return staffMember.status;
  const ist = new Date(
    new Date().toLocaleString("en-US", { timeZone: "Asia/Kolkata" }),
  );
  const hour = ist.getHours();
  const minute = ist.getMinutes();
  const total = hour * 60 + minute;
  // Use id hash for individual variation
  const hash = staffMember.id
    .split("")
    .reduce((acc, c) => acc + c.charCodeAt(0), 0);
  const variant = hash % 4;
  if (total < 9 * 60 || total >= 22 * 60) return "offline";
  if (total >= 13 * 60 && total < 14 * 60) {
    return variant < 2 ? "in-meeting" : "on-break";
  }
  if (total >= 18 * 60 && total < 19 * 60) {
    return variant === 0 ? "in-meeting" : "working";
  }
  return "working";
}

// ── EXECUTIVE TIER (3 members) ────────────────────────────────────────────────────
const EXECUTIVE_STAFF: AIStaffMember[] = [
  {
    id: "md-love-parekh",
    name: "Love Vijaybhai Parekh",
    type: "human",
    role: "Managing Director",
    department: "Executive",
    tier: "executive",
    reportsTo: null,
    directReports: [
      "aria-cai",
      "max-cta",
      "rajan-gm-property",
      "kaveri-gm-finance",
      "sameer-gm-legal",
      "ananya-gm-client",
      "kiran-gm-content",
      "vishal-gm-events",
      "nisha-gm-ngo",
      "roshan-gm-tech",
      "deepa-gm-analytics",
      "farhan-gm-bizdev",
    ],
    avatarColor: "#c9a84c",
    avatarInitials: "LP",
    specialty:
      "Visionary leadership, real estate & diversified business conglomerate, Ahmedabad",
    tasksToday: 0,
    tasksThisWeek: 0,
    performanceScore: 100,
    status: "working",
    statusNote: "Managing Director, MSTC GLOBAL",
    chatEnabled: false,
  },
  {
    id: "aria-cai",
    name: "Aria",
    type: "ai",
    role: "Chief AI Officer",
    department: "Executive",
    tier: "executive",
    reportsTo: "md-love-parekh",
    directReports: [
      "rajan-gm-property",
      "kaveri-gm-finance",
      "sameer-gm-legal",
      "ananya-gm-client",
      "kiran-gm-content",
      "vishal-gm-events",
      "nisha-gm-ngo",
      "roshan-gm-tech",
      "deepa-gm-analytics",
      "farhan-gm-bizdev",
    ],
    avatarColor: "#c9a84c",
    avatarInitials: "AR",
    specialty:
      "Coordinates all 1,500+ AI agents, strategic advisor, compiles daily/weekly/monthly reports",
    tasksToday: 1247,
    tasksThisWeek: 8734,
    performanceScore: 99,
    status: "working",
    statusNote: "Overseeing all AI cluster operations",
    chatEnabled: true,
  },
  {
    id: "max-cta",
    name: "Max",
    type: "ai",
    role: "Chief Technology AI",
    department: "Executive",
    tier: "executive",
    reportsTo: "md-love-parekh",
    directReports: ["roshan-gm-tech"],
    avatarColor: "#6366f1",
    avatarInitials: "MX",
    specialty:
      "Platform infrastructure, all technical systems, security architecture, performance optimization",
    tasksToday: 892,
    tasksThisWeek: 6241,
    performanceScore: 98,
    status: "working",
    statusNote: "Monitoring platform performance metrics",
    chatEnabled: true,
  },
];

// ── GM TIER (10 General Managers) ─────────────────────────────────────────────────
const GM_STAFF: AIStaffMember[] = [
  {
    id: "rajan-gm-property",
    name: "Rajan",
    type: "ai",
    role: "GM — Property",
    department: "Property",
    tier: "gm",
    reportsTo: "aria-cai",
    directReports: [
      "dh-priya-listings",
      "dh-suresh-valuation",
      "dh-meena-compliance",
    ],
    avatarColor: "#c9a84c",
    avatarInitials: "RJ",
    specialty:
      "All property operations: listings, valuation, buyer-seller matching, and property intelligence",
    tasksToday: 234,
    tasksThisWeek: 1638,
    performanceScore: 96,
    status: "working",
    statusNote: "Reviewing new listing pipeline",
    chatEnabled: true,
  },
  {
    id: "kaveri-gm-finance",
    name: "Kaveri",
    type: "ai",
    role: "GM — Finance",
    department: "Finance",
    tier: "gm",
    reportsTo: "aria-cai",
    directReports: ["dh-dev-finance", "dh-pooja-investments", "dh-amit-loans"],
    avatarColor: "#22c55e",
    avatarInitials: "KV",
    specialty:
      "All finance and investment operations: loans, tax, investment strategies, and financial tools",
    tasksToday: 189,
    tasksThisWeek: 1323,
    performanceScore: 95,
    status: "working",
    statusNote: "Analyzing home loan rate movements",
    chatEnabled: true,
  },
  {
    id: "sameer-gm-legal",
    name: "Sameer",
    type: "ai",
    role: "GM — Legal",
    department: "Legal",
    tier: "gm",
    reportsTo: "aria-cai",
    directReports: ["dh-vikram-rera", "dh-anita-docs", "dh-rahul-disputes"],
    avatarColor: "#3b82f6",
    avatarInitials: "SM",
    specialty:
      "All legal and compliance operations: RERA, documentation, dispute resolution, and regulatory monitoring",
    tasksToday: 145,
    tasksThisWeek: 1015,
    performanceScore: 97,
    status: "working",
    statusNote: "Processing RERA compliance checks",
    chatEnabled: true,
  },
  {
    id: "ananya-gm-client",
    name: "Ananya",
    type: "ai",
    role: "GM — Client Relations",
    department: "Client Relations",
    tier: "gm",
    reportsTo: "aria-cai",
    directReports: ["dh-meera-crm", "dh-sujit-support", "dh-nita-onboarding"],
    avatarColor: "#ec4899",
    avatarInitials: "AN",
    specialty:
      "Complete client experience: onboarding, relationship management, satisfaction, and retention",
    tasksToday: 312,
    tasksThisWeek: 2184,
    performanceScore: 94,
    status: "working",
    statusNote: "Reviewing client satisfaction scores",
    chatEnabled: true,
  },
  {
    id: "kiran-gm-content",
    name: "Kiran",
    type: "ai",
    role: "GM — Content",
    department: "Content",
    tier: "gm",
    reportsTo: "aria-cai",
    directReports: ["dh-seema-blog", "dh-rohit-seo", "dh-priti-social"],
    avatarColor: "#a855f7",
    avatarInitials: "KR",
    specialty:
      "All content and marketing: blog posts, area guides, SEO, social media, and multilingual content",
    tasksToday: 456,
    tasksThisWeek: 3192,
    performanceScore: 93,
    status: "working",
    statusNote: "Publishing weekly market report",
    chatEnabled: true,
  },
  {
    id: "vishal-gm-events",
    name: "Vishal",
    type: "ai",
    role: "GM — Events",
    department: "Events",
    tier: "gm",
    reportsTo: "aria-cai",
    directReports: [
      "dh-kavya-planning",
      "dh-rajan-hospitality",
      "dh-sneha-cultural",
    ],
    avatarColor: "#f97316",
    avatarInitials: "VS",
    specialty:
      "All events and hospitality: planning, vendor management, cultural programs, and corporate events",
    tasksToday: 89,
    tasksThisWeek: 623,
    performanceScore: 92,
    status: "working",
    statusNote: "Coordinating upcoming event bookings",
    chatEnabled: true,
  },
  {
    id: "nisha-gm-ngo",
    name: "Nisha",
    type: "ai",
    role: "GM — NGO & CSR",
    department: "NGO",
    tier: "gm",
    reportsTo: "aria-cai",
    directReports: ["dh-sana-csr", "dh-mohan-volunteer", "dh-geeta-impact"],
    avatarColor: "#10b981",
    avatarInitials: "NS",
    specialty:
      "All CSR and social impact: donation management, volunteer programs, impact reporting, and compliance",
    tasksToday: 67,
    tasksThisWeek: 469,
    performanceScore: 94,
    status: "working",
    statusNote: "Processing donation tax certificates",
    chatEnabled: true,
  },
  {
    id: "roshan-gm-tech",
    name: "Roshan",
    type: "ai",
    role: "GM — Technology",
    department: "Technology",
    tier: "gm",
    reportsTo: "aria-cai",
    directReports: ["dh-dev-platform", "dh-vijay-security", "dh-pallavi-qa"],
    avatarColor: "#06b6d4",
    avatarInitials: "RS",
    specialty:
      "All platform development: feature builds, infrastructure, security, and quality assurance",
    tasksToday: 678,
    tasksThisWeek: 4746,
    performanceScore: 97,
    status: "working",
    statusNote: "Deploying new AI cluster features",
    chatEnabled: true,
  },
  {
    id: "deepa-gm-analytics",
    name: "Deepa",
    type: "ai",
    role: "GM — Analytics",
    department: "Analytics",
    tier: "gm",
    reportsTo: "aria-cai",
    directReports: ["dh-arun-data", "dh-lakshmi-reports", "dh-nikhil-bi"],
    avatarColor: "#eab308",
    avatarInitials: "DP",
    specialty:
      "All data and analytics: business intelligence, reporting, predictive models, and executive insights",
    tasksToday: 345,
    tasksThisWeek: 2415,
    performanceScore: 96,
    status: "working",
    statusNote: "Generating weekly analytics brief",
    chatEnabled: true,
  },
  {
    id: "farhan-gm-bizdev",
    name: "Farhan",
    type: "ai",
    role: "GM — Business Development",
    department: "Business Dev",
    tier: "gm",
    reportsTo: "aria-cai",
    directReports: [
      "dh-aditya-nri",
      "dh-sunita-partnerships",
      "dh-ravi-growth",
    ],
    avatarColor: "#ef4444",
    avatarInitials: "FH",
    specialty:
      "All growth and partnerships: NRI clients, strategic partnerships, new market entry, and expansion",
    tasksToday: 156,
    tasksThisWeek: 1092,
    performanceScore: 93,
    status: "working",
    statusNote: "Analyzing NRI client acquisition opportunities",
    chatEnabled: true,
  },
];

// ── DEPARTMENT HEAD TIER (30 members, 3 per GM) ─────────────────────────────────
const dh = (
  id: string,
  name: string,
  role: string,
  dept: string,
  reportsTo: string,
  color: string,
  initials: string,
  specialty: string,
  tasks: number,
  score: number,
  note: string,
): AIStaffMember => ({
  id,
  name,
  type: "ai",
  role,
  department: dept,
  tier: "dept-head",
  reportsTo,
  directReports: [],
  avatarColor: color,
  avatarInitials: initials,
  specialty,
  tasksToday: tasks,
  tasksThisWeek: tasks * 7,
  performanceScore: score,
  status: "working",
  statusNote: note,
  chatEnabled: true,
});

const DEPT_HEAD_STAFF: AIStaffMember[] = [
  // Under Rajan (Property)
  dh(
    "dh-priya-listings",
    "Priya",
    "Head of Listings",
    "Property",
    "rajan-gm-property",
    "#c9a84c",
    "PY",
    "Listing quality, publication standards, photo compliance, and listing intelligence",
    89,
    95,
    "Reviewing 12 new listing submissions",
  ),
  dh(
    "dh-suresh-valuation",
    "Suresh",
    "Head of Valuation",
    "Property",
    "rajan-gm-property",
    "#c9a84c",
    "SU",
    "AVM accuracy, comparable analysis, jantri rate monitoring, and valuation reports",
    156,
    93,
    "Calibrating valuation model with latest registrations",
  ),
  dh(
    "dh-meena-compliance",
    "Meena",
    "Head of Property Compliance",
    "Property",
    "rajan-gm-property",
    "#c9a84c",
    "MC",
    "RERA compliance, builder verification, document authenticity, and regulatory filings",
    67,
    96,
    "Processing RERA project verification queue",
  ),
  // Under Kaveri (Finance)
  dh(
    "dh-dev-finance",
    "Dev",
    "Head of Finance Operations",
    "Finance",
    "kaveri-gm-finance",
    "#22c55e",
    "DV",
    "Loan processing, EMI calculations, bank partnerships, and financial tools",
    234,
    94,
    "Updating bank loan rate database",
  ),
  dh(
    "dh-pooja-investments",
    "Pooja",
    "Head of Investments",
    "Finance",
    "kaveri-gm-finance",
    "#22c55e",
    "PJ",
    "Investment analysis, portfolio advice, wealth planning, and ROI calculations",
    145,
    93,
    "Building Q4 investment recommendations",
  ),
  dh(
    "dh-amit-loans",
    "Amit",
    "Head of Loan Advisory",
    "Finance",
    "kaveri-gm-finance",
    "#22c55e",
    "AM",
    "Home loan eligibility, balance transfer, PMAY eligibility, and lender comparisons",
    189,
    95,
    "Processing 34 loan eligibility requests",
  ),
  // Under Sameer (Legal)
  dh(
    "dh-vikram-rera",
    "Vikram",
    "Head of RERA Affairs",
    "Legal",
    "sameer-gm-legal",
    "#3b82f6",
    "VK",
    "RERA project tracking, complaint handling, compliance monitoring, and legal guidance",
    78,
    97,
    "Monitoring 23 active RERA compliance cases",
  ),
  dh(
    "dh-anita-docs",
    "Anita",
    "Head of Legal Documentation",
    "Legal",
    "sameer-gm-legal",
    "#3b82f6",
    "AT",
    "Agreement drafting, document review, due diligence, and legal document library",
    134,
    96,
    "Reviewing 8 sale agreement submissions",
  ),
  dh(
    "dh-rahul-disputes",
    "Rahul",
    "Head of Dispute Resolution",
    "Legal",
    "sameer-gm-legal",
    "#3b82f6",
    "RH",
    "Property disputes, RERA complaints, court liaison, and resolution strategy",
    45,
    95,
    "Drafting resolution strategy for 3 active disputes",
  ),
  // Under Ananya (Client Relations)
  dh(
    "dh-meera-crm",
    "Meera",
    "Head of CRM",
    "Client Relations",
    "ananya-gm-client",
    "#ec4899",
    "MR",
    "CRM pipeline management, lead nurturing, client lifecycle, and retention programs",
    456,
    93,
    "Reviewing lead pipeline health scores",
  ),
  dh(
    "dh-sujit-support",
    "Sujit",
    "Head of Client Support",
    "Client Relations",
    "ananya-gm-client",
    "#ec4899",
    "SJ",
    "Client support escalations, complaint resolution, satisfaction monitoring, and feedback",
    234,
    94,
    "Resolving 12 escalated client queries",
  ),
  dh(
    "dh-nita-onboarding",
    "Nita",
    "Head of Client Onboarding",
    "Client Relations",
    "ananya-gm-client",
    "#ec4899",
    "NT",
    "New client onboarding, welcome flows, profile completion, and first-30-day experience",
    89,
    92,
    "Onboarding 7 new high-value clients",
  ),
  // Under Kiran (Content)
  dh(
    "dh-seema-blog",
    "Seema",
    "Head of Content Creation",
    "Content",
    "kiran-gm-content",
    "#a855f7",
    "SE",
    "Blog posts, area guides, market reports, case studies, and educational content",
    12,
    91,
    "Publishing 3 new area guides today",
  ),
  dh(
    "dh-rohit-seo",
    "Rohit",
    "Head of SEO & Discovery",
    "Content",
    "kiran-gm-content",
    "#a855f7",
    "RO",
    "Search visibility, meta optimization, keyword strategy, and organic traffic growth",
    89,
    90,
    "Auditing 156 listing meta descriptions",
  ),
  dh(
    "dh-priti-social",
    "Priti",
    "Head of Social & Outreach",
    "Content",
    "kiran-gm-content",
    "#a855f7",
    "PR",
    "Social media, WhatsApp campaigns, email newsletters, and brand voice management",
    234,
    91,
    "Scheduling this week's WhatsApp broadcast",
  ),
  // Under Vishal (Events)
  dh(
    "dh-kavya-planning",
    "Kavya",
    "Head of Event Planning",
    "Events",
    "vishal-gm-events",
    "#f97316",
    "KA",
    "Event conceptualization, logistics, timeline management, and day-of coordination",
    45,
    92,
    "Planning 2 corporate events for next month",
  ),
  dh(
    "dh-rajan-hospitality",
    "Rajan A.",
    "Head of Hospitality",
    "Events",
    "vishal-gm-events",
    "#f97316",
    "RA",
    "Venue selection, catering, accommodation, hospitality packages, and guest experience",
    34,
    91,
    "Negotiating catering packages for 3 events",
  ),
  dh(
    "dh-sneha-cultural",
    "Sneha",
    "Head of Cultural Programs",
    "Events",
    "vishal-gm-events",
    "#f97316",
    "SN",
    "Cultural events, music programs, artist coordination, and cultural partnerships",
    23,
    90,
    "Coordinating upcoming Navratri event lineup",
  ),
  // Under Nisha (NGO)
  dh(
    "dh-sana-csr",
    "Sana",
    "Head of CSR Programs",
    "NGO",
    "nisha-gm-ngo",
    "#10b981",
    "SA",
    "CSR strategy, corporate donor relations, program design, and impact maximization",
    34,
    93,
    "Processing 5 new CSR partnership proposals",
  ),
  dh(
    "dh-mohan-volunteer",
    "Mohan",
    "Head of Volunteering",
    "NGO",
    "nisha-gm-ngo",
    "#10b981",
    "MH",
    "Volunteer recruitment, matching, training, coordination, and recognition programs",
    23,
    92,
    "Matching 28 new volunteer applications",
  ),
  dh(
    "dh-geeta-impact",
    "Geeta",
    "Head of Impact Reporting",
    "NGO",
    "nisha-gm-ngo",
    "#10b981",
    "GT",
    "Impact measurement, beneficiary tracking, 80G compliance, grant reporting, and storytelling",
    12,
    94,
    "Compiling quarterly impact report",
  ),
  // Under Roshan (Technology)
  dh(
    "dh-dev-platform",
    "Dev P.",
    "Head of Platform Development",
    "Technology",
    "roshan-gm-tech",
    "#06b6d4",
    "DP",
    "Feature development, releases, technical architecture, and developer coordination",
    234,
    97,
    "Reviewing AI cluster deployment",
  ),
  dh(
    "dh-vijay-security",
    "Vijay",
    "Head of Cybersecurity",
    "Technology",
    "roshan-gm-tech",
    "#06b6d4",
    "VJ",
    "Platform security, vulnerability management, data protection, and incident response",
    89,
    99,
    "Running weekly security scan",
  ),
  dh(
    "dh-pallavi-qa",
    "Pallavi",
    "Head of Quality Assurance",
    "Technology",
    "roshan-gm-tech",
    "#06b6d4",
    "PL",
    "Test coverage, bug tracking, performance testing, and release quality gates",
    156,
    96,
    "Testing new AI agent UI components",
  ),
  // Under Deepa (Analytics)
  dh(
    "dh-arun-data",
    "Arun",
    "Head of Data Science",
    "Analytics",
    "deepa-gm-analytics",
    "#eab308",
    "AR",
    "ML model training, data pipelines, statistical analysis, and predictive modeling",
    89,
    95,
    "Training updated lead scoring model",
  ),
  dh(
    "dh-lakshmi-reports",
    "Lakshmi",
    "Head of Business Reporting",
    "Analytics",
    "deepa-gm-analytics",
    "#eab308",
    "LK",
    "Executive dashboards, custom reports, KPI frameworks, and data visualization",
    45,
    94,
    "Preparing Monday morning executive digest",
  ),
  dh(
    "dh-nikhil-bi",
    "Nikhil",
    "Head of Business Intelligence",
    "Analytics",
    "deepa-gm-analytics",
    "#eab308",
    "NK",
    "Market intelligence, competitive analysis, trend forecasting, and strategic insights",
    67,
    93,
    "Compiling competitive intelligence brief",
  ),
  // Under Farhan (Business Dev)
  dh(
    "dh-aditya-nri",
    "Aditya",
    "Head of NRI Relations",
    "Business Dev",
    "farhan-gm-bizdev",
    "#ef4444",
    "AD",
    "NRI client acquisition, FEMA guidance, repatriation advisory, and NRI community outreach",
    89,
    95,
    "Following up with 12 NRI enquiries",
  ),
  dh(
    "dh-sunita-partnerships",
    "Sunita",
    "Head of Strategic Partnerships",
    "Business Dev",
    "farhan-gm-bizdev",
    "#ef4444",
    "ST",
    "Builder partnerships, bank tie-ups, corporate tie-ups, and referral network management",
    34,
    91,
    "Reviewing 4 new partnership proposals",
  ),
  dh(
    "dh-ravi-growth",
    "Ravi",
    "Head of Growth",
    "Business Dev",
    "farhan-gm-bizdev",
    "#ef4444",
    "RV",
    "Customer acquisition, lead generation, channel optimization, and growth experiments",
    156,
    92,
    "Analyzing Q3 channel attribution data",
  ),
];

// ── SPECIALIST TIER (50 members) ────────────────────────────────────────────────────
const sp = (
  id: string,
  name: string,
  role: string,
  dept: string,
  reportsTo: string,
  color: string,
  initials: string,
  specialty: string,
  tasks: number,
  score: number,
): AIStaffMember => ({
  id,
  name,
  type: "ai",
  role,
  department: dept,
  tier: "specialist",
  reportsTo,
  directReports: [],
  avatarColor: color,
  avatarInitials: initials,
  specialty,
  tasksToday: tasks,
  tasksThisWeek: tasks * 7,
  performanceScore: score,
  status: "working",
  statusNote: `Specialist: ${role}`,
  chatEnabled: true,
});

const SPECIALIST_STAFF: AIStaffMember[] = [
  sp(
    "sp-rera-specialist",
    "Chirag",
    "RERA Specialist",
    "Legal",
    "dh-vikram-rera",
    "#3b82f6",
    "CR",
    "Gujarat RERA regulations, project registration, complaint tracking, and RERA order analysis",
    45,
    97,
  ),
  sp(
    "sp-nri-specialist",
    "Anil",
    "NRI Property Specialist",
    "Business Dev",
    "dh-aditya-nri",
    "#ef4444",
    "AN",
    "NRI taxation, FEMA, repatriation, joint ownership, and NRI-specific buying process",
    89,
    96,
  ),
  sp(
    "sp-valuation-specialist",
    "Bhavna",
    "Property Valuation Specialist",
    "Property",
    "dh-suresh-valuation",
    "#c9a84c",
    "BV",
    "Comparable analysis, AVM calibration, distressed asset valuation, and luxury valuation",
    67,
    94,
  ),
  sp(
    "sp-luxury-specialist",
    "Minal",
    "Luxury Property Specialist",
    "Property",
    "dh-priya-listings",
    "#c9a84c",
    "ML",
    "High-value properties, UHNW clients, luxury lifestyle amenities, and premium negotiation",
    23,
    95,
  ),
  sp(
    "sp-commercial-specialist",
    "Jatin",
    "Commercial Property Specialist",
    "Property",
    "dh-priya-listings",
    "#c9a84c",
    "JT",
    "Office, retail, warehouse, and industrial properties: leasing, yield, and tenant management",
    45,
    93,
  ),
  sp(
    "sp-redevelopment-specialist",
    "Hardik",
    "Redevelopment Specialist",
    "Property",
    "dh-meena-compliance",
    "#c9a84c",
    "HK",
    "Society redevelopment: consent process, developer evaluation, FSI, and rights protection",
    34,
    94,
  ),
  sp(
    "sp-rental-specialist",
    "Foram",
    "Rental Market Specialist",
    "Property",
    "dh-priya-listings",
    "#c9a84c",
    "FR",
    "Rental yield optimization, tenant screening, lease management, and vacancy reduction",
    78,
    92,
  ),
  sp(
    "sp-compliance-officer",
    "Mansi",
    "Compliance Officer",
    "Legal",
    "dh-anita-docs",
    "#3b82f6",
    "MN",
    "Regulatory compliance, audit support, policy adherence, and compliance documentation",
    56,
    98,
  ),
  sp(
    "sp-fraud-specialist",
    "Keval",
    "Fraud Detection Specialist",
    "Technology",
    "dh-vijay-security",
    "#06b6d4",
    "KL",
    "Fake lead detection, fraudulent document identification, identity fraud, and scam prevention",
    89,
    97,
  ),
  sp(
    "sp-legal-doc-specialist",
    "Poonam",
    "Legal Document Specialist",
    "Legal",
    "dh-anita-docs",
    "#3b82f6",
    "PN",
    "Sale deeds, agreements, POAs, wills, NOCs, and all property legal documentation",
    45,
    96,
  ),
  sp(
    "sp-event-planning-specialist",
    "Riya",
    "Event Planning Specialist",
    "Events",
    "dh-kavya-planning",
    "#f97316",
    "RY",
    "Detailed event logistics, vendor coordination, day-of management, and post-event review",
    34,
    92,
  ),
  sp(
    "sp-artist-relations",
    "Mira",
    "Artist Relations Specialist",
    "Events",
    "dh-sneha-cultural",
    "#f97316",
    "MR",
    "Artist contracts, rider management, backstage coordination, and artist satisfaction",
    23,
    91,
  ),
  sp(
    "sp-csr-compliance",
    "Tarun",
    "CSR Compliance Specialist",
    "NGO",
    "dh-sana-csr",
    "#10b981",
    "TR",
    "Companies Act CSR requirements, 80G compliance, FCRA, and CSR reporting standards",
    23,
    95,
  ),
  sp(
    "sp-sports-management",
    "Dhruv",
    "Sports Management Specialist",
    "Events",
    "dh-sneha-cultural",
    "#f97316",
    "DH",
    "Sports event management, athlete relations, tournament operations, and sponsorship activation",
    34,
    90,
  ),
  sp(
    "sp-tourism-expert",
    "Lara",
    "Gujarat Tourism Expert",
    "Events",
    "dh-kavya-planning",
    "#f97316",
    "LA",
    "Gujarat destinations, travel packages, itinerary design, cultural tourism, and heritage sites",
    45,
    91,
  ),
  sp(
    "sp-content-strategy",
    "Isha",
    "Content Strategy Specialist",
    "Content",
    "dh-seema-blog",
    "#a855f7",
    "IS",
    "Content calendar, topic research, audience targeting, and content performance optimization",
    89,
    92,
  ),
  sp(
    "sp-lead-quality",
    "Vivek",
    "Lead Quality Specialist",
    "Client Relations",
    "dh-meera-crm",
    "#ec4899",
    "VV",
    "Lead quality scoring, disqualification criteria, pipeline hygiene, and lead source analysis",
    234,
    93,
  ),
  sp(
    "sp-market-research",
    "Komal",
    "Market Research Specialist",
    "Analytics",
    "dh-nikhil-bi",
    "#eab308",
    "KM",
    "Primary and secondary market research, survey design, focus groups, and insights reporting",
    45,
    91,
  ),
  sp(
    "sp-customer-success",
    "Hetal",
    "Customer Success Specialist",
    "Client Relations",
    "dh-nita-onboarding",
    "#ec4899",
    "HT",
    "Client health monitoring, success milestone tracking, upsell identification, and retention",
    123,
    94,
  ),
  sp(
    "sp-data-science",
    "Kaushal",
    "Data Science Specialist",
    "Analytics",
    "dh-arun-data",
    "#eab308",
    "KS",
    "Advanced statistical modeling, A/B testing, cohort analysis, and predictive analytics",
    67,
    95,
  ),
  sp(
    "sp-micro-market",
    "Jalpa",
    "Micro-Market Intelligence Specialist",
    "Property",
    "dh-suresh-valuation",
    "#c9a84c",
    "JP",
    "Street-level price tracking, hyperlocal demand signals, and micro-market appreciation trends",
    45,
    92,
  ),
  sp(
    "sp-builder-relations",
    "Nilesh",
    "Builder Relations Specialist",
    "Property",
    "dh-meena-compliance",
    "#c9a84c",
    "NL",
    "Builder trust assessment, RERA history, delivery record, and builder partnership management",
    34,
    91,
  ),
  sp(
    "sp-stamp-duty",
    "Prabhav",
    "Stamp Duty & Registration Specialist",
    "Legal",
    "dh-vikram-rera",
    "#3b82f6",
    "PB",
    "Gujarat stamp duty rates, registration process, jantri application, and SRO procedures",
    89,
    97,
  ),
  sp(
    "sp-capital-gains",
    "Bhoomi",
    "Capital Gains Tax Specialist",
    "Finance",
    "dh-dev-finance",
    "#22c55e",
    "BM",
    "STCG, LTCG, indexation, Section 54/54F/54EC, and capital gains optimization",
    67,
    96,
  ),
  sp(
    "sp-home-loan",
    "Sachin",
    "Home Loan Specialist",
    "Finance",
    "dh-amit-loans",
    "#22c55e",
    "SC",
    "Home loan processing, document verification, lender liaison, and disbursement tracking",
    89,
    95,
  ),
  sp(
    "sp-whatsapp-marketing",
    "Nayna",
    "WhatsApp Marketing Specialist",
    "Content",
    "dh-priti-social",
    "#a855f7",
    "NY",
    "WhatsApp broadcast strategy, message design, segment targeting, and engagement tracking",
    45,
    90,
  ),
  sp(
    "sp-photography",
    "Tanmay",
    "Property Photography Specialist",
    "Property",
    "dh-priya-listings",
    "#c9a84c",
    "TM",
    "Listing photo quality standards, virtual staging guidance, and visual presentation",
    23,
    91,
  ),
  sp(
    "sp-title-search",
    "Girish",
    "Title Search Specialist",
    "Legal",
    "dh-anita-docs",
    "#3b82f6",
    "GR",
    "Property title chain analysis, encumbrance certificate review, and ownership history verification",
    34,
    96,
  ),
  sp(
    "sp-project-tracker",
    "Chandni",
    "Under-Construction Project Tracker",
    "Property",
    "dh-meena-compliance",
    "#c9a84c",
    "CH",
    "Project completion monitoring, milestone tracking, and possession risk assessment",
    56,
    93,
  ),
  sp(
    "sp-investment-advisor",
    "Roshni",
    "Real Estate Investment Advisor",
    "Finance",
    "dh-pooja-investments",
    "#22c55e",
    "RI",
    "Investment portfolio building, yield optimization, diversification, and wealth planning via property",
    45,
    94,
  ),
  sp(
    "sp-tenant-specialist",
    "Parth",
    "Tenant Relations Specialist",
    "Property",
    "dh-priya-listings",
    "#c9a84c",
    "PT",
    "Tenant screening, lease negotiation, maintenance coordination, and tenancy dispute resolution",
    67,
    92,
  ),
  sp(
    "sp-society-specialist",
    "Disha",
    "Housing Society Specialist",
    "Property",
    "dh-suresh-valuation",
    "#c9a84c",
    "DS",
    "Society health analysis, maintenance records, defaulter tracking, and management quality rating",
    34,
    91,
  ),
  sp(
    "sp-floor-plan-analyst",
    "Shivam",
    "Floor Plan & Vastu Analyst",
    "Property",
    "dh-priya-listings",
    "#c9a84c",
    "SH",
    "Floor plan analysis, Vastu compliance scoring, space optimization, and renovation feasibility",
    45,
    89,
  ),
  sp(
    "sp-market-forecast",
    "Zankhna",
    "Market Forecast Specialist",
    "Analytics",
    "dh-arun-data",
    "#eab308",
    "ZK",
    "Property price forecasting models, demand-supply analysis, and 3-year market projections",
    30,
    90,
  ),
  sp(
    "sp-digital-marketing",
    "Prateek",
    "Digital Marketing Specialist",
    "Content",
    "dh-rohit-seo",
    "#a855f7",
    "PK",
    "PPC campaigns, social media ads, remarketing, and digital lead generation",
    89,
    91,
  ),
  sp(
    "sp-grant-writer",
    "Varsha",
    "NGO Grant & Fundraising Specialist",
    "NGO",
    "dh-geeta-impact",
    "#10b981",
    "VR",
    "Grant writing, CSR proposal creation, fundraising campaigns, and donor engagement",
    12,
    93,
  ),
  sp(
    "sp-sports-analytics",
    "Arpit",
    "Sports Analytics Specialist",
    "Events",
    "dh-sneha-cultural",
    "#f97316",
    "AP",
    "Athlete performance analytics, match statistics, training data analysis, and performance optimization",
    34,
    88,
  ),
  sp(
    "sp-music-curator",
    "Ridhi",
    "Music & Culture Curator",
    "Events",
    "dh-sneha-cultural",
    "#f97316",
    "RC",
    "Artist curation, genre programming, cultural calendar, and audience engagement for events",
    23,
    89,
  ),
  sp(
    "sp-loan-processing",
    "Jignesh",
    "Loan Processing Specialist",
    "Finance",
    "dh-amit-loans",
    "#22c55e",
    "JG",
    "Home loan file preparation, documentation checklist, bank submission, and approval tracking",
    89,
    95,
  ),
  sp(
    "sp-client-feedback",
    "Mona",
    "Client Feedback Specialist",
    "Client Relations",
    "dh-sujit-support",
    "#ec4899",
    "MO",
    "Feedback collection, sentiment analysis, NPS tracking, and satisfaction improvement programs",
    89,
    93,
  ),
  sp(
    "sp-competitor-analyst",
    "Krunal",
    "Competitor Intelligence Analyst",
    "Analytics",
    "dh-nikhil-bi",
    "#eab308",
    "KN",
    "Competitor listing monitoring, pricing analysis, campaign tracking, and market share estimation",
    24,
    88,
  ),
  sp(
    "sp-pwaa-specialist",
    "Alpesh",
    "Progressive Web App Specialist",
    "Technology",
    "dh-dev-platform",
    "#06b6d4",
    "AL",
    "PWA optimization, push notification management, offline experience, and mobile performance",
    45,
    94,
  ),
  sp(
    "sp-api-specialist",
    "Hemant",
    "API Integration Specialist",
    "Technology",
    "dh-dev-platform",
    "#06b6d4",
    "HM",
    "Third-party API integrations, data feeds, HTTP outcalls, and integration health monitoring",
    67,
    95,
  ),
  sp(
    "sp-ux-researcher",
    "Dimple",
    "UX Research Specialist",
    "Technology",
    "dh-pallavi-qa",
    "#06b6d4",
    "DM",
    "User research, usability testing, journey mapping, friction identification, and UX improvements",
    23,
    92,
  ),
  sp(
    "sp-tax-compliance",
    "Yogesh",
    "Tax Compliance Specialist",
    "Finance",
    "dh-dev-finance",
    "#22c55e",
    "YG",
    "GST on property, TDS on property, income tax on rental, and property-related tax compliance",
    56,
    97,
  ),
  sp(
    "sp-community-manager",
    "Swati",
    "Community Manager",
    "Client Relations",
    "dh-nita-onboarding",
    "#ec4899",
    "SW",
    "MSTC community building, client events, referral programs, and community engagement",
    67,
    91,
  ),
  sp(
    "sp-risk-analyst",
    "Tejas",
    "Property Risk Analyst",
    "Analytics",
    "dh-arun-data",
    "#eab308",
    "TJ",
    "Property risk scoring, legal risk, market risk, builder risk, and investment risk assessment",
    45,
    93,
  ),
  sp(
    "sp-data-quality",
    "Shruti",
    "Data Quality Specialist",
    "Analytics",
    "dh-lakshmi-reports",
    "#eab308",
    "SR",
    "Data validation, deduplication, enrichment, accuracy monitoring, and data governance",
    89,
    96,
  ),
  sp(
    "sp-infra-analyst",
    "Mukesh",
    "Infrastructure Impact Analyst",
    "Analytics",
    "dh-nikhil-bi",
    "#eab308",
    "MK",
    "Metro, highway, and airport project tracking with property price impact analysis",
    30,
    90,
  ),
  sp(
    "sp-multilingual",
    "Rekha",
    "Multilingual Content Specialist",
    "Content",
    "dh-seema-blog",
    "#a855f7",
    "RK",
    "Gujarati and Hindi content creation, translation quality, and regional language optimization",
    156,
    94,
  ),
];

// ── WORKER TIER (400 agents) ─────────────────────────────────────────────────────────
const WORKER_NAMES = [
  "Aakash",
  "Babita",
  "Chetan",
  "Divya",
  "Esha",
  "Farouk",
  "Gita",
  "Harsh",
  "Isha",
  "Jayesh",
  "Kalpana",
  "Lokesh",
  "Madhuri",
  "Nandini",
  "Omar",
  "Pankaj",
  "Quasar",
  "Rekha",
  "Satish",
  "Tara",
  "Uday",
  "Vasanti",
  "Waqar",
  "Xena",
  "Yuvraj",
  "Zara",
  "Abhay",
  "Bindu",
  "Chirag",
  "Darsha",
  "Ekta",
  "Faizan",
  "Gayatri",
  "Hemali",
  "Indira",
  "Jigna",
  "Komal",
  "Lalit",
  "Megha",
  "Naresh",
  "Omkar",
  "Payal",
  "Quasar",
  "Roshni",
  "Sandip",
  "Tulsi",
  "Umesh",
  "Vibha",
  "Wasim",
  "Yamini",
];

const WORKER_DEPTS = [
  {
    name: "Listing Agents",
    dept: "Property",
    reportsTo: "dh-priya-listings",
    color: "#c9a84c",
    role: "Listing Agent",
    specialty:
      "Property listing creation, photo processing, and listing quality management",
    count: 50,
  },
  {
    name: "Lead Qualification Agents",
    dept: "Client Relations",
    reportsTo: "dh-meera-crm",
    color: "#ec4899",
    role: "Lead Qualification Agent",
    specialty: "Lead qualification, budget assessment, and enquiry routing",
    count: 50,
  },
  {
    name: "Content Creation Agents",
    dept: "Content",
    reportsTo: "dh-seema-blog",
    color: "#a855f7",
    role: "Content Agent",
    specialty: "Article writing, area guide creation, and content publishing",
    count: 50,
  },
  {
    name: "Data Analysis Agents",
    dept: "Analytics",
    reportsTo: "dh-arun-data",
    color: "#eab308",
    role: "Data Analyst Agent",
    specialty: "Data extraction, cleaning, and analysis reporting",
    count: 50,
  },
  {
    name: "Quality Assurance Agents",
    dept: "Technology",
    reportsTo: "dh-pallavi-qa",
    color: "#06b6d4",
    role: "QA Agent",
    specialty: "Feature testing, bug detection, and quality verification",
    count: 50,
  },
  {
    name: "Monitoring Agents",
    dept: "Technology",
    reportsTo: "dh-vijay-security",
    color: "#06b6d4",
    role: "Monitoring Agent",
    specialty:
      "Platform uptime monitoring, error detection, and performance tracking",
    count: 50,
  },
  {
    name: "Communication Agents",
    dept: "Client Relations",
    reportsTo: "dh-sujit-support",
    color: "#ec4899",
    role: "Communication Agent",
    specialty: "WhatsApp follow-ups, SMS campaigns, and lead communication",
    count: 50,
  },
  {
    name: "Property Intelligence Agents",
    dept: "Property",
    reportsTo: "dh-suresh-valuation",
    color: "#c9a84c",
    role: "Property Intelligence Agent",
    specialty:
      "Market monitoring, price tracking, and property intelligence updates",
    count: 50,
  },
];

function generateWorkers(): AIStaffMember[] {
  const workers: AIStaffMember[] = [];
  WORKER_DEPTS.forEach(
    ({ dept, reportsTo, color, role, specialty, count }, deptIdx) => {
      for (let i = 1; i <= count; i++) {
        const nameIdx = (deptIdx * count + i - 1) % WORKER_NAMES.length;
        const name = `${WORKER_NAMES[nameIdx]} ${String(i).padStart(2, "0")}`;
        const initials = `${WORKER_NAMES[nameIdx][0]}${String(i).padStart(2, "0")}`;
        const tasks = 20 + ((deptIdx * 13 + i * 7) % 80);
        const score = 85 + ((deptIdx * 7 + i * 3) % 14);
        workers.push({
          id: `worker-${dept.toLowerCase().replace(/[^a-z]/g, "-")}-${String(i).padStart(2, "0")}`,
          name,
          type: "ai",
          role,
          department: dept,
          tier: "worker",
          reportsTo,
          directReports: [],
          avatarColor: color,
          avatarInitials: initials,
          specialty,
          tasksToday: tasks,
          tasksThisWeek: tasks * 7,
          performanceScore: score,
          status: "working",
          statusNote: `${role} — ${dept}`,
          chatEnabled: false,
        });
      }
    },
  );
  return workers;
}

const WORKER_STAFF: AIStaffMember[] = generateWorkers();

// ── Combined Exports ─────────────────────────────────────────────────────────────
export const AI_STAFF: AIStaffMember[] = [
  ...EXECUTIVE_STAFF,
  ...GM_STAFF,
  ...DEPT_HEAD_STAFF,
  ...SPECIALIST_STAFF,
  ...WORKER_STAFF,
];

export const AI_STAFF_BY_ID: Record<string, AIStaffMember> = Object.fromEntries(
  AI_STAFF.map((s) => [s.id, s]),
);

export interface OrgNode {
  member: AIStaffMember;
  children: OrgNode[];
}

function buildTree(id: string): OrgNode {
  const member = AI_STAFF_BY_ID[id];
  const children = AI_STAFF.filter((s) => s.reportsTo === id).map((s) =>
    buildTree(s.id),
  );
  return { member, children };
}

export const AI_STAFF_ORG_TREE: OrgNode = buildTree("md-love-parekh");

export const AI_STAFF_STATS = {
  total: AI_STAFF.length,
  byTier: {
    executive: EXECUTIVE_STAFF.length,
    gm: GM_STAFF.length,
    "dept-head": DEPT_HEAD_STAFF.length,
    specialist: SPECIALIST_STAFF.length,
    worker: WORKER_STAFF.length,
  },
  byDepartment: Object.fromEntries(
    Array.from(new Set(AI_STAFF.map((s) => s.department))).map((dept) => [
      dept,
      AI_STAFF.filter((s) => s.department === dept).length,
    ]),
  ),
  chatEnabledCount: AI_STAFF.filter((s) => s.chatEnabled).length,
  aiCount: AI_STAFF.filter((s) => s.type === "ai").length,
  humanCount: AI_STAFF.filter((s) => s.type === "human").length,
};
