/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIActivityEntry {
  'result' : string,
  'count' : bigint,
  'agentName' : string,
  'actionType' : string,
  'agentId' : string,
  'timestamp' : string,
}
export interface AIAgent {
  'id' : string,
  'name' : string,
  'tier' : string,
  'description' : string,
  'actionsLog' : Array<string>,
  'isActive' : boolean,
  'category' : string,
  'config' : string,
  'parentId' : [] | [string],
  'lastAction' : string,
}
export interface AIInsight {
  'id' : string,
  'status' : string,
  'title' : string,
  'content' : string,
  'createdAt' : string,
  'agentId' : string,
  'priority' : string,
}
export interface AISystemConfig {
  'totalAgents' : bigint,
  'openAIKeySet' : boolean,
  'activeProvider' : string,
  'fallbackOrder' : Array<string>,
  'claudeKeySet' : boolean,
  'activeAgents' : bigint,
  'geminiKeySet' : boolean,
}
export interface AdminStaffMember {
  'id' : string,
  'accessLevel' : string,
  'canExport' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'role' : string,
  'isActive' : boolean,
  'email' : string,
  'loginId' : string,
  'passwordHash' : string,
  'canDelete' : boolean,
  'accessSections' : Array<string>,
  'phone' : string,
  'lastLogin' : [] | [bigint],
}
export interface AgentActivity {
  'status' : string,
  'result' : string,
  'action' : string,
  'agentName' : string,
  'agentId' : string,
  'timestamp' : bigint,
  'cluster' : string,
}
export interface AiDecision {
  'id' : string,
  'decisionType' : AiDecisionType,
  'reversalReason' : string,
  'agentName' : string,
  'description' : string,
  'confidenceScore' : bigint,
  'reversed' : boolean,
  'timestamp' : bigint,
  'reversedAt' : [] | [bigint],
  'reversible' : boolean,
  'outcome' : string,
  'actionTaken' : string,
}
export type AiDecisionType = { 'BOOKING_CONFIRMED' : null } |
  { 'SECURITY_BLOCKED' : null } |
  { 'ANOMALY_FLAGGED' : null } |
  { 'MINOR_UI_FIX' : null } |
  { 'LEAD_SCORED' : null } |
  { 'COMMISSION_CALCULATED' : null } |
  { 'FOLLOW_UP_SENT' : null } |
  { 'PROPERTY_PUBLISHED' : null } |
  { 'OTHER' : null } |
  { 'CONTENT_PUBLISHED' : null };
export interface AnniversaryReminder {
  'id' : string,
  'clientName' : string,
  'createdAt' : bigint,
  'email' : string,
  'reminderDate' : string,
  'reminderType' : string,
  'notes' : string,
  'phone' : string,
}
export interface Announcement {
  'id' : string,
  'title' : string,
  'expiresAt' : [] | [bigint],
  'createdAt' : bigint,
  'isActive' : boolean,
  'ctaText' : string,
  'message' : string,
  'ctaUrl' : string,
  'bgColor' : string,
  'scheduledAt' : [] | [bigint],
}
export interface AppNotification {
  'id' : bigint,
  'title' : string,
  'appName' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
  'message' : string,
  'targetRole' : string,
  'priority' : string,
}
export interface Appointment {
  'id' : string,
  'service' : string,
  'status' : string,
  'clientName' : string,
  'createdAt' : bigint,
  'type' : string,
  'clientEmail' : string,
  'preferredDate' : string,
  'notes' : string,
  'clientPhone' : string,
  'preferredTime' : string,
}
export interface Auction {
  'id' : string,
  'startTime' : Timestamp,
  'status' : AuctionStatus,
  'title' : string,
  'endTime' : Timestamp,
  'winnerId' : [] | [string],
  'bids' : Array<Bid>,
  'description' : string,
  'propertyId' : string,
  'currentBid' : number,
  'startPrice' : number,
  'bidIncrement' : number,
}
export interface AuctionListing {
  'id' : string,
  'status' : string,
  'title' : string,
  'features' : Array<string>,
  'propertyType' : string,
  'minimumBid' : bigint,
  'description' : string,
  'watchCount' : bigint,
  'currentBid' : bigint,
  'bidCount' : bigint,
  'startPrice' : bigint,
  'location' : string,
  'endsAt' : bigint,
}
export type AuctionStatus = string;
export interface AuditEntry {
  'id' : string,
  'result' : string,
  'action' : string,
  'actorId' : string,
  'target' : string,
  'timestamp' : bigint,
  'details' : string,
  'ipAddress' : string,
}
export interface AuditRecord {
  'id' : bigint,
  'action' : string,
  'staffId' : string,
  'target' : string,
  'deviceId' : string,
  'timestamp' : bigint,
  'details' : string,
  'ipAddress' : string,
}
export interface Bid {
  'id' : string,
  'auctionId' : string,
  'timestamp' : Timestamp,
  'bidderId' : string,
  'amount' : number,
  'isWinning' : boolean,
}
export interface BlogPost {
  'id' : string,
  'metaDescription' : string,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'createdAt' : bigint,
  'slug' : string,
  'author' : string,
  'updatedAt' : bigint,
  'excerpt' : string,
  'category' : string,
}
export interface Booking {
  'id' : string,
  'status' : BookingStatus,
  'clientId' : string,
  'createdAt' : Timestamp,
  'agentId' : string,
  'propertyId' : string,
  'notes' : string,
  'bookingType' : BookingType,
  'scheduledAt' : Timestamp,
}
export type BookingStatus = string;
export type BookingType = string;
export interface BuilderProfile {
  'id' : string,
  'contact' : string,
  'about' : string,
  'ongoingProjects' : bigint,
  'name' : string,
  'registeredSince' : string,
  'localities' : Array<string>,
  'isVerified' : boolean,
  'completedProjects' : bigint,
  'rating' : number,
  'reraNumber' : string,
}
export interface BuilderTrustRecord {
  'deliveryScore' : bigint,
  'trustScore' : bigint,
  'lastUpdated' : bigint,
  'builderName' : string,
  'complaintCount' : bigint,
  'reraFilingCount' : bigint,
  'builderId' : string,
}
export interface CallbackRequest {
  'id' : string,
  'service' : string,
  'name' : string,
  'pageName' : string,
  'isRead' : boolean,
  'timestamp' : bigint,
  'phone' : string,
}
export interface Campaign {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'messagePreview' : string,
  'createdAt' : bigint,
  'audience' : string,
  'sentCount' : bigint,
  'replyCount' : bigint,
  'openCount' : bigint,
  'channel' : string,
  'scheduledAt' : [] | [bigint],
}
export interface CanaryToken {
  'id' : string,
  'createdAt' : bigint,
  'triggeredAt' : [] | [bigint],
  'triggeredBy' : string,
  'tokenValue' : string,
  'isTriggered' : boolean,
  'tokenLabel' : string,
}
export interface ChatInteraction {
  'id' : bigint,
  'messageLength' : bigint,
  'userMessage' : string,
  'timestamp' : bigint,
  'sessionId' : string,
  'sentimentTag' : string,
  'botResponse' : string,
}
export interface Client {
  'id' : string,
  'status' : string,
  'totalValue' : string,
  'name' : string,
  'createdAt' : bigint,
  'joinedAt' : bigint,
  'buyingReadiness' : string,
  'type' : string,
  'lastUpdated' : bigint,
  'email' : string,
  'lifetimeValue' : bigint,
  'address' : string,
  'notes' : string,
  'phone' : string,
  'totalDeals' : bigint,
  'lastInteraction' : [] | [bigint],
}
export interface Client__1 {
  'id' : bigint,
  'ltv' : bigint,
  'clientType' : string,
  'totalValue' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'notes' : string,
  'phone' : string,
  'lastContact' : bigint,
  'totalDeals' : bigint,
}
export interface CommandResult {
  'data' : string,
  'message' : string,
  'success' : boolean,
}
export interface CommissionInvoice {
  'id' : bigint,
  'status' : string,
  'serviceType' : string,
  'clientName' : string,
  'createdAt' : bigint,
  'dueDate' : bigint,
  'description' : string,
  'commission' : bigint,
  'paidDate' : [] | [bigint],
  'amount' : bigint,
}
export interface CommissionRecord {
  'id' : string,
  'status' : CommissionStatus,
  'approvedBy' : [] | [string],
  'createdAt' : Timestamp,
  'agentId' : string,
  'dealId' : string,
  'amount' : number,
  'paidAt' : [] | [Timestamp],
  'percentage' : number,
}
export type CommissionStatus = string;
export interface ComplaintTicket {
  'id' : string,
  'service' : string,
  'customerName' : string,
  'status' : string,
  'createdAt' : bigint,
  'notes' : string,
  'issue' : string,
  'phone' : string,
  'refNumber' : string,
  'resolvedAt' : [] | [bigint],
}
export interface Course {
  'id' : string,
  'title' : string,
  'duration' : bigint,
  'isPublished' : boolean,
  'instructor' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'lessons' : Array<Lesson>,
  'category' : string,
  'enrolledCount' : bigint,
}
export interface CrmAppointment {
  'id' : bigint,
  'status' : string,
  'durationMins' : bigint,
  'clientName' : string,
  'createdBy' : string,
  'type' : string,
  'notes' : string,
  'location' : string,
  'scheduledAt' : bigint,
}
export interface CsrImpactEntry {
  'id' : string,
  'metric' : string,
  'value' : bigint,
  'year' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'category' : string,
}
export interface DailyBriefing {
  'id' : string,
  'marketNews' : Array<string>,
  'dealsMovingCount' : bigint,
  'revenueFigure' : number,
  'generatedSummary' : string,
  'date' : string,
  'createdAt' : bigint,
  'newLeadsCount' : bigint,
  'securityEventsCount' : bigint,
  'tasksDueCount' : bigint,
}
export interface DashboardStat {
  'key' : string,
  'value' : bigint,
  'period' : string,
  'icon' : string,
  'change' : bigint,
  'statLabel' : string,
}
export interface DashboardStats {
  'tasksCompletedToday' : bigint,
  'totalProperties' : bigint,
  'totalLeads' : bigint,
  'totalCallbacks' : bigint,
  'totalEnquiries' : bigint,
  'totalFeedback' : bigint,
  'activeAgents' : bigint,
  'totalInteractions' : bigint,
}
export interface Deal {
  'id' : string,
  'actualCloseDate' : [] | [Timestamp],
  'title' : string,
  'documents' : Array<string>,
  'clientId' : string,
  'createdAt' : Timestamp,
  'agentId' : string,
  'propertyId' : string,
  'expectedCloseDate' : Timestamp,
  'stage' : DealStage,
  'notes' : string,
  'commissionAmount' : number,
}
export interface DealNote {
  'id' : string,
  'content' : string,
  'authorId' : string,
  'dealId' : string,
  'timestamp' : Timestamp,
}
export type DealStage = string;
export interface Deal__1 {
  'id' : string,
  'service' : string,
  'clientName' : string,
  'createdAt' : bigint,
  'clientEmail' : string,
  'updatedAt' : bigint,
  'stage' : string,
  'notes' : string,
  'clientPhone' : string,
  'followUpDate' : [] | [bigint],
}
export interface DeviceRecord {
  'id' : string,
  'status' : DeviceStatus,
  'staffId' : string,
  'lastSeenAt' : bigint,
  'trustScore' : bigint,
  'deviceId' : string,
  'userAgent' : string,
  'registeredAt' : bigint,
  'ipAddress' : string,
}
export type DeviceStatus = { 'trusted' : null } |
  { 'revoked' : null } |
  { 'pending' : null } |
  { 'blocked' : null };
export interface Enrollment {
  'id' : string,
  'completedAt' : [] | [Timestamp],
  'studentId' : string,
  'progress' : bigint,
  'completedLessons' : Array<string>,
  'enrolledAt' : Timestamp,
  'courseId' : string,
}
export interface EventBooking {
  'id' : string,
  'status' : string,
  'clientName' : string,
  'venue' : string,
  'guestCount' : string,
  'createdAt' : bigint,
  'clientEmail' : string,
  'notes' : string,
  'clientPhone' : string,
  'eventDate' : string,
  'eventType' : string,
}
export interface Event_ {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'venue' : string,
  'type' : string,
  'description' : string,
  'confirmedCount' : bigint,
  'capacity' : bigint,
  'budget' : bigint,
  'scheduledAt' : bigint,
}
export interface ExchangeEnquiry {
  'id' : string,
  'listingId' : string,
  'offerPrice' : [] | [number],
  'message' : string,
  'buyerId' : string,
  'timestamp' : Timestamp,
}
export interface ExchangeListing {
  'id' : string,
  'status' : ListingStatus,
  'createdAt' : Timestamp,
  'description' : string,
  'propertyId' : string,
  'askPrice' : number,
  'viewCount' : bigint,
  'enquiries' : Array<ExchangeEnquiry>,
  'sellerId' : string,
}
export interface Feedback {
  'id' : string,
  'pageName' : string,
  'isRead' : boolean,
  'comment' : string,
  'timestamp' : bigint,
  'rating' : bigint,
}
export interface FinancialMetric {
  'totalCommissions' : bigint,
  'averageDealSize' : bigint,
  'period' : string,
  'newLeads' : bigint,
  'conversionRate' : bigint,
  'totalRevenue' : bigint,
  'closedDeals' : bigint,
}
export interface FormStats {
  'todayCallbacks' : bigint,
  'unreadQuotes' : bigint,
  'todayFeedback' : bigint,
  'totalCallbacks' : bigint,
  'unreadMoreInfo' : bigint,
  'totalMoreInfo' : bigint,
  'todayQuotes' : bigint,
  'unreadFeedback' : bigint,
  'totalQuotes' : bigint,
  'totalFeedback' : bigint,
  'unreadSupport' : bigint,
  'todaySupport' : bigint,
  'totalSupport' : bigint,
  'unreadCallbacks' : bigint,
}
export interface InterestRateEntry { 'bank' : string, 'rate' : number }
export type InvestmentGrade = { 'buy' : null } |
  { 'avoid' : null } |
  { 'hold' : null };
export interface Invoice {
  'id' : string,
  'service' : string,
  'status' : string,
  'clientName' : string,
  'createdAt' : bigint,
  'clientEmail' : string,
  'invoiceNumber' : string,
  'totalAmount' : number,
  'notes' : string,
  'clientPhone' : string,
  'taxAmount' : number,
}
export interface JantriRate {
  'area' : string,
  'updatedAt' : bigint,
  'ratePerSqFt' : bigint,
  'effectiveFrom' : string,
}
export interface Lead {
  'id' : string,
  'status' : string,
  'assignedTo' : string,
  'interest' : string,
  'propertyType' : string,
  'source' : string,
  'name' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'email' : string,
  'heatScore' : bigint,
  'score' : bigint,
  'stage' : string,
  'notes' : string,
  'phone' : string,
  'lastContact' : [] | [bigint],
  'budget' : string,
  'location' : string,
  'followUpDate' : [] | [bigint],
}
export interface LeadNurtureReminder {
  'id' : string,
  'service' : string,
  'leadName' : string,
  'reminderDays' : bigint,
  'leadId' : string,
  'isDismissed' : boolean,
  'phone' : string,
  'lastContactedAt' : bigint,
}
export interface LeadQualification {
  'id' : string,
  'propertyType' : string,
  'createdAt' : bigint,
  'leadScore' : string,
  'sessionId' : string,
  'budget' : string,
  'location' : string,
}
export interface Lead__1 {
  'id' : bigint,
  'service' : string,
  'assignedTo' : string,
  'source' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'score' : string,
  'updatedAt' : bigint,
  'stage' : string,
  'notes' : string,
  'estimatedValue' : bigint,
  'phone' : string,
}
export interface LegalDoc {
  'id' : string,
  'title' : string,
  'createdAt' : bigint,
  'version' : bigint,
  'docStatus' : string,
  'updatedAt' : bigint,
  'signedBy' : Array<string>,
  'category' : string,
  'riskScore' : bigint,
}
export interface Lesson {
  'id' : string,
  'title' : string,
  'duration' : bigint,
  'content' : string,
  'order' : bigint,
  'videoUrl' : [] | [string],
  'courseId' : string,
}
export type ListingStatus = string;
export interface LocalityDemand {
  'lastUpdated' : bigint,
  'viewCount' : bigint,
  'enquiryCount' : bigint,
  'locality' : string,
}
export interface MarketDataPoint {
  'id' : string,
  'month' : bigint,
  'trend' : string,
  'propertyType' : string,
  'year' : bigint,
  'avgPricePerSqft' : bigint,
  'locality' : string,
}
export interface MarketReport {
  'id' : string,
  'month' : string,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'createdAt' : bigint,
  'year' : string,
}
export type MediaCategory = string;
export interface MediaPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'views' : bigint,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'publishedAt' : [] | [Timestamp],
  'author' : string,
  'category' : MediaCategory,
}
export interface MoreInfoRequest {
  'id' : string,
  'service' : string,
  'question' : string,
  'name' : string,
  'pageName' : string,
  'isRead' : boolean,
  'email' : string,
  'timestamp' : bigint,
}
export interface MusicArtist {
  'id' : string,
  'bio' : string,
  'name' : string,
  'instagramUrl' : string,
  'available' : boolean,
  'bookingContact' : string,
  'genre' : string,
  'specialties' : Array<string>,
  'youtubeUrl' : string,
}
export interface NewsArticle {
  'url' : string,
  'title' : string,
  'source' : string,
  'publishedAt' : string,
  'summary' : string,
  'imageUrl' : string,
}
export interface Notification {
  'id' : string,
  'title' : string,
  'createdAt' : bigint,
  'type' : string,
  'isRead' : boolean,
  'message' : string,
  'relatedId' : [] | [string],
}
export interface ObserverAccessLog {
  'id' : string,
  'code' : string,
  'scope' : string,
  'timestamp' : bigint,
  'sessionId' : string,
}
export interface ObserverCode {
  'id' : bigint,
  'lastUsedAt' : [] | [bigint],
  'permissions' : Array<string>,
  'useCount' : bigint,
  'expiresAt' : [] | [bigint],
  'code' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'expiryType' : string,
  'labelText' : string,
  'isActive' : boolean,
}
export interface ObserverCodeInfo {
  'codeLabel' : string,
  'active' : boolean,
  'expiresAt' : [] | [bigint],
  'code' : string,
  'usedAt' : [] | [bigint],
  'usedBy' : [] | [string],
  'createdAt' : bigint,
  'createdBy' : string,
  'used' : boolean,
  'scope' : Array<string>,
  'singleUse' : boolean,
}
export interface ObserverCodeRecord {
  'expiresAt' : bigint,
  'isRevoked' : boolean,
  'code' : string,
  'createdBy' : string,
  'used' : boolean,
  'observerLabel' : string,
  'scope' : string,
  'singleUse' : boolean,
}
export interface PartnerApplication {
  'id' : string,
  'status' : string,
  'areas' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'experience' : string,
  'company' : string,
  'notes' : string,
  'phone' : string,
}
export interface PriceHistoryEntry {
  'note' : string,
  'propertyId' : string,
  'recordedAt' : bigint,
  'recordedBy' : string,
  'price' : bigint,
}
export interface Property {
  'id' : string,
  'status' : string,
  'title' : string,
  'propertyType' : string,
  'views' : bigint,
  'area' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'type' : string,
  'builderName' : string,
  'description' : string,
  'amenities' : Array<string>,
  'listingDate' : bigint,
  'enquiries' : bigint,
  'areaRaw' : bigint,
  'price' : string,
  'priceRaw' : bigint,
  'location' : string,
  'reraNumber' : [] | [string],
  'images' : Array<string>,
}
export interface PropertyAlert {
  'id' : string,
  'bhk' : string,
  'action' : string,
  'propertyType' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'phone' : string,
  'location' : string,
  'maxBudget' : bigint,
}
export interface PropertyEnquiry {
  'id' : string,
  'ownerEmail' : string,
  'customerName' : string,
  'status' : string,
  'propertyPrice' : string,
  'ownerName' : string,
  'contactedAt' : [] | [bigint],
  'propertySqft' : bigint,
  'propertyType' : string,
  'customerPhone' : string,
  'visitDate' : string,
  'ownerPhone' : string,
  'propertyTitle' : string,
  'submittedAt' : bigint,
  'propertyId' : string,
  'propertyAddress' : string,
  'sourceTag' : string,
  'customerMessage' : string,
  'propertyBhk' : string,
  'agencyName' : string,
  'notes' : string,
  'preferredTime' : string,
  'agencyPhone' : string,
  'customerEmail' : string,
}
export interface PropertyIntelligence {
  'latitude' : number,
  'builderTrustScore' : bigint,
  'propertyId' : string,
  'amenities' : Array<string>,
  'updatedAt' : bigint,
  'longitude' : number,
  'investmentGrade' : InvestmentGrade,
  'negotiationMax' : bigint,
  'negotiationMin' : bigint,
  'reraNumber' : string,
  'builderId' : string,
}
export interface PropertyListing {
  'id' : string,
  'bhk' : string,
  'ownerEmail' : string,
  'title' : string,
  'action' : string,
  'ownerName' : string,
  'propertyType' : string,
  'mapLink' : string,
  'city' : string,
  'sqft' : bigint,
  'listedDate' : string,
  'ownerPhone' : string,
  'description' : string,
  'sourceTag' : string,
  'amenities' : Array<string>,
  'address' : string,
  'agencyName' : string,
  'priceDisplay' : string,
  'price' : bigint,
  'agencyPhone' : string,
  'furnishing' : string,
  'possession' : string,
  'facing' : string,
  'location' : string,
  'floorNo' : bigint,
  'societyName' : string,
  'images' : Array<string>,
}
export interface PropertyPerformance {
  'title' : string,
  'views' : bigint,
  'alerts' : bigint,
  'propertyId' : string,
  'enquiries' : bigint,
  'price' : bigint,
  'location' : string,
}
export interface Proposal {
  'id' : bigint,
  'status' : string,
  'expiresAt' : bigint,
  'clientName' : string,
  'createdAt' : bigint,
  'propertyTitle' : string,
  'notes' : string,
  'amount' : bigint,
}
export interface QuoteRequest {
  'id' : string,
  'service' : string,
  'name' : string,
  'pageName' : string,
  'isRead' : boolean,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface RSVP {
  'id' : bigint,
  'status' : string,
  'eventId' : bigint,
  'guestCount' : bigint,
  'guestName' : string,
  'email' : string,
  'phone' : string,
}
export interface Referral {
  'id' : string,
  'clicks' : bigint,
  'referrerName' : string,
  'code' : string,
  'createdAt' : bigint,
  'referrerEmail' : string,
  'enquiries' : Array<string>,
  'referrerPhone' : string,
}
export interface ReviewRecord {
  'id' : bigint,
  'responded' : boolean,
  'sentiment' : string,
  'reviewDate' : bigint,
  'reviewText' : string,
  'reviewerName' : string,
  'platform' : string,
  'rating' : bigint,
  'responseText' : [] | [string],
}
export interface RichSecurityEvent {
  'id' : string,
  'aiTierId' : string,
  'resolved' : boolean,
  'description' : string,
  'sourceIp' : string,
  'timestamp' : bigint,
  'severity' : string,
  'resolvedAt' : [] | [bigint],
  'eventType' : string,
}
export interface SatisfactionRating {
  'id' : string,
  'submittedAt' : bigint,
  'feedback' : string,
  'enquiryId' : string,
  'rating' : bigint,
}
export interface SecurityEvent {
  'id' : bigint,
  'staffId' : string,
  'deviceId' : string,
  'timestamp' : bigint,
  'details' : string,
  'ipAddress' : string,
  'eventType' : SecurityEventType,
}
export type SecurityEventType = { 'CANARY_TRIGGERED' : null } |
  { 'OTP_FAIL' : null } |
  { 'OTP_SENT' : null } |
  { 'LOGIN_SUCCESS' : null } |
  { 'EMERGENCY_LOCKDOWN' : null } |
  { 'FORCE_LOGOUT' : null } |
  { 'LOCKOUT' : null } |
  { 'BIOMETRIC_ENROLL' : null } |
  { 'LOGIN_FAIL' : null } |
  { 'ANOMALY_DETECTED' : null };
export interface SecurityHealthReport {
  'canaryTriggered' : boolean,
  'overallScore' : bigint,
  'recommendations' : Array<string>,
  'generatedAt' : bigint,
  'lockoutsLast24h' : bigint,
  'failedLoginsLast24h' : bigint,
  'activeSessions' : bigint,
  'pendingBiometrics' : bigint,
  'suspendedAccounts' : bigint,
  'threatsBlocked' : bigint,
}
export interface Service {
  'id' : bigint,
  'icon' : string,
  'name' : string,
  'slug' : string,
  'description' : string,
}
export interface ServiceSubmission {
  'id' : bigint,
  'submitterPhone' : string,
  'serviceCategory' : string,
  'submitterName' : string,
  'innerPage' : string,
  'formType' : string,
  'isRead' : boolean,
  'fields' : Array<[string, string]>,
  'indemnityAccepted' : boolean,
  'timestamp' : bigint,
  'submitterEmail' : string,
}
export interface Session {
  'staffId' : string,
  'lastActivity' : bigint,
  'createdAt' : bigint,
  'isActive' : boolean,
  'deviceId' : string,
  'sessionId' : string,
  'userAgent' : string,
  'ipAddress' : string,
}
export interface SiteVisit {
  'id' : string,
  'status' : string,
  'clientName' : string,
  'scheduledDate' : bigint,
  'scheduledTime' : string,
  'createdAt' : bigint,
  'propertyAddress' : string,
  'notes' : string,
  'clientPhone' : string,
}
export interface SocietyReview {
  'id' : string,
  'review' : string,
  'isApproved' : boolean,
  'createdAt' : bigint,
  'security' : bigint,
  'amenities' : bigint,
  'maintenance' : bigint,
  'rating' : bigint,
  'management' : bigint,
  'reviewerAlias' : string,
  'societyName' : string,
}
export interface Staff {
  'id' : string,
  'firstLoginDone' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'role' : StaffRole,
  'biometricPublicKey' : string,
  'mobileNumber' : string,
  'isActive' : boolean,
  'email' : string,
  'loginAttempts' : bigint,
  'biometricEnrolled' : boolean,
  'deviceId' : string,
  'sessionToken' : string,
  'isSuspended' : boolean,
  'passwordHash' : string,
  'lastLogin' : bigint,
  'lockedUntil' : bigint,
}
export type StaffRole = { 'manager' : null } |
  { 'admin' : null } |
  { 'agent' : null } |
  { 'viewer' : null };
export interface SupportForm {
  'id' : string,
  'service' : string,
  'name' : string,
  'isRead' : boolean,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface ThreatIntelEntry {
  'id' : string,
  'isBlocked' : boolean,
  'detectedAt' : bigint,
  'severity' : string,
  'ipAddress' : string,
  'reason' : string,
}
export interface TimeSlot {
  'date' : string,
  'slots' : Array<string>,
  'bookedSlots' : Array<string>,
}
export type Timestamp = bigint;
export interface TutorialApp {
  'appName' : string,
  'quickStepCount' : bigint,
  'appKey' : string,
  'fullStepCount' : bigint,
}
export interface TutorialCompletion {
  'completedAt' : bigint,
  'skipped' : boolean,
  'userId' : string,
  'mode' : string,
  'appKey' : string,
}
export interface TutorialStep {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'stepIndex' : bigint,
  'order' : bigint,
  'targetElement' : [] | [string],
  'mode' : string,
  'isActive' : boolean,
  'appKey' : string,
}
export interface TutorialSuggestion {
  'id' : bigint,
  'status' : string,
  'stepIndex' : bigint,
  'mode' : string,
  'createdAt' : bigint,
  'suggestedContent' : string,
  'appKey' : string,
  'reason' : string,
}
export interface Vendor {
  'id' : string,
  'contactName' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'totalJobs' : bigint,
  'isActive' : boolean,
  'email' : string,
  'notes' : string,
  'category' : string,
  'rating' : number,
  'phone' : string,
}
export interface VendorJob {
  'id' : string,
  'status' : VendorJobStatus,
  'completedAt' : [] | [Timestamp],
  'jobType' : string,
  'createdAt' : Timestamp,
  'propertyId' : string,
  'vendorId' : string,
  'amount' : number,
}
export type VendorJobStatus = string;
export interface VisitRequest {
  'id' : string,
  'customerName' : string,
  'status' : string,
  'customerPhone' : string,
  'createdAt' : bigint,
  'propertyTitle' : string,
  'visitType' : string,
  'propertyId' : string,
  'preferredDate' : string,
  'preferredTime' : string,
  'customerEmail' : string,
}
export interface _SERVICE {
  'addAIInsight' : ActorMethod<[AIInsight], boolean>,
  'addActiveVisitor' : ActorMethod<[string], undefined>,
  'addAnniversaryReminder' : ActorMethod<
    [string, string, string, string, string, string],
    string
  >,
  'addAnnouncement' : ActorMethod<
    [string, string, string, string, string, [] | [bigint], [] | [bigint]],
    string
  >,
  'addAppointment' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    string
  >,
  'addBlogPost' : ActorMethod<
    [string, string, string, string, string, string, string],
    string
  >,
  'addBuilderProfile' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      bigint,
      number,
      Array<string>,
      string,
      string,
    ],
    string
  >,
  'addCampaign' : ActorMethod<[string, string, string, string], Campaign>,
  'addClient' : ActorMethod<[string, string, string, string, string], string>,
  'addCommissionInvoice' : ActorMethod<
    [string, string, bigint, bigint, bigint, string],
    CommissionInvoice
  >,
  'addCrmAppointment' : ActorMethod<
    [string, string, bigint, bigint, string, string],
    CrmAppointment
  >,
  'addCrmNotification' : ActorMethod<
    [string, string, string, string, string],
    AppNotification
  >,
  'addDeal' : ActorMethod<[string, string, string, string], string>,
  'addDealCounterUpdate' : ActorMethod<[bigint, string], boolean>,
  'addDealNote' : ActorMethod<
    [string, string, string],
    { 'ok' : DealNote } |
      { 'err' : string }
  >,
  /**
   * / Add an enquiry for a property (frontend-facing convenience wrapper).
   */
  'addEnquiry' : ActorMethod<
    [string, string, string, string, string, string, string],
    string
  >,
  'addEvent' : ActorMethod<
    [string, string, bigint, string, bigint, bigint, string],
    Event_
  >,
  'addEventBooking' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    string
  >,
  'addInvoice' : ActorMethod<
    [string, string, string, string, string, number, number, string],
    string
  >,
  'addLead' : ActorMethod<[string, string, string, string, bigint], string>,
  'addLeadNote' : ActorMethod<[string, string], boolean>,
  'addLeadNurtureReminder' : ActorMethod<
    [string, string, string, string, bigint],
    boolean
  >,
  'addLegalDoc' : ActorMethod<
    [
      {
        'title' : string,
        'docStatus' : string,
        'signedBy' : Array<string>,
        'category' : string,
        'riskScore' : bigint,
      },
    ],
    string
  >,
  'addLesson' : ActorMethod<
    [string, string, string, bigint],
    { 'ok' : Lesson } |
      { 'err' : string }
  >,
  'addMarketData' : ActorMethod<
    [
      {
        'month' : bigint,
        'trend' : string,
        'propertyType' : string,
        'year' : bigint,
        'avgPricePerSqft' : bigint,
        'locality' : string,
      },
    ],
    string
  >,
  'addMarketReport' : ActorMethod<[string, string, string, string], string>,
  'addMusicArtist' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<string>,
      string,
      string,
      string,
      boolean,
    ],
    string
  >,
  'addNotification' : ActorMethod<
    [string, string, string, [] | [string]],
    string
  >,
  'addPartnerApplication' : ActorMethod<
    [string, string, string, string, string, string],
    string
  >,
  'addPriceHistory' : ActorMethod<
    [string, string, bigint, string, string],
    boolean
  >,
  'addProperty' : ActorMethod<
    [string, string, string, bigint, bigint, string],
    string
  >,
  'addProposal' : ActorMethod<
    [string, string, bigint, bigint, string],
    Proposal
  >,
  'addRSVP' : ActorMethod<[bigint, string, string, string, bigint], RSVP>,
  'addReview' : ActorMethod<[string, string, bigint, string], ReviewRecord>,
  'addSiteVisit' : ActorMethod<
    [string, string, string, bigint, string, string],
    string
  >,
  'addStaff' : ActorMethod<
    [string, string, string, string, StaffRole, string],
    boolean
  >,
  'addStaffMember' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      string,
      boolean,
      boolean,
    ],
    string
  >,
  'addThreatEntry' : ActorMethod<
    [string, string, string],
    { 'ok' : ThreatIntelEntry } |
      { 'err' : string }
  >,
  'addTutorialStep' : ActorMethod<
    [
      {
        'title' : string,
        'appId' : string,
        'stepIndex' : bigint,
        'targetElement' : string,
        'description' : string,
        'stepType' : string,
      },
    ],
    string
  >,
  'addVendor' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : Vendor } |
      { 'err' : string }
  >,
  'approveBiometric' : ActorMethod<[string, string], boolean>,
  'approveCommission' : ActorMethod<
    [string, string],
    { 'ok' : CommissionRecord } |
      { 'err' : string }
  >,
  'approveDevice' : ActorMethod<
    [string, string],
    { 'ok' : DeviceRecord } |
      { 'err' : string }
  >,
  'approveSocietyReview' : ActorMethod<[string], boolean>,
  'approveTutorialSuggestion' : ActorMethod<[bigint], boolean>,
  'assignLead' : ActorMethod<[string, string], boolean>,
  'assignVendorJob' : ActorMethod<
    [string, string, string, number],
    { 'ok' : VendorJob } |
      { 'err' : string }
  >,
  'authenticateFingerprint' : ActorMethod<
    [string, string, string, string, string],
    {
      'ok' : boolean,
      'role' : string,
      'message' : string,
      'sessionId' : string,
    }
  >,
  'authenticateStaff' : ActorMethod<
    [string, string, string, string, string],
    {
      'ok' : boolean,
      'role' : string,
      'message' : string,
      'sessionId' : string,
    }
  >,
  'authenticateWithToken' : ActorMethod<
    [string, string],
    [] | [{ 'token' : string, 'staffId' : string, 'role' : string }]
  >,
  'bulkAddProperties' : ActorMethod<
    [string, Array<PropertyListing>],
    {
      'added' : bigint,
      'skipped' : bigint,
      'errors' : Array<
        { 'id' : string, 'rowIndex' : bigint, 'reason' : string }
      >,
      'updated' : bigint,
    }
  >,
  'bulkSetTutorialSteps' : ActorMethod<
    [string, string, Array<TutorialStep>],
    boolean
  >,
  'calculateCommission' : ActorMethod<[string, string, number, number], string>,
  'clearAllInteractions' : ActorMethod<[], undefined>,
  'clearOldAuditEntries' : ActorMethod<[bigint], bigint>,
  'createAuction' : ActorMethod<
    [string, string, number, bigint, bigint],
    { 'ok' : Auction } |
      { 'err' : string }
  >,
  'createBooking' : ActorMethod<
    [string, string, string, string, bigint],
    { 'ok' : Booking } |
      { 'err' : string }
  >,
  'createClient' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'createCommissionRecord' : ActorMethod<
    [string, string, number, number],
    { 'ok' : CommissionRecord } |
      { 'err' : string }
  >,
  'createCourse' : ActorMethod<
    [string, string, string, string],
    { 'ok' : Course } |
      { 'err' : string }
  >,
  'createDailyBriefing' : ActorMethod<
    [string, bigint, bigint, number, bigint, Array<string>, bigint, string],
    { 'ok' : DailyBriefing } |
      { 'err' : string }
  >,
  'createDeal' : ActorMethod<
    [string, string, string],
    { 'ok' : Deal } |
      { 'err' : string }
  >,
  'createLead' : ActorMethod<
    [string, string, string, string, string, string, string],
    string
  >,
  'createListing' : ActorMethod<
    [string, string, number, string],
    { 'ok' : ExchangeListing } |
      { 'err' : string }
  >,
  'createMediaPost' : ActorMethod<
    [string, string, string, string, Array<string>],
    { 'ok' : MediaPost } |
      { 'err' : string }
  >,
  'createObserverCode' : ActorMethod<
    [string, Array<string>, string, [] | [bigint]],
    ObserverCode
  >,
  'createProperty' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      string,
      bigint,
      string,
      string,
      Array<string>,
      [] | [string],
      string,
      Array<string>,
      Array<string>,
    ],
    string
  >,
  'createReferral' : ActorMethod<[string, string, string], string>,
  'createSession' : ActorMethod<
    [string, string, string, string],
    [] | [string]
  >,
  'createSessionSimple' : ActorMethod<[string, string, string], string>,
  'createStaff' : ActorMethod<
    [string, string, StaffRole, string],
    { 'id' : string, 'ok' : boolean, 'message' : string }
  >,
  'createStaffWithRole' : ActorMethod<[string, string, string, string], string>,
  'deactivateStaffMember' : ActorMethod<[string], boolean>,
  'deleteAnniversaryReminder' : ActorMethod<[string], boolean>,
  'deleteAnnouncement' : ActorMethod<[string], boolean>,
  'deleteBuilderProfile' : ActorMethod<[string], boolean>,
  'deleteCallback' : ActorMethod<[string], boolean>,
  'deleteClient' : ActorMethod<[string], boolean>,
  'deleteComplaint' : ActorMethod<[string], boolean>,
  'deleteFeedback' : ActorMethod<[string], boolean>,
  'deleteInteraction' : ActorMethod<[bigint], boolean>,
  'deleteLead' : ActorMethod<[string], boolean>,
  'deleteMoreInfo' : ActorMethod<[string], boolean>,
  'deleteObserverCode' : ActorMethod<[bigint], boolean>,
  'deleteProperty' : ActorMethod<[string], boolean>,
  'deletePropertyAlert' : ActorMethod<[string], boolean>,
  'deleteQuote' : ActorMethod<[string], boolean>,
  'deleteReferral' : ActorMethod<[string], boolean>,
  'deleteSocietyReview' : ActorMethod<[string], boolean>,
  'deleteSubmission' : ActorMethod<[bigint], boolean>,
  'deleteSupport' : ActorMethod<[string], boolean>,
  'deleteTutorialStep' : ActorMethod<[bigint], boolean>,
  'dismissLeadReminder' : ActorMethod<[string], boolean>,
  'emergencyLockdown' : ActorMethod<[string], boolean>,
  'emergencyLockdownCount' : ActorMethod<[], bigint>,
  'enrollBiometric' : ActorMethod<[string, string], boolean>,
  'enrollBiometricWithAdmin' : ActorMethod<[string, string, string], boolean>,
  'enrollFingerprint' : ActorMethod<[string, string, string], boolean>,
  'enrollStudent' : ActorMethod<
    [string, string],
    { 'ok' : Enrollment } |
      { 'err' : string }
  >,
  'executeCommand' : ActorMethod<[string], CommandResult>,
  'fetchLatestNews' : ActorMethod<[], Array<NewsArticle>>,
  'fetchPropertyDataFromPortals' : ActorMethod<[], bigint>,
  /**
   * / Force logout a specific staff member by staffId (removes all their sessions).
   */
  'forceLogout' : ActorMethod<[string], boolean>,
  'forceLogoutStaff' : ActorMethod<[string], boolean>,
  'generateObserverCode' : ActorMethod<
    [string, bigint, boolean, string],
    string
  >,
  'generateObserverCodeInfo' : ActorMethod<
    [string, string, [] | [bigint], boolean, Array<string>],
    string
  >,
  'generateOtp' : ActorMethod<[string], boolean>,
  'getAIAgent' : ActorMethod<[string], [] | [AIAgent]>,
  'getAIAgentStats' : ActorMethod<
    [],
    {
      'agentsActiveNow' : bigint,
      'documentsAnalyzedToday' : bigint,
      'leadsProcessedToday' : bigint,
      'propertiesAddedToday' : bigint,
      'totalInteractionsToday' : bigint,
      'chatMessagesProcessedToday' : bigint,
      'complianceChecksToday' : bigint,
      'contentGeneratedToday' : bigint,
    }
  >,
  'getAIAgents' : ActorMethod<[], Array<[string, AIAgent]>>,
  'getAIAgentsByParent' : ActorMethod<[string], Array<[string, AIAgent]>>,
  'getAIAgentsByTier' : ActorMethod<[string], Array<[string, AIAgent]>>,
  'getAIInsights' : ActorMethod<[], Array<[string, AIInsight]>>,
  'getAIStaffActivityFeed' : ActorMethod<[], Array<AIActivityEntry>>,
  'getAISystemConfig' : ActorMethod<[], AISystemConfig>,
  'getActiveAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getActiveSessionInfos' : ActorMethod<[], Array<Session>>,
  'getActiveSessions' : ActorMethod<[], Array<Session>>,
  'getActiveVisitorCount' : ActorMethod<[], bigint>,
  'getAgentActivitiesByCluster' : ActorMethod<
    [string, bigint],
    Array<AgentActivity>
  >,
  'getAgentBookings' : ActorMethod<[string], Array<Booking>>,
  'getAgentCommissions' : ActorMethod<[string], Array<CommissionRecord>>,
  'getAiDecision' : ActorMethod<
    [string],
    { 'ok' : AiDecision } |
      { 'err' : string }
  >,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllComplaints' : ActorMethod<[], Array<ComplaintTicket>>,
  'getAllDevices' : ActorMethod<[], Array<DeviceRecord>>,
  'getAllObserverCodes' : ActorMethod<[], Array<ObserverCode>>,
  'getAllReferrals' : ActorMethod<[], Array<Referral>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllSocietyReviews' : ActorMethod<[], Array<SocietyReview>>,
  'getAllStaff' : ActorMethod<[], Array<Staff>>,
  'getAllTutorialApps' : ActorMethod<[], Array<TutorialApp>>,
  'getAnalyticsSummary' : ActorMethod<
    [],
    {
      'thisMonthEnquiries' : bigint,
      'peakHours' : Array<[string, bigint]>,
      'topLocations' : Array<[string, bigint]>,
      'totalEnquiries' : bigint,
      'topBudgetRanges' : Array<[string, bigint]>,
      'topPropertyTypes' : Array<[string, bigint]>,
      'thisWeekEnquiries' : bigint,
    }
  >,
  'getAnniversaryReminders' : ActorMethod<[], Array<AnniversaryReminder>>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAuction' : ActorMethod<[string], { 'ok' : Auction } | { 'err' : string }>,
  'getAuctionBids' : ActorMethod<[string], Array<Bid>>,
  'getAuctionListings' : ActorMethod<[], Array<AuctionListing>>,
  'getAuditLog' : ActorMethod<[bigint, bigint], Array<AuditRecord>>,
  'getAuditLogByActor' : ActorMethod<[string], Array<AuditEntry>>,
  'getAuditTrail' : ActorMethod<[bigint], Array<AuditRecord>>,
  'getAutoArchiveDays' : ActorMethod<[], bigint>,
  'getAvailableSlots' : ActorMethod<[string, string], TimeSlot>,
  'getAverageRating' : ActorMethod<[], number>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getBotContext' : ActorMethod<[], string>,
  'getBotResponse' : ActorMethod<[string], string>,
  'getBriefingByDate' : ActorMethod<[string], [] | [DailyBriefing]>,
  'getBuilderByRera' : ActorMethod<[string], [] | [BuilderProfile]>,
  'getBuilderProfiles' : ActorMethod<[], Array<BuilderProfile>>,
  'getBuilderTrust' : ActorMethod<[string], [] | [BuilderTrustRecord]>,
  'getCallbackRequests' : ActorMethod<[], Array<CallbackRequest>>,
  'getCampaignById' : ActorMethod<[string], [] | [Campaign]>,
  'getCampaigns' : ActorMethod<[], Array<Campaign>>,
  'getChatAnalytics' : ActorMethod<
    [],
    { 'totalChats' : bigint, 'topTopics' : Array<[string, bigint]> }
  >,
  'getClient' : ActorMethod<[string], [] | [Client]>,
  'getClientById' : ActorMethod<[string], [] | [Client__1]>,
  'getClients' : ActorMethod<[], Array<Client>>,
  'getClientsByStage' : ActorMethod<[string], Array<Client>>,
  'getCommissionInvoices' : ActorMethod<[], Array<CommissionInvoice>>,
  'getCommissions' : ActorMethod<[], Array<CommissionRecord>>,
  'getCommissionsByStaff' : ActorMethod<[string], Array<CommissionRecord>>,
  'getComplaint' : ActorMethod<[string], [] | [ComplaintTicket]>,
  'getCourse' : ActorMethod<[string], { 'ok' : Course } | { 'err' : string }>,
  'getCrmAppointments' : ActorMethod<[], Array<CrmAppointment>>,
  'getCrmDashboardStats' : ActorMethod<[], Array<DashboardStat>>,
  'getCrmLeadsByStage' : ActorMethod<[string], Array<Lead__1>>,
  'getCrmNotifications' : ActorMethod<[], Array<AppNotification>>,
  'getCsrImpact' : ActorMethod<[], Array<CsrImpactEntry>>,
  'getCurrentVisitors' : ActorMethod<[], bigint>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDeal' : ActorMethod<[string], { 'ok' : Deal } | { 'err' : string }>,
  'getDealCounter' : ActorMethod<
    [],
    { 'desc' : string, 'count' : bigint, 'updatedAt' : bigint }
  >,
  'getDealNotes' : ActorMethod<[string], Array<DealNote>>,
  'getDeals' : ActorMethod<[], Array<Deal__1>>,
  'getEnrollments' : ActorMethod<[string], Array<Enrollment>>,
  'getEventBookings' : ActorMethod<[], Array<EventBooking>>,
  'getEventById' : ActorMethod<[string], [] | [Event_]>,
  'getEvents' : ActorMethod<[], Array<Event_>>,
  'getFeedback' : ActorMethod<[], Array<Feedback>>,
  'getFinancialMetrics' : ActorMethod<[], Array<FinancialMetric>>,
  'getFormStats' : ActorMethod<[], FormStats>,
  'getInteractionCount' : ActorMethod<[], bigint>,
  'getInteractionStats' : ActorMethod<
    [],
    {
      'needsAttentionCount' : bigint,
      'total' : bigint,
      'avgMessageLength' : bigint,
      'todayCount' : bigint,
    }
  >,
  'getInteractions' : ActorMethod<[bigint, bigint], Array<ChatInteraction>>,
  'getInvoices' : ActorMethod<[], Array<Invoice>>,
  'getJantriRate' : ActorMethod<[string], [] | [JantriRate]>,
  /**
   * / Get KPI summary for the Master Control dashboard.
   */
  'getKPIs' : ActorMethod<
    [],
    {
      'totalProperties' : bigint,
      'activeDeals' : bigint,
      'totalLeads' : bigint,
      'totalEnquiries' : bigint,
      'totalAuctions' : bigint,
      'totalStaff' : bigint,
      'activeSessions' : bigint,
      'securityEvents' : bigint,
    }
  >,
  'getLatestBriefing' : ActorMethod<[], [] | [DailyBriefing]>,
  'getLatestMarketData' : ActorMethod<[], Array<MarketDataPoint>>,
  'getLead' : ActorMethod<[string], [] | [Lead]>,
  'getLeadPipelineStats' : ActorMethod<
    [],
    {
      'new' : bigint,
      'closedWon' : bigint,
      'siteVisit' : bigint,
      'contacted' : bigint,
      'closedLost' : bigint,
    }
  >,
  'getLeadQualifications' : ActorMethod<[], Array<LeadQualification>>,
  'getLeadStats' : ActorMethod<
    [],
    {
      'total' : bigint,
      'hotLeads' : bigint,
      'warmLeads' : bigint,
      'coldLeads' : bigint,
    }
  >,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getLeadsByStage' : ActorMethod<[string], Array<PropertyEnquiry>>,
  'getLegalDoc' : ActorMethod<[string], [] | [LegalDoc]>,
  'getListing' : ActorMethod<
    [string],
    { 'ok' : ExchangeListing } |
      { 'err' : string }
  >,
  'getLiveMarketData' : ActorMethod<
    [],
    {
      'interestRates' : Array<InterestRateEntry>,
      'lastUpdated' : string,
      'rbiNote' : string,
      'jantriUpdate' : string,
    }
  >,
  'getLocalityDemand' : ActorMethod<[], Array<LocalityDemand>>,
  'getLocalityDemandFor' : ActorMethod<[string], [] | [LocalityDemand]>,
  'getMarketDataByLocality' : ActorMethod<[string], Array<MarketDataPoint>>,
  'getMarketReports' : ActorMethod<[], Array<MarketReport>>,
  'getMediaPost' : ActorMethod<
    [string],
    { 'ok' : MediaPost } |
      { 'err' : string }
  >,
  'getMoreInfoRequests' : ActorMethod<[], Array<MoreInfoRequest>>,
  /**
   * / Get the morning briefing (latest daily summary + KPIs).
   */
  'getMorningBriefing' : ActorMethod<
    [],
    {
      'totalProperties' : bigint,
      'activeDeals' : bigint,
      'date' : string,
      'greeting' : string,
      'totalLeads' : bigint,
      'summary' : string,
      'activeSessions' : bigint,
      'securityEventsToday' : bigint,
      'newEnquiriesToday' : bigint,
    }
  >,
  'getMusicArtists' : ActorMethod<[], Array<MusicArtist>>,
  'getNewEnquiryCount' : ActorMethod<[], bigint>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getObserverAccessLogs' : ActorMethod<[string], Array<ObserverAccessLog>>,
  'getOverdueLeadReminders' : ActorMethod<[], Array<LeadNurtureReminder>>,
  'getPartnerApplications' : ActorMethod<[], Array<PartnerApplication>>,
  'getPriceHistory' : ActorMethod<[string], Array<PriceHistoryEntry>>,
  'getProperties' : ActorMethod<[], Array<Property>>,
  'getPropertiesForAdmin' : ActorMethod<[], Array<PropertyListing>>,
  'getProperty' : ActorMethod<[string], [] | [Property]>,
  'getPropertyAlerts' : ActorMethod<[], Array<PropertyAlert>>,
  'getPropertyById' : ActorMethod<[string], [] | [PropertyListing]>,
  'getPropertyCount' : ActorMethod<[], bigint>,
  'getPropertyEnquiries' : ActorMethod<[], Array<PropertyEnquiry>>,
  'getPropertyEnquiriesByStatus' : ActorMethod<
    [string],
    Array<PropertyEnquiry>
  >,
  'getPropertyEnquiryCount' : ActorMethod<[], bigint>,
  'getPropertyIntelligence' : ActorMethod<
    [string],
    [] | [PropertyIntelligence]
  >,
  'getPropertyPerformance' : ActorMethod<[], Array<PropertyPerformance>>,
  'getPropertyViewCount' : ActorMethod<[string], bigint>,
  'getProposals' : ActorMethod<[], Array<Proposal>>,
  'getPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getPublishedMarketReports' : ActorMethod<[], Array<MarketReport>>,
  'getQuoteRequests' : ActorMethod<[], Array<QuoteRequest>>,
  'getRSVPsByEvent' : ActorMethod<[bigint], Array<RSVP>>,
  'getRealTimeStats' : ActorMethod<
    [],
    {
      'activeNow' : bigint,
      'totalAgents' : bigint,
      'avgAccuracy' : number,
      'lastUpdated' : string,
      'propertiesAdded' : bigint,
      'contentGenerated' : bigint,
      'leadsProcessed' : bigint,
      'tasksToday' : bigint,
    }
  >,
  'getRecentAgentActivities' : ActorMethod<[bigint], Array<AgentActivity>>,
  'getRecentlyAddedProperties' : ActorMethod<[bigint], Array<PropertyListing>>,
  'getReferralByCode' : ActorMethod<[string], [] | [Referral]>,
  'getResponseTimeBadge' : ActorMethod<[], string>,
  'getReviews' : ActorMethod<[], Array<ReviewRecord>>,
  'getRichSecurityEvents' : ActorMethod<[bigint], Array<RichSecurityEvent>>,
  'getSatisfactionRatings' : ActorMethod<[], Array<SatisfactionRating>>,
  'getSecurityAuditLog' : ActorMethod<[bigint], Array<AuditEntry>>,
  'getSecurityEvents' : ActorMethod<[bigint], Array<SecurityEvent>>,
  'getSecurityHealthReport' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint],
    SecurityHealthReport
  >,
  'getSecurityScore' : ActorMethod<[], bigint>,
  'getSecurityStats' : ActorMethod<
    [],
    {
      'totalEvents' : bigint,
      'criticalCount' : bigint,
      'resolvedCount' : bigint,
      'threatsBlocked' : bigint,
    }
  >,
  'getService' : ActorMethod<[bigint], [] | [Service]>,
  'getServiceSubmissions' : ActorMethod<[], Array<ServiceSubmission>>,
  'getSiteVisits' : ActorMethod<[], Array<SiteVisit>>,
  'getSocietyReviews' : ActorMethod<[string], Array<SocietyReview>>,
  'getStaff' : ActorMethod<[], Array<Staff>>,
  'getStaffById' : ActorMethod<[string], [] | [Staff]>,
  'getStaffMembers' : ActorMethod<[], Array<AdminStaffMember>>,
  'getSubmissionStats' : ActorMethod<
    [],
    {
      'total' : bigint,
      'unread' : bigint,
      'byService' : Array<[string, bigint]>,
    }
  >,
  'getSubmissionsByService' : ActorMethod<[string], Array<ServiceSubmission>>,
  'getSupportForms' : ActorMethod<[], Array<SupportForm>>,
  /**
   * / Get recent security threat events (last N events).
   */
  'getThreatAlerts' : ActorMethod<[bigint], Array<SecurityEvent>>,
  'getThreatIntel' : ActorMethod<[bigint], Array<ThreatIntelEntry>>,
  'getTopViewedProperties' : ActorMethod<[bigint], Array<[string, bigint]>>,
  'getTriggeredCanaries' : ActorMethod<[], Array<CanaryToken>>,
  'getTutorialCompletions' : ActorMethod<
    [[] | [string]],
    Array<TutorialCompletion>
  >,
  'getTutorialStats' : ActorMethod<
    [],
    Array<{ 'completions' : bigint, 'skips' : bigint, 'appKey' : string }>
  >,
  'getTutorialSteps' : ActorMethod<[string, string], Array<TutorialStep>>,
  'getTutorialStepsByApp' : ActorMethod<[string], Array<TutorialStep>>,
  'getTutorialSuggestions' : ActorMethod<[], Array<TutorialSuggestion>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getVendor' : ActorMethod<[string], { 'ok' : Vendor } | { 'err' : string }>,
  'getVisitRequests' : ActorMethod<[], Array<VisitRequest>>,
  'getVisitorCount' : ActorMethod<[], bigint>,
  /**
   * / Get weekly business review summary.
   */
  'getWeeklyReview' : ActorMethod<
    [],
    {
      'totalProperties' : bigint,
      'period' : string,
      'totalLeads' : bigint,
      'summary' : string,
      'totalEnquiries' : bigint,
      'totalStaff' : bigint,
      'securityEvents' : bigint,
      'closedDeals' : bigint,
      'newDeals' : bigint,
    }
  >,
  'incrementPostViews' : ActorMethod<[string], undefined>,
  'incrementPropertyView' : ActorMethod<[string], undefined>,
  'incrementPropertyViews' : ActorMethod<[string], boolean>,
  'incrementVisitorCount' : ActorMethod<[], bigint>,
  'invalidateAllSessions' : ActorMethod<[string], boolean>,
  'invalidateSession' : ActorMethod<[string], boolean>,
  'isDeviceTrusted' : ActorMethod<[string, string], boolean>,
  'isIpBlocked' : ActorMethod<[string], boolean>,
  'isLockdownActive' : ActorMethod<[], boolean>,
  'liftLockdown' : ActorMethod<[string], boolean>,
  'listAiDecisions' : ActorMethod<[bigint], Array<AiDecision>>,
  'listAllCampaigns' : ActorMethod<[], Array<Campaign>>,
  'listAllClients' : ActorMethod<[], Array<Client__1>>,
  'listAllEvents' : ActorMethod<[], Array<Event_>>,
  'listAllObserverAccessLogs' : ActorMethod<[bigint], Array<ObserverAccessLog>>,
  'listAuctions' : ActorMethod<[], Array<Auction>>,
  'listBookings' : ActorMethod<[], Array<Booking>>,
  'listBriefings' : ActorMethod<[bigint], Array<DailyBriefing>>,
  'listBuilderTrust' : ActorMethod<[], Array<BuilderTrustRecord>>,
  'listCanaryTokens' : ActorMethod<[], Array<CanaryToken>>,
  'listCommissions' : ActorMethod<[], Array<CommissionRecord>>,
  'listCourses' : ActorMethod<[], Array<Course>>,
  'listDeals' : ActorMethod<[], Array<Deal>>,
  'listDevices' : ActorMethod<[string], Array<DeviceRecord>>,
  'listExchangeListings' : ActorMethod<[], Array<ExchangeListing>>,
  'listJantriRates' : ActorMethod<[], Array<JantriRate>>,
  'listLegalDocs' : ActorMethod<[], Array<LegalDoc>>,
  'listMediaPosts' : ActorMethod<[], Array<MediaPost>>,
  'listObserverCodeInfos' : ActorMethod<[string], Array<ObserverCodeInfo>>,
  'listObserverCodes' : ActorMethod<[], Array<ObserverCodeRecord>>,
  'listPropertyIntelligence' : ActorMethod<[], Array<PropertyIntelligence>>,
  'listStaff' : ActorMethod<[], Array<Staff>>,
  'listVendors' : ActorMethod<[], Array<Vendor>>,
  'logAIActivity' : ActorMethod<[string, string, bigint, string], undefined>,
  'logAIAgentAction' : ActorMethod<[string, string], boolean>,
  'logAction' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'logAgentActivity' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'logAiDecision' : ActorMethod<
    [AiDecisionType, string, string, bigint, string, boolean, string],
    { 'ok' : AiDecision } |
      { 'err' : string }
  >,
  'logAuditEvent' : ActorMethod<
    [string, string, string, string, string, string],
    string
  >,
  'logCallbackRequest' : ActorMethod<[string, string, string, string], string>,
  'logChatInteraction' : ActorMethod<[string, string, string], bigint>,
  'logChatTopic' : ActorMethod<[string], boolean>,
  'logFeedback' : ActorMethod<[bigint, string, string], string>,
  'logLeadQualification' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'logMoreInfoRequest' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'logObserverAccess' : ActorMethod<[string, string, string], string>,
  'logQuoteRequest' : ActorMethod<
    [string, string, string, string, string, string],
    string
  >,
  'logReferralClick' : ActorMethod<[string], undefined>,
  'logReferralEnquiry' : ActorMethod<[string, string], undefined>,
  'logSecurityEvent' : ActorMethod<
    [SecurityEventType, string, string, string, string],
    bigint
  >,
  'logServiceSubmission' : ActorMethod<
    [
      string,
      string,
      string,
      Array<[string, string]>,
      string,
      string,
      string,
      boolean,
    ],
    bigint
  >,
  'logSupportForm' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  /**
   * / Authenticate with username + password. Returns session token, role, and message.
   */
  'login' : ActorMethod<
    [string, string],
    {
      'ok' : boolean,
      'role' : string,
      'message' : string,
      'sessionId' : string,
    }
  >,
  /**
   * / Invalidate a session by token (logout).
   */
  'logout' : ActorMethod<[string], undefined>,
  'markAllCrmNotificationsRead' : ActorMethod<[], bigint>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markCallbackRead' : ActorMethod<[string, boolean], boolean>,
  'markCommissionPaid' : ActorMethod<[string], boolean>,
  'markCommissionPaidResult' : ActorMethod<
    [string],
    { 'ok' : CommissionRecord } |
      { 'err' : string }
  >,
  'markCrmNotificationRead' : ActorMethod<[bigint], boolean>,
  'markEnquiryContacted' : ActorMethod<[string], boolean>,
  'markFeedbackRead' : ActorMethod<[string, boolean], boolean>,
  'markMoreInfoRead' : ActorMethod<[string, boolean], boolean>,
  'markNotificationRead' : ActorMethod<[string], boolean>,
  'markQuoteRead' : ActorMethod<[string, boolean], boolean>,
  'markSubmissionRead' : ActorMethod<[bigint, boolean], boolean>,
  'markSupportRead' : ActorMethod<[string, boolean], boolean>,
  'placeBid' : ActorMethod<
    [string, string, number],
    { 'ok' : Bid } |
      { 'err' : string }
  >,
  'plantCanaryToken' : ActorMethod<
    [string, string],
    { 'ok' : CanaryToken } |
      { 'err' : string }
  >,
  'publishBlogPost' : ActorMethod<[string, boolean], boolean>,
  'publishMarketReport' : ActorMethod<[string, boolean], boolean>,
  'publishMediaPost' : ActorMethod<
    [string],
    { 'ok' : MediaPost } |
      { 'err' : string }
  >,
  'rateVendor' : ActorMethod<
    [string, number],
    { 'ok' : Vendor } |
      { 'err' : string }
  >,
  'recordLocalityEnquiry' : ActorMethod<[string], undefined>,
  'recordLocalityView' : ActorMethod<[string], undefined>,
  'recordPriceHistory' : ActorMethod<
    [string, bigint, string, string],
    { 'ok' : PriceHistoryEntry } |
      { 'err' : string }
  >,
  'recordPropertyEnquiry' : ActorMethod<[string], boolean>,
  'recordSecurityEvent' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'recordTutorialCompletion' : ActorMethod<
    [string, string, string, boolean],
    undefined
  >,
  'registerDevice' : ActorMethod<
    [string, string, string, string],
    { 'ok' : DeviceRecord } |
      { 'err' : string }
  >,
  'registerForEvent' : ActorMethod<[string], boolean>,
  'rejectTutorialSuggestion' : ActorMethod<[bigint], boolean>,
  'removeActiveVisitor' : ActorMethod<[string], undefined>,
  'removeStaff' : ActorMethod<[string], boolean>,
  'reorderTutorialSteps' : ActorMethod<
    [string, string, Array<bigint>],
    boolean
  >,
  'resetFailedAttempts' : ActorMethod<[string], boolean>,
  'resetTutorialCompletion' : ActorMethod<[string, string], boolean>,
  'resolveSecurityEvent' : ActorMethod<[string], boolean>,
  'respondToReview' : ActorMethod<[bigint, string], boolean>,
  'revokeBiometric' : ActorMethod<[string], boolean>,
  'revokeDevice' : ActorMethod<
    [string, string],
    { 'ok' : DeviceRecord } |
      { 'err' : string }
  >,
  'revokeObserverCode' : ActorMethod<[string], boolean>,
  'revokeObserverCodeInfo' : ActorMethod<[string, string], boolean>,
  'rollbackAiDecision' : ActorMethod<
    [string, string],
    { 'ok' : AiDecision } |
      { 'err' : string }
  >,
  'searchClients' : ActorMethod<[string], Array<Client>>,
  'searchInteractions' : ActorMethod<
    [string, bigint, bigint],
    Array<ChatInteraction>
  >,
  'searchLeads' : ActorMethod<[string], Array<Lead>>,
  'searchProperties' : ActorMethod<[string], Array<Property>>,
  'sendOtp' : ActorMethod<[string], boolean>,
  'setAutoArchiveDays' : ActorMethod<[bigint], boolean>,
  'setMobileNumber' : ActorMethod<[string, string], boolean>,
  'setResponseTimeBadge' : ActorMethod<[string], boolean>,
  'staffLogin' : ActorMethod<
    [string, string],
    [] | [
      {
        'id' : string,
        'accessLevel' : string,
        'name' : string,
        'role' : string,
        'accessSections' : Array<string>,
      }
    ]
  >,
  /**
   * / Submit a callback request form.
   */
  'submitCallbackRequest' : ActorMethod<
    [string, string, string, string],
    string
  >,
  'submitComplaint' : ActorMethod<[string, string, string, string], string>,
  /**
   * / Submit a contact / general enquiry form.
   */
  'submitContactForm' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'submitEnquiry' : ActorMethod<
    [string, string, string, [] | [number]],
    { 'ok' : ExchangeEnquiry } |
      { 'err' : string }
  >,
  'submitLeadQualification' : ActorMethod<
    [
      string,
      {
        'propertyType' : string,
        'name' : string,
        'phone' : string,
        'budget' : string,
        'location' : string,
      },
    ],
    string
  >,
  'submitPropertyAlert' : ActorMethod<
    [string, string, string, string, string, string, bigint, string],
    string
  >,
  'submitPropertyEnquiry' : ActorMethod<
    [string, string, string, string, string, string, string],
    string
  >,
  /**
   * / Submit a quote request form.
   */
  'submitQuoteRequest' : ActorMethod<
    [string, string, string, string, string, string],
    string
  >,
  'submitSatisfactionRating' : ActorMethod<[string, bigint, string], boolean>,
  /**
   * / Submit a service-specific form (routes to the service submission log).
   */
  'submitServiceForm' : ActorMethod<
    [
      string,
      string,
      string,
      Array<[string, string]>,
      string,
      string,
      string,
      boolean,
    ],
    string
  >,
  'submitSocietyReview' : ActorMethod<
    [string, string, bigint, bigint, bigint, bigint, bigint, string],
    boolean
  >,
  'submitVisitRequest' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    string
  >,
  'suspendStaff' : ActorMethod<[string], boolean>,
  'terminateSession' : ActorMethod<[string], boolean>,
  'toggleAnnouncement' : ActorMethod<[string, boolean], boolean>,
  'triggerCanary' : ActorMethod<
    [string, string],
    { 'ok' : CanaryToken } |
      { 'err' : string }
  >,
  'updateAIAgentFullConfig' : ActorMethod<[string, string], boolean>,
  'updateAIAgentStatus' : ActorMethod<[string, boolean], boolean>,
  'updateAIInsightStatus' : ActorMethod<[string, string], boolean>,
  'updateAISystemConfig' : ActorMethod<[AISystemConfig], boolean>,
  'updateAppointmentStatus' : ActorMethod<[string, string], boolean>,
  'updateBookingStatus' : ActorMethod<
    [string, string],
    { 'ok' : Booking } |
      { 'err' : string }
  >,
  'updateClient' : ActorMethod<
    [string, string, string, string, string],
    boolean
  >,
  'updateCommissionInvoiceStatus' : ActorMethod<[bigint, string], boolean>,
  'updateComplaintStatus' : ActorMethod<[string, string, string], boolean>,
  'updateCrmLeadStage' : ActorMethod<[bigint, string, string], boolean>,
  'updateCsrEntry' : ActorMethod<[string, string, bigint, string], boolean>,
  'updateDealStage' : ActorMethod<
    [string, string],
    { 'ok' : Deal } |
      { 'err' : string }
  >,
  'updateDocStatus' : ActorMethod<[string, string], boolean>,
  'updateEnquiryStatus' : ActorMethod<[string, string, string], boolean>,
  'updateEventBookingStatus' : ActorMethod<[string, string, string], boolean>,
  'updateInvoiceStatus' : ActorMethod<[string, string], boolean>,
  'updateLead' : ActorMethod<[string, string, bigint, string, string], boolean>,
  'updateLeadLastContacted' : ActorMethod<[string], boolean>,
  'updateLeadScore' : ActorMethod<[string, bigint], boolean>,
  'updateLeadStage' : ActorMethod<[string, string], boolean>,
  'updateListingStatus' : ActorMethod<
    [string, string],
    { 'ok' : ExchangeListing } |
      { 'err' : string }
  >,
  'updateMarketDataCache' : ActorMethod<[], boolean>,
  'updateMusicArtist' : ActorMethod<[string, string, boolean, string], boolean>,
  'updatePartnerStatus' : ActorMethod<[string, string, string], boolean>,
  'updateProgress' : ActorMethod<
    [string, string, string],
    { 'ok' : Enrollment } |
      { 'err' : string }
  >,
  'updateProperty' : ActorMethod<[string, string, string, string], boolean>,
  'updateSiteVisitStatus' : ActorMethod<[string, string], boolean>,
  'updateStaff' : ActorMethod<[string, string, string, StaffRole], boolean>,
  'updateStaffMobile' : ActorMethod<[string, string], boolean>,
  'updateStaffRole' : ActorMethod<[string, StaffRole], boolean>,
  'updateStaffStatus' : ActorMethod<[string, string], boolean>,
  'updateTutorialStepDesc' : ActorMethod<[string, string], boolean>,
  'updateVendorJobStatus' : ActorMethod<
    [string, string],
    { 'ok' : VendorJob } |
      { 'err' : string }
  >,
  'updateVisitRequestStatus' : ActorMethod<[string, string], boolean>,
  'upsertBuilderTrust' : ActorMethod<
    [string, string, bigint, bigint, bigint],
    { 'ok' : BuilderTrustRecord } |
      { 'err' : string }
  >,
  'upsertJantriRate' : ActorMethod<
    [string, bigint, string],
    { 'ok' : JantriRate } |
      { 'err' : string }
  >,
  'upsertPropertyIntelligence' : ActorMethod<
    [
      string,
      string,
      string,
      Array<string>,
      InvestmentGrade,
      bigint,
      bigint,
      bigint,
      number,
      number,
    ],
    { 'ok' : PropertyIntelligence } |
      { 'err' : string }
  >,
  'upsertTutorialStep' : ActorMethod<[TutorialStep], bigint>,
  'validateObserverCode' : ActorMethod<[string], boolean>,
  'validateObserverCodeInfo' : ActorMethod<[string, string], boolean>,
  'validateOtp' : ActorMethod<[string, string], boolean>,
  'validateSession' : ActorMethod<[string, string], boolean>,
  'validateSessionToken' : ActorMethod<[string], [] | [Staff]>,
  /**
   * / Verify a mobile OTP for the given staffId. Returns session token on success.
   */
  'verifyOTP' : ActorMethod<
    [string, string],
    {
      'ok' : boolean,
      'role' : string,
      'message' : string,
      'sessionId' : string,
    }
  >,
  'verifyOtp' : ActorMethod<
    [string, string, string, string, string],
    {
      'ok' : boolean,
      'role' : string,
      'message' : string,
      'sessionId' : string,
    }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];